### ISSUE TITLE
[Feature Request]: Native arm64 macOS build for Apple Silicon (M1 chips) without Rosetta

### ISSUE THREAD

**Issue by rafrafek** [PCSX2/pcsx2#10042]
### Description

Currently PCSX2 requires Rosetta to run on macOS with M1 chip:

<img width="592" alt="image" src="https://github.com/PCSX2/pcsx2/assets/23004737/78449963-843b-42dd-9503-3889ba98bc4e">

Please provide native arm64 builds or universal builds.

### Reason

It will bring native CPU performance and better battery life for M1 Macs. It will make it possible to run PCSX2 on Rosetta-free Macs with Apple Silicon chips.

### Examples

Binary compiled also for arm64, not only for Intel-based Macs.

**Comment by stenzek** [comment]
We know. There's no point having a request open, because it's a gargantuan task that very few people have the skills *and* interest in doing.

Dynarecs for Apple Silicon for PCSX2 will happen eventually, my (incomplete) attempts from back in 2021 were around a 1.5-3x performance boost depending on the game. But that requires a significant rebase, and a lot of code needs to be centralized/shared with x86, otherwise it's just an unmaintainable mess. And I don't have the time to commit to that due to work at the moment.

Maintainability is more important than anything else going forward, because Apple chips are more than fast enough to run the x64 recs with Rosetta for now, in almost all games. So, as it stands, this is a "won't fix".

**Comment by rafrafek** [comment]
Thank you for your explanation! I haven't found it in other issues and I made this issue with a lot of keywords so I hope it helps other people finding the answer.

**Comment by ghost** [comment]
With Apple announcing the retirement of Rosetta 2 in the next few years, I believe this should be up for discussion again.

**Comment by F0bes** [comment]
We do have a working native arm64 version of PCSX2.
There are just no recompilers (only VIF), and you need to compile it yourself.

**Comment by fizwidget** [comment]
Do games run at playable speeds without the recompilers?

**Comment by F0bes** [comment]
The absolute lightest of games possibly. 
On average no.

**Comment by Pasithea0** [comment]
Rosetta 2 will be EOL 2027 
https://arstechnica.com/gadgets/2025/06/apple-details-the-end-of-intel-mac-support-and-a-phaseout-for-rosetta-2/

Maybe its time to support arm64

**Comment by F0bes** [comment]
> Rosetta 2 will be EOL 2027 
> https://arstechnica.com/gadgets/2025/06/apple-details-the-end-of-intel-mac-support-and-a-phaseout-for-rosetta-2/
> 
> Maybe its time to support arm64

Get to work
