### ISSUE TITLE
[Feature Request]: Assign Game Serial to Manually Added Cover Art

### ISSUE THREAD

**Issue by Tagger102** [PCSX2/pcsx2#10126]
### Description

When adding game cover art manually through the UI (Right click on desired game -> Set Cover Image) the selected image file will be added into the correct PCSX2 folder with the Game Title as the file name. This causes pathing issues after certain GameDB title updates or, most noticeably, in Japanese games when English title sorting is applied. 

I suggest, to alleviate all aforementioned issues moving forward, when manually adding cover art using "Set Cover Image" the image file should be named after the game's Serial number instead of the Title. 

### Reason

- Less user input needed overall.
- Less hassle when Japanese games are sorted differently (i.e. by English name), which would otherwise require multiple instances of file name changing (experienced the hard way on my end).
- Allows PCSX2 to always find the correct cover art once added, no pathing issues. 

### Examples

N/A

**Comment by stenzek** [comment]
I'm not convinced. What "pathing issues"? Modern OSes all use Unicode for filesystems.

**Comment by kamfretoz** [comment]
> I'm not convinced. What "pathing issues"? Modern OSes all use Unicode for filesystems.

It's not really a pathing issue, but rather because as it is stands right now when you set the cover manually (Through the ""Set Cover Image..." option) the file name for the cover is set to the game's title (Which afaik doesn't present an option to set the file name as the serial, like the one on cover downloader). This can cause some problem now that we have multiple option for game titles.

Not to mention that if we push a game title change to GameDB, since the covers file name are tied to the game title that'll cause to the cover to disappear unless that cover's file name is corrected to account for the title change.

So saving the cover with `SERIAL_CRC.png/svg/webp` might be a worthwhile idea, of course the format can be discussed further.

**Comment by TellowKrinkle** [comment]
#10130 should fix the covers getting broken by the use English titles option, but people's covers will still break every time we update names in the gamedb

**Comment by stenzek** [comment]
> So saving the cover with SERIAL_CRC.png/svg/webp might be a worthwhile idea, of course the format can be discussed further.

There's a downside to that too - if you own two regions of the same game, then you no longer get the same cover for both. While that's probably not an intended use case, since the covers are usually different, it is a breaking change from the current behavior.

It's probably best to make it an option, as much as I hate the idea.

**Comment by Tagger102** [comment]
@kamfretoz explained it better than I could, I'm just a general user with no dev knowledge. What I do know is I've had to reapply cover art multiple times throughout the GameDB changes, and the fix would've been to change the image file names to the corresponding games' serial numbers. I had no knowledge of this permanent manual fix and was instead using the built-in Set Cover Image function, which defaults to the title instead of the serial. 

To your point @stenzek of "if you own two regions of the same game, then you no longer get the same cover for both." that's something I personally haven't run into and can't test as I don't own two games from different regions with the same serial number. To address this point, would it be possible to add the option for both formats when setting the cover image? Something akin to... 

"Set Cover Image Using"... -> (submenu shown with multiple options) 
1.) Game Serial
2.) Game Title
3.) English Title
Etc. 

Not sure if this is a feasible workaround from a dev's perspective. Just giving my thoughts on an issue to help future users, as this issue cost me quite a bit of time in the past.

**Comment by stenzek** [comment]
Not really a fan of the idea of making it a submenu - misclicks are easy, and since it's just a general file open dialog, there's no indication of which one you actually selected.

**Comment by Tagger102** [comment]
> Not really a fan of the idea of making it a submenu - misclicks are easy, and since it's just a general file open dialog, there's no indication of which one you actually selected.

Fair enough. Possible then to add the option into Settings -> Gamelist? Would simply be nice to have the option to default covers to the serial number. Does it eliminate all issues? No. But I believe adding the option has the potential to fix more issues than it could possibly cause. The only issue you mentioned seems to arise from a niche gamelist setup to begin with. In any case, time for me to go through all my cover image files and rename them individually lol...
