### ISSUE TITLE
[Feature Request]: Hide Crosshair if no movement is detected or no controller is plugged in

### ISSUE THREAD

**Issue by magicray1028** [PCSX2/pcsx2#10139]
### Description

It would be great if the crosshair png for guncon2 controllers would auto hide if no device is detected. This way even if two guns are setup, if only 1 is plugged in, the second crosshair wont remain on screen.

### Reason

Use just one gun when playing one player but have the emulator permanently setup for 2 players just in case.

### Examples

Auto Hide crosshair if no movement detected, or only show crosshair on movement like mame.

**Comment by stenzek** [comment]
> It would be great if the crosshair png for guncon2 controllers would auto hide if no device is detected.

This is not possible. There's no direct connection between physical and emulated devices - that's why the bindings are always in the format of `DeviceName/BindingName` - you can have >1 physical device bound to an emulated controller.

> Use just one gun when playing one player but have the emulator permanently setup for 2 players just in case.

This is one of the use cases for input profiles, which we already have.
