### ISSUE TITLE
[Feature Request]: IIDX Controller Support and options

### ISSUE THREAD

**Issue by Marsoff9898** [PCSX2/pcsx2#10176]
### Description

I'd like to suggest IIDX controller support and a IIDX controller layout for Keyboards

### Reason

They are IIDX games like 3rd to Empress, and even Beatmania USA

### Examples

![koc](https://github.com/PCSX2/pcsx2/assets/69320817/ace116d6-46ea-496f-a80f-c2938bb9b5fe)

**Comment by Formedras** [comment]
There is no reason for the PCSX2 developers to add specific support for the beatmaniaIIDX controller. As far as the PS2 itself is concerned, the IIDX controller is just a normal PlayStation digital controller.

All one needs to do is to plug in a regular PS1 digital controller using the same adapter that will be used with the IIDX controller and configure it in PCSX2's input settings. (I'd list the mappings myself but I don't remember them at the moment. Maybe in a later edit or comment. I do remember that Button 7, or the furthest-right White button, is D-Pad Left.)
This cannot be pre-configured by PCSX2's developers because different adapters have different mappings. And some adapters will convert PS1 digital controller D-pad input to the left stick, some will leave it as the HAT switch, and some will map it to additional buttons. The devs cannot know which one is going to be the case.

And if you're planning on using an INFINITAS controller (whether Konami-official or 3rd-party), then you have the extra steps of manually recording which PS2 button/direction corresponds with which IIDX control and setting your INFINITAS controller in PCSX2 accordingly. Again, doing this in advance is not, nor should it be, the PCSX2 developers' responsibility.

**Comment by stenzek** [comment]
Thanks for the info. If there's indeed zero difference, then we can close this. I'd just want to check that the unused buttons are left inactive/high - some of these custom controllers (e.g. the popn controller) permanently pull some of the buttons active/low, and that's how the game identifies their presence.

**Comment by Formedras** [comment]
If the PadTest homebrew is considered sufficient evidence, this screenshot should work. I configured my PlayStation->USB adapter using a DualShock 2 in Analog mode with all face buttons, both sticks (including click), all triggers, the D-Pad, Select, and Start, then unplugged the controller from the adapter and plugged in the *beatmaniaIIDX* controller. After hitting buttons to ensure it worked right, I let go of all buttons and the scratch disc and took the screenshot.

![padtest  _ _padtest_20231210000452](https://github.com/PCSX2/pcsx2/assets/2267190/69b93c87-fc10-4645-9d98-1a7ad00d5fc9)

(Note: this adapter seems to do the D-Pad in digital mode as left stick. The other adapter I have, which decided it didn't wanna stay connected today, keeps it at D-Pad.)

**Comment by stenzek** [comment]
Sounds good. Thanks again for checking!
