### ISSUE TITLE
[Feature Request]: Ability to change the patches folder path

### ISSUE THREAD

**Issue by WiIIiam278** [PCSX2/pcsx2#10219]
### Description

I'd like to be able to change the directory where patches are stored through the Folders section of the settings menu, alongside all other directories.

![image](https://github.com/PCSX2/pcsx2/assets/31187453/60c5dd47-ab32-4d73-8fdb-76d7f83db392)

Currently, patches are always stored in `[installation_directory]/patches` and it is not possible to change this.

### Reason

I'm installing the portable release on Windows to a directory that requires escalated privileges. PCSX2 is not able to create the patch file (as expected; it's in an area where I don't want it to!)

![image](https://github.com/PCSX2/pcsx2/assets/31187453/14819de1-7ba9-44df-aafb-c5923e0cbddb)

However, there's no option for changing this. Accordingly, I can't use the patches feature.

### Examples

I'd like to be able to change the patches directory as with the other runtime data folders through the menu.

**Comment by stenzek** [comment]
> I'm installing the portable release on Windows to a directory that requires escalated privileges.

.. why? You won't be able to save any settings, even if you change all paths in the ini.

Anyway, the options is already in the ini, just not in the UI. But we don't support this configuration in the first place, because the updater doesn't currently elevate.

**Comment by WiIIiam278** [comment]
> .. why? You won't be able to save any settings, even if you change all paths in the ini.
> But we don't support this configuration in the first place, because the updater doesn't currently elevate.

I'm installing PCSX2 on an enterprise network of Windows machines with user privilege control - hence, I can't have (and don't want to have) users be able to use the installer or modify their installation otherwise.

> Anyway, the options is already in the ini

Ah, I must've missed that - will take a look, thank you! Given that you can change (seemingly) everything else through the UI, why not this, though? I don't see why the Folders settings page ought to only have _some_ of the paths be present - and I'd say patches are "runtime data" as the tooltip on that page indicates.

Thanks for the reply and your work!

**Comment by stenzek** [comment]
> I'm installing PCSX2 on an enterprise network of Windows machines with user privilege control - hence, I can't have (and don't want to have) users be able to use the installer or modify their installation otherwise.

Again, this is not a supported configuration. PCSX2 assumes it can write to the data directory for play time stats, configuration, various caches, etc. Even just closing the main window will write to the ini, since the position is saved.

Deleting portable.ini will result in PCSX2 saving to the Documents directory instead, which _is_ a supported configuration (just not what we ship in nightly builds by default). But the updater won't work, because it doesn't elevate itself.

If you're trying to use PCSX2 in some paid environment, then I'll close this issue, because there's legal concerns with that, and we don't want to be associated with the disgusting commercialization of emulation in recent years.

**Comment by WiIIiam278** [comment]
> Deleting portable.ini will result in PCSX2 saving to the Documents directory instead, which is a supported configuration (just not what we ship in nightly builds by default). But the updater won't work, because it doesn't elevate itself.

Yeah; basically, I'm just asking for this setting to be exposed via the GUI to better support patches when installing the portable version in more locked down environments :) In this environment, apps can still read/write to files, it's a case that it's not able to make directories or new files (last I checked!)

> If you're trying to use PCSX2 in some paid environment, then I'll close this issue, because there's legal concerns with that, and we don't want to be associated with the disgusting commercialization of emulation in recent years.

No worries, I'm not making use of this in a commercial context whatsoever :) - purely just to sandbox some stuff in a small-scale educational environment.

Thanks for your work!

**Comment by stenzek** [comment]
Then don't use portable mode. That's the whole point of non-portable mode - it saves to Documents, when `%ProgramFiles%` is not writable. I just haven't added automatic elevation to the updater yet, but this will be done in time for 2.0. We don't support whacky configurations, because it just creates impossible-to-debug issues.

>  purely just to sandbox some stuff in a small-scale educational environment. Apologies for coming across this way; to be honest your language kind of scares me a little 

That's intentional. You're supposed to have a PS2 console, and dump the ROM and games yourself for every instance where you're using the emulator. Any concurrent use of said copyrighted material without equivalent physical copies is piracy, and something we cannot be associated with.

**Comment by WiIIiam278** [comment]
Yeah, issue with not using portable mode for me is I'm not able to deploy to Program Files (that's not where I'm installing to).

Conc. legal stuff: it's my responsibility to follow the law, not yours, though I do appreciate your concern and best interests in the project itself; I agree with you and host a personal dump of the bios on a local network drive to avoid this.

Really, this was just a simple request to add a fairly sensible option for the GUI, which I figured was just missing among the others :) Why not remove the other "Folders" options? I'm just not sure your argument for not adding this option over having the existing set of folder configuration options is that persuasive beyond my setup being unusual (which it is, yes).

**Comment by stenzek** [comment]
Pre-edit, I don't appreciate such remarks. Our metaphorical arse is on the line here too, we cannot knowingly assist anyone who's not following correct legal procedure without putting ourself at risk.

Thread closed and locked.
