### ISSUE TITLE
D3D11's "Bilinear (PS2)" Texture Filtering option is not filtering some textures that the PS2 filters

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#1025]
The "Bilinear (PS2)" Texture Filtering option in the D3D11 renderer is not filtering certain textures that the PS2 is, while the D3D9 and OGL renderers do. If you set the D3D11 renderer to "Bilinear (Forced)" though it does filter the textures, so it's obviously capable of it, it's just not doing it on "Bilinear (PS2)" for some reason. Here's some screenshot examples, look at the bottom-left text and icon:
D3D11, Bilinear (PS2):
![D3D11_PS2](http://i.imgur.com/etZBbTh.png)

OGL, Bilinear (PS2):
![OGL_PS2](http://i.imgur.com/SvKorUz.png)

D3D9, Bilinear (PS2):
![D3D9_PS2](http://i.imgur.com/no1YnYj.png)

D3D11, Bilinear (Forced):
![D3D11_Forced](http://i.imgur.com/5KQ2CZS.png)

This issue can be seen as far back as at least 1.2.1.

**Comment by gregory38** [comment]
Hum, it could be related to an ATI hack. Otherwise code is very close between renderer

**Comment by karasuhebi** [comment]
I have an AMD GPU so that seems like a reasonable assumption to make. Is there anything I can do to help confirm that this is the case?

**Comment by karasuhebi** [comment]
bump.

**Comment by DPersonalized** [comment]
I too have an AMD GPU and this is also happening to me, but in the game I tested, **almost nothing** is being filtered!:

Hardware
![hardware_b3_filter](https://cloud.githubusercontent.com/assets/8225831/12517507/ed22d51a-c12a-11e5-9485-ca2aa4bd6bbb.png)

Software
![software_b3_filter](https://cloud.githubusercontent.com/assets/8225831/12517535/0c4bb34e-c12b-11e5-8b9a-f35bbbdcc35e.png)

The most obvious difference here is in the boxes outlined in blue to the right, which feature sharp steps in color instead of having a smooth transition between the different shades of blue.

**Comment by willkuer** [comment]
For you the sane regarding dx9/11/ogl?

**Comment by DPersonalized** [comment]
Yup. DX9 and OGL are unaffected.

**Comment by sudonim1** [comment]
Could you please provide proof that the PS2 is filtering those same textures? The (PS2) option means that it filters when the GS is set to do bilinear filtering and not otherwise.

**Comment by karasuhebi** [comment]
Sorry I thought I had included these in the OP:
http://i.imgur.com/BrSw44w.jpg
http://i.imgur.com/ouhZbpl.jpg
http://i.imgur.com/OIjUMyR.jpg

**Comment by DPersonalized** [comment]
Here's a screenshot from my PS2 showing the same thing:
![b3_filtering_console](https://cloud.githubusercontent.com/assets/8225831/12536808/1456b010-c2a8-11e5-8c02-79a13c3139f6.png)
