### ISSUE TITLE
[BUG]: Ace Combat 04/Zero - Disappearing terrain under specific circumstances

### ISSUE THREAD

**Issue by PositronCannon** [PCSX2/pcsx2#10271]
### Describe the Bug

In Ace Combat 04, specifically in mission 11 "Escort" (may also happen elsewhere, but I've only noticed it there), large parts of the terrain disappear depending on plane and camera position.

![imagen](https://github.com/PCSX2/pcsx2/assets/65429992/6fd2822a-0c9d-480e-9b59-7b490627355c)

In Ace Combat Zero, the issue only happens when the HUD is disabled, whether in gameplay or during a replay.

![imagen](https://github.com/PCSX2/pcsx2/assets/65429992/ed5c729c-ddc1-4d40-8f0a-8aebdd0604ea)
![imagen](https://github.com/PCSX2/pcsx2/assets/65429992/7c78704a-7046-4e4c-a0f6-cf8e70480011)

Both issues are reproduced on a fresh download of version 1.7.5201, with all settings at their defaults, using the Vulkan renderer. The issue is not reproduced in software mode.

I first noticed this problem last week, but it's probably been there for a while as I hadn't played AC04 for some time or watched replays in ACZ. All I know for sure is that 1.7.4492 does not have this issue.

I've also attached a GS dump for both games.

### Reproduction Steps

For AC04: Start mission 11, get closer to the ground and look around.

For ACZ: Start mission 2, get close to the ground and start a replay from the pause menu, then toggle the replay interface off.

### PCSX2 Revision

v1.7.5201

### Operating System

Windows 11

### CPU

i7-12700H

### GPU

RTX 3060

### Logs & Dumps

[Ace Combat 04 - Shattered Skies_SLUS-20152_20231113001732.zip](https://github.com/PCSX2/pcsx2/files/13329479/Ace.Combat.04.-.Shattered.Skies_SLUS-20152_20231113001732.zip)
[Ace Combat Zero - The Belkan War_SLUS-21346_20231113002231.zip](https://github.com/PCSX2/pcsx2/files/13329480/Ace.Combat.Zero.-.The.Belkan.War_SLUS-21346_20231113002231.zip)

**Comment by Buzzardsoul** [comment]
Can you try changing the blending level to maximum?

**Comment by refractionpcsx2** [comment]
It won't fix it, it needs CPU Sprite Render Size 2.

**Comment by PositronCannon** [comment]
> It won't fix it, it needs CPU Sprite Render Size 2.

Yep, I can confirm CPU Sprite Render Size 2 and set to Blended Sprites/Triangles fixes it in both games. Good to know!

**Comment by stenzek** [comment]
For future reference:

Game draws clouds to 128x128 target at FBP 0x2400 (we end up with 130x130, probably because texture min/max shenanigans and bilinear). Game puts a bunch of texture data after 0x2400, as seen below:

![image](https://github.com/PCSX2/pcsx2/assets/11288319/1817456a-7255-4c0c-82cf-e6f442d4eefb)

PCSX2 ends up hitting the 0x2400 for the terrain draw, when it's expecting the texture data lower down, but this doesn't exist in the target, hence black. Target doesn't expand, because it's reading P8 from a C32 target, and clearly not a channel shuffle. So, loading P8 data into here then reinterpreting a copy back doesn't make sense anyway.

So, we should just skip targets that don't contain our texture data, right? Sure, except for the fact that when they want to sample in the actual target area here (the upper bit), it'll load from local memory instead of the GPU, where the target data lives. Wave Rally does this with its 128x256 reflection target. Because the source is "created later" than the target, it doesn't get invalidated.

So I added a format check, that fixes Wave Rally and Tekken Tag, but Crime Life is still broken. I hate that game and its P8 nonsense. The format check is risky anyway, and having sources created after targets which are "partially stale" is setting up an invalidation nightmare.

Soooooo bugger this, let's just force it to CPU to work around it for now. This'll need a fair bit of thought.

**Comment by stenzek** [comment]
Fixed in #10277.
