### ISSUE TITLE
[Feature Request]: Restore backup save state hotkey

### ISSUE THREAD

**Issue by afgks** [PCSX2/pcsx2#10302]
### Describe the Bug

The restore backup save state feature is missing in 1.7, even with the setting enabled in Settings>Interface.

The third screenshot shows what where the button was in v1.6.

![backupss1](https://github.com/PCSX2/pcsx2/assets/11691936/bcc107f4-5627-415d-a62b-c9d73c382652)
![backupss2](https://github.com/PCSX2/pcsx2/assets/11691936/240b9ee7-c233-47a2-b2fc-1344507db567)
![ss160](https://github.com/PCSX2/pcsx2/assets/11691936/d7b2865c-d094-4ee6-ac6b-ce53af996827)

### Reproduction Steps

Open dropdown menu>System>Load State. The "load backup state" button is missing.
Or press Shift+F3. Nothing happens.

### Expected Behavior

The load backup state button should be in System>Load State.
Pressing Shift+F3 should load the backup save state.

### PCSX2 Revision

v1.7.5222

### Operating System

Windows 11

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/6dc8a8dd-968c-4111-8fad-93f77bcd0a99)
 backup creation works here 
 
F3 dose the same thing in 1.7  it dose on 1.6  (load selected state )

**Comment by afgks** [comment]
I know I can rename the save state file, but that's not what I'm talking about. On v1.6 pressing Shift+F3 restores the save state and the feature is very handy. There's no reason for this feature to be removed.

**Comment by Berylskid** [comment]
It sounds more like a Feature Request instead of a Bug Report.

> F3 dose the same thing in 1.7 it dose on 1.6 (load selected state )

@Mrlinkwii , issue author is talking about __Shift + F3__ instead of just F3.

**Comment by stenzek** [comment]
This is indeed a feature request. Not everything in wx exists in qt.

**Comment by afgks** [comment]
According to the update log this feature should have been implemented in the latest nightly build , but I don't see it actually implemented yet.

**Comment by stenzek** [comment]
Please read the commit more carefully. That change only made the backup files show in the file browser when manually loading a file.

Personally I'm against having a hotkey for this, and the only "clean" way I can think of exposing it in the menu would be with a "backups" submenu. Don't want to pollute the main list with backups.

**Comment by afgks** [comment]
I really admire the work you do for this project, stenzek, but I am not sure if I agree with you on this issue. The Shift+F3 key is actually one of the hotkey I used the most on 1.6.0 after F3. (I do use multiple save states, but there are times I realise I need to go back to the previous save state).
Having this key removed means I will have to at least use my mouse to quit full screen and nagivate the menu, if not renaming the file in File Explorer.

**Comment by stenzek** [comment]
Having a hotkey is not good UX. Most users would be unaware that backups are even created in the first place, and there's no confirmation to load it, nor any indication of how old the backup actually is. At least with a menu, we can have confirmation, and/or display the time/date of the backup, so you're actually aware of what you're loading.

1.6 had objectively terrible UX, in so many ways. Just because it had a feature, doesn't mean it is optimal, or should be kept. Qt UI's been out for almost a year now, and this is the first anyone has mentioned of the hotkey - I didn't even know it existed.

I'm happy to consider adding it as a menu option, but unless someone else on the team disagrees, adding a hotkey isn't going to happen, let alone giving it a default binding. Exiting fullscreen and opening a submenu is fine for something which happens so infrequently, if ever.

**Comment by F0bes** [comment]
We have "Save State and Select Next Slot" or "Select Next Slot and Save State" hotkeys that will allow you to not have to depend on backed up save state files.
