### ISSUE TITLE
Pixz support

### ISSUE THREAD

**Issue by AireagoirSteam** [PCSX2/pcsx2#10315]
### Description

Pixz file support for games which has a file extension of  tpxz or .xz

### Reason

Any tar files some of which pcsx2 already supports are used with pixz they are indexed and compressed so that may eliminate the need of a header file and would also save space.

The compression can be quite good as well since compressed a 5 gb game folder to around 2.88gb.

And since everything is indexed should be quite good for compressed games I hope.

### Examples

Tarballs
Compress and index a tarball, multi-core:

pixz foo.tar foo.tpxz

Pixz can be used in wsl2 on windows.

**Comment by stenzek** [comment]
As far as I'm aware, xz is not a seekable format. Therefore we can't load it without fully decompressing first, which means you'd have an excessively long startup/game scan time, and you may as well just scan it yourself.

TPXZ just sounds like it adds a file index, and splits blocks at files, so you can extract individual files, rather than having to decompress the entire stream. Which IMO is an issue with the tar container, rather than the compression. You can do LZMA in ZIP, for example.

gzip only "works" in this regard because it can be carved up into small blocks. And even then, it still takes a decent chunk of time to build the index.

If this is not the case, we can reopen.
