### ISSUE TITLE
[BUG]: pcsx2 won't dump textures, if precache is enabled

### ISSUE THREAD

**Issue by Kupo91** [PCSX2/pcsx2#10321]
### Describe the Bug

The texture replacement option "Precache Textures" had issues in the past. Apparently someone has worked on it, because it works much better now. However if it's enabled, textures won't be dumped anymore. This behavior was probably not intended?

### Reproduction Steps

![Unbenannt](https://github.com/PCSX2/pcsx2/assets/41426906/13884da3-7ce9-4d5d-b429-f9da302869ab)

### PCSX2 Revision

v1.7.5236

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Can't reproduce with settings above.

**Comment by Kupo91** [comment]
To give an example, I removed the font texture from my texture pack. So this texture should be dumped, when font appears in the game.

With "Precache Textures" disabled, the texture will be dumped as it should:

https://github.com/PCSX2/pcsx2/assets/41426906/6dea52ce-6645-43bb-a2b4-14cd6a70d8ec

With "Precache Textures" enabled, the texture will not be dumped:

https://github.com/PCSX2/pcsx2/assets/41426906/651af194-affc-4972-a92d-8770584e3aed

**Comment by stenzek** [comment]
It doesn't really make sense. Dumping checks whether the texture is in the already-dumped list, or in the "known replacement" lists. Precaching has no effect on either of those.

If you can debug and isolate where the issue is, I'm happy to fix it, but I can't do anything about something that I can't reproduce.

<https://github.com/PCSX2/pcsx2/blob/master/pcsx2/GS/Renderers/HW/GSTextureReplacements.cpp#L734> is a good starting point.

**Comment by kamfretoz** [comment]
Can't reproduce either, works fine here.
