### ISSUE TITLE
[Feature Request]: Per game cheats folders

### ISSUE THREAD

**Issue by Organizationguy** [PCSX2/pcsx2#10324]
### Description

I am trying to set up multiple instances of the same game Kingdom Hearts 2 Final Mix using different overall mods on the steam deck. The issue I'm having is that if I just move the patched iso and the pnach file of each into one instance of pcsx2 the patches contradict and when I use the individual preconfigured windows versions that the creators of the overhall mods included the games do not run. Would it possible to make it so that individual games can be targeted to separate cheat folders to run to keep the pnach files separated?

### Reason

It would allow multiple instances of the same game running different mods and would make it easier to use.

### Examples

I'm not sure.

**Comment by stenzek** [comment]
This isn't possible, because folders are handled separately to the rest of the configuration, and cannot be overridden per-game.

Also, what you're proposing wouldn't work anyway. Per-game configuration uses the serial/CRC as an identifier, same as pnach files. If the serial/CRC is the same across each version, then they'll all share the same per-game configuration too.

Easy fix: Change some bytes in the ELF on the ISO to create a different CRC. That means both the INIs and pnach will both be unique.
