### ISSUE TITLE
[BUG]: `Debugger` - Cannot "unhide" the Debugger toolbar after hiding it

### ISSUE THREAD

**Issue by Risae** [PCSX2/pcsx2#10473]
### Describe the Bug

It doesn't seem possible to "unhide" the Debugger toolbar after hiding it.

### Reproduction Steps

![1](https://github.com/PCSX2/pcsx2/assets/37260321/9fa50108-b430-4ab4-ba19-1802093efa6b)
![2](https://github.com/PCSX2/pcsx2/assets/37260321/cfd97a49-ff1e-4d02-886c-9bd942bcd433)

### Expected Behavior

Unhide works? As far as i can tell only completely restarting the PCSX2 emulator resets this setting.

### PCSX2 Revision

pcsx2-v1.7.5336-windows-x64-Qt

### Operating System

Windows 11

**Comment by Daniel-McCarthy** [comment]
It might make more sense to remove the toggle option completely for this toolbar as I don't believe it provides any benefit. This bug seems more on the lines of if you happen to get into this state you can't undo it, rather than gaining benefit from being able to unhide.

So disabling the context menu on the toolbar might be a more appropriate solution here.
It seems that this toggle option was not really planned for as the `windowtitle` was not set (hence the empty text on the toggle).

**Comment by lightningterror** [comment]
I'd say just remove the toggle option.
