### ISSUE TITLE
[Feature Request]: Don't count paused time towards time played

### ISSUE THREAD

**Issue by F0bes** [PCSX2/pcsx2#10497]
### Description

When you pause the game (Spacebar or System -> Pause), the time played counter should stop counting.

### Reason

I sometimes pause and forget about the game. I end up coming back to multiple hours counted towards my time played.
It now says I have 21 hours in a game when it's more like 5.

### Examples

N/A

**Comment by stenzek** [comment]
Copying what I posted on discord for anyone who wants to implement this:

> you'd need to have an accumulator variable, as well as the start time
> and accumulate on pause, then reset the start time on unpause
> since it's all just time_t differences currently
> (which is fun if the clock goes backwards, but I pretend that's not a thing)

**Comment by TheTechnician27** [comment]
I've been wanting to contribute beyond basic copy-editing of documentation and testing for bugs. Given this is probably an easy enough and low-priority issue, maybe this is where I should get started. So I'll try to see if I understand what's going on correctly here:

- The VMManager is what keeps track of all this while PCSX2 is running, and the GameList is what permanently stores this information (in the case of the time, it uses a struct PlayedTimeEntry to track both the total playtime and when the serial was last played).
- GameListModel.cpp for the Qt interface displays a time played for each game (or nothing if 0 playtime) by pulling from a GameList::Entry struct.
- The Entry struct has the method AddPlayedTimeForSerial, which takes in a serial for the game, the previous time total, and the amount of time to add ('add_time') in order to let UpdatePlayedTimeFile store the playtime.
- This add method is called by the VMManager in its method SaveSessionTime which takes in a serial (I don't entirely know why it's called prev_serial, and that's probably a rabbit hole I shouldn't go down). The session time is not saved,  however, if the user is just running a GS dump.
- In a sense, VMManager::SaveSessionTime relies on GameList::Entry::AddPlayedTimeForSerial relies on GameList::UpdatePlayedTimeFile.
- The VMManager keeps track of play time for the ongoing session using a monotonic timer called s_session_start_time.
- The session time is saved whenever the VMManager calls UpdateDiscDetails (which happens in several circumstances), although the added time is 0 if a GSDump is running.
- There are two VMManager methods called OnVMPaused and OnVMResumed. So it may be possible to keep track of a separate timer for the amount of time paused.
- I.e., we could keep track of a separate time that tracks the cumulative time spent between OnVMPaused and OnVMResumed in the current session.
- When calling VMManager::SaveSessionTime, we could then subtract ptime ('paused time') from etime (I assume this means 'elapsed time'?) and send that modified value as the third parameter for GameList::AddPlayedTimeForSerial. Immediately following that, we could set the paused time back to 0 so we don't undercount the amount of time played.

**Comment by F0bes** [comment]
> When calling VMManager::SaveSessionTime, we could then subtract ptime ('paused time') from etime (I assume this means 'elapsed time'?) and send that modified value as the third parameter for GameList::AddPlayedTimeForSerial. Immediately following that, we could set the paused time back to 0 so we don't undercount the amount of time played.

I was thinking of "cheating" and on `VMManager::OnVMResumed` add the paused time delta to the start time (I guess s_session_start_time?).
I'm unsure if this start time is used for anything else though. Otherwise what you said seems to make sense.

**Comment by TheTechnician27** [comment]
> > When calling VMManager::SaveSessionTime, we could then subtract ptime ('paused time') from etime (I assume this means 'elapsed time'?) and send that modified value as the third parameter for GameList::AddPlayedTimeForSerial. Immediately following that, we could set the paused time back to 0 so we don't undercount the amount of time played.
> 
> I was thinking of "cheating" and on `VMManager::OnVMResumed` add the paused time delta to the start time (I guess s_session_start_time?). I'm unsure if this start time is used for anything else though. Otherwise what you said seems to make sense.

`s_session_start_time` is also used i nthe method `VMManager::GetSessionPlayedTime()` (which would also be updated). However, none of the code I've written modifies `s_session_start_time`.

Currently what I have is as follows:

I've added two variables to the `VMManager` namespace:

- `static u64 s_session_paused_time` keeps track of a timestamp for when the session was last changed from running to paused. This is updated by adding a conditional in `VMManager::SetState` which reads:
```
else if (old_state == VMState::Running && state == VMState::Paused)
	{
		s_session_paused_time = Common::Timer::GetCurrentValue();
	}
```

This conditional should mean that we update this value on the first state when the session is paused. This value subtracted from the current time can be added to a running total (next variable) each time the session is resumed.

- `static u64 s_time_paused_since_last_update` keeps track of the total amount of time paused since the last time `VMManager::SaveSessionTime` was called, i.e. it keeps a running total and is then reset to `0` once `VMManager::SaveSessionTime` runs. Thus, the code in `SaveSessionTime` will go from:

```
const std::time_t etime =
	static_cast<std::time_t>(std::round(Common::Timer::ConvertValueToSeconds(ctime - s_session_start_time)
```

to

```
const std::time_t etime =
	static_cast<std::time_t>(std::round(Common::Timer::ConvertValueToSeconds(ctime - s_session_start_time - s_time_paused_since_last_update)
s_time_paused_since_last_update = 0;
```

Similarly, the code in `VMManager::GetSessionPlayedTime()` will be updated to:

```
return static_cast<u64>(std::round(Common::Timer::ConvertValueToSeconds(ctime - s_session_start_time - s_time_paused_since_last_update)));
s_time_paused_since_last_update = 0;
```

I'm pretty sure the only thing I'm missing here is figuring out when I can calculate the delta, i.e. figuring out when the session resumes.

**Comment by F0bes** [comment]
> I'm pretty sure the only thing I'm missing here is figuring out when I can calculate the delta, i.e. figuring out when the session resumes.

Wont this do what you want in the OnVMResumed handler?

const std::time_t delta = Common::Timer::GetCurrentValue() - s_session_paused_time;

**Comment by TheTechnician27** [comment]
> > I'm pretty sure the only thing I'm missing here is figuring out when I can calculate the delta, i.e. figuring out when the session resumes.
> 
> Wont this do what you want in the OnVMResumed handler?
> 
> const std::time_t delta = Common::Timer::GetCurrentValue() - s_session_paused_time;

Yeah, I would want something like:

`s_time_paused_since_last_update += Common::Timer::GetCurrentValue() - s_session_paused_time;`

In `VMManager::SetState`, there's a conditional:

```
if (state == VMState::Paused)
	Host::OnVMPaused();
else
	Host::OnVMResumed();
```

Since it's probably improper for me to mess with the `OnVMResumed` handler itself, I'm thinking about this:

```
if (state == VMState::Paused)
	Host::OnVMPaused();
else
	Host::OnVMResumed();
	s_time_paused_since_last_update += Common::Timer::GetCurrentValue() - s_session_paused_time;

```

However, I can't explain why, but this feels like spaghetti.
