### ISSUE TITLE
[Enhancement] Emulating Useful Functions

### ISSUE THREAD

**Issue by trader5896** [PCSX2/pcsx2#1058]
Level: Low priority

I would like to suggest for the perfection of emulation of the PS2, we should add basic DVD functions and Controller functions:

Tray open (with Hotkey DEL)
Tray close ( pressing againg Hotkey DEL)
Controller Slot 1 Added (with Hotkey page UP)
Controller Slot 1 Removed(with Hotkey page UP)
Controller Slot 2 Added (with Hotkey page DOWN)
Controller Slot 2 Removed(with Hotkey page DOWN)
Memory Card 1 Added  (with Hotkey POS1)
Memory Card 1 Removed (with Hotkey POS1)
Memory Card 2 Added (with Hotkey END)
Memory Card 2 Removed (with Hotkey END)
Network Cable In (With hotkey paste)
Network Cable out (With Hotkey paste)

There are some games, which output a text or something, if you remove a controller or the disc from the tray. I just want this to be emulated, even this is not very important for first. This is just for 100% certainity.

**Comment by willkuer** [comment]
Are there scenarios where you need those functions?

I don't know if I ever played a game that required one of these options. Maybe those controller and memory card features for strange metal gear solid levels but:
tray open/close and network in/out? I can not imagine where you need this... (is tray open/close forwarded to your disk drive?)

Hotkeys is a bad topic btw. Almost all denormal hotkeys are used. Some even twice with shift/alt flags.
The problem is that some users use the keyboard (I did it for a long time) and mapping of input controls can collide with hotkeys. Keeping hotkeys as minimal as possible would be good.

**Comment by trader5896** [comment]
@willkuer , this is as said Low priority, therefore not needed. But if PCSX2 is a ps2 emulator, who will emulate the ps2 fully, than this is required. Because on the real ps2 you can open the tray, close it again, take off the network cable, take it in..


For me the tray open thing could be intresting, because, this is the only way of winning ff9(psx game, which is not emulated at this time) within 12 hours for Excalibur 2. But this said, this is just trivial matter, not a serious one.

Just for the perfection of this emulation of the ps2, I mentioned it here.

And the denormals are used by most emulator, without any problems.... But hotkeys should be less as possible and mappable.
