### ISSUE TITLE
[Bios] Bios Dumping Wizard at the first Start of PCSX2

### ISSUE THREAD

**Issue by trader5896** [PCSX2/pcsx2#1060]
Priority: Low priority

At the tab, where the Bios is selected, we could add a Wizard, where there are pictures shown and a little text, how to dump the bios from ps2. And they can directly dump it from that tab.

1.) Bios Tab: "If you don't have the bios, please click here."
2.) Bios Dumping Wizard: "Please Connect your PS2 with this that"....(don't want to explain all in detail.
There will be pictures showing this like in some jailbreak tutorial softwares....
3.) Bios extracted: "Where do you want to save it?" (Standart folder is always "%CURRENTDIR%\Bios"

This would be much more easy for people I think

**Comment by mirhl** [comment]
Connect this that what?
You need to be able to launch homebrews in order to use BIOS dumper (which is no straightforward feat)
And in turn this needs FMCB or similar exploits that nevertheless requires special "hardware". 

If any, at most, I agree more should be written to streamline these steps. 

At the moment most guides have the "screw you, we don't cover how to launch this" premise. 
And really, this is really discomforting, especially when you want to do all legal like I did. And not to mention had I been noob.
