### ISSUE TITLE
[Question] What does the EETiming Hack actually do?

### ISSUE THREAD

**Issue by trader5896** [PCSX2/pcsx2#1064]
I read all forums and whatever documentation is available, but there is no real explantation, what it does? This hack is the most important one, because most games, which are patched in the database are using this hack. I mean, I'm gone make a list soon in another Issue, where all games are listed, which require EETiming hack and which are broken by EETiming hack. Perhaps this is not needed and a Dev could find the main reason, why the games require this hack.

**Comment by ssakash** [comment]
I think questions like these are better directed to the forums, just to keep the issue tracker clean. :) 

Answering your initial question, the EE timing hack just delays the events / schedules at the EE by 8 cycles instead of triggering them whenever it's requested. this seems to fix some games which are more timing sensitive. I'm sure @refractionpcsx2 can explain it better.

**Comment by trader5896** [comment]
Yeah you mean something like:

Normal Behaviour: Event request--> Triggering the event
EE Behaviour: Event request--> Delay 8 Cycles--> Trigger the event

I mean the EE should be able process the Events as they are requested, but why do we have to wait 8 cyclyes? Normally it should be processed as it's triggered. Perhaps, I think, that this is the main reason, the DMA, VU's should stall the packets, til the EE is ready to process these events. Which should fix this in any way.

**Comment by gregory38** [comment]
There are forums available for this kind of non issue. Please avoid to spam the issue tracker.

**Comment by trader5896** [comment]
@gregory38 okay I will close it.
