### ISSUE TITLE
[Feature Request]: Set emulator settings in a .pnach patch

### ISSUE THREAD

**Issue by PeterDelta** [PCSX2/pcsx2#10797]
### Description

I would like to implement the following emulator functions to put them in the .pnach that require it:
  - Function to enable FMVs to be played in software mode. This would help some FMVs to look pixelated when the resolution is rescaled and also the patches that enable progressive with gsinterlacemode=1 to switch to software and change the interlacing from "none" to "Adaptive" automatically, preventing it from shaking.

  - Function to change the FMV aspect to 4:3. This function is very useful for those widescreen patches that have not been adjusted to 16:9, preventing the image from being stretched.

### Reason

I know that these 2 functions can be enabled from the emulator and for each game but you have to spend some time configuring them all and the idea is to have it automated. For example, these functions can be put in the widescreen patches under "gsaspectratio" or "gsinterlacemode" so that the end user, when running the game simply by having the widescreen patch or interlace enabled, does not have to configure anything else .
Also, in many cases the emulator's default interleaving is more correct than patches that remove the "sceGsSetHalfOffset" routine.

### Examples

This is the function of the emulator and I propose creating access to it to include it in the pnach that need it.

![59](https://github.com/PCSX2/pcsx2/assets/151682118/9b5c3070-5f64-41ac-bce1-2dd494b511f8)

**Comment by refractionpcsx2** [comment]
setting the sw mode switch should be done in the game db, if games require it, then a PR to add them to the GameDB should be submitted, this kind of thing shouldn't really be in pnach files.

The ratio for FMV's could maybe be done, I take it it defaults to 4:3 and doesn't really listen to the widescreen aspect? so I guess it makes sense if the game does adjust the aspect (considering the videos are normally recorded in 4:3)

**Comment by Gabominated** [comment]
> setting the sw mode switch should be done in the game db, if games require it, then a PR to add them to the GameDB should be submitted, this kind of thing shouldn't really be in pnach files.
> 
> The ratio for FMV's could maybe be done, I take it it defaults to 4:3 and doesn't really listen to the widescreen aspect? so I guess it makes sense if the game does adjust the aspect (considering the videos are normally recorded in 4:3)

Hey bro, I was talking with Peter about this hack called use software renderer to FMVs because with are debugging patch with addresses that change to progressive mode all the game except videos but we most use gsinterlacemode=1 so videos will shake because keep in PAL or NTSC and using this hack at pnach we can avoid shake at videos and it's most easily for users when a patch automatic set those configurations.

**Comment by refractionpcsx2** [comment]
the sw switch forces the interlace mode to adaptive, since fmv's rendered for the PS2 expect interlacing to be on, but it's very difficult to do so for hardware mode, since this is kind of baked in to the software fmv switch.

If this is the only reason for wanting it for the patches then hmm, I'm not sure the best way to deal with that, cos we don't really want to add gamefixes just for widescreen hacks

I'll have a talk with the guys at some point, see if we can decide on something... I'm sure there was a reason I didn't change it for hardware mode.

**Comment by Gabominated** [comment]
> the sw switch forces the interlace mode to adaptive, since fmv's rendered for the PS2 expect interlacing to be on, but it's very difficult to do so for hardware mode, since this is kind of baked in to the software fmv switch.
> 
> If this is the only reason for wanting it for the patches then hmm, I'm not sure the best way to deal with that, cos we don't really want to add gamefixes just for widescreen hacks
> 
> I'll have a talk with the guys at some point, see if we can decide on something... I'm sure there was a reason I didn't change it for hardware mode.
> 
> Edit: Ah I remember now, because FMVs playing can be falsely triggered by games putting FMV's in games, and you don't want the renderer/interlace mode switching in the middle of a game, that would be problematic.

Alright, well that's will nice if they can implement this of somekind of command like gsinterlacevideomode= but I understand if decided that isn't good idea, no big deal, thank you anyway.
