### ISSUE TITLE
[Feature Request]: Absolute pointer and joystick support for usb mouse

### ISSUE THREAD

**Issue by nixxou** [PCSX2/pcsx2#10863]
### Description

It would be great if the PS2 mouse pointer would support absolute mouse movement instead of just relative movement.
I don't really know if that's technically doable or how hard it would be to implement it, so feel free to close the issue if it's not doable. 
And if it's doable and you willing to give a shot, you can just add HalfAxis RelativeUp / Down / Left /Right option like in the guncon2 and convert joystick value to absolute x,y coord and it will be just great.

### Reason

The usecase i have in mind is the Silent Scope serie.
Guncon is not working for this game, it's Konami gun.
Using relative mouse, we can't just point and shoot, it drag cursor around.
Absolute mouse would fix that issue.

Also, i think it would make the usage of mouse much more responsive.

### Examples

I'm not sure, but i think the old nuvee plugin use absolute mouse : 
https://github.com/mirror/nuvee/blob/master/nuvee_ps2_usb%20-%20guncon2%2C%20keyboard%2C%20mouse/src/mouse.cpp
Since i read #define PS2MOUSE_READMODE_ABS 1, but i'm not sure it's for reading the value from the user mouse or to send it to the ps2.

**Comment by stenzek** [comment]
USB mouse doesn't provide absolute coordinates to begin with - the HID packets are relative (see https://github.com/PCSX2/pcsx2/blob/master/pcsx2/USB/qemu-usb/hid.cpp#L664-L670). So an "absolute" mode would just be a giant hack that passed a massive delta for a single packet when the position changes after being off-screen, which would break if a game applies any post-processing to the values (e.g. smoothing).

Virtualization applications "solve" this by emulating a drawing tablet instead of a mouse. But I'd be surprised if the game supported that.
