### ISSUE TITLE
[BUG]: Incorrect Internal Resolution for internal res screenshots

### ISSUE THREAD

**Issue by Sukotto-1999** [PCSX2/pcsx2#10922]
### Describe the Bug

Screen resolution when taking screenshots at internal res is always incorrect. (Especially a game running in 512x448, but screen resolution is always 640x448 for latest PCSX2 nightly)

Game used: Aa Megami-sama

![Aa_Megami-sama_-_Title](https://github.com/PCSX2/pcsx2/assets/80495917/b3ea8ed4-9e95-4c53-883a-fe86f8fcbe79)
512x448

![Aa Megami-sama_SLPS-25743_20240312103925](https://github.com/PCSX2/pcsx2/assets/80495917/60c0354e-c238-42b2-aa47-e098cc40d044)
640x448 taken in latest PCSX2 nightly

### Reproduction Steps

Take a screenshot at the internal resolution

### Expected Behavior

When taking screenshots, screenshots should be the expected resolution (especially if game runs at 512x448, screenshot should be 512x448)

### PCSX2 Revision

1.7.5611

### Operating System

Windows 11

**Comment by Sukotto-1999** [comment]
No. The aspect ratio corrected option does not mean the resolution is 512x448.

**Comment by refractionpcsx2** [comment]
I know. I'm saying the screenshot is the correct size, the options are the wrong way around.

**Comment by stenzek** [comment]
This is invalid, and working as intended. See https://github.com/PCSX2/pcsx2/blob/b4992856f7e475b0a4a26aafb997baa69278ec13/pcsx2/GS/Renderers/Common/GSRenderer.cpp#L955-L981

The "Internal Resolution" option takes the internal/render resolution, and scales it to the correct aspect ratio based on the width or height (whichever is larger, to preserve detail). This **will not** match the displayed resolution in the OSD, because the displayed resolution is not corrected. Many PS2 games do not use square pixels.

The "uncorrected" option uses the "real" internal resolution, and will match the OSD. Most users don't want screenshots in a completely different aspect to what is actually displayed, since this gets further exacerbated in widescreen modes.

Perhaps the "Internal Resolution" option should have "Aspect Corrected" suffixed on it, but IMO since there is a separate uncorrected option, obviously the first one implies it is corrected.

If there's a particular game that is behaving incorrectly according to the above, upload a GS dump and we can investigate. But there isn't really much that can go wrong in that routine.

**Comment by Sukotto-1999** [comment]
Still no, "Internal Resolution" with "Aspect Corrected" subfix does not mean the resolution is 512x448. I want to document the regional differences for the Ape Escape PS2 games for the TCRF, and the 640x448 resolution while game resolution if 512x448 does mean the TCRF admins would ban the life out of me. PERIOD!

**Comment by RedDevilus** [comment]
Are we talking about the framebuffer at this rate or texture sizes, or just the video signal? It does matter. That doesn't even address if overscan was enabled which can also influence it and regional variant even in the same region.

**Comment by Sukotto-1999** [comment]
Whoops, i mean the framebuffer.

**Comment by refractionpcsx2** [comment]
The PR #10888 names them correctly. I was wrong in my assumption of the naming, it actually said Uncorrected, which is the option you actually want, but the PR mentioned clarifies the options so there's no confusion.

**Comment by Sukotto-1999** [comment]
Okay, i have a recap. For a game running 512x448. When taking screenshots the size is always 640x448 leaving the screenshot setting to Aspect Corrected means the resolution is 640x480.

**Comment by refractionpcsx2** [comment]
Aspect corrected: 597x448
![Aa Megami-sama_SLPS-25743_20240313195122](https://github.com/PCSX2/pcsx2/assets/6278726/717582a7-3c8e-426a-b239-6e3e23515e88)

Aspect Uncorrected option: 512x448
![Aa Megami-sama_SLPS-25743_20240313195133](https://github.com/PCSX2/pcsx2/assets/6278726/3683e2bf-262d-4ead-8faf-66bec2843e2a)

If you're not getting this, then you've probably ticked "screen offsets".

**Comment by Sukotto-1999** [comment]
Okay, so i ticked off "Screen Offsets" and . . .  it works! So now the screen resolution is 512x448 for screenshots, thank you:

Title screen (taken with PCSX2 nightly):
![Aa Megami-sama_SLPS-25743_20240314083335](https://github.com/PCSX2/pcsx2/assets/80495917/db98cab7-ced5-443c-9b56-8c30d7656ae0)
Event scene:
![Aa Megami-sama_SLPS-25743_20240314083412](https://github.com/PCSX2/pcsx2/assets/80495917/08764d6a-95bb-45b9-a4f8-09d935e0f7fe)
Stage Select:
![Aa Megami-sama_SLPS-25743_20240314083423](https://github.com/PCSX2/pcsx2/assets/80495917/16ac51ee-2970-4845-8c44-fa87eca67d35)

**Comment by refractionpcsx2** [comment]
just to elaborate, the PS2 *always* outputs at 640x448 or 640x512 (depending on NTSC/PAL), but the dimensions get zoomed in depending on what it renders at at the PCRTC settings.

So when you enable screen offsets, it attempts to emulate this 640x448/512 output, so that's what your screenshots will come out as.
