### ISSUE TITLE
[BUG]: invertL and invertR setting incorrect in bigpicture mode

### ISSUE THREAD

**Issue by Tartifless** [PCSX2/pcsx2#10935]
### Describe the Bug

When setting invertL and invertR in the pcsx2-qt interface to "not inverted", the value is set to 0 in pcsx2.ini file, which is correct, but it shows as "UNKNOWN" in BigPicture mode.
Then, when setting "not inverted" in Bigpicture mode, the values are set to "1" in pcsx2.ini, which appears as "inverted left/right" in pcsx2.

It seems the starting index of the options is 0 in pcsx2 but BigPicture starts at 1. Which leads to inconsistencies.

### Reproduction Steps

Launch a game and open BigPicture mode, go to controller settings and set stick inversion to "not inverted".
Close pcsx2 and launch pcsx2-qt.exe

Check controller settings

### Expected Behavior

Alignment of values between BigPicture and pcsx2-qt.exe

### PCSX2 Revision

v1.7.5617

### Operating System

Windows 11

**Comment by gytdoo** [comment]
I’ve also just encountered this on the AppImage. Using my DualShock 2 and steam deck controls result in the same outcome of horizontal stick outputs being reversed.

What’s even stranger is changing the settings in or out of game has no effect. Remapping the sticks does nothing. Editing the ini doesn’t help either.

I’ve disabled steaminput in order to map my DualShock 2 with pressure sensitive buttons, so I can’t even fix this using the steam overlay.

On the latest appimage (1.7.5672) and running the stable branch of steamos

**Comment by stenzek** [comment]
Fixed by https://github.com/PCSX2/pcsx2/commit/d62602820393953fd405a51bdf4d179dd0d8b26d
