### ISSUE TITLE
[Request] GDSX 7x Native

### ISSUE THREAD

**Issue by shinra358** [PCSX2/pcsx2#1098]
I would like to request 7x native. If there is a question about why, a short discussion is here:
http://forums.pcsx2.net/Thread-GSdx-1-0?pid=501689#pid501689

**Comment by gregory38** [comment]
It would only create more glitches for a rendering close of 6x or 8x.

**Comment by DPersonalized** [comment]
I think the problem here is that the reason not to include a 7x option was never really explained all that well. When you say it "creates more glitches", not a lot of the users know what you mean, and they'll often ask "if you can include 6x and 8x, why can't you include 7x?"

If anything, someone should write an explanation on the forum to clear up the confusion.

**Comment by shinra358** [comment]
So when custom rez is removed, then what? That means no one would be able to use the high end 4K. Only the low end one.

**Comment by MrCK1** [comment]
The shimmering you are seeing is probably due to lack of mipmapping in hardware mode; which is not possible at this time

**Comment by SwinglesMan** [comment]
Ah, nevermind about the shimmering. It was because 8bit texture allowance was on.

**Comment by shinra358** [comment]
Nevermind about the shimmering. It was because 8bit textures was on which turned of Aniso.

**Comment by gregory38** [comment]
At the end of the day, you need to interpolate texture pixels. Not power of 2 resolution just create more rounding issue. And I seriously doubt there is any rendering improvement between 6x and 8x. So 7x is useless (and honestly likely 5x too). And again this factor isn't related to the screen resolution.
