### ISSUE TITLE
[BUG]: GUI, low-res stars in HiDPI mode

### ISSUE THREAD

**Issue by Bonney01** [PCSX2/pcsx2#11026]
### Describe the Bug

Main UI, list mode, Compatibility column, stars are low-res in HiDPI mode.
![low-res](https://github.com/PCSX2/pcsx2/assets/165537229/fedd28fc-fa07-4924-a5dc-a81af8c30d6b)

### Reproduction Steps

N/A

### Expected Behavior

hi-res stars

### PCSX2 Revision

Latest

### Operating System

Windows 11

**Comment by RedDevilus** [comment]
I tried fixing this last time, the problem is that it's a single element that is not downscaling properly, so it goes gigantic and offscreen. So I just put it to lower priority personally, but yeah it's also not using svgs to avoid issue if you put your monitor at 150%. The other GUI elements have gone through not aliased effects about any percentage.

**Comment by kamfretoz** [comment]
Tried tackling it before, but it didn't go so well.

![image-26.png](https://github.com/PCSX2/pcsx2/assets/14798312/1e349563-f033-4018-93e7-50a288e2a13c)

**Comment by stenzek** [comment]
I have a hidpi display, and never noticed any issue with it.

If anyone wants to submit a pull request with new icons, go nuts, but this isn't a bug per say.
