### ISSUE TITLE
[Feature Request]: Add extra configuration files when starting from the command line

### ISSUE THREAD

**Issue by crashGG** [PCSX2/pcsx2#11087]
### Description

hope to have an extra configuration file that, when launched from the command line, can load the game's custom diff configuration.

for example: 

pcsx2-qt.exe "Urban Reign (USA).iso" --appendconfig="Urban Reign (USA).ini"

### Reason

All users who use a fancy frontend to manage game startup and loading will benefit.the existing stand-alone game-specific's configuration file is stored in the **\gamesettings** directory in the form of a game serial number, which makes it inconvenient for the front end to associate the game.ini with the game name.

### Examples

ppsspp

ppsspp --gamesettings FILE --appendconfig FILE

see:
https://www.ppsspp.org/docs/reference/command-line/

**Comment by stenzek** [comment]
This is redundant with per-game settings.

We're also not in the business of doing for-profit frontend's work for them. As far as I'm concerned, PCSX2 provides sufficient functionality for them to be redundant for PS2 (Big Picture, Per-Game Settings, Input Profiles, etc).

**Comment by crashGG** [comment]
There are so many free and excellent front-end programs in this world. I am sorry that you default to them as "for-profit". Perhaps in addition to having strong coding skills, a person also needs ainclusive attitude and open heart.

**Comment by stenzek** [comment]
The majority are, and are legally questionable since they download cover art and such. We can't be associated with such things, especially in light of recent events.

We use the serial and "CRC" to identify game configs, because one or the other isn't sufficiently unique. If you can't parse discs and compute this information, then that's your problem, not ours. I'm more than happy to accommodate reasonable feature requests. But providing hacky workarounds for your broken/lacking frontend is not reasonable.

Or, y'know, instead of going straight to throwing insults at of the developers who's software you benefit from, use the game properties editor in PCSX2 itself :). There's both desktop and big picture variants available.

**Comment by crashGG** [comment]
https://wiki.pcsx2.net/Command-line_support
I noticed that the pcsx2 WX version also supports the --cfgpath and --cfg= parameters to specify the cfg path and file. The QT version has removed this function. What is the significance of this? Will there be old users who are uncomfortable with this?

**Comment by JordanTheToaster** [comment]
> https://wiki.pcsx2.net/Command-line_support I noticed that the pcsx2 WX version also supports the --cfgpath and --cfg= parameters to specify the cfg path and file. The QT version has removed this function. What is the significance of this? Will there be old users who are uncomfortable with this?

You have per game settings which renders that moot I don't see the point in continuing this.

**Comment by stenzek** [comment]
The config system is layered, so doing anything in this regard is not that difficult. However, it is a UX issue.

>  The QT version has removed this function. What is the significance of this?

If you're overriding the game settings layer, what happens if you switch to a different disc? We use the disc elf to identify the gamesettings ini, so the ini which is loaded would change. Which one takes precedence?

What happens if the user changes a setting in the in-app pause menu or game properties? Now you have an external file taking precedence over the change that the user just made.

WX didn't support per-game settings, and therefore it was a non-issue. Since Qt does, the two would conflict. WX was the king of terrible design choices, it absolutely makes sense that not everything is brought across 1:1.

> Will there be old users who are uncomfortable with this?

If it's such a big deal to them, they're free to continue to use 1.6/WX, nobody's taken that away. Accommodating every user's niche request is impossible, we make the choices that provide the least UX resistance/confusion for the majority of users. Having too many options is detrimental.

**Comment by crashGG** [comment]
I see
