### ISSUE TITLE
[BUG]: Need for Speed Underground 2 suffering slowdowns after the Vsync update

### ISSUE THREAD

**Issue by madruded** [PCSX2/pcsx2#11323]
### Describe the Bug

After the recent Vsync update on the emulator, the game Need for Speed ​​Underground 2 has been experiencing slowdowns and stutters with it active, on the Vulkan engine. The slowdown occurs mainly in the car menu, making it horrible to use.

Before this update, the game ran excellently with Vsync active. I tested other games and they all ran normally on the emulator with Vsync active.

### Reproduction Steps

1 - Open the game
2 - Go to main menu game
3 - Choice the car

### Expected Behavior

It should run in an original way, without sudden horrible drops in emulation with Vsync active.

### PCSX2 Revision

v1.7.5860

### Operating System

Windows 11

### CPU

AMD Ryzen 5 4600G

### GPU

AMD Radeon RX 6600 8GB

**Comment by stenzek** [comment]
Then don't turn on vsync. The behaviour "now" on AMD is exactly the same as it originally was - using FIFO, because Mailbox isn't supported by AMD drivers.

Vsync with mismatched refresh rates (the PS2 is not 60hz) will result in dropped frames at worst, or stutter at best. Either sync to refresh, or turn it off/use VRR.

**Comment by inpain1994** [comment]
This issue is still occuring with or without vsync in this game. Gameplay slowdown not only in menus as well as in game. Becomes even worse when the game is in fullscreen mode.

**Comment by refractionpcsx2** [comment]
Then it would be useful to find out when that started.  This game has always been kinda heavy, though.

**Comment by inpain1994** [comment]
Yep, apologies. I'll post that now.

For my own purposes: I'm running on a 1TB OLED Steam Deck

Game was running perfectly on my Deck with no noticeable slowdown at all from at least 1.7.5788. I don't recall updating from that point but I could be wrong and happy to see what others say RE: versions. Definite game slow down, with audio and FPS issues.

Irrelevant to this specific case, but i've noticed some issues in other games with similar slowdown issues seemingly around this update, but I am still tinkering with settings and the like before I make a report.

**Comment by refractionpcsx2** [comment]
almost 80 builds have happened since then, so it doesn't really narrow it down too much, but it would be good if you can run older versions in between to try and narrow down where it went wrong. 

I could check but it may not easily show because I'm using a desktop

**Comment by ghost** [comment]
is this ever getting fixed, its driving me insane, it makes Vulkan useless in like every game for me, look it happens to this random dude too years later, blah
https://www.reddit.com/r/SteamDeck/comments/1hbxweb/ps2_nfsu2_performance_drop_when_in_full_screen/

**Comment by davyvs** [comment]
**Workaround: use the OpenGL renderer** — data point from an ARM/Android fork

Seeing the same NFS Underground 2 car-menu slowdown on **ARMSX2 2.6.3**
(Android fork of AetherSX2/PCSX2) — Retroid Pocket 6, Snapdragon 8 Gen 2 /
Adreno 740, Android 13:

- **Symptom:** racing runs at full speed, but the Body Shop / garage drops to
  ~11 FPS on the **Vulkan** renderer.
- **Workaround:** switching the renderer to **OpenGL** completely restores full
  speed in the menu/garage, with no visible change to in-game rendering.
  (Blending Accuracy High, 3× upscale — otherwise unchanged.)

Posting in case it helps others who land here: the slowdown is specific to
**Vulkan + the car menu**, and OpenGL sidesteps it entirely. This is a mobile
GPU / fork, so it may not share the exact upstream cause, but the
Vulkan-vs-OpenGL + car-menu correlation matches what's described here.

Game: NFS Underground 2 (USA), SLUS-21065.
