### ISSUE TITLE
Graphical Corruption on opening screens and title screen in Onimusha - Dawn of Dreams

### ISSUE THREAD

**Issue by Masamune3210** [PCSX2/pcsx2#1141]
When started, the game will first ask for a system save on a mem card, after that the opening few screens and the title screen will have major graphical corruption. Opening video is not affected. Log is spammed with "libdma: sync timeout".

Version - pcsx2-v1.5.0-dev-165-g6dd83d3-windows-x86
Video - https://youtu.be/BBIs9BKQbew
Log - https://gist.github.com/deadair3210/b954d2ce710ffd9ff079

**Comment by refractionpcsx2** [comment]
Yeah the game is a mess, got a ton of IPU problems, the only reason it works (and looks like that) is because we have a patch ignoring the problems :)

**Comment by RazielZnot** [comment]
Such a nasty bug... Did somebody looked into it all this time? Or it requires lots of work?

**Comment by winapp2** [comment]
Onimusha 4 - Dawn of Dreams

This games requires a patch (provided by Shadow Lady) to start, if you don't start with the patch,
it won't start, but it will produce the endless bug:
"libdma: sync timeout (a few times)
IPU Invalid Intra DC Precision, switching to 9 bits"

As known, the 2D Graphics in this Game are not processed, because of the 
shortcoming of GIFdma implentation. This is still as for 05. May 2015 existent and it doesn't matter,
if you select HW or SW and has nothing to with these both.

As said by the old Forum, this is how signal is processed:

"The game performs SIGNAL in the GIF and then performs another SIGNAL before the first is processed.
GS manual claims that GS should halt (what does this word mean???) in these situations. If I'm not mistaken,
PCSX2 doesn't. Might be mistaken, though."

And I think, what I understand from this Emulog (which is growing just on 2D stages to few GB in minutes, 
because of this bug) and what the user in the old forum said is:

: "�IMAGE�IMAGE.AFS;1" --> It send to IPU.cpp (which is corrupeted) --> Corrupted picture on 2D stages.

Source-Code\pcsx2\Ipu\IPU.cpp
...
"
{
// Note: It's assumed that mem's input value is always in the 0x10002000 page
// of memory (if not, it's probably bad code).

pxAssert((mem & ~0xfff) == 0x10002000);
mem &= 0xfff;

switch (mem)
{
    ipucase(IPU_CMD): // IPU_CMD
        IPU_LOG("write32: IPU_CMD=0x%08X", value);
        IPUCMD_WRITE(value);
        IPUProcessInterrupt();
    return false;

    ipucase(IPU_CTRL): // IPU_CTRL
        // CTRL = the first 16 bits of ctrl [0x8000ffff], + value for the next 16 bits,
        // minus the reserved bits. (18-19; 27-29) [0x47f30000]
        ipuRegs.ctrl.write(value);
        if (ipuRegs.ctrl.IDP == 3)
        {
            Console.WriteLn("IPU Invalid Intra DC Precision, switching to 9 bits");
            ipuRegs.ctrl.IDP = 1;
        }

        if (ipuRegs.ctrl.RST) ipuSoftReset(); // RESET

        IPU_LOG("write32: IPU_CTRL=0x%08X", value);
    return false;
}
return true;
}

// returns FALSE when the writeback is handled, TRUE if the caller should do the
// writeback itself.
__fi bool ipuWrite64(u32 mem, u64 value)
{
// Note: It's assumed that mem's input value is always in the 0x10002000 page
// of memory (if not, it's probably bad code).

pxAssert((mem & ~0xfff) == 0x10002000);
mem &= 0xfff;

switch (mem)
{
    ipucase(IPU_CMD):
        IPU_LOG("write64: IPU_CMD=0x%08X", value);
        IPUCMD_WRITE((u32)value);
        IPUProcessInterrupt();
    return false;
}

return true;
"

As this bug exists, the emulog will grow to a few GB's as long you are in 2D Menu's. If you leave, it will end growing.

For more info, please provide informations...

Please rename the jpg to zip to look for the file.

**Comment by winapp2** [comment]
@gregory38 ; @refractionpcsx2 

Please close this issue here:

https://github.com/PCSX2/pcsx2/issues/524

**Comment by refractionpcsx2** [comment]
Done

**Comment by MagicPro1994** [comment]
Is this bug still existing?

**Comment by refractionpcsx2** [comment]
As far as I'm aware, yes.

**Comment by ivan89el** [comment]
Exactly yes

**Comment by lightningterror** [comment]
Do none of the hw hacks help ?

**Comment by refractionpcsx2** [comment]
No, there's a patch to get around it, but that's it

**Comment by ivan89el** [comment]
Hw hacks are unlikely to help

**Comment by kokutoukiritsugu** [comment]
pcsx2-v1.5.0-dev-2484-gd258ef627-windows-x86
still existing


![snipaste_2018-08-13_21-26-43](https://user-images.githubusercontent.com/5471433/44034470-be69c1e8-9f3f-11e8-9692-56888a806346.jpg)
![snipaste_2018-08-13_21-26-58](https://user-images.githubusercontent.com/5471433/44034475-c1b2e91a-9f3f-11e8-8cb1-43235e9efb01.jpg)
![snipaste_2018-08-13_21-27-15](https://user-images.githubusercontent.com/5471433/44034476-c1eb0f70-9f3f-11e8-871f-ca6e9b642874.jpg)
![snipaste_2018-08-13_21-27-35](https://user-images.githubusercontent.com/5471433/44034477-c21048bc-9f3f-11e8-8e87-aba506450d49.jpg)

**Comment by theStamos** [comment]
I'm completely unversed in this, but the topic is still open. Is there any possibility of this garbage bug getting fixed?

**Comment by MagicPro1994** [comment]
> 
> 
> I'm completely unversed in this, but the topic is still open. Is there any possibility of this garbage bug getting fixed?

Not yet.

**Comment by Zarbucks** [comment]
With this option the message stops appearing and the menu fps return to normal, sorry for my bad English


<a href="https://ibb.co/xfDFyD1"><img src="https://i.ibb.co/X3bY9b7/oni.png" alt="oni" border="0"></a>

**Comment by AdalbertoRodrigues** [comment]
Any news about this issue?

**Comment by Lolibox** [comment]
> Any news about this issue?

improved with an updated patch, still broken.
https://forums.pcsx2.net/Thread-Fixing-unplayable-games?pid=619166#pid619166

**Comment by AdrianoMoser** [comment]
Apparently no news about that. Am I right?

**Comment by raul3d** [comment]
In case it helps: with a patch to bypass the crash on boot, the game renders the 2D elements correctly in Play.

**Comment by AdrianoMoser** [comment]
Yeah, I've managed to get to play it, with some level of correction. However, it's not perfect yet.

**Comment by Lolibox** [comment]
kozarovv's updated fix should be appended to the gameindex, felix has ported it to the other versions of the game as well.

**Comment by RedDevilus** [comment]
Any patches that just 'fix' HW renderer partially won't be added. That attitude let us not caring about real fix.

**Comment by RedDevilus** [comment]
Oh nevermind seems it's an IPU patch.
