### ISSUE TITLE
PCSX2 stable doesn't seem to be working on Ubuntu 15.10

### ISSUE THREAD

**Issue by amnesiac-kid** [PCSX2/pcsx2#1143]
I added the ppa and tried to install it and got the following errors: 

The following packages have unmet dependencies:
 pcsx2:i386 : Depends: libgdk-pixbuf2.0-0:i386 (>= 2.22.0) but it is not going to be installed
              Depends: libglib2.0-0:i386 (>= 2.12.0) but it is not going to be installed
              Depends: libgtk2.0-0:i386 (>= 2.24.0) but it is not going to be installed
              Depends: libwxgtk3.0-0v5:i386 (>= 3.0.2+dfsg) but it is not going to be installed

![Image of Yaktocat](http://i.imgur.com/MIoE1BH.png)

When I tried to install the missing dependencies it just goes on and on and that another and another package is missing.
![Image of Yaktocat](http://i.imgur.com/6t29xrp.png)

Is there a way for me to fix this?

**Comment by gregory38** [comment]
Well, if `sudo apt-get install libgtk2.0-0:i386` doesn't work on your system, I'm not sure why you report the issue here.

**Comment by gregory38** [comment]
Feel free to ask support on the forum but so far it isn't a PCSX2 issue so I'm closing this bug report.

**Comment by Flix01** [comment]
Not sure if it can be useful, but I guess that maybe this can happen if you don't install the i386 multiarch with:
> sudo dpkg --add-architecture i386
(please see: https://github.com/PCSX2/pcsx2/wiki/Installing-on-Linux).

However I think it must be possible to "manually" install pcsx2 even WITHOUT installing the i386 arch,
because in Synaptic I can find the dependencies you've mentioned above by setting <b>arch: i386</b> on the left pane filters (otherwise they don't show up, at least if you didn't install the i386 arch).
