### ISSUE TITLE
[BUG]: Meta thread for translations

### ISSUE THREAD

**Issue by xujibbs** [PCSX2/pcsx2#11511]
### Describe the Bug

![捕获](https://github.com/PCSX2/pcsx2/assets/79200793/aed1f71f-131c-4478-b9a4-11311d7b1a17)
Translation "Disable Mailbox presentation")shown in Big picture failure. 

### Reproduction Steps

Change the 

### PCSX2 Revision

1.7.5958

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
Duplicate #9062

**Comment by xujibbs** [comment]
Do you really understand what happened to this translation bug? What I mean is I translated it but the Chinese word can't be shown in Big picture mode. I don't think it would be reported in Crowdin.

**Comment by IlDucci** [comment]
@xujibbs I'm afraid you mistook the name of the issue, copying an existing name, and that's why the Issue was closed.

However, this error might happen because of one of two situations:
 - You are testing an updated version of the translation downloaded from Crowdin without updating the glyph ranges for the Big Picture mode. In this case, you must do a local compilation of PCSX2 to check any updates done to your languages.
 - The current translation found on PCSX2 does not match the current state of the glyph ranges updated. That would be an actual bug for the PCSX2 team.
