### ISSUE TITLE
[BUG]: PINE does not return result code for each request in a batch request

### ISSUE THREAD

**Issue by entriphy** [PCSX2/pcsx2#11532]
### Describe the Bug

According to the [PINE spec](https://github.com/GovanifY/pine/blob/master/standard/draft.dtd), `0e 00 00 00 | 00 34 7d 34 00 | 00 34 7d 34 00` (Size | MsgRead8(0x00347D34) | MsgRead8(0x00347D34)) should return a buffer with a size of 8, i.e. `08 00 00 00 | 00 00 | 00 00` (Size | (ResultCode | Uint8) | (ResultCode | Uint8)). However, the current PINE implementation returns a buffer with a size of 7, i.e. `07 00 00 00 | 00 | 00 | 00` (Size | ResultCode | Uint8 | Uint8).

### Reproduction Steps

1. Enable PINE in PCSX2.
2. Send batch request with two MsgRead8 commands.
3. PINE responds with a buffer of size 7.

### Expected Behavior

PINE should respond with a buffer of size 8.

### PCSX2 Revision

v1.7.5973

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch Linux

**Comment by GovanifY** [comment]
Hi there, thanks for your interest in PINE!

Went back looking at the spec/codebase and it seems the spec is indeed wrong; only a single result code is given for a batch message. The reasoning being that, currently, failures in the server means it was unable to parse the packet it received, either because of malformed packets (wrong opcode) or OOB length:

https://github.com/PCSX2/pcsx2/blob/75defbededc6b4a7fb799f44b1145598c3efb2c6/pcsx2/PINE.cpp#L495

https://github.com/PCSX2/pcsx2/blob/75defbededc6b4a7fb799f44b1145598c3efb2c6/pcsx2/PINE.cpp#L724


The spec is indeed wrong about this, thanks for spotting it! Will correct it ASAP

**Comment by GovanifY** [comment]
https://projects.govanify.com/govanify/pine/-/commit/50cabd246961d396f27d1dc8bf414249b9883826
