### ISSUE TITLE
[BUG]: Debugger window theme fails to change when global theme is changed

### ISSUE THREAD

**Issue by TheTechnician27** [PCSX2/pcsx2#11568]
### Describe the Bug

If you change the theme under Settings > Interface > Theme, you need to restart PCSX2 for the changes to take effect to the debugger. Otherwise, everything under the 'R5900' and 'R3000' tabs are set to the default color scheme (dark grey). The rest of the debugger changes its theme just fine. In essence, the R5900 and R3000 tabs do not re-draw themselves upon the update of the Qt theme.

### Reproduction Steps

Start using any theme (preferably one with a color scheme very distinct from grey to easily see this), open the debugger window (you can also leave it closed then open it after changing theme), and then select any theme other than the one you are currently using. If you go to the debugger window, it should be partially themed grey.

### Expected Behavior

The debugger theme should update upon Qt theme change.

### PCSX2 Revision

v2.0.3

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Manjaro - Flatpak

**Comment by AmyRoxwell** [comment]
A small update on this bug:

It seems the debugger takes into consideration the old theme you had before changing it, so it you switch from `PCSX2 (White/blue)` to `Pizza time` then the debugger will keep `White/blue` instead of getting updated to pizza time, but if you switch back to `White/Blue` then the debugger will switch to `Pizza time` 

![Image](https://github.com/user-attachments/assets/3b661e7b-18c0-418c-b20b-d131d3260ad9)


![Image](https://github.com/user-attachments/assets/6a1d6524-2c5e-4ec2-9340-4ecc5faccf9d)
