### ISSUE TITLE
[Feature-Request] - Patch finder and browser dialogs

### ISSUE THREAD

**Issue by eadmaster** [PCSX2/pcsx2#1162]
This was already discussed [here in the forums](http://forums.pcsx2.net/Thread-PCSX2-Patch-Finder-Removed-completely-or-just-hidden).
I've found CheatEngine is a good Patch finder alternative, but the patch browser dialog is necessary if you want to load big patch files and enable/disable cheats interactively at runtime.

**Comment by DigitalMajestic** [comment]
Seconding what link said, if you're already using CE to create the patches themselves then the new cheat dialog (and pnach v2.0 format) does what you're trying to do.

The one thing it's missing is the ability to disable patches without a game reboot, but in my opinion that's a good thing because forcing users to do a fresh boot of the game can rule out issues with patches. For example, if a bad patch causes corruption elsewhere in memory, then the patch is fully disabled/reverted without a fresh boot of the game, the game will still have issues with the corruption elsewhere, and suddenly users will think it's the emulator's fault when it really isn't.
