### ISSUE TITLE
[Feature Request]: [OSD]: Add unscaled resolution on the resolution field

### ISSUE THREAD

**Issue by knight-ryu12** [PCSX2/pcsx2#11961]
### Description

It should be easy to implement this; but only having the upscaled resolution looks off.

### Reason

For convenience; there is no way to get original (CRTC) resolution when you are upscaling, and I felt off.

### Examples

![Image](https://github.com/user-attachments/assets/da69affa-144e-43ef-81fa-f9561acffd1b)

**Comment by Mrlinkwii** [comment]
i think this will just confuse people adding 2 resolution fields

**Comment by knight-ryu12** [comment]
I think we could add a prefix to it.

**Comment by crashGG** [comment]
> Yes but it's not visible in the HW when Upscaled; it's just a convenience really.

Users don't need to check this indicator all the time. If who wants to know the original resolution, just use the hotkey to switch and check it once.I think this should be the most convenient way.

**Comment by JordanTheToaster** [comment]
> > Yes but it's not visible in the HW when Upscaled; it's just a convenience really.
> 
> Users don't need to check this indicator all the time. If who wants to know the original resolution, just use the hotkey to switch and check it once.I think this should be the most convenient way.

Then you don't need to use it it's that easy.

**Comment by F0bes** [comment]
I'm apprehensive. Our OSD is getting filled with a lot of things and your rational is "It looks cooler"...

**Comment by knight-ryu12** [comment]
Sorry, I will update my reason.

**Comment by TheTechnician27** [comment]
> I'm apprehensive. Our OSD is getting filled with a lot of things and your rational is "It looks cooler"...

I'm with fobes on this one; we already have 16 settings for the OSD, taking up the entire 8x2 area in the settings. Granted, this lack of space itself is partly my fault for making the two OSD message position options, but it's more that it's emblematic of creep. I 100% agree with @crashGG that the most reasonable way to view this information is to simply toggle F9 and view the resolution; I can't seriously think of any realistic situation where someone would need the original resolution in real-time. Moreover, under 'Show Settings', we already display the multiplier to the internal resolution, making it so that even if you absolutely must know the original internal resolution in a given screenshot, you can just divide the X and Y by that multiplier to immediately retrieve the native res. I think there's an argument based on reasonable use cases to be made for every existing OSD setting, but not this one.

**Comment by Mrlinkwii** [comment]
i agree with @TheTechnician27  , adding more settings wont help anyone  ,

**Comment by knight-ryu12** [comment]
While I do think it is still a nice addition, I think this went nowhere, so I will close this issue
