### ISSUE TITLE
[BUG]: Flathub builds failing, stuck at old version

### ISSUE THREAD

**Issue by muchhesitate** [PCSX2/pcsx2#12079]
### Describe the Bug

Flathub builds are stuck at v2.1.226, see [here](https://flathub.org/apps/net.pcsx2.PCSX2). Noticed that [the CI](https://github.com/PCSX2/pcsx2/actions/runs/12246848245/job/34163566001#step:12:18) is failing.

### Reproduction Steps

Install PCSX2 on Linux through `flatpak`.

### Expected Behavior

Have either latest release (v2.2.0) or latest pre-release (v2.3.53) available.

### PCSX2 Revision

v2.1.226

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Any

**Comment by F0bes** [comment]
We need a new token generated.
I've been trying to get ownership of the Flathub package, the current owner doesn't want to generate a new token for us for the time being.
The FlatHub/Flatpak people I've spoken to have told me that they don't have any user administration system, I guess they can't change the owner then?
I was also told that we can go back to using their [repo](https://github.com/flathub/net.pcsx2.PCSX2), but I really don't have the time or motivation to start redoing infrastructure I **just** set up before our latest release **just** because we need a silly token.
