### ISSUE TITLE
Make onepad && lilypad Properly emulate controller sticks instead of just directions

### ISSUE THREAD

**Issue by belldandu** [PCSX2/pcsx2#1358]
I'm sorry but if i had to choose between pcsx2 and any other emulator for ps2 (if any) that could play fragment and had better controller emulation i would choose that other emulator because as of now every controller plugin for pcsx2 is absolute garbage when it comes to emulation of a joystick. I have a controller and the emulation is so bad my character jumps in a random direction its not supposed to even though i told it to go the other direction.

In General PCSX2 needs to actually emulate a ps2 instead of always implementing cheap hacks however i wont go into too many details as its been discussed so many times and yet the staff still get pissed when people bring it up.

The bugs in the emulator have been becoming more appearant and annoying recently and they are because the emu just sucks at being just that, an Emulator.

This is another classic example of this "garbage" being called an emulator when its anything but.

If my ps2 wasn't broken i would be using it instead.

**Comment by gregory38** [comment]
You can complain only if your contribute. I don't say everything is perfect but do you seriously think that ranting in the bug tracker will yield us (me as the only the linux dev) more free time and desire to improve the situation.

**Comment by belldandu** [comment]
@gregory38 You realize i was also talking about windows "lilypad" too hence why i never specified an os this time.

You sound condescending as hell. Not that i care. But the reason people get pissed and rant is because pcsx2 devs are known to be condescending pricks when people bring up flaws in their little "baby" that can't do proper emulation.

@ssakash go invalid your damn computer.

**Comment by ssakash** [comment]
I've marked it as invalid since you haven't followed the official template for reporting bugs, also your post is more of a whining of a single user rather than a bug report. And I rather doubt it's an issue on the controller plugin side... I suggest you visit the forum instead for support. This is a issue tracker for **valid** bugs.

>This is another classic example of this "garbage" being called an emulator when its anything but.
If my ps2 wasn't broken i would be using it instead.

Just an advice : please avoid mentioning stuffs like these in case you're making a bug report on the future, thanks.
It's irrelevant to the topic and doesn't motivate the developers to help your issue.

**Comment by gregory38** [comment]
Lilypad exists on linux too. However onepad doesn't exists on windows.

Anyway, first rule above all rules is to be respectful and polite, period.
