### ISSUE TITLE
ATV Offroad Fury 4 - SCUS_974.79;1 - GSDx D3D Hardware Anisotropy filter issue

### ISSUE THREAD

**Issue by juanvmr** [PCSX2/pcsx2#1359]
All core options are in the default preset (Safest). No hacks, but my CPU is overclocked (turbo boost), but I don't think this is a problem.

With anisotropic filter on (any value):
![gsdx_20160510211941](https://cloud.githubusercontent.com/assets/15989866/15166765/543d8bdc-16f8-11e6-8674-79a46483c61d.jpg)

With anisotropic filter off (zero):
![gsdx_20160510212010](https://cloud.githubusercontent.com/assets/15989866/15166779/780277f8-16f8-11e6-81d2-0bc57e51557b.jpg)

In garage:
With anisotropic filter off (zero):
![no anisotropy garage](https://cloud.githubusercontent.com/assets/15989866/15177846/a4b2a976-1748-11e6-8cfd-1ef4898da791.jpg)

With anisotropic filter on (any value) and skipdraw set to 1:
![anisotropy on skipdraw set 1](https://cloud.githubusercontent.com/assets/15989866/15177871/bc68c5be-1748-11e6-9e4d-8e76c53d078e.jpg)

Those images are in .bmp format, I changed it to .jpg for uploading. Try copy and paste the url.

This only happens when using DirectX Hardware mode. If changed to Software, this bug disappears. Also, the anisotropic filter can be turned on, but I need to activate the skipdraw in the GS hardware hacks, setting it to 1. But in this case, when in the main menu, if I go to the garage, the vehicles look like a ghost, only the customizable parts that change on the vehicle, they look normal.
If the 8-bit textures are allowed, this bug also disappears, but I think is because the anisotropy filter is turned off by default.

I have not tested with OGL, because my video board does not support it. Actually, I do not have a video board.

CPU: Intel i5 3337, 1.8ghz, 2.7ghz in turbo mode.
Video: Intel HD Graphics 4000.
Motherboard: don't know. It's one of a Acer v5-571.

**Comment by gregory38** [comment]
```
I have not tested with OGL, because my video board does not support it. Actually, I do not have a video board.
```
The issue is your driver not the GPU. if you install a linux system, you will see that openGL is working fine for your GPU (actually it even works with the first version of HD Intel GPU).

It is a shame that you can't test openGL as it potentially fixes most of your issues.

Some PS2 textures aren't compatible with aniso filtering. OpenGL renderer will better handle this case (i.e disable aniso when it is wrong), but now people complain aniso doesn't work well with openGL. So yeah aniso is provided without any guarantee.

As you have guessed aniso is automatically disabled in 8 bits texture (in this case most textures aren't compatible with aniso).

**Comment by refractionpcsx2** [comment]
> With anisotropic filter on (any value) and skipdraw set to 1:

What happens if you don't set skipdraw to 1? As that will break things.

**Comment by juanvmr** [comment]
As I thought. I have tried to build pcsx2 on Linux, but I had some problems with dependencies. But now I will format my pc and install OpenSUSE Leap.

In garage, with aniso both on or off, nothing happens, everything appears normal. Only during a race, that white line appear.
