### ISSUE TITLE
[silly question] 1.5.0 roadmap

### ISSUE THREAD

**Issue by Tajnymag** [PCSX2/pcsx2#1366]
When could 1.5.0 become stable? I'm only curious :)

**Comment by DPersonalized** [comment]
It's a good question, but one I feel would be better suited to the forum. The issue tracker is really just for actual problems with PCSX2, feature requests etc. You'd probably also get a bigger audience on the forum i.e. more people giving their thoughts, since it's mostly just active developers/testers that hang around here.

**Comment by Tajnymag** [comment]
Alright, I'll try that. I just didnt want to create a new account for this simple question :)

**Comment by Tajnymag** [comment]
OK, I've already posted it there :)

**Comment by ramapcsx2** [comment]
Closing then. See you on the forum :)
