### ISSUE TITLE
Ready 2 Rumble Round 2 General Graphical Issues

### ISSUE THREAD

**Issue by JacobAL** [PCSX2/pcsx2#1480]
http://i.imgur.com/LK6rSpb.jpg

Issues with both OGL and DX11. Shadows are pretty messed up and applying MSAA really slows down the game in DX11 HW renderer (other games run fine with the same).

VIdeo: https://www.youtube.com/watch?v=SKO__k-Yr1M

Specs: http://i.imgur.com/LK6rSpb.jpg

**Comment by ssakash** [comment]
As stated on https://github.com/PCSX2/pcsx2/issues/1481#issuecomment-235629569 , closing this issue.

**Comment by JacobAL** [comment]
Fair enough. I'll stick it on the forums. I thought the video would be enough info for you, sorry.

**Comment by ssakash** [comment]
> I thought the video would be enough info for you, sorry.

Sorry, but it isn't enough :/

It's time consuming for the developers to go through the full video compared to reading a text description and you had used upscaling and various other hardware hacks on GSdx plugin settings according to that video. So it's quite resource demanding to identify whether it's a valid issue (or) issues caused due to non-default settings. I hope you understand,

> Fair enough. I'll stick it on the forums.

Thanks.
