### ISSUE TITLE
Onimusha Warlords Layering Issue DX11

### ISSUE THREAD

**Issue by JacobAL** [PCSX2/pcsx2#1481]
Pictures for side by side comparison:
DX11: http://i.imgur.com/D6qp1hn.jpg
OGL: http://i.imgur.com/1Wdhw73.jpg

Specs: http://i.imgur.com/ToXTOBF.png

**Comment by ssakash** [comment]
Please follow the bug reporting template present over [here](https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues). (Same for **#1480**)

Github issue tracker is only used for maintaining valid and detailed bug reports, personally I suggest making your bug report on the [forums ](http://forums.pcsx2.net/Forum-Bug-reporting), bug squad members will push it to the Github issue tracker if the issue is valid. Thanks.
