### ISSUE TITLE
Enter the Matrix Freezes on Videos. (Unplayable)

### ISSUE THREAD

**Issue by AmbientMalice** [PCSX2/pcsx2#1494]
-PCSX2 version: 1.5.0-dev-1060-g6376e8d

-PCSX2 options: Defaults, no settings modifications affect the issue.

-Plugins used: Defaults.

-Plugin settings: Defaults, no settings modifications affect the issue

-Description: The game freezes and spams "IPU1 Normal Error!" in the log after playing the initial Atari logo video. The game will also freeze on all other videos if that video is bypassed with hacks. And since the game has a lot of live action FMVs, the story is incomprehensible

The game will also invariably freeze during the first mission or if you try to enter the Options menu if the FMV skip hack is used.

-How to replicate: Simply boot the game.

-Last known version to work: Never worked, AFAIK. All reports on the Wiki have this error.

-PC specifications: CPU: Q9400 @ 3.2Ghz. GPU: GTX 750 Ti 2GB OS: Windows 10 64-bit

Other-
I only have a US copy of the game, but since nobody has actually reported the game ever working properly, I assume it's the same with the PAL versions.

**Comment by MrCK1** [comment]
Are you sure you aren't using cycle rate hacks? I've had this happen on GH3 when I booted with the EE overclocked

**Comment by AmbientMalice** [comment]
>Also, the game freezing with the FMV skip modifier enabled is irrelevant

It means the game can't be played by skipping FMVs.

And no, no cycle rate hacks were used.

**Comment by jcdenton2k** [comment]
To be fair, this game is terribly buggy and CRASHES a real-life Playstation 2 console!  It was so ubiquitous and rampant that people would joke that you'd get to see the actual 'matrix' by watching a PlayStation 2 get the equivalent of a blue screen of death.

If your original console works you can try to give it a go but honestly I would recommend the devs not even bother trying to fix this game.

"The AI in the game is also a bit of a mess, so you can expect to see things like enemy cops running into a wall and staying there, enemies clipping through walls and doors instead of running around to get to you, and so on."
"Enter the Matrix bears the additional weight of being a pretty buggy game."
"The PlayStation 2 version suffers from serious frame rate problems and a bevy of audio errors, the most troublesome of which causes some cutscenes' audio to be played twice at slightly different times, creating an echo effect that renders almost all the dialogue completely unintelligible."

And it gets far worse than that.

"I purchased this game the day it came out and it has serious issues due to rushing the game for release to coincide with the movie. The game voices echo. The game freezes 5 levels in and background disappear!! This game wasn't even beta tested for PS2! EVERY copy I exchanged it for did the same thing and I'm NOT alone. I was lucky enough to get my money back. Atari and Sony know of this problem and offer no resolution presently. I'd LOVE to have this game ONLY if all problems are corrected! BEWARE. If you don't believe me, rent it and see if the game doesn't freeze as Niobi approaches the plane in the "Catching a Plane" level. The screen attempts to load then goes black.. FOREVER. Thank you kindly for your time and patience."

I don't believe it would be a good use of developer resources on PCSX2 to attempt to get this game playable.  Some things deserve to be forgotten and this trash can be considered one of them.  We have more than enough terrible games flooding Steam Early Access to 'learn from' when it comes to game design and what not to do.

**Comment by AmbientMalice** [comment]
>To be fair, this game is terribly buggy and CRASHES a real-life Playstation 2 console!

And so does Indiana Jones and the Infernal Machine for the N64, or Uncharted 3 for the PS3. But refusing to improve emulation accuracy to get those games running because "they crash on real hardware" would be silly.

>And it gets far worse than that. This was a game pulled from shelves and recalled because of the flood of demands for refunds for a broken CONSOLE game.

Citation needed. The game sold 5 million copies. It spawned a spiritual successor, Path of Neo. Mass refunds would be newsworthy, but I can't find anything. Nor can I find anything about a recall.

> If you don't believe me, rent it and see if the game doesn't freeze as Niobi approaches the plane in the "Catching a Plane" level.

A brief google has people claiming that Enter the Matrix becomes prone to crashing on certain levels if you use any of the hacking features (cheats). Did you enable any cheats? I've only ever 100% completed the PC version of the game, which is easily the worst version because it has massive performance issues.

**Comment by jcdenton2k** [comment]
My local Gamestop at the time did do a recall and offered full refunds to anyone who purchased the game.  Perhaps it was only a local thing rather than nationwide but I'd be surprised if there are absolutely no news stories about it.

The thing about the internet is that print media has to be scanned specifically and transcribed in order to show up in search results otherwise it is inaccessible.  Even if it did show up in newspaper articles you wouldn't know about it unless it was also on a website somewhere or otherwise scanned-in.

Back around the release of this game the internet wasn't quite yet at 'Web 2.0' fully and we were a decade away from really innovative things.  Most people were still using Internet Explorer and Firefox was JUST getting off the ground with some stable releases.

That said, if the devs feel like taking the time to fix this game they are welcome to do so but with limited resources (time) available for much better games to improve their compatibility, I wouldn't see it as a useful expenditure of said resources.

**Comment by prafullpcsx2** [comment]
@AmbientMalice can you try this patch and report how better or worse it is than skipmpeg hack?

http://www.filedropper.com/enterthematrixslus20454u

**Comment by AmbientMalice** [comment]
@prafullpcsx2 Game freezes when I try to load saves. I'm getting a lot of TLB errors.

**Comment by FlatOutPS2** [comment]
@AmbientMalice can you try this exe(turn off patch and skipmpeg hack)?

[pcsx2-IPU.zip](https://github.com/PCSX2/pcsx2/files/408604/pcsx2-IPU.zip)

**Comment by prafullpcsx2** [comment]
@FlatOutPS2 : Good job, that fixes video hang issue. This may fix all other games with the issue too. What's the code you changed? Even I was trying to have a look at IPU code to sort out this error.

**Comment by AmbientMalice** [comment]
Like @prafullpcsx2 says, the videos are working fine. The log shows a single "IPU1 Normal Error!" for every video played, but there seem to be no stability issues.

The game has a second problem. After you press a button to open the shutters in the Post Office, the game starts spamming "Vif1: Unknown VifCmd" errors, accompanied by some slowdown. They seem to stop after a while, though.

Anyway, after you follow the arrow for a while, you'll come to a door that freezes the game when you open it. Enabling the "Preload TLB hack" reliably fixes that freeze at least, based on testing the level four times, twice with, twice without. (The game seemed a bit prone to freezing anytime the Vif1 errors start, but I dunno whether the TLB hack reliably fixes that instability because I haven't tested enough.)

**Comment by FlatOutPS2** [comment]
> @FlatOutPS2 : Good job, that fixes video hang issue. Even load screen is working now. This may fix all other games with the issue too. What's the code you changed? Even I was trying to have a look at IPU code to sort out this error. Make a PR :+1:

It should fix all other games with this issue, I tested it on two demo's with IPU normal errors(Rygar, Freestyle Metal X). The fix is really simple, but it gets the job done(see PR). :P

**Comment by prafullpcsx2** [comment]
@AmbientMalice : This game requires ee timing hack, I hope you have that enabled to avoid vif errors.

**Comment by AmbientMalice** [comment]
@prafullpcsx2 vif errors (and the crash at this door)

![gsdx_20160810012731](https://cloud.githubusercontent.com/assets/10704701/17522290/ccfb92e2-5e99-11e6-86f6-ec61a7eba806.png)


 seem to occur regardless of timing hack being enabled.

Why was EE timing hack enabled for ETM?

**Comment by prafullpcsx2** [comment]
EE timing hack gets rid of initial Vif1: Unknown VifCmd! errors for me. If the hack is disabled game would hang on the first cutscene itself. I played around a bit and game still hanged after sometime. How far is that elevator door from start of the game? A savestate will help.

**Comment by refractionpcsx2** [comment]
#1507 might fix the video issues in this game.

**Comment by FlatOutPS2** [comment]
> #1507 might fix the video issues in this game.

You obviously didn't read the PR or the earlier posts here. :P

**Comment by refractionpcsx2** [comment]
Nope :P Well, I did read earlier, just much earlier than that :P

**Comment by antoyo** [comment]
The pull request #1507 did not fix the video issues in the game Harry Potter and the Order of the Phoenix.
I still get many errors like:
```
---------
DMA Crash
---------

General DMA state:

	DMA enabled
	DMA transfer enabled
	Cycle-stealing off
	FIFO off
	Stall control source unspecified
	Stall control drain unspecified
	Release cycle 8
	DMA Stall interrupt disabled (interrupt state clear)
	MFIFO empty interrupt disabled (interrupt state clear)
	BUSERR interrupt clear
	Stall address 0x00000000

Channel 0 - VIF0 

	Channel stopped
	Channel interrupts disabled (interrupt state set)
	Chain mode
	Transfer address 0x005862e0
	Tag address 0x005862d0
	Transfer size 0 QWs
	TTE enabled
	TIE disabled
	Last tag was 0x7000
	No addresses on stack

Channel 1 - VIF1 

	Channel stopped
	Direction to memory
	Channel interrupts enabled (interrupt state clear)
	Chain mode
	Transfer address 0x00c40bb0
	Tag address 0x00c40b90
	Transfer size 0 QWs
	TTE enabled
	TIE enabled
	Last tag was 0x7000
	No addresses on stack

Channel 2 - GIF 

	Channel stopped
	Channel interrupts disabled (interrupt state set)
	Chain mode
	Transfer address 0x00c40b70
	Tag address 0x00c40b50
	Transfer size 0 QWs
	TTE disabled
	TIE disabled
	Last tag was 0x7000
	No addresses on stack

Channel 3 - fromIPU 

	Channel stopped
	Channel interrupts disabled (interrupt state set)
	Normal mode
	Transfer address 0x00003600 (scratchpad)
	Tag address 0x00000000
	Transfer size 0 QWs
	TTE disabled
	TIE disabled
	Last tag was 0x0000

Channel 4 - toIPU 

	Channel stopped
	Channel interrupts enabled (interrupt state clear)
	Chain mode
	Transfer address 0x015ca4f0
	Tag address 0x01629e90
	Transfer size 0 QWs
	TTE disabled
	TIE disabled
	Last tag was 0x0000

Channel 5 - fromSIF0 [running]

	Channel running
	Channel interrupts enabled (interrupt state clear)
	Chain mode
	Transfer address 0x00784360
	Tag address 0x00000000
	Transfer size 0 QWs
	TTE disabled
	TIE enabled
	Last tag was 0x0000

Channel 6 - toSIF1 

	Channel stopped
	Channel interrupts disabled (interrupt state set)
	Chain mode
	Transfer address 0x00796470
	Tag address 0x00021310
	Transfer size 0 QWs
	TTE disabled
	TIE enabled
	Last tag was 0x0000

Channel 7 - SIF2 

	Channel stopped
	Direction from memory
	Channel interrupts enabled (interrupt state clear)
	Normal mode
	Transfer address 0x00000000
	Tag address 0x00000000
	Transfer size 0 QWs
	TTE disabled
	TIE disabled
	Last tag was 0x0000

Channel 8 - fromSPR 

	Channel stopped
	Channel interrupts disabled (interrupt state set)
	Normal mode
	Transfer address 0x015a7080
	Tag address 0x00000000
	Scratchpad address 0x00003000
	Transfer size 0 QWs
	TTE disabled
	TIE disabled
	Last tag was 0x0000

IPU state :

	IPU is idle
	0 QWs in input FIFO
	0 QWs in output FIFO
	0 QWs in internal buffers
	Error code not detected
	Start code detected
	Bitstream is MPEG 2
	Frame type is I-frame
```
Does anyone else still have this issue with this game?

**Comment by AmbientMalice** [comment]
The game still crashes for me during the first mission when you're following the waypoints, as mentioned https://github.com/PCSX2/pcsx2/issues/1494#issuecomment-238590710 If the TLB hack is enabled, the crash doesn't occur. But the video issue appears to be resolved, and perhaps a new issue should be made for the door opening freeze.

I'll close this for now.

**Comment by gregory38** [comment]
Which tlb hack? The one from goemon?

**Comment by AmbientMalice** [comment]
@gregory38 Yep.

**Comment by gregory38** [comment]
Honeslty I'm very surprised the hack as any impact on this game. Does the game start correctly with the EE interpreter and no tlb hack?

**Comment by willkuer** [comment]
Why do you always assume that goemon is the only game using that feature?

**Comment by FlatOutPS2** [comment]
Maybe because the hack is tied to a game more than any of the other hacks are, in both the description and the code( it's called the GoemonTlbHack ).

**Comment by gregory38** [comment]
First I'm the one that spent week to make the hack reality.
Second, the hack intercept the memory allocator/deallocator tlb function. It is based on the hardcoded address of the game. However there is a potentially side effect on the jump instruction. IIRC, I forced a v2p translation on jump destination to solve code in virtual memory.
So it is really unexpected that it get a positive effect on this game.

**Comment by AmbientMalice** [comment]
@gregory38 I'm aware how strange it is, but the game consistently crashes at that doorway without the hack, but seems magically fixed with that hack.

Has anyone managed to complete the first level with the default settings?

**Comment by Levan7** [comment]
Still an issue on latest dev build getting Vif1: Unknown VifCmd! messages and the game hangs for a while then starts
