### ISSUE TITLE
Berserk - FMV missing subs in HW (UI was fixed)

### ISSUE THREAD

**Issue by vortexofdoom** [PCSX2/pcsx2#1526]
- PCSX2 version: v1.5.0-dev-1165-g02cfe9a
- PCSX2 options: Defaults, no settings modifications affect the issue
- Plugins used: GSdx, SPU2-X, LilyPad, Gigaherz CDVD, the rest are null plugins
- Plugin settings: Misbehavior differs based on whether you use software or hardware rendering, OpenGL or DirectX9/11 made no difference, only hw/sw.
- Description: Various UI elements fail to properly display. For reference, the desired behavior is referenced [here](https://youtu.be/pBpgwemvFYE?t=518) and I made [a couple screenshots](http://imgur.com/a/3NAkq) to illustrate the difference. Tested with the same patch as the video but not burned to disc. The issue is also present in unpatched versions.
  - When using hardware rendering, player health/berserk bars, button icons, and combo count do not display at all, leaving only a black square in the top left corner with no visual disruption otherwise. Feedback on the final result of your combo will show up (eg. "Nice!")
  - When using software rendering, player health shows up as a textured square overlaying the visuals, berserk bar to the right still doesn't display, button icons show up but their charge doesn't show beyond whether it's ready to use or not. Combo does display properly.
- How to replicate: Simply playing the game should replicate it once past initial cutscenes
- Last known version to work: Never worked
- PC specifications: CPU: Intel Core i7 4770K GPU: Gigabyte Geforce GTX770 2GB OS: Windows 10 64-bit no modding or OC on any hardware.
- Other comments: Software issue appears at a glance to be a layering problem overall, with the base state for the charge bars (berserk/button) showing all the time with the layer that alters them over time either being hidden or not displaying (can't tell which myself). This would also explain (as much as this is a real explanation at least) the health texture showing on top of the UI outline. Basically my instinct is that they're all related to the same problem of which layer is drawn on top. As to the difference between hardware and software, that's further above my pay grade.
  - [Here](http://forums.pcsx2.net/Thread-Bug-Report-Berserk-Millennium-Falcon-Hen-Seima-Senki-no-Shou) is the first forum post about this issue for some other hardware configurations and to see it's been ongoing.

**Comment by ssakash** [comment]
Simply redirecting to a bug report on the forums isn't helpful. Please follow the template mentioned over [here](https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues). Providing status of the issue on [latest development build](http://pcsx2.net/download/development/git.html) would also be useful.

**Comment by vortexofdoom** [comment]
I updated it, hope it's more helpful now!

**Comment by ssakash** [comment]
Thanks for the quick update!

**Comment by gregory38** [comment]
Could someone test build from #1550 with `UserHacks_AutoFlush = 1` hack enabled?

**Comment by gregory38** [comment]
@vortexofdoom 
And does it work better with Zerogs (or zzogl)

**Comment by pipyui** [comment]
No luck with UserHacks_AutoFlush = 1 nor ZeroGS.

I would note that when hardware rendering with GSdx OpenGL, UI displays just as software mode when 'Preload Frame Data' is configured in 'Configure Hacks', but only when emulator is started so configured and remains uninterrupted by configurations or switch to/from software render.

**Comment by gregory38** [comment]
The HW renderer is likely a texture cache issue. Hum, could be a wrong palette.

**Comment by pipyui** [comment]
If it helps, the UI elements don't disappear after render switch, but all seem to get misplaced into the top corner, while also apparently failing to reflect any information.  I've screenshots [in this post](http://forums.pcsx2.net/Thread-Pushed-Bug-Report-Berserk-Millennium-Falcon-Hen-Seima-Senki-no-Shou?pid=534880#pid534880) (wasn't running an official git build at time of post, but have since been).

**Comment by gregory38** [comment]
Hw renderer is a texture cache issue. I got a depth buffer instead of the real input texture.

I also noticed some invalid PSM format for the framebuffer. In this case GSdx will skip the draw call. I try to replace the invalid format with a valid one. Rendering is a bit better but I got some strange triangle.
![broken_hud](https://cloud.githubusercontent.com/assets/1569559/19048402/741b5d32-89a6-11e6-811c-8eb1014c5f22.png)

Maybe there is a also core bug. I don't know.

**Comment by gregory38** [comment]
I potentially have a fix for the HW renderer. But main issue still exists.

**Comment by gregory38** [comment]
Be happy I found the crazyness.

**Comment by MarcoEstevez** [comment]
How epic are you  :)

**Comment by gregory38** [comment]
Honestly on this one, I deserve a very good :beer:  => #1605

**Comment by gregory38** [comment]
For the posterity
![berserk](https://cloud.githubusercontent.com/assets/1569559/19051104/dbf86d72-89b1-11e6-875e-88d423b7983e.png)

**Comment by gregory38** [comment]
I pushed the frame format fix. So you can play the game properly on the SW renderer. I still have a pending fix on the pull request for the HW renderer.

**Comment by AzazelDC** [comment]
On HW, all UI disappeared now except health boss and minimap.

Cutscene subtitle doesn't appear before and after commit on HW also. Is it the same kind of problem ?

**Comment by gregory38** [comment]
```
I still have a pending fix on the pull request for the HW renderer.
```
https://ci.appveyor.com/project/gregory38/pcsx2/build/1.1906-master/job/dvu2dypdafj6rirl/artifacts

**Comment by AzazelDC** [comment]
Yes i know. It was mainly to note the subtitle problem on video, if that was the same kind of problem.

**Comment by gregory38** [comment]
maybe you can test the build on the previous post link ;)

**Comment by AzazelDC** [comment]
On that build, i have no UI and no subtitle on HW also.

I missed something ?

**Comment by Omusoru** [comment]
With the build you provided above the UI does indeed show up in HW mode but not the subtitles from cinematics. They still only show up in SW.

**Comment by gregory38** [comment]
@Omusoru could you provide me a gs dump of those subtitle.

**Comment by Omusoru** [comment]
@gregory38 
[berserk_gsdump.zip](https://github.com/PCSX2/pcsx2/files/514566/berserk_gsdump.zip)
I made one in HW and one in SW

**Comment by gregory38** [comment]
Good news, I found the code that remove the subtitle. The bad new it is the same code that show the video... Ok I understand what happen. 

* subtitles are rendered into 0 (bottom)
* EE will write the video into 0 (top) (here we mark the frame buffer as dirty)
* a will blit be done from 0 to 1000. So you need to lookup 0 a new texture input. However currently the texture cache skip dirty framebuffer (because it contains bad data, the image written by the EE).

It is a very complex topic.

**Comment by AzazelDC** [comment]
Ok, i understand my problem. On that build, there have no SSE4 version of GSDX, I was always on old GSDX plugin in SSE4 then...

I used SSE2 version and UI works perfectly. :)

**Comment by willkuer** [comment]
so there is a difference between the sse4.1 and sse2 plugin of the same revision?

**Comment by AzazelDC** [comment]
Yes i always overwrite files in one folder, but the build provided here don't have SSE4 version of GSDX that i usually use, then i used wrong version...

it's my fault, I'll be careful next time. :)

At least I was able to highlight the problem of subtitles. :p

**Comment by psennermann** [comment]
Since a proper fix for the subtitles seems very hard to find, wouldn't it be possible to have at least an automatic game fix (CRC hack?) that enables for this game the software rendering option for FMV, instead of having always to enable it manually in the GameFix menu? (with this option enabled subtitles would show up not only in movies, but also in the game-engine rendered cut-scenes)...

**Comment by gregory38** [comment]
Did you actually test the fmv hack option?

**Comment by psennermann** [comment]
Yes, I've seen that this option shows subtitles (automatically changes to software mode) for the opening movie and also for the first game-engine rendered cut-scene (the one where the snow monsters come out), then when game starts it switches back to hardware mode...

**Comment by seta-san** [comment]
this seems to be fixed.

**Comment by Mrlinkwii** [comment]
The game has SW fmv , the game needs checked without this

**Comment by seta-san** [comment]
> The game has SW fmv , the game needs checked without this

I did. The subtitles still show in hardware mode
