### ISSUE TITLE
EE (and maybe VU) cycle overclock

### ISSUE THREAD

**Issue by fredgido** [PCSX2/pcsx2#153]
Basically overclock EE/VU to fix some games fps slowdowns while running pcsx2 at full speed.
Wondering is this is feature is still planned. Less people nowadays should have cpu speed problems to do it.

"It is on our TODO list by the way to remove the EE speedhack system and replace it with an actual EE mhz scalar value, so you can just set like 33->1200mhz as your EE core speed."

http://forums.pcsx2.net/Thread-EE-and-VU-cycle-overclock-reverse-speedhack
http://forums.pcsx2.net/Thread-EE-cycles-question
http://forums.pcsx2.net/Thread-Question-about-EE-clock-speed

**Comment by Sarania** [comment]
Sorry to jump in this so late.

I did the same thing a while ago, modifying the slider to work in both directions and set the variables accordingly.

It works, doesn't break much, but doesn't help much either. Basically it is only useful if the game has uncapped FPS, and is EE limited. Suffice to say not a lot, and at most its a few fps improvement. The system requirements however increase MASSIVELY. 50% overclock on the EE causes slowdowns on a 4790k. 33% is doable on powerful hardware.

Here is an example I recorded showing that it does indeed work though:
https://www.youtube.com/watch?v=skG7DwVVWic

**Comment by ramapcsx2** [comment]
"Phantasy Star Complete Collection" is a game disk with a Sega Genesis emulator that runs those old games. With the current default PCSX2 settings, it's just slightly starved of CPU (so the audio crackles a bit). It's great to see even small cylce changes make a difference. (And yea, the defaults need to be fixed).

**Comment by Sarania** [comment]
I made a thread on the forum to discuss the pros and cons of this, and maybe gather some testers to see if it's worthwhile or not. As I said in the thread I am concerned that novice users would think overclocking the EE is some magic way to make games run faster on their old hardware. Then there is the fact that many users don't understand the difference between the emulated and real FPS. So yeah, I think it warrants a good discussion and some testing to see if it is worthwhile.

**Comment by ramapcsx2** [comment]
Do you still have your modifications or remember what they were?
Hopefully it's just adding some slider states and extra cases in the switch/state :p 
We can add all the required stuff now but not expose it to users yet.
It's useful to force cycle timing related bugs to happen more frequently, besides other things.

**Comment by Sarania** [comment]
Yeah, I kept them and remember them. And yes, I simply added more positions to the slider and more cases in the switch. The one issue is I couldn't get a WX slider to have negative numbers(i wanted it to go from -2 to +2 so that 0 was still the default). So it runs from 0 - 4(internally, 1-5 in the UI):
0 - 50% Underclock
1 - 33% Underclock
2 - Default
3 - 33% Overclock
4 - 50% Overlcock

And that's a small issue because it means when the "new" version with OC reads from the INI of the old version without it, the slider won't be where it's expected to. E.G.

Using regular PCSX2 without OC and no EE hack at all, so the INI has it at 0. Load the new version, it reads the ini at 0, and the slider is set to 50% underclock.

I don't really like that, which is one of the reasons I didn't bring my work up before now. Anyway, maybe you guys that know WX better can get it to work in a way that's compatible with current INI set up.

Anyway, I made a fork and applied the changes to the most recent source, you can see what I did there: https://github.com/Sarania/pcsx2/commit/4e7d96e9d195fff3d848f304062dbfdfbf01070b

As I said, hopefully we can figure out a way to make the WXslider go from -2 to +2. It broke when I tried to, and not sure why.

**Comment by ramapcsx2** [comment]
That should be doable :)
Thanks for sharing, I was just getting ready to hack away at it myself :p

**Comment by ramapcsx2** [comment]
Your problem with the slider prolly was that EECycleRate is u8 and making the slider go negative requires it to be s8.
Now this works:
```
m_slider_eecycle = new wxSlider( eeSliderPanel, wxID_ANY, 1, -2, 3,
		wxDefaultPosition, wxDefaultSize, wxHORIZONTAL | wxSL_AUTOTICKS | wxSL_LABELS );
```

**Comment by Sarania** [comment]
I figured it was exactly that, but back when I was working on it I could not find where EECycleRate was being defined lol.

Well, good. That makes it drop in compatible.

**Comment by Sarania** [comment]
Oh, btw, when I had refraction look over that code, he said that the highest setting(50%, which those numbers are only just estimates anyway) with Scalars as 0,1,0 might cause some hanging issues because of 0 delay on the blocks. So far in testing, Fezzer found one game where that happened(but neither he nor I remember what it was).

**Comment by ramapcsx2** [comment]
Ref didn't see the safety in the caller function. Cycles cannot go below 1 there.
However, setting one of those scalers to 1 is very off the mark. 0 is worse, as that actually makes the whole block take zero time (minimum 1 cycle because of the safety). The game will see a faster EE but it's out of our control then just *how fast* exactly.
I recommend not using the block scalers for any new over/under clock slots and just doing this:
```
case -1: return (u32)(s_nBlockCycles >> 3) * 0.9f;
```

**Comment by Sarania** [comment]
Yeah I actually noticed catch to keep them > 0 earlier.

Anyway, this comes from you guys actually understanding what things do vs me just changing numbers around based on hypothesis I get from looking at the code lol. Either way, I'm happy I was able to spark interest in this.

**Comment by ramapcsx2** [comment]
Oh I recognize your position. It looks pretty much like mine in the first 2 years or so. Only I still don't actually code today, unlike you :)

**Comment by Sarania** [comment]
I really wish I understood C better, because I would be happy to contribute small things here and there. Every time I try to learn it, it puts me off though. Of course, even without understanding much of a language, anyone who programs in ANY language can understand variables and cases(at least, I hope so) which is why I was able to do this at all.

But that's half the battle too, I guess. When I first started coding in BASIC that's what I did. Modify a small part of a program, see what happens, repeat.

But yeah in a way it feels crappy to be a legitimate programmer(just not in C), very active on the forums, but never contributing to the project itself. That's also why I expressed interest in the UI changes. I want to add something to the core program, leave my mark on it. Lol.

But that's enough off topic here.

I noticed masterotaku's results in the thread(I had him test for me but he never reported before now) where he said he got KH running at 120FPS (!) internally by using both 60FPS hacks at once + overclock, and how it also helped SotC a good bit.

**Comment by gregory38** [comment]
Instead to put a fixed position slider why not put a continous slider with special fixed/highligted value (so people can spend days of tuning).

**Comment by Sarania** [comment]
@gregory38 - interesting idea. That could be useful. That way you could set the slider to the max position your PC could tolerate, just exactly, and get the most benefit out of it.

**Comment by ramapcsx2** [comment]
@gregory38 Want to code that slider? It should fit within EECycleRate being 8 Bytes though, so this doesn't require overhauling the entire configuration code.
Also it should be done in a branch at first because we still need to decide how to expose this to end users. Also new defaults will be needed.

**Comment by Sarania** [comment]
@ramapcsx2 Well, one option for exposing it would be an INI variable. For instance, if it's set to 0 (which would be default) display the current slider, else if it's !=0, display the full slider.

**Comment by ramapcsx2** [comment]
@Sarania I think that will be problematic with the GUI setup ><

**Comment by Sarania** [comment]
@ramapcsx2 Yeah, it could be. I'm not really confident in my understanding of how the whole UI is put together, so I'm just throwing ideas out there.

Well, another option would be to throw a message box if the user tried to enable the OC, explaining what it does and that it increases requirements and that it isn't a magic optimization etc.

**Comment by pauldacheez** [comment]
This was very recently implemented in Dolphin – feel free to look at it for examples. I'll outline the two actual implementation details I know about it here:
-The hack only changes the IPC (instructions per cycle, duh) of the emulated CPU instead of the actual clockrate – the game always sees 486/729 MHz, but what's done in those cycles can vary.
-The slider in the UI controls a float that's at 1.00f at the default 100% (486 MHz), and that float is what's used to multiply the IPC count.

The UI text itself is pretty descriptive and idiot-resistant, too.
https://github.com/dolphin-emu/dolphin/pull/1798

**Comment by Sarania** [comment]
@pauldacheez - I briefly glanced over that and it seems that you guys had very similar concerns about what novice users would do with such a setting.

As far as your actual suggestions - I'm not sure whether they are or are not applicable here. We seem to do our timing in a pretty weird way lol

**Comment by Sarania** [comment]
There is another way to look at this that I just thought I'd throw out here -

We already have a million ways that uninformed users can break/slowdown/glitch games. So what's one more?

I mean, the EE overclock is less "dangerous" than simply enabling every manual gamefix and HW hack like so many youtube videos advise.

I think maybe instead of hiding it we should just put a large, very visible warning by it, That simplifies the logistics too. Of course, that's just my opinion. I'm really not sure which way I prefer right now.

**Comment by ramapcsx2** [comment]
I think I want a dev menu tab with all this stuff in it, hidden away via config.ini toggle :p

**Comment by gregory38** [comment]
I'm in favor of a new dev tab that contains those extra options. A toggle button can be added like "enable speedhack".

**Comment by avih** [comment]
Keep in mind that it should also play nicely with the presets.

**Comment by Sarania** [comment]
I updated my branch: https://github.com/Sarania/pcsx2/commit/8c5e9ef083d0587409ee480f2894e929cac8150e

Now the slider lines up with our current way(so presets and ini are fine) and also has more granularity, and the values are more sane.

The slider now goes from:
+50%, +40%, +30%, +20%, +10%, default, -33%, -50%

I changed scalars to floats, I expected that to cause issues but it doesn't. I added some commenting for my sanity.

I'm gonna send out builds to my testers and see how it does.

**Comment by Sarania** [comment]
My fork of this is here now https://github.com/Sarania/pcsx2/commit/3675bcfe288d3afbb1e524c378007f7a71086455

I had to refork things to straighten some issues out with the way I made changes initially. Should be good now.

**Comment by karasuhebi** [comment]
Just thought I'd drop by and say that I'm in favor a new tab for dangerous stuff, I think it's a good idea. I don't know how this will mess with the presets stuff though like @avih pointed out.

**Comment by ramapcsx2** [comment]
@avih was working on the scaler function and I think he did away with the factors.
It's best if we use that code, combined with @Sarania's gui and string changes.

**Comment by Sarania** [comment]
Yeah @avih wrote the function to do it without the scalar. Unfortunately that was on my OLD fork and because of my stupidity with Github I had to delete that fork to make things right >_< Hopefully it wasn't too much work and he remembers. It was pretty simple, so it should be okay.

**Comment by ssakash** [comment]
@ramapcsx2  @avih 

any progress on this ? what's the main concern about this actually ?

@Sarania 

I think you need to do some changes to that fork, any reason on why you commented out the following ? 

>if (EmuConfig.Speedhacks.EECycleRate > 2 && EmuConfig.Speedhacks.EECycleRate < 100) {
        scalarLow *= EmuConfig.Speedhacks.EECycleRate;
        scalarMid *= EmuConfig.Speedhacks.EECycleRate;
        scalarHigh *= EmuConfig.Speedhacks.EECycleRate;
        }

In result of the following PCSX2 wouldn't read greater than 2 values and apply the increase in scalar values. also on the comments how did you determine the overclock rate ? (120% and other stuffs)

**Comment by avih** [comment]
I wasn't and am not working on it. I only had a request that the old slider values (mappings of slider-value -> stealing configuration) are kept and that new slider values would include the new configurations.

**Comment by Sarania** [comment]
@ssakash 
As I recall that commented part was for the ini EE cycle rate under clock where you can set values much greater than the slider. Those lines interfered with the way I did the scalars as I recall.

The % values were made by benchmark testing in PS2 SNES emulator inside PCSX2. It has a frame rate counter, and the speed of the EE affects it directly as it runs entirely on the EE. However the ultimate affect on true PS2 games is much less than those % will indicate.

The reason I stopped work on this was twofold:
There was a lot of resistance/questioning whether it was useful
I was reaching the limit of my C ability

If we think it is useful I can finish it and make it nice.

**Comment by ssakash** [comment]
@Sarania 
> Those lines interfered with the way I did the scalars as I recall

I don't think it could interfere with the overclock commit, could you provide an example ?

**Comment by Sarania** [comment]
@ssakash It shouldn't anymore, but originally my scale went from 0-5 because I couldn't make it use negative. Since it used numbers > 2, those lines interfered.

**Comment by ssakash** [comment]
@Sarania 

yeah, that's why I was suggesting to revert it back and make it usable again, so you can PR it and others can choose values higher than 2 in INI file.

also about your concerns related to this feature,

>There was a lot of resistance/questioning whether it was useful

There were lots of members in the forum in support of this feature and lots of requests on this, so I think it's a valid feature in user's perspective. also according to the poll in the forum, majority did accept this.

>I was reaching the limit of my C ability

is there anything left to do ? I thought the fork was quite complete excluding the lines which previously interfered, you can bring those lines back again and make a PR.

**Comment by Sarania** [comment]
@ssakash 

Well, @avih had devised a cleaner looking way to do it on my original fork of PCSX2, but I had to delete that fork because of issues in how I made it and so that comment got lost.

Also even I personally have some issues with how I'm doing it now, like how I said the % may be really inaccurate depending on various factors. I'd very much like the feature included, but I'm not sure my current code is the best way. That said, given our current timing set up I am not sure there is much of a better way.

Also we haven't solved the end user problem - the fact that users will probably think "overclock = go faster" and think it will make games easier to run. What of that?

**Comment by karasuhebi** [comment]
>Also we haven't solved the end user problem - the fact that users will probably think "overclock = go faster" and think it will make games easier to run. What of that?

We shouldn't be responsible for user stupidity. Just put a warning in there. That's the best we can do.

**Comment by Sarania** [comment]
@karasuhebi Put a warning where though?

And anyway it wasn't just me - a lot of people felt that was an issue.

**Comment by ssakash** [comment]
I also agree with @karasuhebi on this, the least we could do is add a description related to the change. don't forget to edit the tooltip to also describe the overclock changes. ;)

I don't know what you mean by cleaner looking ? isn't the changes made by avih present at the commit ? the placing of the values in the slider.

I'd rather suggest calculation of the % by the scalar values instead.

If there are any more concerns, please mention.

**Comment by Sarania** [comment]
@ssakash 
1. Well, one of the initial issues brought up by the team themselves was that users would use it improperly and etc etc

2. Well I meant basically checking it over, making sure it's commented well, etc. No, avih's changes are not present in the commit. The commit is my work. Except for rama changing the slider to a s8 so negative would work, avih used a much smaller, nicer little block of code that achieved the same effect.

3. It cant be done based on the scalar easily. The relationship is not linear, and figuring it out would be a pretty big pain. Unless someone just happens to know already.

4. I did edit the tooltips.

Lastly, again the warning wasn't really my idea. I do see the potential for the OC ability to be misused, but not to the point of not including it. Other people were more concerned.

**Comment by ssakash** [comment]
@Sarania 

1. no clue how @avih made that, why not ask him again ?
2. thought so, the %'s  would just be misleading,  better discard that part IMO.
3. Nice :) 

about the chances of user's misusing it, It'd be better to make it clear at the tooltip and description box that overclocking the EE will lead to slow downs. by the way, shouldn't the overclock values on the slider be over the right side rather than the left ? that would be better.

**Comment by ssakash** [comment]
In any case, I'd suggest to check whether this works well on the master branch and PR it after confirmation. Reviewing the code will be easier this way and we could get a lot of opinions on it.

**Comment by Sarania** [comment]
@ssakash well avih should be getting pings from us tagging his name, so I guess he knows.

If not %, then what? The current way is pretty effective. It's no different than how OCing the CPU on your PC by 20% won't lead to 20% gains in most programs, unless they are entirely CPU bound. The % were created with an entirely EE bound program, so they should be close.

The reason the slider goes how it does is to keep compatibility with old INI and the presets, which was a major thing for the devs. I know no way to make the OC be on the right ways without breaking that.

The tooltip needs changed, cuz yeah it's based on the old way I did it. The warning however is currently in the red text.
![1](https://cloud.githubusercontent.com/assets/7574269/9530969/aac776f2-4cc8-11e5-85fa-e7cfba570b1e.png)

**Comment by Sarania** [comment]
Also - someone on the forum suggested adding more granularity to the underclock. I think this is a good idea actually, so I will implement that as well.
