### ISSUE TITLE
[Regression] PCSX2 doesn't save in user-configured directories

### ISSUE THREAD

**Issue by jcdenton2k** [PCSX2/pcsx2#1548]
PCSX2 doesn't save in user-configured directories; always keeps folders in Documents\PCSX2 even when other directories are specified.

-PCSX2 version: Any GIT version from August 29th or later.

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: GSdx, SPU2-X, LilyPad, the rest are null plugins

-Plugin settings: Defaults, no settings modifications affect the issue.

-Description: PCSX2 forces settings/folders to be created under 'User\Documents\PCSX2' instead of any other user-specified directory.  Even when manually overriding some of the directories it still maintains certain files/folders in that forced directory.  Manually editing directories in the INI files does NOT solve this issue.

-How to replicate: Download any git version from August 29th or later, extract to any folder outside of Documents and try to specify your directories.  Despite all efforts you will be forced to have files in Documents even if you want them all in one place.  puNES does something similar but PCSX2 avoided this terrible practice prior to the Aug 29th git download.

-Last known version to work: v1.5.0-dev-1214-gda68811 and any versions prior to August 29th.

-PC specifications: Win7 SP1 x64; other specs not applicable.

Other comments:  Let us specify whatever user-specific directories we want all files and folder to be placed within.  DO NOT force this Documents dir on us!

**Comment by avih** [comment]
> -How to replicate: Download any git version from August 29th or later, extract to any folder outside of Documents and try to specify your directories. Despite all efforts you will be forced to have files in Documents even if you want them all in one place. puNES does something similar but PCSX2 avoided this terrible practice prior to the Aug 29th git download.

Please describe the steps more explicitly. Like:
- Download the portable binary from (wherever) and extract PCSX2 in `c:\myfiles\pcsx2` (or any other folder).
- Run PCSX2.
- Menu - Config -> emulation settings -> whatever.
- etc.

I.e. that someone could follow your instructions click by click and reproduce the issue, and when you describe it, describe exactly what you expect (e.g. "folder c:\x\y is created") and what happens instead (e.g. "my-documents\y is created instead").


> -Last known version to work: v1.5.0-dev-1214-gda68811 and any versions prior to August 29th.

Are you sure you tested this version? Because unless you compiled it yourself or someone compiled it specifically for you, this version is not available for download at the build bot.

Also, I'm looking at the changelog of and since da68811, and TBH I don't see any commit which could have affected folder locations issues... Seems the vast majority of commits since then are gsdx specific, or iop recs, or one cdvd commit. None seems related to config dirs...

> Other comments: Let us specify whatever user-specific directories we want all files and folder to be placed within. DO NOT force this Documents crap on us!

Take it easy, no one tried to force dirs, and even if we did, such statement would not make anyone want to help or listen to you.

**Comment by jcdenton2k** [comment]
Solved issue:
I was missing a blank 'portable.ini' file in the PCSX2 directory that resolves this issue.  There are no errors in the code or program.
