### ISSUE TITLE
Lilypad: Allow for separate bindings between controller modes (ie. Dualshock 2 and Guitar)

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1576]
Would it be possible to have separate bindings for each controller mode?

For example, say I have everything bound to their matching button on my DS3. Unfortunately, Band Hero forces me to rebind a few buttons due to its' guitar detection. The problem is that when you switch to and from "Guitar" mode, I have to change the bindings everytime I play another game because every mode shares the same configuration.

**Comment by vsub** [comment]
Not sure if this is what you are asking for but did you tried "Allow binding multiple PS2 controls to one PC control"

**Comment by willkuer** [comment]
Until it is resolved you could always save the lilypad ini file. With a frontend or the command line you could load the ini game specific in an automatic fashion. However what you suggest sounds like a solid feature.

**Comment by vsub** [comment]
> Sorry, that won't work for this scenario- I think that's meant for keyboards so you can press L1 and R1 with 1 keypress.

No that's not what it means...it means that you can set more than one key/button to execute for example Square
![2016-09-19_191109](https://cloud.githubusercontent.com/assets/5032540/18639604/34684f4c-7e9d-11e6-86ed-ff4e0a0dcc47.jpg)
Setting it like this,I can execute Pad1 square by using my usb gamepad,my logitech gamepad or by pressing J

Setting for example L1 and square to a single button/key will execute a combo but that's not because of that option
