### ISSUE TITLE
Haunting Ground missing footsteps after Reverb mods SPU2-X

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#1645]
Issue introduced after git build 1491 which was the merge of PR #1635 noted by a user on the forum which you can see here: http://forums.pcsx2.net/Thread-Haunting-Ground-No-Footstep-Sounds

**Comment by sudonim1** [comment]
Huh.

**Comment by sudonim1** [comment]
Okay I haven't got the game to test it yet, but if this isn't user error (e.g. loading an old state, or simply being mistaken about the volume of footsteps in the game on a real PS2 in that particular area) then either:

A) Footsteps aren't in the dry mix (that would be odd), which should be unaffected, and the reverb is wrong (it is wrong but I'm not aware that it's substantially wrong enough to go from audible to silent).
B) Footsteps are in the dry mix but the reverb is nearly or actually cancelling them out, perhaps because of the final negation step which I put in to better match hardware tests.

Thinking about the negation I added reminds me of a supposed hardware bug Martin Korth describes:

> vIIR works only in range -7FFFh..+7FFFh. When set to -8000h, the multiplication by -8000h is still done correctly, but, the final result (the value written to memory) gets negated (this is a pretty strange feature, it is NOT a simple overflow bug, it does affect the "+[mLSAME-2]" addition; although that part normally shouldn't be affected by the "*vIIR" multiplication). Similar effects might (?) occur on some other volume registers when they are set to -8000h.

The testing was obviously not complete as evident in that quote and several other places, I'm thinking this is an explicit feature to allow a fixed point coefficient of 1.0, although I'm sceptical about the details mentioned.

I'll be very happy if this is a real bug because it means we have a test case which doesn't involve writing many test programs to run reverb on real hardware and save the exact samples in the work area and output.

I'll start playing around with this again.

**Comment by FlatOutPS2** [comment]
User must've used an outdated savestate, as it reproduced the issue. Savestates from releases after 1491 are fine

**Comment by refractionpcsx2** [comment]
Fair enough :)
