### ISSUE TITLE
[Request] Frame Advance

### ISSUE THREAD

**Issue by ReyVGM** [PCSX2/pcsx2#1708]
This is a neat feature other emulators have. Basically, while the emulator is paused, you can hit a key to advance the game frame by frame. It's a great feature for Tool Assisted Speedruns and also for sprite rippers to be able to rip complete animations.

Would that be something that could be added?

**Comment by willkuer** [comment]
TAS doesn't work with pcsx2 as the timing seems not to be stable. At least this is was TASer claim.

The problem here is that to my knowledge all plugins are suspended and are releasing all/most resources. They are relaunched upon continuation of emulation. That's the reason why resuming the emulation takes so much time. Advancing by one frame would take exactly the same time. Also I am not sure that advance by one frame is something meaningful in multi-threaded pcsx2 language. VSyncs are a thing but I guess it is more complicated than just waiting for another vsync. But who knows...

**Comment by refractionpcsx2** [comment]
It might be possible, I'm not sure.  The debugger kind of lets you step through in the recompiler, which may or may not advance frames too (obviously not per click), but I haven't sat there long enough going through blocks to find out, nor do i intend on it, but maybe if we implemented a similar system to use vsync as a breakpoint.

**Comment by ReyVGM** [comment]
Well, the emulator already has a slowdown feature. If you slow it enough, it probably goes frame by frame. Can't that be turned into a manual feature?

**Comment by mirh** [comment]
(¿) Depends on #2412

**Comment by lightningterror** [comment]
Feature added in https://github.com/PCSX2/pcsx2/pull/2412
