### ISSUE TITLE
Jak series, unsual object speedup 

### ISSUE THREAD

**Issue by FerrazaDazzle** [PCSX2/pcsx2#1712]
***PCSX2 LATEST DEV

***PCSX2 options:***
EE, VU default, Fast loading off, everything else under speedhacks are on

***Plugins used:***
SSE4.1, everything else is default

***Description of the issue:***
Jak series have some issues where there is excessive speedups on player (best example is on Jak 2, at the first fortress mission avoiding the KG machine which shoots you) volume and everything else runs at default 60 including voices but the player moves so fast.

***How to reproduce the issue:***
attempt Jak 2, get up to 5% through the game (SAVE FILE LINKED BELOW) where you have to go into the fortress and play there.

https://mega.nz/#!TsR0iZha!HFJVM0xp5Xyct6vgTo-aTxtljFPFYW7cmPjeiS23dOY   -Jak 2 save file, PLAY SAVE 2. (save slot 2 with 5% complete)

***Last known version to work:***
never worked in any version

***PC specifications:***
i7- 5960x, GTX 980Ti G1 Gaming, Windows 10 Enterprise 64bit

**Comment by FlatOutPS2** [comment]
I believe one of the EE/VU slider settings on the speedhacks tab removes this speedup. Try them all one by one and see if it helps.

**Comment by FerrazaDazzle** [comment]
@FlatOutPS2 when EE is set to -33% it helps FEW parts, VU doesnt help really. Regarding this, there is also a FPS issue with the Jak series, some parts even lag on native.
in terms of FPS, Jak 2 has the most issues, Jak 1 is near perfect, Jak 3 has very few issues.

**Comment by MrCK1** [comment]
Is this really a valid issue?

**Comment by SpiffyJUNIOR** [comment]
Yeah, this is still an issue even on the latest version. Increasing the EE rate to 180% or higher helps remove some of these slowdowns, although this will cut your FPS in half or more.
The reason this happens is because Jak automatically speeds up and slows down the game based on the framerate. J_P on the fourms managed to pin point the commit that caused this regression though:
(https://github.com/PCSX2/pcsx2/commit/c8a7a709dcc33172bc252fb6ac7f2fb75da65605)
This most likely won't ever be fixed unless a custom branch is made just for this game :(
