### ISSUE TITLE
PCSX2 hangs when trying to boot compressed isos.

### ISSUE THREAD

**Issue by LoathingKernel** [PCSX2/pcsx2#1820]
***PCSX2 version:***
``1.5.0.r1885.f86ea9f19``

***Description of the issue:***
``Trying to run isos compressed as gz, makes PCSX2 hang during boot with high cpu usage. Trying to run uncompressed isos or mounting them using cdemu before running them, works as intended. With the same PCSX2 version on Windows, everything is working fine with compressed isos.``

***Last known version to work:***
``I believe it is an issue with the latest zlib, as it was working as intended with 1.2.8. Current version of zlib in Archlinux is 1.2.11 which was updated in January 17``

***PC specifications:***
``Intel i5-4690k, Nvidia GeForce GTX 560 Ti, Archlinux 4.9.8``

**Comment by deadair3210** [comment]
Booting gz images is working fine for me, have you tried clearing your settings and seeing if it still happens?

**Comment by LoathingKernel** [comment]
Yes, I have tried with clean settings. I have also tried building and testing various random previous commits to find a working version, going as far back as October 2016. The reason that I build this doesn't have to do something with settings is that I had built a working version in early January, before the zlib update.

**Comment by deadair3210** [comment]
Asked about settings to make sure. I have no issue with the latest dev build from the buildbot, perhaps an issue with your build env?

**Comment by LoathingKernel** [comment]
Builds from buildbot work fine for me too, but the buildbot builds are only for windows as far as I know. The problem is my PCSX2 build in Linux, as I said in my specifications.

**Comment by deadair3210** [comment]
Sorry, didnt see it, guess i didnt read carefully enough. Sorry, ill bow out

**Comment by turtleli** [comment]
Confirmed. Seems to be an issue from zlib 1.2.9 onwards.

**Comment by avih** [comment]
Interesting. zlib doesn't support random access, and so PCSX2 uses zlib in a non trivial way to create an index which allows random access (when booting the gzipped ISO for the first time), and later to use this index (any consecutive boot of that gzipped ISO).

The PCSX2 code is based on one of the zlib's own example files, and was written after personal advice from Mark Adler (co-creator of zlib). What I don't recall, however, is whether or not the index file includes internal data structures from zlib. I think it might.

At which case, the solution is to hopefully delete the index file and let PCSX2 create it again on next boot, such that it contains the new format of zlib's internal structures.

On windows it's not an issue because PCSX2's repository includes its own copy of zlib, and so it's guaranteed not to change.

Could you please try deleting the index file and boot again? it should have the same name as the ISO file, with a `gz.pindex.tmp` addition. On windows it's at the same dir as the ISO file. Not sure if someone placed it elsewhere  on Linux.

If deleting the index solves the issue, then we'd need to add code which adds the zlib version to the index file, and in case it uses a different version than the index has, delete and recreate the index.

If it doesn't solve the issue, then it could be more complex. Possibly much more complex.

**Comment by turtleli** [comment]
It's not an index file issue. Basically it's failing this check in newer zlib versions:
```
local int inflateStateCheck(strm)
z_streamp strm;
{
    struct inflate_state FAR *state;
    if (strm == Z_NULL ||
        strm->zalloc == (alloc_func)0 || strm->zfree == (free_func)0)
        return 1;
    state = (struct inflate_state FAR *)strm->state;
    if (state == Z_NULL || state->strm != strm ||
        state->mode < HEAD || state->mode > SYNC)
        return 1;
    return 0;
}
```
`state->strm != strm` is true, so the function fails (non-zero is failure).

**Comment by avih** [comment]
This is not PCSX2's code, right? At which case, it could still be an incompatible index file issue, where we feed zlib with an incompatible stream state (taken from the index).

**Comment by turtleli** [comment]
Yes, that's zlib code. And no, I still don't think it's an index file issue (I already tried deleting the file before I commented to this issue).

I removed the specific check I highlighted in a local Windows build with zlib updated to 1.2.11, and the game I gzipped seemed to work (I say "seemed to" because I didn't test much and I don't actually use compressed ISOs myself, but it did stop the infinite loop from taking place).

The log shows nothing useful after the index has been created (inifinite loop).

**Comment by LoathingKernel** [comment]
I can confirm it is not an issue with the index. I deleted a few of my indexes too and had them recreated, sadly the issue persisted.

**Comment by gregory38** [comment]
Based on @turtleli feedback

Here the zlib commit that introduce the extra check https://github.com/madler/zlib/commit/b516b4bdd7c0c9f0858adfebf732089014f7b282
```
This verifies that ... and that at least the
first several bytes of the internal state have not been clobbered.
```
As far as I can see, the `inflate_state` struct got a new field. And `inflate_mode` enum got hardcoded magical value.
