### ISSUE TITLE
[GSdx HW Bug] Sakura taisen: atsuki chishioni / サクラ大戦　〜熱き血潮に〜

### ISSUE THREAD

**Issue by 13xforever** [PCSX2/pcsx2#1919]
***PCSX2 version:***
Any, up to v1.5.0-dev-2016-g201c9cd

***PCSX2 options:***
Any combination looks the same, including safe defaults and any hw hacks combination and hw renderers

***Plugins used:***
```
Loading plugins from C:\Games\Emulators Collection\Emulators\PS2\pcsx2\plugins...
	Bound   GS: GSdx32-AVX.dll [GSdx 20160809151530 (MSVC 19.00 AVX) 1.1.0]
	Bound  PAD: LilyPad.dll [LilyPad (20170423160019) 0.12.1]
	Bound SPU2: Spu2-X.dll [SPU2-X 20170423160019 2.0.0]
	Bound CDVD: cdvdGigaherz.dll [cdvdGigaherz 20170423160019 0.11.0]
	Bound  USB: USBqemu.dll [USBqemu 20170423160019 0.1.0]
	Bound   FW: FWnull.dll [FWnull Driver 20170423160019 0.7.0]
	Bound DEV9: DEV9null.dll [DEV9null Driver 20170423160019 0.5.0]
```
Any combination of hw renderers and settings produce shadow artifacts, results slightly vary depending on scene and internal resolution. Dumps with 3 most representative scenes: https://www.dropbox.com/s/naxxgi72el59a9f/sakura%20taisen%20shadows.7z?dl=0

***Description of the issue:***
Instead of the shadows, we have partial-to-fullscreen gray overlay, and in some battle scenes water overlay/artifact.
Software renderer:
![sakura taisen shadows 1 sw](https://cloud.githubusercontent.com/assets/36445/25429576/e9694328-2a92-11e7-979f-94d5b9e47935.png)
Typical hw result:
![sakura taisen shadows 1 hw _small](https://cloud.githubusercontent.com/assets/36445/25429568/e10c5d64-2a92-11e7-92d6-0d7bac5ec0b2.png)

***How to reproduce the issue:***
Load any 3D scene

***Last known version to work:***
As far as I know, this was always a problem

***PC specifications:***
CPU: Intel i7-3770K
GPU: AMD HD7970, nVidia GTX 980, nVidia GTX 1080 Ti
OS: Windows 7 Ultimate, 8 Pro, 8.1 Pro, 10 Pro (up to 1703), all x64

**Comment by 13xforever** [comment]
Dumps separately (had trouble attaching them to the original post):
[sakura taisen shadows 1 (hw).zip](https://github.com/PCSX2/pcsx2/files/958033/sakura.taisen.shadows.1.hw.zip)
[sakura taisen shadows 2 (hw).zip](https://github.com/PCSX2/pcsx2/files/958035/sakura.taisen.shadows.2.hw.zip)
[sakura taisen shadows 3 (hw).zip](https://github.com/PCSX2/pcsx2/files/958036/sakura.taisen.shadows.3.hw.zip)

**Comment by willkuer** [comment]
Your gsdx plugin is outdated. Please try a more recent one.

**Comment by 13xforever** [comment]
I apologize, didn't notice that some versions of GSdx were dropped.
The issue still stands though. I presume I don't need to re-dump frames?

```
Loading plugins from C:\Games\Emulators Collection\Emulators\PS2\pcsx2\plugins...
	Bound   GS: GSdx32-SSE4.dll [GSdx 20170423160019 (MSVC 19.00 SSE4.1/AVX) 1.1.0]
	Bound  PAD: LilyPad.dll [LilyPad (20170423160019) 0.12.1]
	Bound SPU2: Spu2-X.dll [SPU2-X 20170423160019 2.0.0]
	Bound CDVD: cdvdGigaherz.dll [cdvdGigaherz 20170423160019 0.11.0]
	Bound  USB: USBqemu.dll [USBqemu 20170423160019 0.1.0]
	Bound   FW: FWnull.dll [FWnull Driver 20170423160019 0.7.0]
	Bound DEV9: DEV9null.dll [DEV9null Driver 20170423160019 0.5.0]
```

![gsdx_20170426194403](https://cloud.githubusercontent.com/assets/36445/25440405/ccf9fc84-2ab8-11e7-8622-ae77e86c45e2.png)

**Comment by MrCK1** [comment]
@13xforever any status update on latest git?

https://buildbot.orphis.net/pcsx2/

**Comment by lightningterror** [comment]
The dumps still show the issue so it's still broken.

**Comment by tadanokojin** [comment]
Notes for future me/others:

1. Game renders some geometry (ground, etc) with 32bit color and 24bit depth
2. Later, switches to rendering to a 16bit color buffer and clears it to a solid color
3. Draws shadows in 16bit buffer
4. Copy by BLIT of 16bit color buffer into 16 bit depth buffer at another address
5. Switch to new depth buffer, back to old 32 bit color buffer
6. Perform a depth test (GTE) with color mask puts pixels into alpha of 32 bit color
7. Perform destination alpha test places shadow

Game is emulating a stencil. Point of issue for gsdx is somewhere between 4 and 6. The left side line is the result of what seems to be only part of the 16bit depth surviving.

**Comment by tadanokojin** [comment]
This game has a lot of issues

issue 1: cache will miss the first BLIT, this can be worked around with preload frame hack (will break scaling) but even then we have an issue where data isn't entirely there. Take a look at z buffer with preload hack.

![_00306_f5002_rz0_035c0_Z_16S](https://user-images.githubusercontent.com/26046960/85323670-70df5500-b496-11ea-9326-791ac712dda9.png)

Issue 2: depth test is not working. Preload is enough to see at least how top part will do and it doesn't do well. Game wants to clear the color buffer to 16, then write 15 for shadows, then BLIT to z, then depth test to produce shadows in alpha channel. I feel the issue here is accuracy problem.
![_00306_f5002_rt1_01180_C_32_alpha](https://user-images.githubusercontent.com/26046960/85324006-0d095c00-b497-11ea-814e-e2928d80a177.png)

Issue 3: later this game tries to clear depth from EE side. There is a known issue on the cache where EE write isn't full data, I feel this issue is the same here. This results in the line you see on the left as only the left part gets the clear.
![_00310_f5002_rz0_035c0_Z_16S](https://user-images.githubusercontent.com/26046960/85328423-b7d14880-b49e-11ea-9de8-ae0c8fe31212.png)
