### ISSUE TITLE
Oni : Flickering in ingame cutscenes under DirectX11.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2057]
***PCSX2 version:***
Last dev version

***PCSX2 options:***
All default, tested with and without speedhacks.

GSDX options:
![capture](https://user-images.githubusercontent.com/26351275/29781558-df012f5c-8c19-11e7-8b20-e5678ac8a077.JPG)
![capture2](https://user-images.githubusercontent.com/26351275/29781587-f3bbcf56-8c19-11e7-9338-503b6434ac4a.JPG)

***Plugins used:***
All default 

***Description of the issue:***

***-The DX11 mode have an ingame cutsceen rendering bug (look at the top and the bottom of the screen):***
![capture6](https://user-images.githubusercontent.com/26351275/29781763-907da300-8c1a-11e7-94fd-cb083c43f5a7.JPG)
(note: DX9 and OpenGL are fine)

***How to reproduce the issue:***
Load pcsx2 and "ONI"

***Last known version to work:***
Don't exist, the game is also broken on 1.4

***PC specifications:***
Intel Core 2 Duo E4600 Gigabyte GTX 560Ti  Windows 10 64 Bit

***Gs dump will be post if you want***

**Comment by gregory38** [comment]
If OpenGL is fine, it is a depth of field effect. Tbh, D3D renderer isn't really supported.

**Comment by atomic83GitHub** [comment]
Yes, OpenGL is fine.

**Comment by atomic83GitHub** [comment]
I will close this, the issues are know and there is no need to keep this open.

**Comment by FlatOutPS2** [comment]
@atomic83GitHub Can you add a gsdump?

**Comment by atomic83GitHub** [comment]
Here is the Gsdump:
https://drive.google.com/file/d/1ua2HAzmE8CrOXoHosRzjbsT1j9SR-1wU/view?usp=sharing

**Comment by lightningterror** [comment]
> If OpenGL is fine, it is a depth of field effect. Tbh, D3D renderer isn't really supported.

Thing is Direct3D9 and OpenGL are fine going back to v1.0.0

**Comment by atomic83GitHub** [comment]
@lightningterror And even now DX9 is fine, it's only DX11 which have the issue.

**Comment by KrossX** [comment]
There's a hackfix for this line of code: [tfx.fx#L442](https://github.com/PCSX2/pcsx2/blob/d632454a23d62fb6255bf601570409e5cf083a52/plugins/GSdx/res/tfx.fx#L442), which "fixes" the issue. For some reason, that dd.y is odd enough that even replacing it for 0, 0.5 or 1 show no problem yet clamping dd.y did not work. The proposed new hack is the following:

```cpp
		float4 cx1 = lerp(c[0], c[1], dd.x);
		float4 cx2 = lerp(c[2], c[3], dd.x);
		t = lerp(cx1, cx2, dd.y); //dd.y problem
		t.a = cx1.a;
```

This makes alpha be linearly filtered instead of bilinearly, looks good enough and oddly "fixes" Xenosaga's hair problem too. Also, if [HalfTexel @ tfx.fx#L404](https://github.com/PCSX2/pcsx2/blob/d632454a23d62fb6255bf601570409e5cf083a52/plugins/GSdx/res/tfx.fx#L404) is removed the problem also disappears (not Xenosaga's hair though). Maybe it's a pixel/texel center problem?
