### ISSUE TITLE
1 Second Stutter on all Games using Gsdx32-AVX2 (Hardware/Software) fixed if using Gsdx32-SSE4

### ISSUE THREAD

**Issue by Nashismo** [PCSX2/pcsx2#2156]
PCSX2 version:
pcsx2-v1.5.0-dev-2233-gbc8d9d40b-windows-x86

Issue:
All my games, specially Shadow of the Colossus and GOW2 have a 1 second stutter every minute or so. Sound cut off too.

After tweaking with different settings, I have found this only happens when using the Gsdx32-AVX2 plugin! (Hardware and Software. Opengl/DX11).

This is completely fixed if I change the plugin to Gsdx32-SSE4. But this is not ideal as the AVX2 plugin is much faster on my PC.

PC specifications:
i7 6700 4ghz
Nvidia 1050ti
Windows 10

I hope this information helps.

Sincerely,
Ignacio.

**Comment by Nashismo** [comment]
UPDATE:

I put my PS2 games on an SSD and I nolonger have these stutter issues. But it makes no sense! The real PS2 DVD disc reader is even slower than a standard HDD and it never gives you problems, by making games stutter, etc.

Any idea what could be causing this? It seems like a problem with the ISO/DVD plugin.

**Comment by willkuer** [comment]
It makes no sense that either SSD or SSE4.1 fix your issue. I guess you have reproducibility issues and neither of both is triggering your issue. Sounds to me rather like dynamic throttling due to overheating of your CPU in case you have a notebook. But just guessing into the dark.

HDD issue could as well be related to bad sectors and/or anti virus software.

**Comment by lightningterror** [comment]
It could be the power plan as well that throttles the cpu when not fully utilized.

I suggest you switch to high performance.

**Comment by Nashismo** [comment]
I am using high performance and I am on a dektop. The CPU is using a Coller master fan, no problems there.

Also, as an update, the stutter was present on all GDSX plugins, only more pronounced on AVX2. I put the game ISO on an SSD and all those issues were fixed.

Both HDD and SSD are new and I don't run ANY antivirus, I am a PC user extrordinare :) I don't need Antivirus. My PC at idle has 0% use on the HDD and 0% use on the CPU.

I have 16GB od DDR4 ram also. Like I said, the only thing that makes sense to me is whatever software that controls the reading of the ISO. I bet my life on it.

**Comment by MrCK1** [comment]
You said the issue was still fixed correct? Are there any problems that still remain?

**Comment by Nashismo** [comment]
Yes. The issue is completely fixed by moving the game (SOTC) to the SDD. I haved been testing for 2 days and I am 100% certain. The problem comes back if I use a standard HDD.

Thing is, I have used PCSX2 before (other PC's) and I had never encounter an issue like this. I always used standard HDD's also.

The only error PCSX2 gives me is this:
[wx] Failed to load shared library 'C:\PCSX2\plugins\DEV9ghzdrk.dll' (error 126: no se puede encontrar el módulo especificado.)

I haven't install ANY plugins besides the one that come with the emulator.

**Comment by lightningterror** [comment]
> Oh, I do have to add this: The 2nd HDD (the mechanical HDD) is a Toshiba 1tb, 5400rpm HDD (new and 0% fragmented). But it shouldn't be an issue, I have run PCSX2 before on laptops without problems, and I would remember because SOTC is my favorite game to emulate and tweak. And I am SUPER perceptible to stutters and problems like that.

It can be an issue if other programs are reading data from the HDD constantly.
I found that Windows 10 was constantly reading data from the HDD which resulted in 100% disk usage.
Here are some of the services you can close.
Diagnostic Tracking, Windows Search, Superfetch.

**Comment by Nashismo** [comment]
I know that :) Windows 10 is horrible in that regard. But I have NONE of those issues, believe me, I have unisntalled/disabled all those processes weeks ago, I have blocked (through the Hosts file) all the digusting spyware by Microsoft and I have killed all their spyware scheduled processes.

I fix computers for a living! (among other things) So I know what you mean and that is not the issue, that is why I said that my PC has: 0% use on the HDD and 0% use on the CPU while idle. Because everytime I install a new OS, I am DAYS tweaking it to reach maximum performance and 0% idle states.

**Comment by Nashismo** [comment]
By the way, anyone knows of other game/ISO reader plugins? Because I believe that is the issue. Thanks.

**Comment by lightningterror** [comment]
It could be the specific to that HDD maybe and the delay it takes to move the head.

What about Link Power Management in intel RST ? Is it disabled ? Same goes for Windows write
cache buffer.

**Comment by avih** [comment]
GOW2 and SoTC are known to read constantly from the disk/DVD. SoTC streams world data from seemingly arbitrary locations at the ISO image _constantly_ wherever you go, and GOW2 constantly reads the DVD for the sound track at all times.

Your issue is completely unrelated to AVX2 or the GFX/GS plugin, and completely related to reading data from the ISO image. The fact that it works fine with an SSD is the final nail in this coffin.

Are you by any chance using compressed ISO? If yes, then this could happen, especially with these two games (even though I tested these two games extensively when I added the gzip support, and at least for GOW2 the data should be cached well enough and unaffected by decompression times. For SoTC it depends on your CPU speed and it's certainly a worst-case scenario for disk access pattern a game could have).

IF the ISO is not compressed, then something prevents PCSX2 from reading data from the HDD as fast as it wants. Could be fragmented HDD, or dying HDD, or some process which accesses the disk intensely every once in a while and prevents PCSX2 from reading when it needs to.

If you have another HDD (or disk on key, etc) laying around which you can connect _in addition_ to your current HDD, I'd suggest using it for testing.

I'm 99.999% sure it's an issue with your system and beyond PCSX2's control.

**Comment by Nashismo** [comment]
Thank you guys! It probably is the ISO as it weights 2.50gb, Shadow of the Colossus US version. Probably the issue will be fixed by using a FULL ISO, which should be around 4.16gb, if I am not mistaken.

**Comment by avih** [comment]
> it weights 2.50gb, Shadow of the Colossus US version. Probably the issue will be fixed by using a FULL ISO, which should be around 4.16gb

While it's true that the US version has smaller ISO, Both versions read constantly from random places at the ISO whenever you move around. So no, it doesn't matter which version you try.

It does matter that you fix your PC or replace your HDD or use another drive.

**Comment by Nashismo** [comment]
Thank you for your time then. You guys are great, the best!
