### ISSUE TITLE
Castlevania Symphony of the Night PGPUSTAT hang

### ISSUE THREAD

**Issue by Nobbs66** [PCSX2/pcsx2#2232]
***PCSX2 version:***
v1.5.0-dev-2234-g7a71b6f3d

***PCSX2 options:***
Default clamping/rounding, no speedhacks. 

***Plugins used:***
Default plugins

***Description of the issue:***
The game will get into an endless loop after pressing start because it's waiting for Bit 28 of PGpuStat to be set indicating the GPU is ready to receive a new DMA block. This can be worked around by always returning bit 28 as set on PGpuStat reads. 

***How to reproduce the issue:***
Boot the game and press start. 

***PC specifications:***
Intel Core i7 5820K @ 4.4Ghz
MSI X99A SLI Plus
Sapphire R9 Fury Tri X
Windows 10 (64 bit)

**Comment by atomic83GitHub** [comment]
Is it dangerous to implement this workaround as a hack?

**Comment by ramapcsx2** [comment]
Well, it would hide this problem. I'd like to know a PSX dev's opinion on this.

**Comment by lightningterror** [comment]
Perhaps @RedPanda4552 and @kenshen112 can also take a look at this.

**Comment by RedPanda4552** [comment]
If we're going to hackfix this, I'd be a little more open to a stall detection, e.g. a timeout counter similar to memcard auto ejection, rather than arbitrarily forcing it on. But if we want a more permanent and proper solution, we need someone who understands PGIF better. But if a hackfix suffices considering PGIF as-is is a giant hack, this should be an easy one.

**Comment by Nobbs66** [comment]
Uncommenting Line 469 in pgif.cpp fixes the issue as well.

**Comment by lightningterror** [comment]
Closing as it's a ps1 issue.
