### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by TotalCaesar659** [PCSX2/pcsx2#2415]
Hello, could you add 18.04 "Bionic Beaver" support to Ubuntu PPA (https://launchpad.net/~gregory-hainaut/+archive/ubuntu/pcsx2.official.ppa)?

**Comment by Sunderland93** [comment]
PCSX2 also in my Retrogames PPA with 18.04 support https://launchpad.net/~samoilov-lex/+archive/ubuntu/retrogames

**Comment by helkaluin** [comment]
If you don't mind getting daily updates given there's a new git commit, you can use the daily PPA: https://code.launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily

**Comment by PhoenixLandPirate** [comment]
I've had issues finding the correct ppa to add, Perhaps the official website should show all active PPA options and a small description, this could also have a deprecated PPA section, or if anyone mentions an unofficial PPA, that ppa could be in a "Unofficial" section of webpage, so that if anyone is having a problem with said PPA, they can easily find out why.

**Comment by gregory38** [comment]
Sorry for the delay, I try to relaunch a build for newer Ubuntu. It's been a long time, I don't remember how to do it :blush: It might not work due to various GCC buggy release. I don't have time to backport GCC workaround into 1.4 branch.
