### ISSUE TITLE
[Linux] OnePad issues

### ISSUE THREAD

**Issue by kenshen112** [PCSX2/pcsx2#2495]
PCSX2 1.5.0 latest build

Issue:
The latest builds of OnePad can't detect controller's I had to switch to OnePad Legacy to map and use my DS4 controller, note 1.4.0 doesn't have this issue.

***PCSX2 options:***
NA.

***Plugins used:***
OnePad / OnePad Legacy.

***How to reproduce the issue:***
Use the latest version of onepad to map controller's. 

***Last known version to work:***
OnePad legacy in the 1.5 versions / pcsx2 1.4.0 

Edit by @lightningterror 
Let's keep this as a meta issue for any Onepad issues with the same/similar nature.
Xbox Controller: https://github.com/PCSX2/pcsx2/issues/3108
Xbox 360 Controller: https://github.com/PCSX2/pcsx2/issues/2707
Microntec USB joystick: https://github.com/PCSX2/pcsx2/issues/2010

**Comment by kenshen112** [comment]
@arcum42 I could try that, but why would the older version work and not the newer version mind you i'm not the only one to have experienced this behavior.

**Comment by arcum42** [comment]
Well, yes, I'd imagine not. That's why I'd want a copy of the string.

The legacy version didn't have any sort of auto-detection. You manually configured your gamepad. As such, it didn't really care what type of gamepad you had.

The non-legacy version picks up your controller automatically, no configuration needed. But it does that by scanning through a list of controllers:
https://github.com/PCSX2/pcsx2/blob/04ff2aff65e070ea61dc6cc0b5914d458ac19dce/plugins/onepad/res/game_controller_db.txt

If the controller is not on the list, it doesn't detect it. It didn't detect *my* controller, when I tried it earlier.

So I looked around, found that tool, added the string it gave me to the appropriate file, recompiled, and it now knows about my particular model of controller. Given that mine was a Logitech F510 controller, that's not too helpful for your controller, but the same steps should work.

**Comment by kenshen112** [comment]
So one thing to note I haven't looked at the tool yet. But in the text file you mentioned the DS4 makes an appearance.

**Comment by arcum42** [comment]
When you actually go to configure it in onepad and it won't let you configure it, it should print out a message in the log that looks like this, only with different controller information:

"onepad: Joystick (Logitech Gamepad F510,GUID:030000006d0400001ec2000019200000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.onepad: Joystick (Logitech Gamepad F510,GUID:030000006d0400001ec2000019200000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database"

That GUID is the important part. It's possible for there to be more than one model of the same controller, but the GUID is how it is identifying it internally. Now, if that GUID is in the list, there's definitely a problem.

The tool I mentioned is an alternative to antimicro, btw. 

Based on the message, it looks like you could just stick "SDL2=" and the string in the ini file to get it to work, too. But if that works, definitely post the string here too, so that it can be added to the file, in case someone else has the same controller.

If I get a chance, I may see if I can update that file, too, because I looked at the original file that was taken from, and there are more controllers in it by now. Don't know if yours is one of them, but it's worth looking at. Trick is making sure anything that's been added to the list since it was copied stays in...

This is assuming that it's not recognising it at all, anyways. Not working in the new version but working in the legacy version sounds like it. Unfortunately, the version I'm more familiar with is the legacy version...

**Comment by kenshen112** [comment]
GUID: 030000004c050000a00b000011810000

**Comment by arcum42** [comment]
I've just been fiddling with it, and I'm not actually sure putting it in the ini file is working, because I removed my controller from the internal list on my computer, and tried putting it in the ini file several different ways. Might be a bug on that front.

Now basically what that tool does I mentioned is that you run it, it asks you to press all the buttons on the controller, and then it outputs a line identical to the ones you see in that file. The theory is that you then put the line it gives you into that file, \pcsx2\plugins\onepad\res\game_controller_db.txt, and then recompile it and it would see it there. That actually worked on my controller.

However, I actually do see that GUID in that file. It's still possible something could be wrong with the line, I suppose, so running that command, getting the line, and replacing the one in the file with the one you get might help.

Otherwise, we might need to wait till gregory looks at it, since the autoconfiguration code is his. I did a bunch of work on onepad-legacy back in the day, but that's the version that's actually working for you...

**Comment by gregory38** [comment]
Here an example of syntax for the ini. (spaces around = are likely important, final comma too)
```
SDL2 = 03000000a306000020f6000011010000,PS2700 Rumble Pad,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,lef
tstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2,righty:a4,start:b9,x:b0,y:b3,platform:Linux,
```

**Comment by kenshen112** [comment]
Well for me I'm on antegros a branch of Arch so latest on everything the other's who've faced this particular issue would probably be a different case

**Comment by gregory38** [comment]
Hum potentially old onepad was built with SDL1 which mean the old jsdev interface. Whereas new version is based on evdev.

**Comment by gregory38** [comment]
Hum, do you have multiple pad ? Maybe you should select the pad in the GUI (Gamepad Configuration button on bottom left).

**Comment by turtleli** [comment]
Just checking - have you tried booting a game to see if the buttons work without mapping the controller?

**Comment by arcum42** [comment]
Just to mention, contrary to what I said earlier, the ini file *is* working. What I didn't notice in my test, which involved commenting my Logitech F510 controller out of the database and putting it in the ini file, is that I appear to have put it in the Onepad.ini file, when it should have been the Onepad2.ini file, as that is the non-legacy version's ini file. Be careful of this if you want to test any ini changes. (Maybe there should be a comment in both inis about that to avoid confusion?)

I don't know if a line in there would override a line in the main database. I'd hope the ini file would have priority, as if the inputs are mapped wrong in the line in the database, I could see that being an issue.

Sadly, I don't own a Dualshock 4 controller at all to test things with...

**Comment by gregory38** [comment]
Priority should be 
* user
* onepad internal db
* SDL db

@kenshen112 what happen if you edit onepad db file to remove all ps4 controller. I think it should be builtin in SDL2.

Then, could you try `evtest` on all devices in `/dev/input/event*`. You need to found the one related to your controller (few of them are accessible by user). Just print the initial info and test a button. For example
```
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x6a3 product 0x109 version 0x100
Input device name: "SAITEK P880"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 288 (BTN_TRIGGER)
    Event code 289 (BTN_THUMB)
    Event code 290 (BTN_THUMB2)
    Event code 291 (BTN_TOP)
    Event code 292 (BTN_TOP2)
    Event code 293 (BTN_PINKIE)
    Event code 294 (BTN_BASE)
    Event code 295 (BTN_BASE2)
    Event code 296 (BTN_BASE3)
    Event code 297 (BTN_BASE4)
    Event code 298 (BTN_BASE5)
    Event code 299 (BTN_BASE6)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 1 (ABS_Y)
      Value    136
      Min        0
      Max      255
      Flat      15
    Event code 2 (ABS_Z)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 5 (ABS_RZ)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 16 (ABS_HAT0X)
      Value      0
      Min       -1
      Max        1
    Event code 17 (ABS_HAT0Y)
      Value      0
      Min       -1
      Max        1
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
```

**Comment by gregory38** [comment]
@arcum42 
```
If I get a chance, I may see if I can update that file, too, because I looked at the original file that was taken from, and there are more controllers in it by now. Don't know if yours is one of them, but it's worth looking at. Trick is making sure anything that's been added to the list since it was copied stays in...
```
Don't hesitate to update the DB. It should be a bit outdated now.

**Comment by kenshen112** [comment]
@gregory38 One interesting thing I discovered is that in evtest their's three separate entries for the DS4 one for the touch pad, one for the motion sensor and one for the device itself I wonder if One pad in grabbing one of the other entries instead.

**Comment by kenshen112** [comment]
```Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x54c product 0xba0 version 0x8111
Input device name: "Sony Interactive Entertainment DUALSHOCK®4 USB Wireless Adaptor"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 304 (BTN_SOUTH)
    Event code 305 (BTN_EAST)
    Event code 307 (BTN_NORTH)
    Event code 308 (BTN_WEST)
    Event code 310 (BTN_TL)
    Event code 311 (BTN_TR)
    Event code 312 (BTN_TL2)
    Event code 313 (BTN_TR2)
    Event code 314 (BTN_SELECT)
    Event code 315 (BTN_START)
    Event code 316 (BTN_MODE)
    Event code 317 (BTN_THUMBL)
    Event code 318 (BTN_THUMBR)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value    129
      Min        0
      Max      255
      Flat      15
    Event code 1 (ABS_Y)
      Value    123
      Min        0
      Max      255
      Flat      15
    Event code 2 (ABS_Z)
      Value      0
      Min        0
      Max      255
      Flat      15
    Event code 3 (ABS_RX)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 4 (ABS_RY)
      Value    127
      Min        0
      Max      255
      Flat      15
    Event code 5 (ABS_RZ)
      Value      0
      Min        0
      Max      255
      Flat      15
    Event code 16 (ABS_HAT0X)
      Value      0
      Min       -1
      Max        1
    Event code 17 (ABS_HAT0Y)
      Value      0
      Min       -1
      Max        1
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
  Event type 21 (EV_FF)
    Event code 80 (FF_RUMBLE)
    Event code 81 (FF_PERIODIC)
    Event code 88 (FF_SQUARE)
    Event code 89 (FF_TRIANGLE)
    Event code 90 (FF_SINE)
    Event code 96 (FF_GAIN)
Properties:
Testing ... (interrupt to exit)
Event: time 1535142744.435069, type 3 (EV_ABS), code 0 (ABS_X), value 128
Event: time 1535142744.435069, -------------- SYN_REPORT ------------
Event: time 1535142744.444065, type 3 (EV_ABS), code 0 (ABS_X), value 129
Event: time 1535142744.444065, -------------- SYN_REPORT ------------``` Note that in this example I'm using Sony's official DS4 adaptor but it ultimately doesn't make a difference as I'm not the only one who's experienced this Behaviour Will try removing the entries and seeing if OnePad works off the bat with that.

**Comment by kenshen112** [comment]
@gregory38 taking every entry for the ps4 controller in onepad like you suggested made no difference the pad rumbles but doesn't map

**Comment by kenshen112** [comment]
Soo just tried playing Kingdom Hearts with normal onepad non legacy with no mapping whatsoever and it just magically decided to start working out of nowhere. I wonder if it's because I mapped the legacy plugin that it's somehow working because it certainly wasn't before.

**Comment by kenshen112** [comment]
@gregory38 Nothing bad happens it works fine after power cycling the controller even taking out the adapter.

**Comment by cglmrfreeman** [comment]
Can't seem to get the Dualshock 4 working on my setup. Running Opensuse Tumbleweed with a gamepad GUID of "030000004c050000c405000011010000". Controller is working and is recognized, but no button presses will register in PCSX2.
