### ISSUE TITLE
SLES-54153 & SLES-54151 memory card filter issue

### ISSUE THREAD

**Issue by NexxusDrako313** [PCSX2/pcsx2#2524]
SLES-54151 (Let's Make A Soccer Team!) can interface with SLES-54153 (Virtua Pro Football) memory card data to import players from completed career saves in the latter game.
Meanwhile, Virtua Pro Football can import teams from LMAST to play with in game.

The memory card filter in the gamedb does not account for this, and thus these features cannot be used.
 at the minute.

Can this be fixed?

**Comment by ramapcsx2** [comment]
This should be doable, yeah.
Might want to think about adding other known pairs as well, and maybe even something for Suikoden 2 (PSX) and Suikoden 3 (PS2).

**Comment by kenshen112** [comment]
sounds like something @RedPanda4552 could look into

**Comment by lightningterror** [comment]
Status ?

**Comment by trostboot** [comment]
I'm doing this right now, and also researching and adding other pairs (although Suikoden II/III was already in the DB) plus various serials that aren't in the DB yet.

Here's a question, though: how do re-releases with different serials behave? While most Greatest Hits etc. releases seem to share the serial with their original release, there are some that do not (for example, Naruto: Narutimate Hero 3 is SLPS-25589, the _PlayStation 2 the Best_ re-release is SLPS-73251).
I can kinda see it going either way (the re-release looking for saves under the original serial, or looking for it under its own), but have no way to actually test it. In theory there would be no harm to include both serials in these cases, but that means a lot of extra work, so maybe someone has some actual experience with this.

A different question regarding style: currently there are a number of different styles used for titles within the DB. Any entries I'm adding or changing I'm currently converting to the style as used in the redump database, as that also seems to the be the style most widely used across other places, but it isn't the most common style within the DB as it is currently.
Are there any objections to this?

**Comment by willkuer** [comment]
How probable is it that somebody has a release and its rerelease? I don‘t think there is much experience regarding that. Also it might depend on the game.

Noop changes typically are not a good idea. Is there a benefit to change the dash to colon and vice versa other than satisfying the committer‘s perfectionism? Because definition of perfect varies from person to person.

**Comment by trostboot** [comment]
That is why I am asking. The more pressing issue is, if a re-release with a different serial uses the original serial for its saves, then it cannot see its own save games because by default it will be filtered to only include the re-release serial.
I don't if or how often that happens, hence my question.

The benefit to changing names like this is that it is actually the correct name. In this particular instance, it is _Twisted Metal: Black_ on [Wikipedia](https://en.wikipedia.org/wiki/Twisted_Metal:_Black), or on [Metacritic](http://www.metacritic.com/game/playstation-2/twisted-metal-black), or pretty much anywhere else you look. And the same is true for many other titles.

Let me turn the question around, is there anything that would even be impacted functionality-wise by having the name field in the database altered? Because as far as I can tell, the name is only used for display purposes, where having the actual correct name is always preferable.

**Comment by willkuer** [comment]
I never heard that a game doesn‘t recognize it‘s savegame. With the new foldermemcard I could believe that save games made with an old game version might not show up on a new game version‘s loading screen whereas that might work on a real device but as I said that should be a rare case. I‘d assume in such cases people will complain in the forum and therefore I‘d fix it after such a thread appears.

Regarding the naming I don‘t mind and my opinion doesn’t matter. The problem with noop changes is that they clutter the history. Not sure how many people git blame’d gamedbf though. And possibly in one month somebody will come around the corner and reference two other trustworthy sources and change all names back.

**Comment by trostboot** [comment]
Obviously that can only happen with memory card folders, that's what this issue is about. With regular memory cards that will never ever happen. Speculation and hoping for the best is fine and all, pro-active action is always better, hence why I asked if someone had first-hand experience with such a title.

As for gamedb clutter, I've already added or changed hundreds of lines, I'm not sure it matters too much if I change the name field along with other changes. Should just be a single commit in the end.

**Comment by turtleli** [comment]
I would think that they all use the same serial, but I guess the only way to know for sure is to have someone with those discs verify it. That's going to be hard with Japanese region games.

I have some Japanese games that requires MemCardFilter lines to be added (it might be useful as data too):
* Growlanser 2 re-release (part of Growlanser Collections) - serial is SLPM-62439. The disc should be identical to SLPS-20105 (Deluxe pack, not confirmed because redump doesn't have data for it but it's very likely), which saves data using the SLPS-20106 (normal edition) serial.
* Growlanser 3 re-release (part of Growlanser Collections) - serial is SLPM-62438 (not a typo), The disc is identical to SLPM-62107 (Moe Moe Lucky Pack, confirmed by identical redump md5), which saves data using the SLPM-62108 (normal edition) serial.
 * Super Robot Wars OG Gaiden - serial is SLPS-25836. It can import save data from Super Robot Wars OG (SLPS-25733). It saves as SLPS-25836. I assume the special edition (SLPS-25835) saves to the same serial.

Also, I suspect that Xenosaga Episode II (SLPS-25388, SLPS-25389) doesn't need SLPS-29001 and SLPS-73224 in the MemCardFilter. I grepped both discs for all the serials currently present on the MemCardFilter line (the method doesn't alway work, but it's useful at times) and those were the only serials that didn't return a match. I assume that also means that the Xenosaga Episode I premium box version (SLPS-29001) saves data using the SLPS-29002 serial.

It's worth noting that according to redump, some SCAJ serial games are the exact same games as SCPS/SLPM/SLPS games (e.g. Xenosaga Episode II), so at least some of the current GameDB entries won't ever be used by PCSX2.

**Comment by trostboot** [comment]
Right, I would be 100% certain that games that have identical hashes and are grouped together in the redump database save to the same serial, which tends to be helpfully noted in the database as internal serial, as well. That's the easy part and we can safely remove those duplicates from the GameDB.

Your Growlanser additions are very helpful. Those would confirm (and redump backs this up by having different internal serials listed) that there are currently different versions of games that would not be able to see their own savedata. I'll add those manually and have a think about how to best find these instances.

**Comment by ramapcsx2** [comment]
Just chiming in on _Twisted Metal: Black_, if redump has that name, then this is what we should use.
By it's own, it's not worth a commit. But if you're there anyway.. ;p

**Comment by pgert** [comment]
Is this correct?

Serial = SLES-54151
Name   = Let's Make a Soccer Team!
Region = PAL-M5
Compat = 5
// Enables import of players from completed career saves.
MemCardFilter = SLES-54151/SLES-54153

Serial = SLES-54153
Name   = Virtua Pro Football
Region = PAL-M5
// Enables import of teams.
MemCardFilter = SLES-54153/SLES-54151

Serial = SLPM-66316
Name   = Pro Soccer Club o Tsukurou! Europe Championship
Region = NTSC-J
// Enables import of players from completed career saves.
MemCardFilter = SLPM-66316/SLPM-66324/SLPM-66442

Serial = SLPM-66324
Name   = World Football Climax [Special Edition]
Region = NTSC-J
// SLPM-66316 enables import of teams.
MemCardFilter = SLPM-66324/SLPM-66316/SLPM-66442

Serial = SLPM-66442
Name   = World Football Climax
Region = NTSC-J
// SLPM-66316 enables import of teams.
MemCardFilter = SLPM-66442/SLPM-66316/SLPM-66324

SLPM-66442 is listed in pcsx2 Wiki but not in GameIndex.

**Comment by Vyktory** [comment]
Original issue poster here (lost my old Github due to 2FA failure), has there been any progress on this issue as yet? I'm preparing to start a Twitch series on Virtua Pro Football as a follow up to my successful LMAST series and want to know whether I'm okay to go ahead. 

Thanks y'all.
