### ISSUE TITLE
GTK-GSDX: Userhack TC-Offsets issue

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#2568]
The issue was reported on discord a few days ago so I'll post it here before all of us forget.
Version v1.5.0-dev-2512 as a reference

The way TC Offsets works on Windows is that it uses bitmasking to store two values in one hexadecimal value. Explained by @RedPanda4552 

Windows:
```
	SendMessage(GetDlgItem(m_hWnd, IDC_TCOFFSETX), UDM_SETRANGE, 0, MAKELPARAM(10000, 0));
	SendMessage(GetDlgItem(m_hWnd, IDC_TCOFFSETX), UDM_SETPOS, 0, MAKELPARAM(theApp.GetConfigI("UserHacks_TCOffset") & 0xFFFF, 0));

	SendMessage(GetDlgItem(m_hWnd, IDC_TCOFFSETY), UDM_SETRANGE, 0, MAKELPARAM(10000, 0));
	SendMessage(GetDlgItem(m_hWnd, IDC_TCOFFSETY), UDM_SETPOS, 0, MAKELPARAM((theApp.GetConfigI("UserHacks_TCOffset") >> 16) & 0xFFFF, 0));
```

On linux it doesn't do that so you end up not knowing what the hexadecimal value is so you don't know what to put there and you end up with a not properly working hack.

Example: TC offsets 350 X 350 Y => UserHacks_TCOffset=22937950

**Comment by turtleli** [comment]
IMO `UserHacks_TCOffset` should be split into something like `UserHacks_TCOffset_X` and `UserHacks_TCOffset_Y`. I don't understand why they're combined.

**Comment by willkuer** [comment]
Maybe the coder didn’t want to consider the usecase where only one of both is set in the ini. :)

They’re floats? It never came to me to set a floating point number. Is that supported via the gui?

**Comment by turtleli** [comment]
The GUI takes ints, but the value is converted to floats after loading.
```
	UserHacks_TCOffset       = theApp.GetConfigI("UserHacks_TCOffset");
	UserHacks_TCO_x          = (UserHacks_TCOffset & 0xFFFF) / -1000.0f;
	UserHacks_TCO_y          = ((UserHacks_TCOffset >> 16) & 0xFFFF) / -1000.0f;
```

**Comment by arcum42** [comment]
On the Linux side of the GUI, they way things were set up was like this.

Functions were written for each type of widget used. That function creates the widget, connects it to the same callback, and gives it the name the value has in the ini file. All the callback does is write to the ini file.

The trouble is that this means you no longer have a reference to any of the widgets after they are created, and all the ini file writing is being done immediately, rather than writing all of them at the end, so you'd be trying to write half of UserHacks_TCOffset without knowing what the other half is.

(Usually when I set up configuration dialogs, I set them up with an Ok and Cancel button, and write out all the values at the end when Ok is pressed...)

It's doable, I'm sure, but tricky enough that I started working on something else.

If you can separate the two values in the code and ini file, that would be a good way to go, as that would make the Linux Gui side of it rather easier to handle.
