### ISSUE TITLE
Dynasty warriors 4 XL, screen tearing issue

### ISSUE THREAD

**Issue by elksha** [PCSX2/pcsx2#2614]
***PCSX2 version:***
pcsx2 v1.5.0-dev-2569-g560966c53

***PCSX2 options:***
Setting as default, no speedhacks or hardware hacks

***Plugins used:***
Default plugins from 1.5.0-dev-2569
Gsdx : opengl(hardware), bilinear(ps2), 4x native internal resolution, mipmapping/crc automatic
          
***Description of the issue:***
https://puu.sh/sCV5z/acab065f03.jpg
(not my screenshot but the problem is exactly the same as mine)
there's a little tearing in the screen
I can get rid of it by making internal resolution to just native or changing renderer to software mode
but if i use hardware mode and multiplied internal resolution, the problem appears 

***PC specifications:***
CPU : i7 6700k @ 4.0ghz
GPU : GTX1070
RAM : 16gb

**Comment by RedPanda4552** [comment]
A more complete screenshot may help here, in case it is affecting a large region of the screen, and also for determining what part of the screen this is.

**Comment by elksha** [comment]
https://puu.sh/sCUnL/994855622a.jpg

there are 7 lines in the screen
and the screenshot above is the center part of the screen

**Comment by MrCK1** [comment]
That's a normal artifact of upscaling. You can try decreasing the resolution and/or adjusting texture filtering. Other then that, you'll just have to live with it.

**Comment by willkuer** [comment]
Align hack won‘t help?

**Comment by elksha** [comment]
yeap, most of hw hacks are not helping.
I found that adjusting tc offset helps, but It's not completely solving the problem
I think there is one pair of tc offset values that can solve this problem, but i don't know how to find it because there's so many pairs of values that I can put.

**Comment by willkuer** [comment]
One is for x and one is for y. You only have an issue in one dimension so keep the other fixed at zero (I guess you only need to touch x).

If I understood correctly tc offset is given as per one thousandth of a pixel. E.g. if you set 1000 something might shift by 1 pixel. Since this is a rounding issue you typically want to push the border a fraction of a pixel into the right direction. Hence 250, 500, 750 are reasonable values. Then you can also fine tune but I guess not more accurate than by a value of 50 or even 100 makes sense.

**Comment by elksha** [comment]
okay thanks! i will try that

**Comment by MrCK1** [comment]
Closing since it is a misalignment issue of upscaling due to the way the game is rendered.
