### ISSUE TITLE
Myst III issues

### ISSUE THREAD

**Issue by kenshen112** [PCSX2/pcsx2#2629]
All Versions of pcsx2 have shown this problem.

All options default though no options change or satiate this issue. 

![pcsx2_myst](https://user-images.githubusercontent.com/22896793/46649704-e2eef980-cb4e-11e8-81c6-3b261d55cf4f.png)
![new_game_screen](https://user-images.githubusercontent.com/22896793/46649713-e5e9ea00-cb4e-11e8-8997-3a3a3489b781.png)
![myst-ingame](https://user-images.githubusercontent.com/22896793/46649716-e7b3ad80-cb4e-11e8-91fb-0bedc98baad2.png)

This issue is reproduce able regardless of version or settings. Note that Play! nor DobieStation to a limited extend produce this issue or any signs of it. 

[Myst 3 Exile (USA) (2018-09-08 23-02-25).zip](https://github.com/PCSX2/pcsx2/files/2459046/Myst.3.Exile.USA.2018-09-08.23-02-25.zip) - A requested block dump of the issue

**Comment by ramapcsx2** [comment]
This problem is the DMA issue that we collectively called Voodoo ;p
One problem in PCSX2 is that the way the real console moves data around, which processors act on it (with the queues and all), is not emulated well.

To properly address these issues, half the emulator would have to be redesigned.
It would probably be too slow to play and may uncover more issues.

Because of that, I recommend not changing the code we have currently, unless there are actual bugs of course.
It may be a better move to apply some HLE here, and maybe patch the IPU library used by this game.

**Comment by kenshen112** [comment]
This still occurs on latest master

**Comment by refractionpcsx2** [comment]
This has been resolved on master with a patch, not sure it will ever get fixed properly, it's serious timing voodoo
