### ISSUE TITLE
GTA San Andreas Buggy Texture

### ISSUE THREAD

**Issue by Solniz** [PCSX2/pcsx2#2650]
***PCSX2 version:***
Build v1.5.0-dev-2633-ga8e8cb9b6

***PCSX2 options:***
OpenGL Software, AA1, 3 rendering threads and mipmapping.

***Note:*** 
Happens on any hardware or software setting I have.

***Description of the issue:***
Car dirt produces a pink, mirror like effect
![gt](https://user-images.githubusercontent.com/44263219/47153900-c41ffe00-d2d8-11e8-9c7f-95998957fb88.png)

***How to reproduce the issue:***
Simply grab a car (preferably a light colored car to be more noticable) and drive it around the countryside or the beach to accumulate a bit of dirt or mud.

***Last known version to work:***
None, I think.

***PC specifications:***
Intel i5-4570
8GB DDR3 RAM
Nvidia GTX 1060 6GB
Windows 10 Pro 64-bit

**Comment by Solniz** [comment]
> Try changing the clamping options and see if that changes anything or the manual gamefixes.

I messed around both options but nothing seemed to change at all.

**Comment by atomic83GitHub** [comment]
Is the game ok with Software mode?

**Comment by lightningterror** [comment]
> Is the game ok with Software mode?

> PCSX2 options:
> **OpenGL Software**, AA1, 3 rendering threads and mipmapping.

**Comment by atomic83GitHub** [comment]
Did you test every core Hacks? (The VU XGKICK hack mainly)?

**Comment by Solniz** [comment]
> Did you test every core Hacks? (The VU XGKICK hack mainly)?

I tested them out individually. None of them seemed to do anything. Though the "Preload TLB" hack crashes the emulator.

**Comment by MaxBowie** [comment]
I have to confirm the issue, unfortunately.
Tried with
pcsx2-v1.5.0-dev-2379-g290397d1a-windows-x86
pcsx2-v1.5.0-dev-2433-g46866268e-windows-x86
pcsx2-v1.5.0-dev-2601-g897b17d25-windows-x86
pcsx2-v1.5.0-dev-2638-gbb5d120a3-windows-x86
I spent a day trying every possible setting combination in the latest build. 
Manual hacks do nothing.
"Preload TLB" crashes the emu, but works after restart, but does nothing though.
The only thing that kinda changes is that the dirt is a blank purple texture if the Blending Unit Accuracy is set to HIGH and mirror like if set to FULL.
Thats all :(
On the forum someone called it "Path3 Masking bug" but I have no idea what it is.

**Comment by MaxBowie** [comment]
Well, looks like the only workaround so far is to replace the vehiclegrunge256 texture in vehicle.txd with transparent texture and rebuild the image. Cars will always be clean but at least that ugly pink mud wont be seen. Havent played enough to tell for sure if there are some bugs caused by this replacement.

**Comment by MrCK1** [comment]
@MaxBowie Try older versions of PCSX2 (1.4.0, 1.2.1, 0.9.8) and see if the issue still exists there.

**Comment by MaxBowie** [comment]
Tried stable 1.4.0, 1.2.1, 1.0.0, 0.9.8 - same pink mud with all renders in both HW and SW modes.

**Comment by orbea** [comment]
I can reproduce this too, it appears to be related to `Blending Unit Accuracy`.
![High](https://i.imgur.com/HdSWdVC.png)
GS dump - http://0x0.st/s07B.xz

With `Full` or `OpenGL (Software)` the colors change to more red and purple instead of pink and there are transparency issues with the vehicles.
![Full](https://i.imgur.com/vkxZaEN.png)
GS dump - http://0x0.st/s07M.xz

With `Ultra` and only with `OpenGL (Hardware)` the sky gains giant yellow squares...
![Ultra](https://i.imgur.com/k03RCla.png)
GS dump - http://0x0.st/s07u.xz

Additionally the `VU1` interpreter changes the depth of the grass, but that seems to be a different issue.

**Comment by MrCK1** [comment]
Did a dump of this and it appears to be a CLUT issue. Might be the same (or a manifestation) of those "purple games". If anybody understand's what's possibly happening, feel free to take a look :)

![_01062_f5005_itpx_03be0_c_32](https://user-images.githubusercontent.com/16314399/50463331-1d4f8200-0959-11e9-9615-991ab9a1e5c7.png)

[_01062_context.txt](https://github.com/PCSX2/pcsx2/files/2711287/_01062_context.txt)

**Comment by fcole90** [comment]
Same issue in 1.7.0-0(git) (from Ubuntu ppa for focal 20.04)

**Comment by iMineLink** [comment]
Is there a GS dump available of this issue? I want to inspect any missing CLUT invalidation after render to CLUT in SW mode.

**Comment by refractionpcsx2** [comment]
> Is there a GS dump available of this issue? I want to inspect any missing CLUT invalidation after render to CLUT in SW mode.

It's not that. the CLUT is just broken (I believe this game was broken by the mirroring code Sudonym did), Kojin already has my fixes for this game and some other CLUT fixes.

**Comment by refractionpcsx2** [comment]
The linked PR kind of solves it.

Does it stop it being pink/transparent? yes

However, the dirt doesn't seem to apply correctly and build up, in fact if you get a dirty can and drive around the country/beach, it cleans it, which is weird.  I've replicated this on Dobiestation too, so it's not just PCSX" or a bad fix, I think the fix for the pink textures is indeed accurate and there's something else going on.

But at least your cars won't be pink anymore :)

**Comment by Solniz** [comment]
Looking at it sideways, I saw the dirt build up and then suddenly (once it reaches max dirt) most of it disappears. It definitely doesn't happen on original hardware though so as you said, there is something else going on. I recall the texture for the car dirt having a transparent background so.. could it be possibly be an issue related to alpha transparency? Either way, thanks for getting rid of the obnoxious pink, it's already much better. :D

**Comment by refractionpcsx2** [comment]
yes, I think I know what's happening, this is again something which isn't documented.  The CLUT (The colour lookup table) is stored in a linear temporary buffer, not really proper RAM.  What I was initially doing was looping on that buffer to stop it reading invalid data if the CSA  (CLUT offset) was anything higher than 0, GTA SA uses 15 which is the last offset position, the problem being it's using an 8bit Index format so it can address up to 256 colours in the CLUT, each CLUT offset only has 16 colours.  So before I was looping on that buffer and it was actually cleaning off the dirt, I just changed it to clamp to the last CLUT offset if it runs out of CLUT and, well, this was the result


![image](https://user-images.githubusercontent.com/6278726/139940258-824a954e-3d73-4e4c-84f0-092be49fefcd.png)

**Comment by InsanityM** [comment]
Awesome work! now the game is fully playable.
