### ISSUE TITLE
PCsx2 issue with game Malice

### ISSUE THREAD

**Issue by IAlexPlay** [PCSX2/pcsx2#2658]
Hey, saw you doing interesting stuff with pcsx2 emulator, so i found problem in game called "Malice", that textures in second location are flashy, purple, and in next locations black, hope you can fix it, it's actually not that hard to get there (3mins after game starts). I have tried many ways to fix it, changing to SW helped but game was extremely laggy.

 My specs
Graphic C Geforce GTX 1060 6GB
Proccesor Intel i5 4460
And Ram 8GB, so i think it's pretty enought.

Thanks :*

**Comment by MrCK1** [comment]
Please format your issue accordingly and upload a GS Dump (Shift +F8) and pictures so we can see what's going on.

**Comment by IAlexPlay** [comment]
![image](https://user-images.githubusercontent.com/44381960/47322544-03e04000-d661-11e8-83cf-9f4874eec86b.png) First location (Seems like 2 layers of picture)
![image](https://user-images.githubusercontent.com/44381960/47322624-54579d80-d661-11e8-9f47-060e560ed530.png) 
![image](https://user-images.githubusercontent.com/44381960/47322687-941e8500-d661-11e8-9196-320c8cc6c64d.png) (3rd location is to much purple) 4th will be full black.
![image](https://user-images.githubusercontent.com/44381960/47322728-b9ab8e80-d661-11e8-80a1-01e2faa87ff6.png) (3rd location with SW mode, i got legit 4 fps, but the collors was as they needed to be and in 4th location aswell)

**Comment by IAlexPlay** [comment]
Didn't change anything

**Comment by IAlexPlay** [comment]
Can you please test this game your own, because i saw several same reports without any resolves. :*

**Comment by atomic83GitHub** [comment]
Ok, so let's try various options. First make shure your hardware render is set to OpenGL, secondary put the Half pixel offset value to special-texture. This should fix the sever ghosting issue, also can you enable the preload frame data hack along with GS memory wrapping?
Don't hesite to post your results here.

**Comment by Krusher97** [comment]
This is one of those games that has less glitches in HW renderer than the software one. In SW mode the bloom effect is so misaligned that it might as well be completely missing and the objective menu is a completely black background instead of a blurry transparent one. Another weird thing that happens in SW mode is that the framerate shoots up to 7 times when looking at objects from certain angles or when certain objects are not in the screen. 
The ghosting issues only appear when the resolution is set above Native. Setting Half Pixel Offset to Normal completely fixes it from what I can see.
![pcsx2_2018-10-25_22-17-42](https://user-images.githubusercontent.com/25664221/47517364-9a04a800-d8a5-11e8-92da-2f98b8c68284.png)
![pcsx2_2018-10-25_22-17-48](https://user-images.githubusercontent.com/25664221/47517374-9d982f00-d8a5-11e8-96f0-6f5e1c5e757e.png)
![pcsx2_2018-10-25_22-19-25](https://user-images.githubusercontent.com/25664221/47517377-9ffa8900-d8a5-11e8-950d-0013ac1cc183.png)
![pcsx2_2018-10-25_22-19-32](https://user-images.githubusercontent.com/25664221/47517380-a1c44c80-d8a5-11e8-8fa1-9d6b30b0fa65.png)

**Comment by atomic83GitHub** [comment]
This game should be listed in the software render meta.

**Comment by MrCK1** [comment]
So Half-Pixel offset fixes the ghosting? Can this be closed then?

**Comment by lightningterror** [comment]
> The ghosting issues only appear when the resolution is set above Native. Setting Half Pixel Offset to Normal completely fixes it from what I can see.

Closing then.
