### ISSUE TITLE
TextureCache: DBZ BT3 regression when Allow 8-bit Textures is enabled

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#2706]
@AlessandroVetere looks like the Palette management rework https://github.com/PCSX2/pcsx2/pull/2344
caused a regression in DBZBT3, perhaps other games are affected as well.

In this example character faces appear as blocks when Allow 8-bit Textures is enabled. Note there are other graphical issues as well. I don't know if other games are affected but it's quite possible.

Image:
![gsdx_20181123003210](https://user-images.githubusercontent.com/18107717/48924431-6888f780-eeb8-11e8-8745-2f125b1f6841.png)

GS Dump:
[DBZ BT3 - TC 8-bit.gs.zip](https://github.com/PCSX2/pcsx2/files/2609410/DBZ.BT3.-.TC.8-bit.gs.zip)

Last working build:
v1.5.0-dev-2653-g77a924ee7

Regression build:
v1.5.0-dev-2654-g9fa1b290b

**Comment by lightningterror** [comment]
I compiled the first commit only https://github.com/PCSX2/pcsx2/pull/2344/commits/44726afb780f06d3356c2b3f625bdc67f0d28b2f and that too has the regression. That should narrow things down.

**Comment by AlessandroVetere** [comment]
I have so the game so I can debug the issue.
Fortunately, the entry points in the existing code of the PR are very few, so in the worst case reverting the code would not be a huge work; but I think this can be solved.
My fear is that moving these lines:

https://github.com/PCSX2/pcsx2/commit/44726afb780f06d3356c2b3f625bdc67f0d28b2f#diff-7436adf7406199c56fd673a16e6086b2L1460-L1464

Did change the 8-bit texture enabled behaviour, as now the first clut lookup is done at:

https://github.com/PCSX2/pcsx2/commit/44726afb780f06d3356c2b3f625bdc67f0d28b2f#diff-7436adf7406199c56fd673a16e6086b2R391-R392

So if in between the first creation of the Source and the first Lookup the CLUT changes, now we pick the latter CLUT values instead of the former.
In small words, the `m_initpalette` mechanism has been dropped, and maybe needs to return.
If this is the case, I can design a solution.

Could you confirm that with 8-bit texture DISABLED, the game doesn't have regressions? In this case the codepath has remained the same, given that the PaletteMap works.

**Comment by lightningterror** [comment]
Yea having the option disabled doesn't have the regression.

**Comment by AlessandroVetere** [comment]
Ok that's good to hear. I'll re-establish the copy of the CLUT before the end of `Source` creation in the 8-bit texture enabled case so the codepaths should just match. Sorry for that!

**Comment by AlessandroVetere** [comment]
Seems like anticipating CLUT write to palette did not fix the problem.
I may have found the cause of the bug, and it is unexpected `GSVector4i::compare64` behavior, as can be seen in the screenshot below:

![image](https://user-images.githubusercontent.com/15114320/48980504-436bd300-f0ca-11e8-8575-a1a2e99dee4c.png)

A naive for loop for comparing clut content between different PaletteKey, which as implemented FIXES this issue, behaves differently from the `GSVector4i::compare64` function. In the specific bug case, the vectorized function return true, so equal clut content, whereas the for loop does not.
By printing the clut content:

https://pastebin.com/S7HMC8Lz

See from line 994, you can see that "clut" is different from "src old clut", but `compare64` returns true, causing a false map hit ("src new clut" is the clut copy after the fix, which coincides with "clut").
