### ISSUE TITLE
align sprite hack...

### ISSUE THREAD

**Issue by mondaychicken** [PCSX2/pcsx2#2739]
Align sprite hack is option for fixing vertical line in namco games.

But this hack is utilized properly, when it is set only internal resolution upscaling (native x number type).

This hack does not perform for custom resolution.

Is it impossible implementing align sprite hack on custom resolution ?

Though custom res has a lot problems, it must be big advantage to pcsx2.

When it is set appropriate values, it can kill a variety of  aliasing.

Then the resolution quality is better than internal res (native x number) setting.

**Comment by lightningterror** [comment]
Actually it's the other way around. Custom resolution quality is much worse because it does improper scaling, and we always recommend using native upscaling instead of custom because of the various issues it causes. There are also many features that won't work properly on custom resolution as well.

It will be better to expand native upscale to support decimal values. Then we can just purge custom resolution altogether.
