### ISSUE TITLE
Create POT file to influence translator/Ttanslations.

### ISSUE THREAD

**Issue by knight-ryu12** [PCSX2/pcsx2#2886]
- POT files are, referring and containing to all translatable string.
but there's no POT files to begin/update translate to
which, should be available since there is many translatable strings.
maybe xgettext (or equivalent) can generate one.

- Issue #2882
With only one percentage sign in the c-format string, Gettext will treat "% c" as a placeholder, which is not the case of these strings.

**Comment by pgert** [comment]
Your english is so bad it's almost amusing.
Is this what you are trying to say?

POT files refers to all translatable strings,
 but there isn't any POT-files to begin/update a translation with,
 which should be available since there are many translatable strings.
maybe xgettext (or equivalent) can generate them.

If so then consider that to encourage contributions,
 the entire GitHub-repository could be included in the build,
 which (of course) would be Overkill.

**Comment by tadanokojin** [comment]
> Your english is so bad it's almost amusing.

You could have left this out and just asked for clarity.

**Comment by knight-ryu12** [comment]
look
