### ISSUE TITLE
[Regression] Final Fantasy X Bad Screen Overlay

### ISSUE THREAD

**Issue by Mensa41** [PCSX2/pcsx2#2890]
***PCSX2 version:***
v1.5. dev 3007

- **Notes**:
  Bad Screen Overlay in some areas in both ogl and dx11. 
This issue doesn't happen in software mode

![gsdx_20190316031653](https://user-images.githubusercontent.com/48634435/54482715-e4c89180-483f-11e9-88a4-2df38d158c15.png)

![gsdx_20190316032342](https://user-images.githubusercontent.com/48634435/54482718-f6aa3480-483f-11e9-92c5-03352d0f3f63.png)

***PCSX2 options:***
Default Settings, no widescreen or cheats enabled

***Last known version to work:***
1.5 Dev 2656

**Comment by lightningterror** [comment]
Can you upload a gsdump of the issue ?

**Comment by Mensa41** [comment]
[gsdx_20190317013415.gs.zip](https://github.com/PCSX2/pcsx2/files/2974674/gsdx_20190317013415.gs.zip)

This issue seems to happen when underwater

**Comment by lightningterror** [comment]
Is this what you're referring to ?

1.5 hw
![hw](https://user-images.githubusercontent.com/18107717/54484897-7b607700-486f-11e9-9788-92f2829a1887.png)

1.4 hw
![hw 1 4](https://user-images.githubusercontent.com/18107717/54484901-84514880-486f-11e9-9861-c839977baaaf.png)

**Comment by Mensa41** [comment]
yeah, is it fixed ?

**Comment by lightningterror** [comment]
If you look closely it is also an issue on 1.4 just maybe less, could be coordinates issue ?

**Comment by lightningterror** [comment]
Closing in favor of #2961

**Comment by NTZ1989** [comment]
@MrCK1 no, I tried to disable every filter, this issue isn't related to something graphical otherwise disable everything would prevent it to happen, the user Mensa41 at the thread #2890 said something that I found interesting:

"Bad Screen Overlay in some areas in both Ogl and Dx11.
This issue doesn't happen in **software mode**
PCSX2 options:
Default Settings, no widescreen or cheats enabled."

He also reported the last version that worked fine to him was 1.5 Dev 2656, while for raymonders only from 1.5 Dev 2965 below and to me, the last version working fine on FF was 1.5 Dev 2970. So we can assume that not all emulators versions render the cutscenes in the game properly to all users. This is just an assumption...
