### ISSUE TITLE
GSdx: reduce HW texture cache overhead when creating a source from a target

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#2894]
When the texture cache hit an older target/depth, it will create a new input source
```GSTextureCache::Source* GSTextureCache::CreateSource```

In most case, it will either copy/rescale/convert the old target. However in most case it is either slow/reduce quality/useless.

Here the code that we want to avoid
```
		if ((sRect == dRect).alltrue() && is_copy)
		{
			if (half_right) {
				// You typically hit this code in snow engine game. Dstsize is the size of of Dx/GL RT
				// which is arbitrary set to 1280 (biggest RT used by GS). h/w are based on the input texture
				// so the only reliable way to find the real size of the target is to use the TBW value.
				float real_width = dst->m_TEX0.TBW * 64u * dst->m_texture->GetScale().x;
				m_renderer->m_dev->CopyRect(sTex, dTex, GSVector4i((int)(real_width/2.0f), 0, (int)real_width, h));
			} else {
				m_renderer->m_dev->CopyRect(sTex, dTex, GSVector4i(0, 0, sRect.z, sRect.w)); // <= likely wrong dstsize.x could be bigger than w
			}
		}
		else
		{
			// Different size or not the same format
			sRect.z /= sTex->GetWidth();
			sRect.w /= sTex->GetHeight();

			if (half_right) {
				sRect.x = sRect.z/2.0f;
			}

			m_renderer->m_dev->StretchRect(sTex, sRect, dTex, dRect, shader, linear);
		}
```

The idea is to defer this code later in the renderer in order to make better choice. Note StretchRect can't be called after `BeginScene`

Case1: current texture and framebuffer overlap. Because of the overlapping, the source will be deleted at the end of the draw...
* OpenGL can sample directly from frame buffer. So copy/rescaling is useless, but it would be slow if there are too many primitives (see Dx below for an extra optimization)
* DirectX can't sample the frame buffer. However we could limit the copy based on the draw call value. Note: it could help OpenGL too if there is too many primitives. For example, on Jak or Star Ocean, the copy will be limited to the shadow area rather than the full framebuffer. 

Case2: current texture and framebuffer don't overlap. Therefore it is possible to bind both during rendering. However remain conversion/scaling issue.
* If conversion is needed -> no choice it must be done
* If scaling is needed -> it can potentially be done on the coordinate level. It might depends on current clamping mode.
  * UV coordinate (aka absolute coordinate) is easy. Coordinate aren't normalized, so we just need to normalize them on the real frame buffer size. Something like that `U * scaling_factor / old_target.size`
  * ST coordinate are normalized on the GS size. So it must be unormalized first. I think it can be done with something like that `S * GS.size * scaling_factor / old_target.size`. Note most game uses UV.

**Comment by iMineLink** [comment]
I know that #5387 was a step towards direct framebuffer binding avoiding the copy into the intermediate texture. Probably @tellowkrinkle has a better overall picture here.

This is still a nice improvement to be implemented.

**Comment by stenzek** [comment]
Sampling arbitrary locations in the framebuffer isn't really doable on anything other than GL, because in Vulkan, you can only load the same texel you're drawing to from a subpass. And the full texture barriers tend to be.. nasty for the GPU, as one would expect. I've extended the fb-is-tex case a bit further on one of my branches (mainly for texture shuffles), will PR that at some point.

As for copy elision, I did do a proof-of-concept where instead of copying sources, it just sampled directly from the target. Worked wonders for Jak3, which creates mip chains in realtime. The only tricky part is scaling the coordinates correctly, handling repeating/minmax, and making sure you don't sample outside of the rectangle which the texture would be sources from (bilinear makes that fun). But definitely a worthwhile optimization, particularly at high resolutions.

**Comment by tellowkrinkle** [comment]
That is something I'd like to do eventually

**Comment by stenzek** [comment]
This was done with my TC refactors a couple months back.
