### ISSUE TITLE
Dirge Of Cerberus : FF7 (SLUS 21419) materia glow effect 

### ISSUE THREAD

**Issue by lordmedo** [PCSX2/pcsx2#2962]
***PCSX2 version:***
v1.5.0-dev-3126-g2941fd9b8

***PCSX2 options:***
all default, tested on dx11 hw and opengl hw, native resoluton, gpu hacks don't seem to affect it. 

***Description of the issue:***
In chapter 5, in the event cutscene called "The chronicles of Yore", Vincent is holding materia whose shining effect is rendered as black. 
Dx11 HW:
![gsdx_20190513232614](https://user-images.githubusercontent.com/13256611/57868228-dd534380-7802-11e9-91a3-c3f94ce45f3b.jpg)

Software mode renders it correctly:
![gsdx_20190513232615](https://user-images.githubusercontent.com/13256611/57868259-ee9c5000-7802-11e9-9aa2-690effcd16f3.jpg)

***How to reproduce the issue:***
event is playable directly via special features menu
memory card: [dirge ff7.zip](https://github.com/PCSX2/pcsx2/files/3187860/dirge.ff7.zip)
GS dump: [gsdump ff7 doc black.zip](https://github.com/PCSX2/pcsx2/files/3187949/gsdump.ff7.doc.black.zip)

***PC specifications:***
w10x64/i7 3770k/950gtx

**Comment by lightningterror** [comment]
Feels like a TC issue with a miss, so far I reached draw 91 from the provided dump with bad alpha, needs to be further debugged.

**Comment by tadanokojin** [comment]
First obvious issue is a clear here

Pattern:
- double half clear buffer 0x1c00 with buffer width of 4
- reuse 0x1c00 with a buffer width of 8

It causes an issue in the cache where only the left side of the buffer is cleared.
![_00003_f5000_rt1_01c00_C_32](https://user-images.githubusercontent.com/26046960/85950657-175ea680-b92c-11ea-898b-b2b7b3332fe6.png)


Not positive this is the exact issue but it is an issue. Honestly I'm surprised the game doesn't have more issues.
It's possible there is a later clear since a temp buffer is used, but I gave up searching for now.

I'll investigate more later.

**Comment by Mrlinkwii** [comment]
can this be check on lastest nightly ?

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/ece7fcdc-88e0-42cb-9f47-ad0358da2177)
seems fixed as of v1.7.4490
