### ISSUE TITLE
Fedora package

### ISSUE THREAD

**Issue by Jan200101** [PCSX2/pcsx2#3021]
The Fedora package provided by rpmfusion is considered obsolete now and installs nothing, sometimes even causing conflicts

I suggest it should be removed from the [wiki](https://github.com/PCSX2/pcsx2/wiki/Installing-on-Linux#fedora)

**Comment by mirh** [comment]
It was killed because it didn't build anymore [AFAIU](https://pkgs.rpmfusion.org/cgit/nonfree/pcsx2.git/commit/?id=7b7036fe5efc926fe6b0ae0ed9348ab3cadf4d06) (even though that may be fixed again [soon](https://bugzilla.rpmfusion.org/show_bug.cgi?id=5070))
Regardless, 1.4 really shouldn't be recommend at all. 

But what to suggest between [snap](https://copr.fedorainfracloud.org/coprs/victoroliveira/pcsx2-git/), [flatpack](https://flathub.org/apps/details/net.pcsx2.PCSX2) and [copr](https://copr.fedorainfracloud.org/coprs/victoroliveira/pcsx2-git/)?

**Comment by Jan200101** [comment]
I'd say a copr would be best for Fedora users

**Comment by mirh** [comment]
*Be the change*, I guess? Nobody in the team uses fedora afaik.

**Comment by kenshen112** [comment]
I'm already working on it

**Comment by Jan200101** [comment]
I've looked into the [pcsx2-git](https://copr.fedorainfracloud.org/coprs/victoroliveira/pcsx2-git/) mentioned before and that seems to be the best PCSX2 copr out there and should definetly replace rpmfusion in the Wiki

**Comment by turtleli** [comment]
I'll close this as it appears rpmfusion have updated the PCSX2 package.

As for what package should be on the wiki - anyone can edit the wiki. Feel free to improve it.
