### ISSUE TITLE
Scarface memory leak (MicroVU1: Program cache limit reached)

### ISSUE THREAD

**Issue by Donovan24** [PCSX2/pcsx2#314]
I've noticed while playing the game it gets progressively slower and it reaches a point where it freezes for a few seconds and then it's faster again and it repeats this every time. While playing the ram usage slowly rises from just over 2gig (+- idle for my computer) all the way to about +-4.6gig usage and then the emulog says something about "Program Cache Limit reached" right after that the ram usage again rises again until it repeats itself.

And pretty often the game just randomly crashes.

You can check these two threads if you need anymore info on the specific problem.

http://forums.pcsx2.net/Thread-Need-help...o-problems

http://forums.pcsx2.net/Thread-Calling-a...t-Scarface

Please tell me if there's any additional information you need.

I will be so happy if you can look into this.

Thanks in advance

Just to add. After the message "MicroVU1: Program cache limit reached" the game freezes a bit and while frozen the ram usage lowers quickly down to idle again. Every time the ram usage lowers the game speeds up again. Until the whole process repeats itself.

**Comment by Donovan24** [comment]
Still not fixed... Sucks.. Im willing to donate if this gets fixed.

**Comment by refractionpcsx2** [comment]
This one is a really hard one to fix, the game constantly updates one value in the VU program causing the program to be recompiled, beyond checking the program as it's uploaded (which is gonna be really slow) it's going to be difficult to fix properly beyond the hack in the microvu thread on the forum.

we might be able to hack fix it, but i don't think it's going to be a change easy to implement otherwise.

**Comment by refractionpcsx2** [comment]
Hack fix was implemented a couple of weeks ago, forgot to reference/close this

Commit: 22de86558225e029f2edefdce92612200e4e5901
