### ISSUE TITLE
[Feature Request] [Buildbot] Could you add to buildbot a link that always points to the latest release?

### ISSUE THREAD

**Issue by fabiorzfreitas** [PCSX2/pcsx2#3179]
In the near future, I'd like to maintain a PCSX2-nightlies Chocolatey* package. Currently, there's only a [package](https://chocolatey.org/packages/pcsx2) for the stable 1.4.0.

I still haven't studied as deep as I want to all of the tools available for package maintainers, but it would certainly make things a lot easier if the package could point to a fixed destination on buildbot redirecting to whatever the latest build is instead of using some fancy regex to guess the actual link by comparing wihh github's commits info.

Thanks

<details><summary>*About Chocolatey:</summary>
<p>
From PCWorld.com: "Chocolatey is a command line application installer for Windows based on a developer-centric package manager called NuGet. Unlike manual installations, Chocolatey adds, updates, and uninstalls programs in the background requiring very little user interaction.

Chocolatey has its own package feed that is created and maintained by the project’s community members.

Behind the scenes, most Chocolatey packages simply download a program’s official executable and install it without any further interaction from the user".
</p>
</details>

**Comment by MrCK1** [comment]
We don't maintain the existing Chocolatey package (looks to be added by a random user) or the buildbot. However, there is an auto updater in the works that will scrape from Orphis' site if that is of interest for you.

https://github.com/PCSX2/pcsx2/pull/3121

**Comment by fabiorfreitas** [comment]
Ah, yes, most Chocolatey packages are maintained by random users (like me), but they're always sourced in the original and have hash file checkings :)

Anyway, this is really cool, I'm sure it will come in hand! It also ocurred to me: is the building process something that one can be done on my side? Are there instructions anywhere? If so, it would be better to use Github's server instead of Orphis'!

**Comment by tadanokojin** [comment]
Donno about chocolatey but you might be able to automate something based on appveyor (ie if branch is master get the artifact). You could also pull the latest git and build it yourself (you need visual studio's compiler). You can check out appveyor.yml for more info.

**Comment by yiays** [comment]
Once the auto-updater is complete, you could release just the auto-updater as a pcsx2 package, and it could install and maintain pcsx2 from there. Either that, or you'd probably want to use whatever API the auto-updater ends up using to release builds for chocolatey and remove the auto-updater from the zip.

**Comment by yiays** [comment]
Regarding the concept of a chocolatey package, there's now a far better source for nightly builds, [GitHub Actions](https://github.com/PCSX2/pcsx2/actions/workflows/windows-workflow.yml) though I'm not sure if there's a way to directly download the latest build, every commit is built and is [accessible via the GitHub API](https://docs.github.com/en/rest/reference/actions#list-artifacts-for-a-repository). The only catch is that the API caller must be logged in in order to download artifacts - as to why this isn't very helpful for a client-side auto-updater.
