### ISSUE TITLE
A debugger 'Call Cursor' option added to right click menu in debugger

### ISSUE THREAD

**Issue by tilkinsc** [PCSX2/pcsx2#3197]
I want to get into the source myself and add such a feature.

This is what it would do essentially (pseudo-code)
```Asm
# push current state
push $1
push $2
...
push $31

# execute parameter-less void function
jal cursor_highlight

pop $31
pop $30
pop $29
...
```

Which seems like a simple task to do. I would just like some source links to know where existing code resides for the right click menu functionality, etc.

I will be doing this on a windows box.

**Comment by tilkinsc** [comment]
https://github.com/PCSX2/pcsx2/tree/master/pcsx2/gui/Debugger The debugger is located here.

Any additional info on executing an opcode during break would be appreciated.

**Comment by F0bes** [comment]
### This wont be possible to implement. If you want a long explanation why, read below.

We don't know the calling convention of what is running. There was an ABI break between the SCE and homebrew toolchains.

Because of this, we don't know what arguments need to be pushed to the registers or the stack.
If we do need to pass by the stack, we need to insert some sort of prologue and epilogue, we can't just move $sp.
If we do need to pass by registers, we can't just clobber registers either, we need to handle this in our prologue and epilogue.

So now we would need to have some sort of compiler that supports multiple ABIs. We would require the user to input a function signature. Then we would generate a prologue that saves _all_ registers, sets the correct parameters and calls the function. Then at the end of that function an epilogue is called to restore everything.

Now it gets even worse. What if an interrupt happens in / during this called function? What if the function messes with something like the [DMAC](https://fobes.dev/ee/2024/02/02/ps2-dmac-basics.html), or COP0 registers, what if the game has tight timing between itself and VU1? You're going to return back to the normal programs flow and probably cause havoc.
