### ISSUE TITLE
increase onepad plugin gamepad number

### ISSUE THREAD

**Issue by adit787** [PCSX2/pcsx2#3233]
since many game support more than 2 player please change the default gamepad number to 4 or 8
i have tried to compile onepad with 8 pad but pcsx from ppa wont recognize the plugin, maybe because iam using ubuntu 64bit to compile

**Comment by ordovice** [comment]
Would like to add a +1 to this to support the equivalent of multitap functionality.

**Comment by arcum42** [comment]
If it gives some perspective on why this hasn't been done, I'm the most likely one to make changes beyond updating the gamepad database to onepad, and I've never used multitap. All the ps2 games I play, I've basically played solo, so I'm not familiar with it from a user *or* developer standpoint.

Beyond that, I was just looking through what games support multitap. Only thing I see I have on the list at the moment is Ape Escape: Pumped and Primed, and I didn't even realize that used multitap until now. I'm pretty sure I fished it out of a bargain bin because I remembered there being some issue it was a test case for... (Something with VIF?)

All in all, I highly encourage other people to hack multitap support into onepad and submit a PR.

**Comment by ordovice** [comment]
List of Multitap games: 
https://en.wikipedia.org/wiki/PlayStation_Multitap

FYI: Lilypad has it, so might be worth looking in that code base.  @arcum42 Appreciate all you do for the community.  Sadly I'm not much of a coder in that regards so I wouldn't even know where to begin.

**Comment by KrossX** [comment]
If I remember correctly, the API makes it quite simple. `PADqueryMtap` to see if there's a mtap device in that port, then `PADsetSlot` to set which pad to poll next.

**Comment by refractionpcsx2** [comment]
Qt now contains multitap (which uses OnePad), so marking this as fixed.
