### ISSUE TITLE
Shadow Tower Abyss - Flickering and dark picture

### ISSUE THREAD

**Issue by Krusher97** [PCSX2/pcsx2#3281]
When Blending is enabled(set to anything above None) the game flickers constantly in the HW renderer. 
Video HW: https://gfycat.com/dangerousbelatedfiddlercrab
Video SW: https://gfycat.com/welltodoinsistenthoopoe

There are also really extreme differences in lighting between the two 
HW : 
![gsdx_20200309214813](https://user-images.githubusercontent.com/25664221/76235614-58359100-6251-11ea-84d5-0819db9a3187.png)
SW : 
![gsdx_20200309214816](https://user-images.githubusercontent.com/25664221/76235623-5c61ae80-6251-11ea-9757-9b8624ea5e90.png)

gsdump of screenshot : 
[gsdx_20200309220352.gs.zip](https://github.com/PCSX2/pcsx2/files/4307824/gsdx_20200309220352.gs.zip)

**Comment by lightningterror** [comment]
Disabling Depth gets around the dark picture, shadows are still an issue on hw renderer tho.

**Comment by Mrlinkwii** [comment]
still an  issue as of 1.7.4854

![image](https://github.com/PCSX2/pcsx2/assets/17685135/031fd857-7f66-44d2-bd11-45e453bf6def)

**Comment by dante3732** [comment]
Yep, still not fixed.

**Comment by refractionpcsx2** [comment]
Okay I did some investigation in to this and the problem is this.

The game sets the Z buffer value to a solid number/colour of 29696, in RGB this translates to 0, 116, 0. It does this with the Z set to C16S, but I *think* this should only affect the swizzle, not the value which should be written as-is (we need to hardware test this).
The problem then is the hardware renderer reads this from the depth to a render target (colour) and so it converts it from Z16 to C16, which truncates the colours, so this flat colour now becomes 0, 112, 0 (or 28672)

The target is then reused again as a depth texture to stencil out the shadows, and it tests drawing the black shadows to a completely white render target checking for when the the Z of the draw (which is all 29696) is higher than the current Z buffer (which is now max of 28672 because of the truncation), so every pixel passes, making the entire render target black.

After some messing this gets blended back in with the frame, making the entire screen a shadow instead of just the shaded bits.

**Comment by refractionpcsx2** [comment]
So it turned out to be data loss during shader conversion.

if somebody gets a chance, if they could quickly test #10053 with the actual game (not the GS dump, I've done that, it's fine), that'd be awesome.

**Comment by refractionpcsx2** [comment]
This has been tested, thanks.

**Comment by dante3732** [comment]
It different issue?
https://drive.google.com/file/d/1n-stIH-NgFGCwP92kQD0JI0Oghyxqxna/view?usp=sharing

**Comment by Mrlinkwii** [comment]
@dante3732 that looks like  z-fighting in HW mode
