### ISSUE TITLE
Metal Gear Solid 2: Sons of Liberty cutscenes glitch in HW mode [SLUS-20144]

### ISSUE THREAD

**Issue by levonnn** [PCSX2/pcsx2#3285]
**pcsx2-v1.5.0-dev-3391-gbf9519433-7012-vs2019-Win32**

**PCSX2 options:**
Native resolution. Any settings. OpenGL HW.

**The problem:**
Vertical block appears on the left of the screen during cutscenes in HW mode. SW mode doesn't have it.

**Screens:**
![](https://i.imgur.com/sPRVmyw.png)
![](https://i.imgur.com/O5AAL9Y.png)
![](https://i.imgur.com/BvILqEd.png)

**gsdx snap:**
[Metal Gear Solid 2 Sons of Liberty cutscenes glitch in HW mode [SLUS-20144].zip](https://github.com/PCSX2/pcsx2/files/8564770/Metal.Gear.Solid.2.Sons.of.Liberty.cutscenes.glitch.in.HW.mode.SLUS-20144.zip)

**How to replicate the problem:**
Start game, watch intro cutscene on the bridge. But it's present in many cutscenes throught the game.

**PC specifications:**
i7 2700, GTX 760, Windows 7 64 Bit

**Comment by Mrlinkwii** [comment]
is this still an issue on latest 1.7? :slightly_smiling_face:

**Comment by levonnn** [comment]
Yes. Proof: https://www.youtube.com/watch?v=JKV8FpqX71E

**Comment by RIKLAVIEGASINTRODUCTION** [comment]
Saw that this was marked as "fixed" on the PCSX2 wiki. 
https://wiki.pcsx2.net/Metal_Gear_Solid_2:_Sons_of_Liberty
>Description: Some cutscenes are rendered at 10fps with motion blur to give a dramatic slow-motion effect but the effect is only shown on a small portion at the left side of the screen.
>Workaround: Fixed in PCSX2 dev build 1.7.2234. For older builds use Software mode.

Could anyone confirm?

**Comment by coornio** [comment]
I am skeptical of whether that issue entry on the wiki refers to the issue described here. The one on the wiki talks of a blur effect for cutscenes that's only present on the left side, whereas this issue here is an upscaling artifact. Here's a multi-frame dump showing the effect in all its glory:

https://www.mediafire.com/file/5jim73qmzy4jga2/gs_20220511130904_Metal_Gear_Solid_2_-_Sons_of_Liberty__NTSC-U__SLUS-20144.7z/file

![gs_20220511131737](https://user-images.githubusercontent.com/11655762/167827455-4a11621b-8c1f-4471-a15f-afb3f7a2f12a.png)

I should note that this upscaling artifact cannot be fixed by any hacks I've tried. That said, it only occurs in certain engine-rendered cutscenes where certain light effects happen and is not omnipresent -- meaning you'll only catch it for a few frames and then it's all normal again. Hardly intrusive if I do say so.

**Comment by RaduNastase** [comment]
This glitch happends when a certain cutscene (usually a 3 - 5 seconds segment) has an intentional (very) low framerate, for dramatic effect.
On ps2 , these moments are also usually very heavy on the blur and trails effects.

Their are generally not easy to spot in emulation (which is a good thing), but they're there.

**Comment by RaduNastase** [comment]
An easy fix for this issue is as follows:

While using the widescreen patch, the glitch now affects the far left side. Now just crop the left (and right) parts of the screen to ~ the normal 4/3 aspect, and the gitch will be outside the vsible area now.

**Comment by Mrlinkwii** [comment]
@RaduNastase  thats not a fix.....

**Comment by Oymat** [comment]
update: it has gotten much better, but it's still there 

![image](https://user-images.githubusercontent.com/122278577/213743436-8f292412-960a-4c9b-bba1-86e1898badfb.png)

**Comment by RIKLAVIEGASINTRODUCTION** [comment]
The broken effect now appears in a different spot as of latest dev:
![Metal Gear Solid 2 - Sons of Liberty_SLUS-20144_20230225183215](https://user-images.githubusercontent.com/92535412/221368476-daa921e7-fff3-46ac-9bf0-27bfffa1a86a.png)
![Metal Gear Solid 2 - Sons of Liberty_SLUS-20144_20230225182845](https://user-images.githubusercontent.com/92535412/221368338-fa364e56-a999-4668-a33c-122d523f8a06.png)
Rather than the left side like in the original issue report it's now the top left side

**Comment by Toastarrr** [comment]
This is definitely related to the slow motion effect being broken.
![Metal Gear Solid 2 - Sons of Liberty_SLUS-20144_20230306012748](https://user-images.githubusercontent.com/68636505/223035870-81f3d810-1cf2-46b3-9f39-5c6d1b89ddc0.png)
![Metal Gear Solid 2 - Sons of Liberty_SLUS-20144_20230306013133](https://user-images.githubusercontent.com/68636505/223035880-b9771393-90dd-4aa1-883a-db4da34530e9.png)

**Comment by refractionpcsx2** [comment]
#8289 seems to further change this by making it half the screen instead of just a chunk in the corner, I kinda suspect some sort of shuffle shinanigans.
