### ISSUE TITLE
Official PCSX2 PPA release file

### ISSUE THREAD

**Issue by Arawn-Davies** [PCSX2/pcsx2#3319]
***PCSX2 version:***
Linux 1.4.0-11 

Is the Ubuntu PPA repository going to be updated to work with Eoan Ermine? 20.04 is going to be released really soon, but I'll give building the repo a go, but having a deb to install via command line would be handy :)

**Comment by RedDevilus** [comment]
Well the PPA will work with anything that can use apt. Since Ubuntu/Debian uses that it should normally work fine. Below are the instructions for the dev builds/ dailies. I see that you use the old 1.4 which is outdated by this point and its better to use 1.5 for now.

![image](https://user-images.githubusercontent.com/24227051/79639441-2686e280-818c-11ea-9614-cd38bf5abfa4.png)

**Comment by RedPanda4552** [comment]
The maintainer of the PPAs has been busy with a number of things and has not been able to work on this. The PPA can be updated but until we sort out who will do this and when, the next best thing you can do is compile from source.

**Comment by helkaluin** [comment]
@RedPanda4552 I've finally got around to fixing the daily PPA. Focal is done and others are being built. Could you try and see if the builds work? (Currently it's enabled for Focal, Groovy, Hirsute, and Impish.)

**Comment by lightningterror** [comment]
Closing as we currently provide appimages on the new dev/nightly website.
