### ISSUE TITLE
Using Boot ISO (fast) emulator sets language to English for every SLES Multi5 games

### ISSUE THREAD

**Issue by BroKill** [PCSX2/pcsx2#3387]
***PCSX2 version:***
1.6 & 1.7 dev

***PCSX2 options:***
Any

***Plugins used:***
Default

***Description of the issue:***
As the title says PCSX2 does that.
I mean, here in Europe there are many Multi5 games that give you no in game option for changhing the language, they use the PS2 system language set in the console option.
Since I noticed PCSX2 doesn't use the system language I set in the consoles option I need to use Boot ISO (full) to make the emulator recognizes language I choose in the PS2 Configuration. 
But the emulator saves PS2 Configuration in memory card so is this  a bug?
It seems it doesn't use PS2 Configuration saved in memory card when using Boot ISO (fast).

***How to reproduce the issue:***
Europe BIOS, set language configuration in console option to Es, Fr, De, It ( not En english ) and SLES Multi5 games like Time Crisis II & 3 and Boot ISO (fast).

***Last known version to work:***
Dunno, never noticed.

***PC specifications:***
i7 4790k, GTX 770 2Gb, 16 Gb  DDR3, Windows 10 1909.

**Comment by vsub** [comment]
That's expected
Unless the game go through the bios(Full Boot...loading the settings),the game will start in the default language set in the game
Some game even start in Japanese unless you use Full Boot

**Comment by RedPanda4552** [comment]
Full boot launches the PS2 BIOS which is what reads the system configuration for language information and passes this to multi-language games. Using Fast boot does not launch the PS2 BIOS but immediately executes the game, ignoring any parameters the BIOS may pass to it. As such, games which need a language to be specified will pick one on their own with no way to change it. This is expected behavior and not a bug or issue with memory card reading.
