### ISSUE TITLE
Feature Request - Crop mode for FMV

### ISSUE THREAD

**Issue by FuxorLuck** [PCSX2/pcsx2#3430]
Many PS2 Games have FMV Videos with a 16:9 aspect ratio but with black bars to fit a 4:3 TV.
on a 16:9 screen, it looks like a small video inside a black screen

example:
1:15
https://www.youtube.com/watch?v=1EBHrdRl4wk

PCSX2 has the option to swap the aspect ratio while FMV is being played.

There should be an option for called a crop mode, so the video will match the screen 

https://imgur.com/a/Yu9F35G

and an option to customize how much the user wants to crop 
for example, if the user wants to keep the subtitles

https://imgur.com/a/4DjFEpz

Thanks for reading

**Comment by lightningterror** [comment]
Such feature already exists. FMV Aspect Ratio override.

**Comment by FuxorLuck** [comment]
@lightningterror 
FMV Aspect Ratio override doesn't crop the image
I actually mentioned this feature in my post, I asked for something different

**Comment by genova447** [comment]
There is an undocumented function in PCSX2.
If you look here: https://wiki.pcsx2.net/index.php/Hotkeys
then look at the function: 

Ctrl + numpad * | Resets the zoom on the GS window

That function has an additional, well, function.
If you press CTRL + * (on numpad) - it will change between no Zoom (default) and "Auto-crop"
It's a really neat little feature... it's not entirely perfect, it can sometimes fail to 'readjust' if the screen format changes from one FMV leading into another (it seems), but otherwise is quite neat.

Again, this function is not actually listed anywhere in settings for PCSX2, nor documented on the Wiki - I just came across it randomly playing around - and you can use it simultaneously with "use 4:3 during cutscenes".

I don't know if this then should have it's own "issues" - but this issue here could be reopened to request to add the "Auto, no black borders" to the GUI settings window, rather than have it as an obscure undocumented function of CTRL + *.
