### ISSUE TITLE
[Bug] PS2 Logo goes at the bottom just before disappearing

### ISSUE THREAD

**Issue by Immersion95** [PCSX2/pcsx2#3485]
The title is self-explanatary, the bug is known but I couln't find any opened issue regarding the matter.

**Comment by RedDevilus** [comment]
Are you referring to the PS2 Logo in Full(Boot) before it goes in-game?

**Comment by Immersion95** [comment]
Yes I do

**Comment by RedDevilus** [comment]
I remember getting that issue in the past. But i don't get it anymore. I wonder if the BIOS version also matters.
![image](https://user-images.githubusercontent.com/24227051/85483562-5657c980-b5c5-11ea-89db-a736ee3b45a2.png)

What are your specs, what games (mention if its PAL or NTSC), what PCSX2 version and put screenshot(s).

**Comment by Immersion95** [comment]
- Latest PCSX2

- Bios --> Sony PlayStation 2 SCPH-39001 System ROM v5.0-01.60 (2002-02-07)(Sony)(US) & Sony PlayStation 2 SCPH-10000 System ROM v5.0-01.00 (2000-01-17)(Sony)(JP)

- Game -->Generally japanese games -->Capcom vs. SNK 2 / Capcom Fighting Jam

**Comment by ichee** [comment]
(Copy pasted from issue [#3543](https://github.com/PCSX2/pcsx2/issues/3543).)




The playstation 2 logo drops off to the bottom of the screen near the end of its display. Issue was fixed in HW renderer about a year or 2 ago, but has been present in SW throughout.

Tested in stable 1.6.0 and dev 1.7.0-dev-120-g715672481

All defaults used except for GSDX-SW renderer. 
Interpreter, recompiler, and all rounding and clamping modes have no effect.

Attached are the emulogs and video recording of both sw and hw renderers, as well as a gs dump.


Windows 10
Intel Haswell CPU
Intel GPU, but also occurs on another system with an nvidia 1080ti gpu.


[gsdx-sw.zip](https://github.com/PCSX2/pcsx2/files/4916280/gsdx-sw.zip)
[gsdx-hw.zip](https://github.com/PCSX2/pcsx2/files/4916281/gsdx-hw.zip)
[gs-dump_sw.zip](https://github.com/PCSX2/pcsx2/files/4916315/gs-dump_sw.zip)
[gs-dump_hw.zip](https://github.com/PCSX2/pcsx2/files/4916316/gs-dump_hw.zip)

**Comment by ichee** [comment]
GSDX-SW only issues listed in [#1562](https://github.com/PCSX2/pcsx2/issues/1562)

**Comment by Immersion95** [comment]
Is there any news on that problem ?

**Comment by ichee** [comment]
Issue can be worked around in latest QT builds under Windows by setting `Direct3D 11` globally and setting `Software` to the per-game settings.

Other renderers briefly flash back to the desktop.
