### ISSUE TITLE
how can I get reshade  4.7.0 to work with pcsx2?

### ISSUE THREAD

**Issue by ihavetubes** [PCSX2/pcsx2#3506]
I want to use it in dx11. Anyone know any fixes? thanks

**Comment by RedDevilus** [comment]
Unfortunately this only works with OpenGL currently.

**Comment by tadanokojin** [comment]
dupe #2106

**Comment by ihavetubes** [comment]
thanks for letting me know.

**Comment by ihavetubes** [comment]
> dupe #2106

I read this topic before posting but couldn't get the fix to work.

**Comment by tadanokojin** [comment]
Our github is for tracking issues only and is not a support forum. So having a new ticket for issue that we are already tracking only clutters our issue tracker. As such this ticket is being closed as a duplicate. In the future I suggest you either create an account https://forums.pcsx2.net if you have a support request or otherwise update the existing ticket.

Thanks
