### ISSUE TITLE
Merge cdvdGigaherz plugin

### ISSUE THREAD

**Issue by MonJamp** [PCSX2/pcsx2#3515]
I think PCSX2 would benefit from removing plugins and merging everything into the core. The CDVD plugin seems like the easiest one to merge. AFAIK the ISO option for booting games works flawlessly and a CDVD plugin is only necessary for booting games from the disc drive. I remember there being other CDVD plugins for PCSX2 but I'm not sure if they still work or are useful in any way.

I already began trying to merge the plugin but after removing references to the CDVD plugin I was left with linker issues which I'm unsure how to resolve. Here's that branch: https://github.com/MonJamp/pcsx2/tree/merge-cdvd. There's still some work left to do even after I resolve the issues. I would like any tips or help on how I can merge the plugin. The PCSX2 code base is large and I'm having a hard time navigating through it all.

**Comment by arcum42** [comment]
Not sure if this helps at all, but at one point, I started looking at that, and created a cdvd branch, which compiled on Linux, but not windows, and barely did anything yet, since I was more putting the framework in to add it than actually adding it, so I basically added a whole bunch of function stubs that did nothing, with the intention of adding the actual code from the plugin later.

You can see that here:
https://github.com/PCSX2/pcsx2/commit/50e2b10fe6067a7267b16fd3b20d53963d1bcea7

It mostly sets up a Disc menu item next to ISO, Plugin, and No Disc, which calls all the stubbed out api calls in pcsx2/CDVD/CDVDdiscReader.cpp/h...

**Comment by MonJamp** [comment]
I like how you went about it. I did things in the opposite order and probably ended up removing code I shouldn't have. Initially I was still learning how PCSX2 interfaced with the CDVD plugin so seeing your commits helps and shows that I was heading in the right direction. Thank you!

**Comment by arcum42** [comment]
Thanks, and no problem!

One thing here is that I knew that the iso code that was in pcsx2 used to be in a plugin as well, so I pretty much looked at how that was handled and went from there.

I end up starting a lot of things, poking at them a bit, and moving on to something else, and sometimes coming back to them. One of my other ideas on this subject was bringing in most of the null plugins as built-in plugins that were always in the plugin lists. Never quite got that to work, though. I'll probably get back to it one day...
