### ISSUE TITLE
[OnePad] Unable to recognize button presses of DualShock 4 controller

### ISSUE THREAD

**Issue by cglmrfreeman** [PCSX2/pcsx2#3570]
***PCSX2 version:***
``(For example, stable build v1.6.0 (or) development builds v1.7.0-dev-xxx)``
v1.6.0

- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](https://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``
Default/Clean Install

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``
Onepad 0 2.0.0

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``
OnePad detects my wireless Dualshock 4 controller and is able to send it a test rumble, but no buttons can be assigned to any of the button configs.

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``
Open PCSX2 with the Dualshock 4 controller connected via Bluetooth and attempt to configure the OnePAD settings.

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``
N/A

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``
CPU: 16x AMD Ryzen 7 3800X 8-Core Processor GPU: GeForce RTX 260 OS: OpenSUSE Tumbleweed.

Additonal notes: SDL2 Gamepad Tool sees the GUID of the PS4 Controller as "030000004c050000c405000011010000"

**Comment by lightningterror** [comment]
Onepad is plug and play and should work right away. You can't configure the controller otherwise. Do all buttons not work?

**Comment by cglmrfreeman** [comment]
Everything but the touchpad "press down" button, which assigns "Left Mouse Click"... also I am no longer able to open PCSX2 due to a new error:
```
Program received signal SIGILL, Illegal instruction.
0x569247c1 in Threading::Mutex::Acquire(wxTimeSpan const&) ()
```
But I think that is for a separate issue.

**Comment by Shoegzer** [comment]
@cglmrfreeman Keep in mind there are at least [two releases](https://wiki.gentoo.org/wiki/Sony_DualShock#cite_note-ds4v2-support-3) of the DS4 (CUH-ZCT1 and CUH-ZCT2, both of which are documented in the linux kernel/HID source.  Electronically they are slightly different, notably that they report different ID strings.  I'm not sure if that would apply here but it might depending on the onepad db, perhaps your particular DS4 ID isn't in the db or isn't mapped properly, I haven't looked at the db or code.

I too prefer to map/remap buttons myself rather than force internal database mappings on the user, the latter provides only trivial benefit anyway when the most common use case is to map once and forget.  You might try onepad-legacy rather than lilypad as I do, although be aware you can't hot-plug a controller so if for example the battery dies during use, you have to restart the emulator.  It's a pain, but definitely worth the cost for the extra control you get over your mappings.  Would be great to have both features merged into one onepad plugin (and it would live up to its name) but that's an entirely separate matter.

**Comment by cglmrfreeman** [comment]
I decided to revisit this issue today by updating pcsx2-1.6.0-2.1.i586 to pcsx2-1.6.0-61.2.i586, however, the issue still seems present with both LilyPAD and OnePAD having the exact same issues.

@Shoegzer My model of DS4 is the CUH-ZCT2U, which may be why I am experiencing issues? I don't know what to do in that case. I can't remember when I bought my PS4, possibly at the end of 2018, so this isn't a brand new controller I don't think.
