### ISSUE TITLE
Please stop using discord

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#3629]
Since the issue where this was being discussed was locked for little good reason...

> What is the added benefit of this? 

https://sneak.berlin/20200220/discord-is-not-an-acceptable-choice-for-free-software-projects/

Personally discord ensures that several users will be excluded from participating.

_Originally posted by @orbea in https://github.com/PCSX2/pcsx2/issues/2915#issuecomment-680037120_

**Comment by refractionpcsx2** [comment]
And how is IRC better? as soon as you connect to a channel it announces your IP address/host which is an even bigger invasion of privacy than Discord, at least with discord the end to end users don't see each others details beyond the discord ID, only discord themselves know about your phone number or email address etc, but with IRC, as soon as you log in, you're open to being hacked and having your personal details stolen by random users.

I know you can connect with a VPN/DNS Mask before you suggest it, but 99% of our users are not going to do that.

**Comment by lightningterror** [comment]
Github isn't the place for these discussions.

**Comment by orbea** [comment]
> And how is IRC better? 

I made no arguments for irc, the article I linked also did not.

> Github isn't the place for these discussions.

Where would be a better place? This is an issue which relates to discussing pcsx2 development or rather that some people can not do that. I think github is the right place.

**Comment by lightningterror** [comment]
> Where would be a better place?

Discord. All discussions are handled there.

**Comment by refractionpcsx2** [comment]
Well what do you suggest then? You're quick to tell us on what *not* to use but not offer any solutions.  We have a forum and a Discord to provide somewhere for users to go and you're the first person I've come across who cares so much about their privacy that they can't bare to have Discord know their email address (as far as I'm aware you don't need to give them a phone number, pretty sure I didn't).  I did look at the article, and it looks like a lot of tinfoil hat nonsense to be honest.  If you're trying to avoid your precious privacy being invaded in 2020, then you better disconnect from the internet and destroy all your credit cards, destroy your mobile phone and live off cash and be in a non-connected world, because those are a bigger problem to your privacy than Discord is.

**Comment by tadanokojin** [comment]
Why do we need to move away from discord when you can simply choose not to use it if you object to it so much? I and the other devs have the freedom to use discord and you have the freedom not to. Why does your desire to not want use to use it supersede my freedom to use it?

How many people would we be excluding by not using it? It's a popular platform and most emulator projects I'm familiar with use it and I use to to contact other emulator devs and to provide support for my users most of whom don't want to be bothered with using another client or any of this encryption stuff.

I read parts of the article. Really I think if you want to make a case for something, then I don't see why you need and article to make the case for you. Just make your points and don't give us homework to understand your point of view. When I debate with someone, I don't say "go read this". I explain why I think something should be a way myself and if I need to reference a source I provide the source and the relevant part of it and in a natural way not by bombarding people with a dozen points in a 4k word essay.

It would be way too unrealistic for me to read the entire article and address every point made all at once considering it's ages long and it would reduce this conversation to nothing more than essays back and forth.

**Comment by atomic83GitHub** [comment]
Discord allows hundreads of peoples to chat and share their project much easier than before. If you don't like it, okay but let us do what we want. And as Refraction mentioned, we do have forums.

**Comment by orbea** [comment]
> Well what do you suggest then? You're quick to tell us on what not to use but not offer any solutions.

Not to sound like a broken record, but the article did suggest several possibilities. I have no strong opinions as long as it is a freedom and privacy respecting solution.

> you're the first person I've come across who cares so much about their privacy that they can't bare to have Discord know their email address (as far as I'm aware you don't need to give them a phone number, pretty sure I didn't)

You do need to provide a phone number if you use something like TOR. None of your other points have anything to do with discussing PCSX2 development.

> Why do we need to move away from discord when you can simply choose not to use it if you object to it so much?

I would think a platform which doesn't discriminate against potential contributors would be preferable. I linked the article because it goes far more in depth than I could since the author has obviously spent more time digging into it than me.

> Discord. All discussions are handled there.

@lightningterror This is just rude, I know you are capable of better...

**Comment by orbea** [comment]
To be clear, I am not making an argument to not use discord for your own personal uses. What I am asking is to not use it to discuss PCSX2 development and then use a more inclusive platform instead.

If people want to use malware that does not respect their users and potentially abuses their trust on their own time, then that is on them, but please don't force others to choose between compromising their values or being excluded from participating in development.

**Comment by refractionpcsx2** [comment]
I did look at the alternatives.

Email: Bloody ridiculous, but we do have email contacts if you really must do that, but it's hardly a community
Email mailing lists: Even more ridiculous
Discourse: This is basically a forum, we have one of those, which we host ourselves.
Mattermost: Okay so that's an alternative chat that *nobody* has ever heard of. Did you consider that people use Discord to connect with other emulation, gaming etc projects? Why would they be happy that we made them download another chat client just to hang around on our server and ask questions? That's really inconsiderate to do.

Just to be clear, I think your motives in this are entirely selfish and most people do not care about having to give out their email address or care about any potential spying that may go down (which is more likely that it doesn't anyway, this is just pro-privacy nuts going crazy over stuff like this), the services we provide are convenience because of what the masses like to use.  If you don't agree with discord, fine, we have a forum for you to use, we aren't forcing you to use Discord, just as we're not going to forcefully stop using discord because you don't like it.

This isn't a request which is going to be actioned, we are going to continue using Discord if you like it or not, we have alternatives just for you.

**Comment by atomic83GitHub** [comment]
So if I understand you don't like discord just because it's open source? Awsome. Then why not sugesting to the team to make PCSX2 Linux exclusive? At some point it's not because it's open source that it is better (yeah, even if we do open source stuff). Discord is just the best chat platform all around and actually, they do care for your privacy at leist. P2P is just a unsecure way of connecting with each others.

**Comment by orbea** [comment]
> Just to be clear, I think your motives in this are entirely selfish 

I resent your false implications and given by the rest of your response you clearly do not understand the issue. I'll leave it at that.

> So if I understand you don't like discord just because it's open source? Awsome.

Uhh.... Have you read the discord license and terms of use? :) If it was free software this would not be an issue.

**Comment by tadanokojin** [comment]
> To be clear, I am not making an argument to not use discord for your own personal uses. What I am asking is to not use it to discuss PCSX2 development and then use a more inclusive platform instead.

But we'd be excluding more people by not having our development conversations there.

**Comment by kenshen112** [comment]
Ok no. Are you seriously trying to suggest that opensource software is somehow magically more secure than something like discord? Software that OPENLY broadcasts it's code to the public? Hell naw. And Discord absolutely is free software. Did you have to pay a dime to use it? No. Discord nitro? Optional addon that makes one or two enhancements that some people prefer.

**Comment by atomic83GitHub** [comment]
"Uhh.... Have you read the discord license and terms of use? :) If it was free software this would not be an issue."

I don't need to read that to know that it's free ;), what are you trying to do lol?

**Comment by orbea** [comment]
> But we'd be excluding more people by not having our development conversations there.

Those people were using other platforms and were not being excluded before discord was a thing. I don't think this has any basis in reality.

> Are you seriously trying to suggest that opensource software is somehow magically more secure than something like discord? 

If discord was free software (Not proprietary), then:

* It could be audited to find security issues.
* It could be modified  to fix security issues.
* It could be forked if and when the discord upstream did not resolve security issues in their released code.
* It could be used to spin up own private discord severs which are not under a single centralized authority.

Clearly I have no hope discord would actually allow any of this.

**Comment by tadanokojin** [comment]
> Those people were using other platforms and were not being excluded before discord was a thing. I don't think this has any basis in reality.

Before maybe, but time is a thing that exists and things change. If we had this conversation a few years ago we'd be talking about Skype or AIM. That has nothing to do with the reality now.

**Comment by avih** [comment]
> I think your motives in this are entirely selfish

I entirely don't see it that way.

> and most people do not care about having to give out their email

And this is entirely true. Most people simply don't care about this and similar things. They will run programs with root kit DRM because otherwise they can't play game X, give out their email addresses and browser histories to the biggest companies on earth to get free search, let various assistants listen to every breath they make so that they can ask in voice how's the weather tomorrow, and other such things.

The vast majority of people prefer convenience over invasion to their privacy. That is a fact which I don't think anyone would dispute. But it also doesn't make invasion to privacy a great thing. It's still bad, but people are still willing to allow it depending on how much they feel they get in return.

So I think the point @orbea was making was that if people here care enough about it, then there might be better places from the privacy point of view.

I don't think it was more selfish than anything which anyone ever does. Everything we do is selfish, even saving whales - because it makes us (or whoever does it) feel good.

I think it's pretty obvious that the people here are aligned on this subject. And that's fine. But there's no need to downvote or be rude only because other people think different than you.

**Comment by RedDevilus** [comment]
There is already an IRC channel so the alternative is there. You can just say no and yes to irc or discord. Semantics about free and opensource left alone. I'm open to improvements but punishing the majority for stopping discord is not the way. Intolerance for a different intolerance is not the way to go. It's better to use pros for others instead of only targeting weaknesses which to be honest every program and platform has.

**Comment by refractionpcsx2** [comment]
> I entirely don't see it that way.

How come? How is asking us to stop using discord because he doesn't like it not selfish?  A non-selfish person would just choose not to use it, they wouldn't demand we change our ways because they aren't happy with it.  I find it unlikely he's worried about anybody else's privacy.

**Comment by orbea** [comment]
> If we had this conversation a few years ago we'd be talking about Skype or AIM. That has nothing to do with the reality now.

Did PCSX2 development discussion ever occur solely on Skype or AIM? I hope not...

> Irrelevant because those auditors could be someone trying to hack the software

I sincerely can't tell if you are serious or just trolling. How do you even contribute to PCSX2 without using free software like git which is obviously full of people auditing code to secretly add vulnerabilities.... [/sarcasm]

> There is already an IRC channel so the alternative is there. 

Offering a reportedly dead IRC channel doesn't offer much confidence. It might be different if the core developers where to use it primarily. Given the responses to this thread I am not holding my breath...

**Comment by tadanokojin** [comment]
> So I think the point @orbea was making was that if people here care enough about it, then there might be better places from the privacy point of view.

No he's telling us to stop using discord for development conversation. Which by the way we can't even enforce. We just have devs and users who use discord and that's how it is. All implementing another chat client would do is further fragment us when we already have alternatives:
1. github
2. forums

Who am I to tell someone like @refractionpcsx2 or @lightningterror that we have to move now? They'll just continue to use discord anyway and I can't stop them and why would I?

**Comment by dio-gh** [comment]
"Let's move away from the de facto platform the very vast majority of the userbase uses because of arbitrary reasons that even if valid, won't convince anyone of said userbase."

Gee, I wonder how did that not happen already!

**Comment by tadanokojin** [comment]
> Did PCSX2 development discussion ever occur solely on Skype or AIM? I hope not...

PCSX2 development discussion doesn't happen solely on Discord. Just a lot of us use it casually and so a lot of conversation happens to happen there. This is a complete non-point and entirely misses my point which was that most people use discord and I can't force them to use something else and that your argument about what was happening before discord is entirely irrelevant to that.

**Comment by orbea** [comment]
> Which by the way we can't even enforce. 

@tadanokojin The question is not enforcing it for every user, but it would be enough if the core development team were to take a stance to not use it.

**Comment by tadanokojin** [comment]
Aright well I'm not taking *your* stance.

**Comment by avih** [comment]
> How is asking us to stop using discord because he doesn't like it

I can't answer for him, but I think he was suggesting it to help YOU protect YOUR privacy, and yes, probably also because he can't take part in it due to HIS preferences.

I don't think it's called selfish, I think it's called a discussion where different people have different views on a subject. Not every discussion has to end in agreement, but in EVERY discussion, EVERY ONE is selfish. You always argue YOUR point of view. That's how humans operate - from THEIR point of view.

**Comment by dio-gh** [comment]
Protecting privacy at the small price of cutting off contact from an incredibly large amount of people by making yourself unavailable through one of the current basic means of internet chat and communication in favor of switching to way less popular if not largely unknown, less polished services.

What a deal, I sure wonder how Discord can keep up their privacy invasive practice by just being maximally polished, readily available, well established, easy to use, and free of charge! Unexplicable why people wouldn't just switch away.

**Comment by refractionpcsx2** [comment]
> I can't answer for him, but I think he was suggesting it to help YOU protect YOUR privacy, and yes, probably also because he can't take part in it due to HIS preferences.

That's very noble, but I don't need other people to look out for my own privacy, I know the risks going in to it, I just don't care. We're in 2020, everything invades your privacy and everybody sells your data, I think making concessions to inconvenience yourself just to avoid the inevitable is ridiculous and a complete waste of time, but if it makes that person feel better they can knock themselves out, but please don't tell me what to do, and I'm certainly not going to change everything and inconvenience a large majority of our user base when they don't care either.

If the rest of the dev team all said they didn't like it, then democratically I'd be fine with it, but this is an issue that has never been an issue and nobody has had a problem with it previously, this is the first time it has been mentioned, I don't see a lot of support for it.

> Not every discussion has to end in agreement, but in EVERY discussion, EVERY ONE is selfish. You always argue YOUR point of view. That's how humans operate - from THEIR point of view.

Well, indeed, however this wasn't really a discussion, it was a "Stop using discord, this is why discord is bad" there was no opinion and no alternatives suggest to what we could use, just complete reliance on an article complaining about how discord sucks and we should use some obscure apps nobody has ever heard of.  The entire premise of this post is based upon what I'd consider an exaggerated problem that 99% of users care little about - RE my previous statement.

**Comment by avih** [comment]
> If the rest of the dev team all said they didn't like it, then democratically I'd be fine with it

So, it's selfish because he's not a PCSX2 developer? What if another PCSX2 developer have suggested it?

> it was a "Stop using discord, this is why discord is bad"

I don't think so. I've read his latest and original OP post, and i didn't see anything more than suggestion.

Let me put it this way, how should it have been suggested without raising so much hostility?

I'm assuming you're not objecting to people making suggestions in general, but rather only to the way in which he did it, right?

**Comment by DJScias** [comment]
Hello there,

I think this issue can't be fixed.

For the simple reason that OP has suggested this phrase as being the main issue:
> discord ensures that several users will be excluded from participating.

The article talks about privacy and such and it's understandable people have concerns. Some people won't be interested in giving a service their email (even though services exist where you can anonymize it, protonmail springs to mind) and that's entirely up to their choice. The info you want to share is what you decide to share yourself and that creates the "exclusion" barrier that some might not be up for (and that's just talking about people who care about privacy).

Let's say Discord is not used for some communication. That would mean PCSX2 has to shift to using a forum (which they do, afaik), IRC, or any other chat communication means. However all of these means require people to either go somewhere, download something, etc..

Each and every one of the methods above will create the same problem because in and by itself these communication platforms start excluding people because for some users it might not be easily accessible, not their preferred choice, not the necessary toolset they're used to, etc... It's been known the lack of a "dark theme" in communication methods can already make people not want to use certain options and let's be fair that this should, logically, be one of the least big issues in contributing somewhere.

And then we've come to the point of where it's basically opinions vs opinions.

Considering open-source means "publicly available and to contribute to" it means that all programming will be shared as-is here on Github in the public domain. Github requires you to sign up with an email and lets you make connections to ensure you can prove to Github you are who you are (keys, etc..) so there's information kept on record.

It seems like contributors to the PCSX2 project can get behind that idea of privacy then it's not that many steps removed from other communication tools like Discord, forums, etc..

Unless we're talking about people that don't trust github and would prefer bitbucket or gitlab.. Those people are already excluded because Github is being used.. And you can see how this issue can keep on going and going in many different directions without no end?

So I say perhaps the best option is the "catching net" that gets as many people to contribute as possible? There's no definitive option that will make everyone happy so striving for the "all" is impossible. Perhaps find a way to raise to contributors what their easier/preferred choice of communication would be? Whether that's viable or not is another case..

In the end the PCSX2 team chose Github to put their stuff on, if organically they've teamed up and this resulted in having a lot of team members together in Discord like other emulation projects do then I guess so be it? If switching now makes the project lose contributors because Discord was what kept them contributing then that's also not a gain but a loss.. Every side has winners and losers.

And for all the above reasonings, I feel this issue can't be fixed (and could go on for eternity...). Whatever people would choose, there's always going to be people feeling excluded.

**Comment by refractionpcsx2** [comment]
> > If the rest of the dev team all said they didn't like it, then democratically I'd be fine with it
> 
> So, it's selfish because he's not a PCSX2 developer? What if another PCSX2 developer have suggested it?
> 
> > it was a "Stop using discord, this is why discord is bad"
> 
> I don't think so. I've read his latest and original OP post, and i didn't see anything more than suggestion.

The title says "Please stop using discord" how can you not thing he's telling us to stop using discord?

> I'm assuming you're not objecting to people making suggestions in general, but rather only to the way in which he did it, right?

Of course I'm not against people making suggestions, if they make a coherent and decent argument for doing so, then I would consider it and discuss it with everybody else to see if they would like to be in another place or not.

> Let me put it this way, how should it have been suggested without raising so much hostility?
Okay if we ignore the fact the forums exist, if it was approached more like so:
Title "Alternative to discord for development discussion"

Content: 
"Myself and quite a few others are not fans of Discord due to privacy concerns in how things are handled, for more information you can read this *link to article*

It would be great if there was an alternative we used either X app/site because of X reasons and I think that would be good for the community and wouldn't cause any inconvenience for your users.  Would you guys be willing to adopt this platform?"

Or something along those lines.

**Comment by avih** [comment]
> The title says "Please stop using discord" how can you not think he's telling us to stop using discord?

LOL so true, I completely forgot what the title was :) oops.

Though it did begin with "Please", so one could also see it as begging, or even a polite request rather than an order ;)

> ... Or something along those lines.

@orbea now you know...

Anyway, yeah, it's pretty obvious it's not going to happen. Every fight has a looser... and in this one Discord won ;)

**Comment by tadanokojin** [comment]
Please stop replying.

**Comment by atomic83GitHub** [comment]
Yeah because as far we know, Discord is not a north korea spy app design to steal infos.

**Comment by orbea** [comment]
> Though it did begin with "Please", so one could also see it as begging, or even a polite request rather than an order ;)

It was intended as an polite request to be taken in context of the op, I obviously spent very little time considering the title.

Although @refractionpcsx2 is right that the content was "discord is bad" essentially. It is literally malware where like other social media platforms designed to collect user data on a massive scale for undisclosed reasons and uses with absolutely no oversight or recourse possible.

Also most people who avoid discord for similar reasons are not going to be saying this because they do not want to be exposed to the abusive replies witnessed here. Its often easier to do nothing than stop the masses from flinging themselves off every cliff the less respectable offer them for "free".

**Comment by tadanokojin** [comment]
Here's the thing. You're welcome to your view that Discord is malware. I think it's hyperbole, but it's neither here nor there.
I don't really consider your crusade against discord to be a reason not to use it. Nor were any of the arguments you presented really compelling. They seem to be based on some weird idea that Discord is the only valid place for development discussion but this thread and hundreds of other threads on github and the forums prove the contrary.

If some number of devs want to use Discord to communicate on the subject of development because that's convenient for them... what do you want me to do? Tell them they can't? Is github and the forums not acceptable for some reason? What constitutes "Development" where I'd have to direct them to some alternative? Does this apply to any development talk at all?

I don't see what the issue is.

**Comment by orbea** [comment]
> They seem to be based on some weird idea that Discord is the only valid place for development discussion but this thread and hundreds of other threads on github and the forums prove the contrary.

Take a look at the issue you locked preceding this one for some context. For example the quote, `"Generally speaking, I think the pcsx2 discord group is where a fair amount of discussion happens,"`. The initial objection is that to take part in this "fair amount of discussion" using a proprietary platform that doesn't respect privacy or their users is an requirement.

> where I'd have to direct them to some alternative?

By all means if this discussion entered a phase where not using discord was seriously considered we can start talking about alternatives, but I don't think it will reach that point given the current discussion.

**Comment by kimberly990** [comment]
Here's a simple solution. If you want to partake in development discussion but don't want to sacrifice your privacy:
1. Get a throwaway Google account, get a Google Voice phone number for free
2. Make a Discord account with that
3. Install Discord on a VM with TOR if you _really_ feel that's necessary
4. ta da, all solved

**Comment by tadanokojin** [comment]
> Take a look at the issue you locked preceding this one for some context. For example the quote, "Generally speaking, I think the pcsx2 discord group is where a fair amount of discussion happens,". The initial objection is that to take part in this "fair amount of discussion" using a proprietary platform that doesn't respect privacy or their users is an requirement.

I don't see the issue with the quote and I didn't see the issue when I locked the thread either. Nothing about that quote means you don't have alternatives or that Discord is a requirement. Again, I keep telling you that you have the option to use github or the forums and you ignore it.

>  I don't think this is appropriate for a software project licensed under a free software license such as the GPL/LGPL.

Okay, but I don't care. Just because PCSX2 is GPL doesn't mean everything we do has to be GPL or that we can't use proprietary software internally. I'm just not as religious on this as you are.

> By all means if this discussion entered a phase where not using discord was seriously considered we can start talking about alternatives, but I don't think it will reach that point given the current discussion.

You've got an entire thread of people seriously considering it. Just because they didn't come to the same conclusion as you did doesn't mean this thread isn't full of thoughtful objections to your request and entertaining the idea. @DJScias wrote an entire thoughtful explanation for you which you promptly ignored.

You don't seem to understand how this works. Here, I'll tell you what I'll make a server or channel on an application of your choosing and when none of us go over there because Discord is more convenient for talking to our users, testers, other devs, etc you'll see why you can't just compel people into using software you like because you personally like it. What makes you think that if IRC is dead that suddenly we can make whatever else not dead.

It's as if you think that we can just decide to use something else and by virtue of that we will just start using something else, but I or anyone else can't compel any of the devs to do anything. This isn't a dictatorship. People are free to associate with other people on the platform of their choosing. That platform for most people happens to be Discord. If you don't want to use Discord, don't.

But this is the problem I have with this orbea. You cherry pick our points and never actually address any of the arguments you're being presented. Where's the answer to my other questions? When are you going to address my other points? What about the fact that there are other alternatives available to you? How are we going to enforce this when the devs have the freedom to use Discord anyway? Even in the quoted question you avoided giving an answer and instead made some unrelated comment.

**Comment by CookiePLMonster** [comment]
Side note - if you want change, why not be one? For example, Dolphin devs use IRC but there is an unofficial Discord server for it where **some** people post.

If you want Discord out, I'd say you could try kicking off a PCSX2 chat somewhere using a truly free, open and liberated medium, and then convince people to join it. This way you'll not only achieve your goal, but you also get to be a positive influence beyond just merely suggesting things.

**Comment by tellowkrinkle** [comment]
> If discord was free software (Not proprietary), then:
> 
> * It could be audited to find security issues.
> * It could be modified  to fix security issues.
> * It could be forked if and when the discord upstream did not resolve security issues in their released code.

If you assume that everything you post into the PCSX2 Discord is public (which it is, even if you could audit your version of the app and the server, you still can't prevent people from running custom clients which record everything you say in it, or taking screenshots, etc), then there aren't any security issues to fix.  Secure messaging systems like Signal only work when you trust everyone in the conversation, which (I hope) isn't the case in a server with thousands of anonymous people.  All platforms PCSX2 uses for general conversation should be considered as public like this, be it Discord, GitHub, the forums, IRC, or any platform we use in the future.

If you're worried about your personal data, run Discord in an open source web browser and don't give Discord any data you're worried about leaking.  If you really wanted to, Discord allows you to join servers before you've registered an email address, though I'd recommend using a throwaway email instead.

> * It could be used to spin up own private discord severs which are not under a single centralized authority.

We could still spin up our own private non-Discord server and switch to it if we decide Discord is no longer the best fit for us.

**Comment by JibbityJobbity** [comment]
Element/Matrix is a possible alternative. It's kind of a mix between Discord and IRC. Main thing that sucks about it though is its lack of Discord's server oriented channel model which is pretty nice to have. Matrix has communities but I wish that feature had a bit more work put into it.
Regardless, I don't think everyone would be happy with the switch but I'd like to see it be available.
