### ISSUE TITLE
add a minimum delay between consecutive F9

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#370]
Quickly switching between hardware/software renderer is not very stable. The idea is to put a minimum delay of a couple of seconds between consecutive hit.

Some references:

http://forums.pcsx2.net/Thread-Bug-Report-Project-Zero-2-Fatal-Frame-2-PAL?pid=380261#pid380261

http://forums.pcsx2.net/Thread-Bug-Report-Shin-Megami-Tensei-Persona-4-NTSC-SLUS-21782?pid=380265#pid380265

**Comment by shinra358** [comment]
This seems to be an issue with most (if not all) pcsx2 hotkeys. While not all crash the emu, simply holding the button down repeats the button's function over and over. Perhaps just the holding down of the button can be excluded from all hotkeys and just have the functions activate for just a press. That's because even if you add 500ms delay, it would still activate again if the button is still held down.
