### ISSUE TITLE
Evil dead a fist full of boom stick

### ISSUE THREAD

**Issue by timothywhosoevers** [PCSX2/pcsx2#3728]
how do I fix shadowing on the newest version￼

**Comment by tadanokojin** [comment]
Hello,

It appears your question is not related to an issue or request for the PCSX2 application and is instead a support request. In order to keep the issue tracker organized, we ask that you instead create an a thread in the [support forums](https://forums.pcsx2.net/) which has better resourced to assist you with your request.

Thank you.
