### ISSUE TITLE
Armored Core: Last Raven (NTSC-U) black screen entering mission

### ISSUE THREAD

**Issue by awksie** [PCSX2/pcsx2#373]
Windows 8.1 Pro x86-64, PCSX2 version 1.2.1 (newest stable) and 1.3.0-20141202231058 (git) (extracted to separate directories, tested separately)

Using GSDX SSE2, AVX, or AVX2, D3D9/D3D11 hardware mode results in a black screen upon entering the mission, regardless of settings. (Tried many variations on internal resolution, with widescreen hacks on or off, window resolution always set to 1280x720) Software mode runs fine (very fast!). When the screen goes black, the game is still running fine otherwise; you can hear the AC moving around and shooting with controller input.

Tested with compatibility preset on Safe (fast) and Safest.

OpenGL gives a white screen on console startup. Will test with another title in a second, make a separate issue if it persists in other games.

Hardware is Core i7-4790K with Intel HD 4600, and a Radeon R9 290X (driver version 14.11.2).

Easiest way to test is to go to the Garage, then enter the AC Test.

**Comment by jonaand** [comment]
ant hope that add custom resolution in software mode? thanks

**Comment by gregory38** [comment]
Try the build of this thread http://forums.pcsx2.net/Thread-GSdx-2-0
Note: OpenGL only

**Comment by Fedearg** [comment]
Can confirm that said build, using openGL, still shows no image on missions or training mode.

Does anyone know of where is the incompatibility between this games version of the Armored Core engine, and the HW mode? 
It must be something specific of this game, because all previous sequels of the series have no issue with it, Nine Breaker included, which came out only a year before Last Raven.

**Comment by awksie** [comment]
I will test and try again later today, and report back this evening. (*‘∀‘)

**Comment by prafullpcsx2** [comment]
@gregory38 : I want to confirm that the bug still exists both with dx and opengl. Also there seems to be huge memory leak with GSdx opengl right at the start because it badly crashed my windows and nvidia drivers too with memory errors (even crashed firefox window which was open).

Here you will find block dump for crash at start and also gs dump for ingame black screen issue.

http://www.filedropper.com/armoredcore

**Comment by gregory38** [comment]
For the mem leak, could you test without depth support?

**Comment by prafullpcsx2** [comment]
Sorry, I Checked again, crash happens only if I select 3X native resolution or above. It seems to hurt my pc, the game must be pretty demanding. Can't there be some safeguard that in such situations PCSX2 closes itself without hurting the PC?

**Comment by gregory38** [comment]
yeah I need to improve it.  Not sure on the best solution.

**Comment by gregory38** [comment]
I marked the bug as fix. I keep it open because it requires an hidden option.

**Comment by lightningterror** [comment]
Direct3D fixed with #2120
