### ISSUE TITLE
Metal Gear Solid 3 Cut Scenes Slwo Motion on good PC Why ?

### ISSUE THREAD

**Issue by zerr11** [PCSX2/pcsx2#3882]
pcsx2-v1.7.0-dev-514-g86e6745f2-windows-x86 I USE DX11 , openGL is a tragedy I don't know what this plug is for is completely unplayable for this game.

MGS 3 Slow Mo-tion only FPS 30-40 on Cut Scenes Moves game play normal 60 fps why problem whit moves :/

PC : Windows 10 Pro x64

i7 6700 4x3,4 Ghz ( Multi Core ) ~4,0Ghz (Single Core ) Threds (8) RAM 8 GB 2133Mhz Dual CHannel Card : GTX 1070 8 GB

why is so weak this emulator god 2020 y. and still problem whits this game i check all option i use all option nothing help some time cut scenes speed 50-60 but game go slwow motion lol wtf with this scenes slow motion or game slow motion lol why is not fix yet, cannot be combined ? problem is only cut scenes 30-40 fps

why still no add DX12 ? or Vulkan maybe this will by help/

it's sad that in 2020 this game is still unplayable

dolphin added DX12 NO LAG and works much better than dx11

**Comment by zerr11** [comment]
some time i all option off and use everthings low but still same problem some fps go up but only little is not 50-60 fps lol on i7....

so there is no point in changing the options because the difference is tiny MTVU + 3 core I tried but no difference I tried all different combinations and then problems with scenes

**Comment by zerr11** [comment]
it is that the emulator was created while dual-core processors still reigned supreme maybe this is the problem that this emulator is too old
will it get better in the future?

**Comment by tadanokojin** [comment]
User who creates a github account and same day goes to the repo of a free and open source project run by people who work in their free time and without compensation, makes a support request on our issue page without any of the proper information whilst going on about dx12, VK and dual core processors without having any idea what they are talking about and then whining that their particular wants are not being catered to in a fashion that think is timely because it's _current year_ all while continuing to spam the issue with more speculative nonsense in violation of our rules.

You are right, that's pretty sad.
