### ISSUE TITLE
[Feature Request] Reenable Guncon support (nuvee plugin deprecation)

### ISSUE THREAD

**Issue by legend800** [PCSX2/pcsx2#3931]
**Description**
Due to this: https://github.com/PCSX2/pcsx2/pull/3889, USB plugins are deprecated, disallowing users to continue using the nuvee plugin which provides guncon support. So users can no longer use the guncon feature in games and map input to mouse or external guns (aimtrack, sinden, etc.). 

**Reason**
Without this, light games games are basically unplayable as you need to point quickly at things and you just can't do that with a gamepad stick. 

**Examples**
Some example impacted games:

    Endgame
    Gunfighter
    Ninja Assault
    Time Crisis Zone
    Time Crisis 3
    Vampire Night
    Virtua Cop
    Police 911

**Comment by AmFobes** [comment]
Now that the usb plugin is merged, it will be next priority to implement all missing functionality that other plugins would've otherwise provided.

Please be patient as merging plugins is a messy and slow process :)

**Comment by refractionpcsx2** [comment]
Dunno if it'll help, but this is the source for the nuvee plugin, if you need hints oin how it works https://github.com/mirror/nuvee/tree/master/nuvee_ps2_usb%20-%20guncon2%2C%20keyboard%2C%20mouse/src

**Comment by n1ghttrap** [comment]
Bringing more attention to this.

**Comment by freddyyeddy** [comment]
Is there some workaround for the short term here. Specifically for Police 911. I can get it to see a usb mouse for input but there is no way to calibrate the game to match my mouse input. So it is way off.

**Comment by refractionpcsx2** [comment]
Yes, use 1.6

**Comment by tadanokojin** [comment]
Yeah I mean, I don't know how else we can get the word out. Lots of stuff is be moved around and refactored and there will be things that get removed or readded and bugs to fix.

Unless 1.7.0 fixes a bug for you or you're just interested in helping the team test the dev series you don't need to be using it. This isn't the 1.5.0 dev series where everyone had to use it because 1.4.0 was so far behind. A lot of 1.7.0 has been some fixes here and there and a bunch of merging plugins and redesigning things.

Locking this thread because people keep bumping it without adding anything germane to seeing it implemented.

**Comment by stenzek** [comment]
Completed by https://github.com/PCSX2/pcsx2/pull/7534
