### ISSUE TITLE
USB gamepads recognized but not working under Linux

### ISSUE THREAD

**Issue by isaacvonaaron** [PCSX2/pcsx2#414]
Hello

I have a couple of cheap USB controllers that work with everything but PCSX2 (on Ubuntu 14.04 x64), installed from the "gregory-hainaut-pcsx2.official.ppa". I tried both the stable and unstable version. The game pads test well on
jstest
wine control joy.cpl
pcsx

OnePAD seems to recognize the pads, but that's about it - no response during gameplay. Keyboard works fine. I might be doing something wrong here but I seem to have tried everything I found on Google and got the same result.

![image](https://cloud.githubusercontent.com/assets/10384285/5603922/7fbaa4ee-93a4-11e4-9b95-0b0ca3268c61.png)

![image](https://cloud.githubusercontent.com/assets/10384285/5603925/990e632c-93a4-11e4-8be6-221c271b0304.png)

Could this be a bug on OnePAD? How can I help resolve this? Should I send debug logs? If so, which?

**Comment by gregory38** [comment]
On your screenshot nothing is configured for the pad. Did you try to click on "button" on the right and then on the gamepad?

**Comment by isaacvonaaron** [comment]
Hmmm.. I used to think of myself as an intelligent person. Now I don't seem to recall why. My only "excuse" is that PCSX worked straight out of the box without having to properly introduce the pad to the emulator.

One issue left though - the plugin does not recognize the PS3-compatible pad's "Start" and "Select" buttons. They do respond for jstest. I am testing against the stable version. Though this situation acceptible to me, I can try compile the latest SVN if you think it's worth maintaining.

![image](https://cloud.githubusercontent.com/assets/10384285/5607712/885bc324-946e-11e4-8563-ec710960dec5.png)

**Comment by gregory38** [comment]
give me a couple of days to check select/start behavior

**Comment by gregory38** [comment]
bluetooth or usb.
If usb did you try the bottom/rigth option?

**Comment by isaacvonaaron** [comment]
Took me some time but I got to it.
It's a USB gamepad.
The "Hack: Sixaxsis...." checkbox seems to have no effect.
Test method:
- Marked the checkbox.
- Clicked OK
- Went back to the dialog
- Pointed at either Start, Select, L3, R3 and mouse-clicked.
- Attemped to press either Select, Start, L3, R3 on the gamepad - no response.

**Comment by meuwe** [comment]
I have a Xbox 360 controller, I had to remove all the default settings in ```Pad 1``` and then add controller under Pad 1. 

At first I left the default settings in Pad 1 and configured the controller under Pad 2 but when I started a game it didn't work.

So is what I did correct, any controllers need to be added under Pad 1?

I don't understand what is pad 2 for, if you want to use a second controller, like in a two player game?

thank you

**Comment by gregory38** [comment]
Pad 2 is for 2nd player.

**Comment by meuwe** [comment]
Ok, that is what I was starting to wonder, 2 players...

thank you

**Comment by v-fox** [comment]
I'm not sure if that's the same issue as one discussed but I'm having reaaaaly big troubles with the gamepad (Sony DualShock 3 with latest kernel and Bluez 5) under Linux:
1) In OnePad trigger, upper buttons and shaped (△○⤫◻) buttons are ignored in both USB and BT modes. Vibration doesn't seem to be working either. However, if I run `xboxdrv` to imitate XBox gamepad, it is fully recognized (again, without vibration, it seems, despite it working in `fftest` on event device even on BT connection). But I doubt that pressure sensitivity works with this pathetic XBox imitation.
2) LilyPad has no GUI but it dumps logs into console about successfully finding DS3 (and XBox imitation, if `xboxdrv` is used). But no input of any kind is happening.

What's up with that ? Is it only me having this ? I tried running pcsx2 while giving my account full read/write access to js and event interfaces of the gamepad but nothing changed. I also tried putting [this button config](http://forums.pcsx2.net/Thread-OnePAD-Dualshock-3-on-Linux?pid=429021#pid429021) into manually but at least ○ seems to be stuck in pressed state.
I even tried forcibly building the damn thing with GTK3 and SDL2. With GTK3 it failed because of #465 and with SDL2 nothing has changed (it didn't crash thought, probably because SDL1 Wx library wasn't installed since it is separately packaged).

**Comment by sergiobenrocha2** [comment]
Same problem here, d-pad, select, start and analog axis are recognized, but not the shoulder and face buttons.

**Comment by gregory38** [comment]
I created an option in latest build. Please test both value. If you change the option, you will need to restart the emulator.

**Comment by thomwiggers** [comment]
An USB xbox 360 gamepad seems to be working fine for me in 1.4.0

**Comment by aFoxNamedMorris** [comment]
All game pads I have tried so far work fine. Xubuntu 15.10 64-bit.

**Comment by gregory38** [comment]
New onepad 2 version available. It should take care of any remaining problem. Code is based at 100% on SDL2 auto-detection.
