### ISSUE TITLE
FPS HZ improve games for that version 1.7.0 dev 877

### ISSUE THREAD

**Issue by kurdischerjapane** [PCSX2/pcsx2#4154]
**Description**
 i want  seperate  framte rate settings between  the gameplay and the cutcenes because if i set the fps to 65 is running really good but at the movies the framerate are much faster then the audio 65 fps will be amazing in game and for pal version 50 fps at movies  
should be inlucded on game fixes 

**Reason**
 faster smooth gameplay  are more fun 

**Examples**

**Comment by tadanokojin** [comment]
It's hard to tell what you want. While I don't really like to harp on people for their English, you need to at least be able to convey an idea in English and have it be intelligible. Can't really help someone I can't understand.

My understanding is you want a feature that makes the emulator run at a different framerate based on whether the game is currently in an FMV or not. We've had some functionality in the past similar to this (switch to sw mode in FMV) and it's possible to detect when a game is in an FMV (with moderate success) but such features are by definition hacks that will never be good general solutions and so I don't really favor adding more things like this since they make the emulator inherently more complex for something that someone will indefinitely complain doesn't work all the time.

Additionally, most games are tied to framerate anyway so when you set it to 65 fps, the game is actually running in fast forward. This is pretty undesirable for most.

Plenty of games separate out their internal framerate based on whether a fmv is playing. Dark Cloud 2 for example runs FMVs at a different internal framerate from gameplay. If that is the sort of thing you want, then you should just patch the game to do that.

It's becoming clear based on your issue history that you don't really understand how to interact with our github, in the future I suggest you go to the forums and post your issues/requests there so that they can be reviewed before they come to us.

**Comment by kurdischerjapane** [comment]
explanation is hard because i dont have emulator experience.  but it seems you understand me well. yes exactly what i need when can you add it in the emulation?

**Comment by tadanokojin** [comment]
Well then you should go get emulator experience. Our Github is meant to be a place where people can post issues, feature requests, review code, etc. Things that are helpful to the project. We do our best to keep extra noise out of here. So it's not a place for you to get support or learn about emulation through spamming us with invalid issues. 

I suggest the forums or the discord to be good places full of people who share an interest in emulation and can review your ideas and point out any potential pitfalls with them and help you learn about emulation.

And the answer to your request is no.
