### ISSUE TITLE
[BUG] Buffy the Vampire Slayer: Chaos Bleeds demo: VIF Unknown CMD spam.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4179]
**Describe the bug**
When playing the demo of "Buffy the Vampire Slayer: Chaos Bleeds" (issue 85 of the EU magazine), the console will spam a lot of VIF Unkown CMD logs all the time when playing the demo. the demo itself *seems* to work but that issue can't be ignored.

![image](https://user-images.githubusercontent.com/26351275/105638254-f20a2a80-5e71-11eb-9164-64ac46bc4dc5.png)

**To Reproduce**
Start the "Buffy the Vampire Slayer: Chaos Bleeds" demo.

**Expected behavior**
There shouldn't be any logs of that sort while playing the demo.

**Emulation Settings**
Everything default.

**System Info**
PCSX2 Revision: pcsx2-v1.7.0-dev-pr[4171]
OS: Windows 10
CPU: I9 9900k
GPU: RTX 3070

**Dumps**
https://drive.google.com/file/d/1fwX9O9y_fx0_AsRuraFTmTN2SviIFDnv/view?usp=sharing

**Comment by refractionpcsx2** [comment]
This is an interesting one, It doesn't look like junk data, it looks very intentional and the code they used (0x12) is sandwiched right between 3 types of FLUSH (0x10, 0x11, 0x13) and they do it right after starting a GIF transfer off (one of the things some of these flushes wait for), so I wonder if there's some freaky undocumented command there..

Gonna have to run some tests on my PS2 to find out what's going on.

**Comment by refractionpcsx2** [comment]
@F0bes tested this on the PS2, and 0x12 is treated as a NOP, so considering the game isn't broken and PCSX2 already treats it like a NOP, I'm gonna go ahead and say "Replicated on real HW"

**Comment by F0bes** [comment]
[vifcmd12_hwtest.zip](https://github.com/PCSX2/pcsx2/files/8656135/vifcmd12_hwtest.zip)
Just for documentation, here are two identical programs, they both upload an infinite looping micro program to VU. One stalls using FLUSHE and the other uses the mysterious VIF command 0x12.
