### ISSUE TITLE
[Feature Request] Possible ARM/Android port?

### ISSUE THREAD

**Issue by eltomas2003** [PCSX2/pcsx2#4202]
**Description**
PCsx2 arm port for retroarch and google play store.
**Reason**
Get PCSX2 running on ARM devices like m1 mac or smartphones. The current android ps2 emulator (DamonPS2) is inaccurate. Could bring possibility of Ps2 games on the go or on Raspberry Pi if it becomes powerful enough to emulate ps2.

**Examples**
https://play.google.com/store/apps/details?id=org.dolphinemu.dolphinemu&hl=en_US&gl=US 
Dolphin already has an android port, and raspberry pi game do gamecube games
https://www.youtube.com/watch?v=l4TyYU9Xhcs

**Comment by eltomas2003** [comment]
Why did you invalid this

**Comment by lightningterror** [comment]
Sorry but we don't accept feature requests related to retroarch as it's maintained separately at this time.

As for ARM you can find related threads here
https://github.com/PCSX2/pcsx2/issues/2915
https://forums.pcsx2.net/Thread-Pcsx2-for-android--54105

**Comment by Gamemulatorer** [comment]
Your wish granted 🎉🎉🎉
https://pcsx2.net/301-aethersx2-pcsx2-mobile.html?fbclid=IwAR1nHFanNEo4dHBqLzTvBA-DnDbGq--Ts54ALxHVWRn4QBRFSUYfIcaRYwI

**Comment by Maxkatsur** [comment]
I know it's a dead topic, but...
AetherSX2 is dead since 2023. This tragedy raises concerns about the future of PS2 emulation within Raspberry Pi 5 as well as its more powerful and advanced future successors. Not helped by Libretro implementation of PCSX2 being out of date since 2021, in my personal witness. I just want everyone to be aware, since it's 2025, and I think there's _still_ no answer... 
P.S. AetherSX2 uses **STOLEN** code from PCSX2, marked as proprietary rather than GPL. And that sounds illegal for me.

**Comment by RedPanda4552** [comment]
Not happening.

Also, you can stop slandering the Aether dev please.
