### ISSUE TITLE
[BUG] wx white borders in fullscreen

### ISSUE THREAD

**Issue by nadenislamarre** [PCSX2/pcsx2#4231]
on linux, pcsx2 commit 7187b883b07cf5d89ee63b22ed19dd907df5e83d,
in fullscreen, if you set ratio to 4/3, border are white.

in the file pcsx2/gui/FrameForGS.cpp, GSPanel::DoResize() resize the window.
the setBackgroundColor (black) (some lines above) doesn't apply to the part which is not included in the resized part.
the rendering color on these part is white.

modifying the code i were not able to fill this part of black.
my current understanding to fix, is that the window must kept the full screen size (not been resized) but the renderer must be precised a part to render.

**Comment by ViniHS74** [comment]
Hi everybody,

I have the same issue! I use Batocera and there are white borders (instead of black) when screen ratio is 4/3...
It's really unpleasant!! How can we solve it?

Thanks!!

**Comment by Dr-KerbalMD** [comment]
Having the same issue.

**Comment by ViniHS74** [comment]
> Having the same issue.

What are your settings? (resolution, screen ratio etc...)

**Comment by nadenislamarre** [comment]
for example, on a 16/9 screen, 1920x1080. if you select 4/3.

**Comment by ViniHS74** [comment]
> for example, on a 16/9 screen, 1920x1080. if you select 4/3.

Exactly!! I think it could be caused by the internal resolution...

**Comment by nadenislamarre** [comment]
no, this is not the internal resolution. the problem root cause is exactly the one described on the first comment.
If you play a 4/3 game on a non 4/3 screen or a 16/9 on a non 16/9 screen, a resize is performed after a create window, in full screen. So, pcsx2 doesn't control anymore the full screen size to paint. The window manager (or something else) take the relay and render the rest of the screen.

**Comment by Mrlinkwii** [comment]
can you post a screenshot of the issue ?

**Comment by Dr-KerbalMD** [comment]
Interestingly enough, and in what could be a hint as to the cause of the problem, a taking a screenshot using Batocera's built in screenshot hotkey results in a screenshot that is 4:3, sans white bars:

![screenshot](https://user-images.githubusercontent.com/20614697/114311120-82dcc380-9abb-11eb-9a05-c0d5da34d786.png)

So I have also included a photo of the issue so you can see the white bars:

![photo](https://user-images.githubusercontent.com/20614697/114311131-8ec88580-9abb-11eb-9cb7-2b5f0340a5d2.jpeg)

Batocera 30 running on an Intel NUC with an i7-1165G7, if it matters.

**Comment by ViniHS74** [comment]
> Interestingly enough, and in what could be a hint as to the cause of the problem, a taking a screenshot using Batocera's built in screenshot hotkey results in a screenshot that is 4:3, sans white bars:
> 
> ![screenshot](https://user-images.githubusercontent.com/20614697/114311120-82dcc380-9abb-11eb-9a05-c0d5da34d786.png)
> 
> So I have also included a photo of the issue so you can see the white bars:
> 
> ![photo](https://user-images.githubusercontent.com/20614697/114311131-8ec88580-9abb-11eb-9cb7-2b5f0340a5d2.jpeg)
> 
> Batocera 30 running on an Intel NUC with an i7-1165G7, if it matters.

That's the same issue for me!! 😉 Thanks

**Comment by ViniHS74** [comment]
![IMG_20210412_150942](https://user-images.githubusercontent.com/69899615/114400254-112b7500-9ba2-11eb-8749-4d1d76d6d0ac.jpg)

Here is my issue too! Thanks guys!!

**Comment by ViniHS74** [comment]
> no, this is not the internal resolution. the problem root cause is exactly the one described on the first comment.
> If you play a 4/3 game on a non 4/3 screen or a 16/9 on a non 16/9 screen, a resize is performed after a create window, in full screen. So, pcsx2 doesn't control anymore the full screen size to paint. The window manager (or something else) take the relay and render the rest of the screen.

Exactly!! It seems to be a resized issue!

**Comment by ViniHS74** [comment]
> can you post a screenshot of the issue ?

Have you seen my screenshot? Thanks

**Comment by carekovisk** [comment]
Any news? I have the same issue.

**Comment by leturbo** [comment]
Same issue here unfortunately...

**Comment by stenzek** [comment]
https://github.com/PCSX2/pcsx2/pull/4615 should have fixed it, or at least got rid of the window manager being the cause.

**Comment by nadenislamarre** [comment]
i confirm this is fixed with last commit.
thanks a lot.

**Comment by johanmenac** [comment]
Hello, I am currently using the pcsx2 in the batocera, the image of the games appears stretched but I corrected it to 4/3 and it turned out great, the drawback is that there are white bars in the corners and the truth is that it looks very uncomfortable, the ideal is that those bars remain b
![WhatsApp Image 2022-12-07 at 7 27 14 PM](https://user-images.githubusercontent.com/120065874/206328233-c96e461e-02ee-4c87-876c-91fec7fd89e
![WhatsApp Image 2022-12-07 at 7 26 31 PM](https://user-images.githubusercontent.com/120065874/206328265-b7aa1e87-36de-4df8-9999-e37bba6d9284.jpeg)
c.jpeg)
![WhatsApp Image 2022-12-07 at 7 25 31 PM](https://user-images.githubusercontent.com/120065874/206328253-b90f1d1b-e7bc-42a9-9d4e-aeb5f5d1173d.jpeg)

lack. Is there any way to correct this? I've spent many hours trying to solve it, I would really appreciate it

**Comment by johanmenac** [comment]
Hello, I am currently using the pcsx2 in the batocera, the image of the games appears stretched but I corrected it to 4/3 and it turned out great, the drawback is that there are white bars in the corners and the truth is that it looks very uncomfortable, the ideal is that those bars remain black. Is there any way to correct this? I've spent many hours trying to solve it, I would really appreciate it

![WhatsApp Image 2022-12-07 at 7 27 14 PM](https://user-images.githubusercontent.com/120065874/206328881-8c7da0cc-afea-4d49-bda8-479ef3ea5071.jpeg)

![WhatsApp Image 2022-12-07 at 7 25 31 PM](https://user-images.githubusercontent.com/120065874/206328896-e5d576ee-e83b-4525-8044-befb8e4a9e6a.jpeg)

![WhatsApp Image 2022-12-07 at 7 26 31 PM](https://user-images.githubusercontent.com/120065874/206328908-f88b4984-9ff5-4971-bc96-271bdde6823c.jpeg)

**Comment by stenzek** [comment]
This is the PCSX2 issue tracker, not batocera, please report such issues to them.

**Comment by johanmenac** [comment]
> 

Do you know of any solution to this problem? I see you already commented on this

**Comment by RedDevilus** [comment]
> > 
> 
> Do you know of any solution to this problem? I see you already commented on this

You can notify batocera maintainers and let them fix it or don't use batocera. Either way WX is on the fast-track to become deprecated and be fully replaced by Qt.

**Comment by johanmenac** [comment]
> > > 
> > 
> > 
> > Do you know of any solution to this problem? I see you already commented on this
> 
> You can notify batocera maintainers and let them fix it or don't use batocera. Either way WX is on the fast-track to become deprecated and be fully replaced by Qt.

Your answer does not help me, I will wait for another answer from a good server of this page, thanks

**Comment by stenzek** [comment]
Locking as discussion is unrelated to PCSX2.
