### ISSUE TITLE
[BUG] Final Fantasy X random enc graphics

### ISSUE THREAD

**Issue by Jakey757** [PCSX2/pcsx2#4309]
**Describe the bug**
A small box/hollow rectangle shows up on the random encounter animation.

**To Reproduce**
Set rendering mode to software or either hardware mode with no CRC hacks enabled. Enter any non scripted random encounter and watch the top left of the screen.

**Expected behavior**
This artifact/corruption shouldnt be there. It doesn't exist if you use at least the minimum CRC settings in the GS for DX11 and OGL.

**GS Settings**
CRC hack level set to none in DX11 and OGL, or any software mode settings.

**Emulation Settings**
Tested default and with speed hacks disabled

**GS Window Screenshots**
![image](https://user-images.githubusercontent.com/49990481/111858727-927c4880-8911-11eb-8f65-418fd3e24b6a.png)

**System Info**
PCSX2 1.7.0 dev 1083
Windows 10
i7 4790
AMD RX 570

**Comment by tadanokojin** [comment]
We have a hack for it which is why it doesn't show in CRC none. Bit odd that it's an issue in sw mode though. Did you try with auto flush?

**Comment by Lolibox** [comment]
yes i've tried auto flush on and off for software it still shows up

**Comment by tadanokojin** [comment]
okay, can you upload s gs dump?

**Comment by Lolibox** [comment]
https://drive.google.com/file/d/1K6XoOQUlNZcaEZq4rEzHet0PHSbDHByR/view?usp=sharing

**Comment by lightningterror** [comment]
> We have a hack for it which is why it doesn't show in CRC minimum. Bit odd that it's an issue in sw mode though. Did you try with auto flush?

Do we know if it's a GS or core issue? If it's core then that hack shouldn't be there.

**Comment by RedDevilus** [comment]
[FFX-RandomEncounter.zip](https://github.com/PCSX2/pcsx2/files/7585213/FFX-RandomEncounter.zip)
Issue in SW:
![gs_20211123013146](https://user-images.githubusercontent.com/24227051/142955116-d690e235-689c-41c0-9252-40e373778d80.png)
It's patched with CRC hack level for HW:
![gs_20211123013058](https://user-images.githubusercontent.com/24227051/142955148-820ff6da-c3ec-4f5f-95ef-d88158854a1c.png)
Without CRC hack on HW:
![gs_20211123013013](https://user-images.githubusercontent.com/24227051/142955170-e14e4840-ddde-4f62-8957-c790e7a1517f.png)

**Comment by refractionpcsx2** [comment]
Should probably update this.

Okay so the problem here, is how our swizzling works and how it deals with offsets when reading/writing memory.  The big problem here is the game uploads image information (or depth information, I forget), butted right up against what you see on the screen, but its done so with a block offset inside the page, and our swizzling handling is designed to take a page boundary and work it out from there, so it kinda ends up pointing to the wrong place.

TellowKrinkle is looking in to how to deal with this I believe, then we can squash another bug which has lasted the life of the emulator :)
