### ISSUE TITLE
Suggestion: Git tags

### ISSUE THREAD

**Issue by micove** [PCSX2/pcsx2#431]
In trying to upload PCSX2 to Debian an interesting issue was pointed out. When doing
```
$git describe --tags
v1.2.1-861-g079ed2c
```
and using this for versioning as indirectly done in
```
http://buildbot.orphis.net/pcsx2/
```
may confuse some people since the last release is 1.2.2 while PCSX2 says 1.3.0.

It seems that when converting svn to git the 1.2.x branch was created at tag v1.2.1 instead of branching at tag v1.2 which is part of the issue but not really the main cause. Creating a tag v1.3.0 in the following commit after branching would solve this issue. Ideally it would have been this commit:
https://github.com/PCSX2/pcsx2/commit/1fb3d7dd172ae40576516adfea88993dcd8f9602

but since tag v1.2.1 was created after that commit then it's too late for that ( we want to avoid renaming/deleting tags) but doing this in the future would be cleaner.

Doing
```
$ git tag -a v1.3.0 b8f8459 -m "Start development for v1.3.0 after v1.2.1 was branched."
```
would be the cleaner workaround. It just uses the commit after branching/tag:v1.2.1 (we don't want to tag v1.2.1 twice)
and results in
```
$ git describe --tags
v1.3.0-860-g079ed2c
```
instead of 
```
$git describe --tags
v1.2.1-861-g079ed2c
```

The short version of the suggestion is to use an annotated tag whenever the version number in pcsx2/SysForwardDefs.h gets bumped. This ideally is  done as the last commit before a release or when switching to the odd numbered unstable branch which is usually the commit after the stable release. Since github automatically adds tags to the release page then marking the unstable tags as pre-release software (this is done in the github webpage not in git) fixes that although they ideally only contain a version number change when compared to the stable branch. Also branching when the stable PCSX2_VersionLo = 0 (tag v1.X.0) also helps.

This is only a suggestion since this could be solved by manually manipulating the version number on my end so this could easily be tagged "won't fix" and closed down since it just tries to standardize the release procedure from subversion to git.

**Comment by avih** [comment]
> The short version of the suggestion is to use an annotated tag whenever the version number in pcsx2/SysForwardDefs.h gets bumped.

True for the future, but we haven't done it for 1.3.0 and and now we need to think how to handle it.

I don't like the suggestion to add the 1.3.0 tag to the "correct" place, since it could confuse people who download from the build bot.

What I thought is just to add a new tag 1.3.1 for HEAD, and note that it's 100% superficial just to let the build bot start from 0 with a version which wouldn't confuse users with overlapping of already-built "1.2.1" builds.

But so far it hasn't happened.

**Comment by micove** [comment]
Sure a v1.3.1 tag is also fine and just requires a commit with only bumping PCSX2_VersionLo to 1.

**Comment by micove** [comment]
Alternatively the HEAD could be tagged as v1.3.0 and no code changes would be required. This avoids the theoretical question of "what happened to v1.3.0?" since it got skipped.

**Comment by avih** [comment]
The problem with tagging HEAD as 1.3.0 is that there are already many builds out there (from the build bot) which show up as 1.3.0 when you run them, so this would create confusion IMO when new 1.3.0 builds show up with new numbering.

And, you're right to guess that the reason we haven't yet tagged HEAD as 1.3.1 is that it could create some unwanted endless stream of questions from users about what changed since 1.3.0, and this is also the reason I added that it should be noted that 1.3.1 is a 100% superficial tag just to align the build bot numbering.

We'll probably get to that at some stage.

**Comment by bositman** [comment]
I think we should go with HEAD as 1.3.1. People have matured since the old days and a simple explanation will probably be enough for everyone. I think we should do it ASAP since the longer we leave it as is the worst confusion there will be

**Comment by avih** [comment]
267ff7d196df1b4009f576cc76307d57abe843d5 - updated the pcsx2 version to 1.3.1 and added a new tag `v1.3.1`. Hopefully the next buildbot version will reflect it. If it does, then we should close this bug.

**Comment by avih** [comment]
The buildbot shows v1.3.1, but without `-0` and without the git changeset. I pushed another dummy commit to see if it straightens out with non-zero numbers of commits after the tag.

**Comment by avih** [comment]
Looks great. Now http://buildbot.orphis.net/pcsx2/ shows: v1.3.1-1-gdacadcd and when executing PCSX2 it also shows 1.3.1 at the main titlebar.
