### ISSUE TITLE
[Feature Request] UserHacks in GameIndex.yaml

### ISSUE THREAD

**Issue by tony971** [PCSX2/pcsx2#4374]
**Description**
Some games require specific user hacks to function correctly. These settings shouldn't be used universally, but defaulting on for games that need it would be very helpful.

**Reason**
Game runs correctly by default vs running incorrectly, checking the wiki, enabling a hack manually, and disabling manually when switching to a different game.

**Examples**
Harry Potter and the Chamber of Secrets requires Framebuffer Conversion hack to avoid this garbage:
![Screenshot (5)](https://user-images.githubusercontent.com/7101253/115154762-58e24e80-a031-11eb-89ee-1b375a7d0025.png)

**Comment by RedDevilus** [comment]
It would be better to have this idea as Per-game configuration in a gamelist like other emulators do instead of bloating the Gameindex.yaml

**Comment by lightningterror** [comment]
Frame buffer conversion isn't a good solution btw, it would be better to fix the edge case and get rid of the hack completely.

**Comment by tony971** [comment]
> It would be better to have this idea as Per-game configuration in a gamelist like other emulators do instead of bloating the Gameindex.yaml

Agreed. Things like MTVU could be disabled on a per-game basis as well.

> Frame buffer conversion isn't a good solution btw, it would be better to fix the edge case and get rid of the hack completely.

It would be better if all hacks were made irrelevant, yes. But there will be years before this is realized.

**Comment by RedDevilus** [comment]
I have actually tried to do MTVU as an option in the GameIndex, however in the development builds 1.7 only 2 games that we know of (Transformers + a demo game) is broken with it compared to the dozen of the stable version due to this PR:
https://github.com/PCSX2/pcsx2/pull/4035
 So there is no point anymore to include it there.

**Comment by tony971** [comment]
Yes, but having it as a per-game configuration for Transformers and possibly the Sly Cooper series would allow removing the option from the GUI entirely.

**Comment by RedDevilus** [comment]
Why would we remove a valuable option from the GUI? The same could be said about the other manual game fixes as well then. I disagree with that statement.

**Comment by tadanokojin** [comment]
Framebuffer conversion is slower than piss. Enabling it by default on a per-game basis would make the game run poorly on many people's machines who may prefer to find other ways to deal with the issue. It's not PCSX2's job to decide which per-game graphical hacks should be enabled in order to address the problem and that's why those hacks are exposed to the user so they can make their own educated decision. Regulating that to a bunch of developers to decide for them is just going to result in flame wars over which option gives the better result, something that is going to be, at the end of the day, a value judgement. That's just the obvious "enable this and get rid of garbage" hacks. Many of these hacks cause as many problems as they fix making deciding then to or not to use them a crap shoot.

If you want PCSX2 to provide functionality that will allow users to configure these things and for PCSX2 to remember them on a per-game basis (game list) then I'm more supportive of that idea. But as for the idea of automatic graphical hacks I'm strictly opposed. While I support the idea of making the emulator easier to use you can't simply hide away the underlying complexity of emulating the GS on the hardware renderers.

**Comment by Josegg0** [comment]
If you really need to have per-game config.ini folders, you can use –cfgpath=inis\Name
https://forums.pcsx2.net/Thread-Per-Game-Config-Settings?pid=532185#pid532185
Also you can use a frontend like Playnite for a semi-automated process.
"{ImagePath}" --cfgpath="inis\{ImageNameNoExt}"

**Comment by RedDevilus** [comment]
There is also PCSX2 specific frontends like PCSX2Bonus, Spectabis.
Or general like  Launchbox, GOG Galaxy, etc . Enough 3rd party choices.
