### ISSUE TITLE
[Feature Request] Unlock "Enable fast CDVD"

### ISSUE THREAD

**Issue by Anuskuss** [PCSX2/pcsx2#4465]
**Description**
*Enable fast CDVD* is locked when using any preset.

**Reason**
I would like to use the *Balanced* preset **and** have fast loading times. Locking the field is pointless since no preset even touches that setting, so it should be unlocked but defaulting to off.

**Comment by F0bes** [comment]
Having preset 1/2 or even 3 with fast cdvd kind of defeats the purpose of a preset. 
Fast cdvd is a hack and can create timing issues.
I believe it's best not to guarantee any safety with that hack by unlocking it. 
The only reason why MTVU is unlocked is due to the few (and now almost none!) problematic games being _known and documented_.

My 0.5 cents.

**Comment by Anuskuss** [comment]
> I believe it's best not to guarantee any safety with that hack by unlocking it.

Yeah okay, but it should definitely be unlocked atleast after *Safe* (and even enabled for *Mostly Harmful*) because using presets shouldn't mean forgoing faster loading times.

**Comment by seta-san** [comment]
fastcdvd is more of a timing hack or gamefix than an actual speed hack.

**Comment by lightningterror** [comment]
Closing, reasons stated by F0bes.
