### ISSUE TITLE
[Customizable hotkeys] A menu where we can personalize the shortcuts on the fly

### ISSUE THREAD

**Issue by Shideravan** [PCSX2/pcsx2#4514]
**Description**
It would be great to be able to customize the various emulator hotkeys for a keyboard/controller key (or button/key combinations).

**Reason**
It's nice to personalize the shortcuts on the fly for user preferences. I personally like, as an example to bind the fast forward button as a controller button, to skip the loadings without even need to stand up from the chair. But it can also can be used for savestate save/load, activate/deactivate cheats, press a key to slowdown in certain points, etc.

**Examples**
This is the duckstation hotkey settings as an example. Most of modern emulators has a similar feature.
![image](https://user-images.githubusercontent.com/12163923/124424832-13831280-dd3e-11eb-8838-d0883cbe10ce.png)

**Comment by OCRBonk** [comment]
I agree with this. In particular, I wish I could set a hotkey toggle to switch on and off certain emulator settings. For example. MTVU or Instant VU. For a specific use case with Xenosaga EP1 where when playing with `EnableVsyncWindowFlag=True`. And forcing OGL FSE Vsync through drivers while using Instant or MTVU will cause slowdowns under 60FPS during cutscenes. But disabling either will run at full speed. On the contrary, during gameplay without Instant or MTVU the game can dip under 60FPS, but with them enabled. Never. Without Vsync the game with either option never dips under 100FPS on my 3600XT. But then frame pacing goes out the window.  (Since the borderless display mode PCSX2 uses doesn't support Multi Plane Overlay).
Having a hotkey would make this a painless thing to switch while playing.

**Comment by Shideravan** [comment]
Qt version developed by @stenzek already has customizable hotkeys support. When the Qt version becomes official in the regular builds, we can close this issue :)
Thanks for the feature @stenzek

**Comment by lightningterror** [comment]
Done on Qt, won't be done on wx.
