### ISSUE TITLE
[BUG] This is Football 2005: EE JIT issue at boot.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4543]
**Describe the bug**
When starting the game "This is Football 2005" the console will throw a EE issue following by a delay slot log when the EE is set to JIT.

![image](https://user-images.githubusercontent.com/26351275/125499746-28098192-a269-4b8f-8ad6-fa5ae8c6b3fe.png)

Note: The issue doesn't happen with the interpreter.

**To Reproduce**
Boot This is Football 2005 with the ee jit.

**Expected behavior**
The console shouldn't print that.

**System Info (please complete the following information):**
PCSX2 Revision: v1.7.0-dev-1458-g14be2649c
OS: Windows 10
CPU: I9 9900k
GPU: RTX 3070

**Logs and Dumps**
https://drive.google.com/file/d/1UiTBijTouvNRyzhC5gN3S38duHR3xsxN/view?usp=sharing

**Comment by kozarovv** [comment]
Similar bug happen in Dirge of Cerberus: FF7 title screen. Same like with TIF2005, interpreter is fine. 

`EE: Unrecognized op 1`
`Branch 53554c53 in delay slot!`

Seems to be some data, `SLUS` in LE ASCII, tif 2005 have `SCUS` in LE ASCII instead.

**Comment by Mrlinkwii** [comment]
still an issue as of v1.7.3589 , running the game  gives this  info a bit more 

[  921.4330] FMV ended
[  921.4357] Unknown R5900 SPECIAL: 00000001
[  921.4357] EE: Unrecognized op 1
[  921.4358] Branch 53454353 in delay slot!
[  921.4531] Set GS CRTC configuration. PAL  640x512 @ 50.000 (49.76) Interlaced (FIELD)

**Comment by Goatman13** [comment]
During movie playback EU version of game is running thread at 0x2F9878. At the end jr ra points to 0x1001D8 which is ExitThread syscall. This syscall won't return to 0x1001DC, because EPC changes so eret points to 0x4F15D8 in the end.
This shouldn't be issue in general, but pcsx2 recompile what it finds after syscall at 0x1001D8. Here game developer placed some small chunk of data like argc and argv.

![a](https://user-images.githubusercontent.com/101417270/210221529-662d9df9-1963-41a3-a3a3-3a4618ff2f43.jpg)

This accidentally gets recompiled, but never run as a code. I don't know what real issue in recompiler is, but it seems that block just don't end at syscall, and is going further till next branch. This branch is obviously data that is placed there, not real code.

![b](https://user-images.githubusercontent.com/101417270/210221669-62ea287f-f7e9-4348-bd78-da0dbbdfd7f0.png)

Since code never run this isn't critical issue, but still it's unneeded recompilation of junk data. Maybe it's worth to break block on syscall or something? At the second hand this is corner case that don't even affect how game work, and ending block on every syscall can degrade performance.
