### ISSUE TITLE
[Feature Request] ui  Overhaul

### ISSUE THREAD

**Issue by Yoshi9800** [PCSX2/pcsx2#4549]
**Description**
Because pcsx2 ui looks bad so should ui that looks like 

**Reason**
Because pcsx2 needs able staff like per game configuration 
Make ui look.
Add ps2 boxact per game configuration.
I don't miss 3rd party software per game configuration 

**Examples**
The new ui should look  Spectabis and do staff per game configuration and ps2 boxact in Good look ui.

**Comment by tadanokojin** [comment]
Request title and description are too vague and subjective to have any meaning.

Your real request in under "reason" and sounds like "per-game configuration" and I think (?) you're trying to say "box art".

With regards to per-game config, there are plans to add but it's not happening in the immediate future.
With regards to box art, no idea of the legality of that as I'm not a lawyer but I think as long as we're not providing it automatically it's fine.

You'll also find that if you leave off the vague and unproductive stuff like "UI looks bad" or whatever your issues will be more likely to be taken seriously. We're not here to decipher what you mean when you're shit-talking an application that many people put a ton of hard work into and we're less likely to care what you want when you do that. If instead you had been like "I like this aspect of this an that UI better" or "I like this design language better" with examples we might be more receptive to that.

We provide this application for free for people to use. If you don't like it instead of coming to our github to insult our work, just don't use it. No one is here to entertain you being unproductive and rude.

**Comment by Squall-Leonhart** [comment]
i can't believe they joined github just to post this.
