### ISSUE TITLE
Porting to 32-bit FreeBSD

### ISSUE THREAD

**Issue by uyjulian** [PCSX2/pcsx2#472]
I got another computer and set up Linux/FreeBSD dual boot.
I might try this, simply because it's POSIX and I have a lot of free time on my hands :-P

**Comment by gregory38** [comment]
Please synchronize with the MAC port. I'm sure most of the changes are the same.

I also suggest to fix clang build

**Comment by uyjulian** [comment]
@juhalaukkanen 's fork or @aktau 's fork?

**Comment by gregory38** [comment]
Well I suggest to contact them and see with them. I think the first fork might be better for you.

**Comment by juhalaukkanen** [comment]
Well the one I have worked quite recently includes @aktau 's changes. I think it is quite complete but I wasn't able to fix mmap issue. Core builds, plugins at good level like GSdx with SDL2 OpenGL support, etc...

However on OSX I get pagefaults during runtime since I haven't found the core issue within LnxHostSys.cpp.

https://github.com/juhalaukkanen/pcsx2/commits/master

**Comment by gregory38** [comment]
```
However on OSX I get pagefaults during runtime since I haven't found the core issue within LnxHostSys.cpp.
```
You mean segmentation fault, isn't it. It could be the expected behavior. It must call this handler: SysPageFaultSignalFilter

It must execute this kind of code and return. Maybe you can execute the code step by step.
```
Source_PageFault->Dispatch( PageFaultInfo( (uptr)siginfo->si_addr & ~m_pagemask ) );
// resumes execution right where we left off (re-executes instruction that
// caused the SIGSEGV).
if (Source_PageFault->WasHandled()) return;
```

**Comment by uyjulian** [comment]
Okay, I'll base my branch off of @juhalaukkanen 's work. Thanks for the tip!
