### ISSUE TITLE
Question - Fit To Window/Screen?

### ISSUE THREAD

**Issue by meuwe** [PCSX2/pcsx2#475]
In Linux on a 17" 1920x1080 gaming laptop, I noticed when I pick the  Fit To Window/Screen, I was assuming this was going to fill the entire screen, and if I wanted the wide screen look with the black borders on top and bottom, then the 16:9 would give this look.

Is Fit To Window/Screen suppose to fill the entire screen on a wide screen monitor, without any borders?

Fit To Window/Screen and 16:9, both options looks exactly the same. hmm

thank you

**Comment by avih** [comment]
> Is Fit To Window/Screen suppose to fill the entire screen on a wide screen monitor, without any borders?
> Fit To Window/Screen and 16:9, both options looks exactly the same. hmm

It's supposed to fill the entire window with the image that the emulation produces without enforcing any specific aspect ratio.

Since your monitor has aspect ratio of 16:9, when in full screen - fit to screen is identical to 16:9. If your monitor was 4:3, then fit to screen would have been identical to 4:3, etc. It just stretches the image such that it fits the window at whatever aspect ratio it is, and at full screen the window covers the entire screen.

To understand better what 16:9/4:3/fit-to-screen does, don't use full screen, and then resize the window into arbitrary aspect ratios in each of those modes.

Next time please post questions to the forum. Thanks.

**Comment by meuwe** [comment]
Hi avih, sorry I didn't know there was a forum, I just use GitHub is all.

In window mode it just does the same thing, it doesn't fill the entire window.

You say it's suppose to fill the entire window without forcing any specific aspect ratio, I hope this is something that can be worked on then.

thank you

**Comment by avih** [comment]
I'm not sure I understand what 's the issue.

Could you please attach a screenshot of how it looks, and then describe in words how you think it should look instead? (and also mention if you're in fit-to-screen mode or not)

**Comment by avih** [comment]
If your issue is that you see black borders also in fit-to-screen mode, it might mean that the game itself adds them (e.g. sometimes when playing FMV). Please also test another game and make sure you start playing the game.

Also, does changing the mode between 4:3 / 16:9 / fit-to-window does anything at all?

**Comment by meuwe** [comment]
I have it working...

thank you

**Comment by AnixGroup** [comment]
for those of you still looking for the solution, it depends what you are looking for. If you alter the 'resizable' property under the "MainWindow" object-class in the pcsxr/pcsxr.ui file, you can alter the size of the main window.  If you go to the monitor icon in the main window toolbar, you can change the in-game settings for the window size and plugins and such.
