### ISSUE TITLE
[BUG]: Sega Ages - Virtual On, Health-bar rendering issue.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#4826]
### Describe the Bug

In the game "Sega Ages - Virtual On", the health-bar is rendered in black while they should have colors.

None of the existing hacks/settings can fix the problem.

Note: Dobiestation displays the health-bar fine.

### Reproduction Steps

Load any level in the game "Sega Ages - Virtual On".

### Expected Behavior

The health-bar should colors like on real hardware.

### PCSX2 Revision

v1.7.0-dev-1789-gb8eb18836f

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

### GS Window Screenshots

The bug in action:

PCSX2:

![image](https://user-images.githubusercontent.com/90222976/134776489-bc5d1b03-4bdd-4f5e-a4f0-adf06fae8433.png)

Dobiestation:

![image](https://user-images.githubusercontent.com/90222976/134776497-9f496a5d-5922-44bc-b6a9-7497dfba20a2.png)

### Logs & Dumps

Blockdump + savestate: https://drive.google.com/file/d/1z8odfLqaa3-elMdVvMWo8ZkHFcYElOqf/view?usp=sharing

**Comment by refractionpcsx2** [comment]
Initial investigation, the problem is the CLUT isn't invalidating correctly, so it's reporting that it isn't dirty and refreshing itself.  I'm not entirely sure where it's getting overwritten right now though.

I can make it right by forcing an invalidation when writing to a frame buffer as seen below, though this is heavy handed, it usually checks the memory pointer (though It seems to be comparing the non-multiplied to the multiplied which is a bit weird).  So yeah, CLUT invalidation issue, not sure where or why right now..

![image](https://user-images.githubusercontent.com/6278726/134779563-ea0c1e1d-73e1-472c-9188-f034302d755c.png)

**Comment by refractionpcsx2** [comment]
The invalidation stuff is all a bit beyond me :P So I'll let Kojin investigate the rest.
