### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [PCSX2/pcsx2#494]
I would like to point out that identifiers like "[`__CACHE_H__`](https://github.com/PCSX2/pcsx2/blob/dde94adec321c54d2b6bb875e06223b20c1d39e1/pcsx2/Cache.h#L16)" and "[`__SPR_H__`](https://github.com/PCSX2/pcsx2/blob/3271048ab6c73708dda7b6919f595ea6786fc200/pcsx2/SPR.h#L17)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by avih** [comment]
While I don't disagree that compliant or more standard formats of code are better, unless this applies only to the two cases you mentioned, I think it's preferable to avoid mass changes of files without it actually fixing anything, since it makes tracking changes harder.

See also e.g. https://groups.google.com/forum/#!msg/wx-dev/XIZE9TPzJ-s/cOaq9VOcOIYJ

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by avih** [comment]
It's declared as undefined behavior only because the platform *may* define itself such identifiers. I haven't noticed bad behavior due to this, and apparently other big projects haven't either.

- If you _know_ it makes something behave incorrectly, then by all means do submit a PR to fix it.
- If it's only these two include guards regardless if you know or don't know that it breaks something, then submit a PR and I'll merge it.

Otherwise, please state the scope of the changes you want to submit. In other words, how many files are affected by this?

**Comment by gregory38** [comment]
A quick & dirty  grep of  "_H__" seems to imply hundred of files. If someone want to change it, I would suggest to use the "#pragma once" macro

gr "_H__" pcsx2 -l | wc -l
36
gr "_H__" common -l | wc -l 
14
gr "_H__" plugins/ -l | wc -l
88

**Comment by avih** [comment]
I'd prefer not to change it then. Modifying hundreds of files for something which is unlikely to fix anything but quite likely to make looking through change history harder does not sound like fun to me.
