### ISSUE TITLE
Final Fantasy 10 Text is corrupted at higher internal resolutions.

### ISSUE THREAD

**Issue by cexikitin** [PCSX2/pcsx2#500]
With the latest commits by @gregory38 the text has really been cleaned up but there is still a bit of corruption.

UserHacks_round_sprite_offset = 2
http://i.imgur.com/8rGnLtM.png
UserHacks_round_sprite_offset = 1
http://i.imgur.com/O9e0xyx.png
UserHacks_round_sprite_offset = 0
http://i.imgur.com/DRXUncO.png

**Comment by cexikitin** [comment]
Here is what it looks like at native res:

http://i.imgur.com/jn8FvZU.png

**Comment by gregory38** [comment]
Check latest git. With a hell of luck it might be better. Otherwise please send me a gs dump.

Shift + F8 on the bad screen
File will be generated in snaps (feel free to rename the gs file ;) )

**Comment by cexikitin** [comment]
http://hiberniagaming.net/snaps.rar

Guess this is akin to dolphins, FIFO log.
Wasn't sure if you wanted it set to either 2 or 0 so I got both.

I got you two different screens + first menu running at 2x as well as third gs running at a custom internal resolution of 1024x1024 which is interesting as 2-6 all have the same level of corruption, yet 1024x1024 has same amount of corruption as previous revisions or mode1

**Comment by gregory38** [comment]
Actually gs options don't have any inpact on the dump. The dump registers gs input so I can replay any step of gsdx with any options/configurations (no dx on my linux box).

**Comment by gregory38** [comment]
I need to debug further but some issue won't be fixable easily. My hack only correct the projection of texture in quad. However FFX10 uses 2 triangles to draw a quad. It would be costly to detect this kind of situation.

Anyway I need to check the rendering of text

**Comment by ramapcsx2** [comment]
From memory, this is one of the hardest tests to get right when upscaled.
Definitely worth it to have a GS dump of this ;)

**Comment by gregory38** [comment]
The thing is that upscaling is right. It works at native resolutions because of aliasing of initial textures/primitives. Any method that have an anti-aliasing (msaa, upscaling) effect at texture sampling level (aka not fxaa) will break it.

The UserHacks_round_sprite_offset updates the geometry to reduce a bit the initial aliasing (move & stretch texture) for 2D sprites. It works nicely for flat sprite (hack = 1). It is completely broken for bilinear sprite (hack =2). I'm currently searching an acceptable solution that will improve a bit the situation without breaking everything :)

If we did a manual interpolation in the fragment shader, we could "unscale" some primitives (including triangles unlike my hack). This way, users can choose between full upscale (more AA but more glitches) to partial upscale (less AA but less glitches).

**Comment by gregory38** [comment]
I'm closing this issue, because I don't think there is any way to improve it further.
