### ISSUE TITLE
[BUG]: PCSX2 not applying CRC Hack Level on startup

### ISSUE THREAD

**Issue by DrMasquerade** [PCSX2/pcsx2#5005]
### Describe the Bug

When you boot PCSX2 and a game, the CRC Hack Level doesn't apply until you go back into graphics settings and apply it (even if it was already set to the proper level by default, you still have to apply it on start up).

### Reproduction Steps

Go to the first level on Crash Bandicoot Wrath of Cortex with OpenGL and whatever CRC Hack Level and it will produce horizontal lines, when applying an automatic or aggresive hack level it will go away. But you have to apply it every time you start PCSX2

### Expected Behavior

It should just apply the setting automatically like every other setting in PCSX2

### PCSX2 Revision

nightly-v1.7.2031

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 3600

### GPU

GTX 1080

### GS Settings

![2021-11-10 16_47_49-Graphics Settings](https://user-images.githubusercontent.com/43123409/141198890-18652276-b08a-4355-a69b-0b4735f703bb.png)

**Comment by dio-gh** [comment]
While I cannot really confirm this due to my CRC not being in the database, I have found that the game requires `Frame Buffer Conversion` and `Preload Frame Data`.

The former pushes back the fog, making it look like in SW mode:
![image](https://user-images.githubusercontent.com/10439488/166123860-693d0dce-2dff-42e3-b9b4-56b41fdb3d6e.png)
![image](https://user-images.githubusercontent.com/10439488/166123879-45920eba-1d8d-48af-8d99-72176c95e2f8.png)

The latter fixing a weird line glitch, making it look like in SW mode:
![image](https://user-images.githubusercontent.com/10439488/166123928-ec9d6c8a-13f3-45a0-86c4-c08c75d3674c.png)
![image](https://user-images.githubusercontent.com/10439488/166123949-87d462d8-3535-4c36-aaca-482b5b728107.png)

It's a bit difficult to see, but quick swap between the images and it's easy to notice that way. Do note that `Preload Frame Data` may be expensive while upscaling.

**Comment by dio-gh** [comment]
Cannot repro, the CRC hack applies fine for me as intended (using #5990).

**Comment by Mrlinkwii** [comment]
is this still an issue on master ?

**Comment by refractionpcsx2** [comment]
No response for 6 months, assuming it's fine, we can reopen if it crops up again.

**Comment by Ghost-Frank-Woods** [comment]
Hello, I encountered this graphic problem while playing the game and I make any changes in the settings. The problem of multiple lines or broken image is not solved. Please take care of it.
![Uploading thpture.PNG…]()

**Comment by Mrlinkwii** [comment]
@Ghost-Frank-Woods please  join the forum/discord for support
