### ISSUE TITLE
[Feature Request] Debugger: Conditions for memory breakpoints.

### ISSUE THREAD

**Issue by Scorpeg** [PCSX2/pcsx2#512]
Please, could anyone (Kingcom?) add possibility to do a conditional breakpoint if some memory value = X. So add some command like MB(0x8000000)/MW(0x8000000)/MH(0x8000000) [means memory_byte, memory_word, memory_halfword]. So to be able to stop when some value in some memory = some known value. It is very important feature for any debugger, by me. And remove restriction to be able to put conditional breakpoint only for execution - as again would be nice to break on write to some memory if in some register there is some known value or some other memory value = X, when write to other memory field.

**Comment by mirh** [comment]
#1172?
And if not, anyway, edit the title more specifically.

**Comment by Aced14** [comment]
@mirh #1172 resolved a breakpoint bug I reported in #1161.

This issue is requesting two new debugger features:

1. Support for "fake" registers that map to live memory addresses, for use in breakpoint conditions. They'd be formatted as ``mb(0x80000000)``, ``mh(0x80000000)`` or ``mw(0x80000000)``. The first part would indicate that it represents memory and identify its width (byte, half or word). The part in parentheses would contain the memory address itself.
2. Support for conditions on memory breakpoints. This would allow a breakpoint to be triggered on a given address if certain registers and/or other memory addresses meet specific conditions.

@Scorpeg To bring any issues/comments you post to the attention of specific users, I'd recommend @mentioning them. I'll mention a few debugger contributors in this post (in case any are interested): @Kingcom @NZJenkins @turtleli @mogaika.

**Comment by mogaika** [comment]
1. I right understand what you are talking about the possibility of getting memory values in the condition of a breakpoint? (where there fake registers)
Where is diff with current ```1,[0x80000000]!=0```,```2,[0x80000000]!=0```,```4,[0x80000000]!=0```?

**Comment by Kingcom** [comment]
To be precise, you can read memory using ```[address,size]```. Size is optional and defaults to 4, so ```[address]``` is equivalent to ```[address,4]```. You can use this in all expression and therefore also in breakpoint conditions. address can itself also be an expression, ie. ```[[r2]+20h,2]```.
Conditions for memory breakpoints would probably be manageable, it shouldn't cause extra overhead either if it's checked after the breakpoint was found to trigger.
