### ISSUE TITLE
[BUG] [DEV9] Star Ocean 3 never detects DEV9 HDD properly

### ISSUE THREAD

**Issue by knight-ryu12** [PCSX2/pcsx2#5159]
### Describe the Bug

Seems Star Ocean 3 V1.1(?) will never detects HDD presense, BIOS will detect it's there, but.

This is particularly nasty thing that no log is being made.

### Reproduction Steps

1. attach the HDD in DEV9 menu.

### Expected Behavior

Install menu will not gray out; Selectable.

### PCSX2 Revision

v1.7.2126

### Operating System

Windows 11

### CPU

i7-9750H

### GPU

GTX 1660Ti

**Comment by gilderoylockhart01** [comment]
Be carefull with star ocean 3 v1.1 as the vdvd changes to make it work were reverted, so the game will not work yet.

**Comment by TheLastRar** [comment]
Can you provide a log file

**Comment by TheLastRar** [comment]
After initial investigation, this is a CDVD issue

In master the game fails to load the DEV9.irx module which needed to access the HDD, with the log 
```
loadmodule: fname cdrom0:¥DEV9.IRX;1 args 0 arg 
open fail name ¥DEV9.IRX;1
loadmodule: id -203, ret 0
```

This is related to the audio stutter/hang reported here https://github.com/PCSX2/pcsx2/issues/4550
That issue (and also this issue) was fixed by https://github.com/PCSX2/pcsx2/pull/4881 but regressed after https://github.com/PCSX2/pcsx2/pull/4927
