### ISSUE TITLE
Can't boot from optical drive on Linux pcsx2

### ISSUE THREAD

**Issue by Furaihai** [PCSX2/pcsx2#519]
Running 1.3.1-0 on Linux Mint 17. Everything else works well but it did not come prepackaged with the Linuz CDVD or EFP CDVD plugins that come default with the windows install. I've looked pretty hard for the linux versions of those plugins and couldn't find anything but uncompiled source code. 
An advantage to being able to boot off the disc is that I play on both my desktop and my laptop (which both have linux installed). Being able to play off of the disc saves me the hassle of having to have one soft copy of each game I have saved on each computer. I do travel a lot so I'm frequently playing off of my laptop which has less hard disc capacity than my desktop. @gregory38 I heard you were the main Linux dev for pcsx2. Could you please add a feature to the linux version of pcsx2 allowing to boot off of optical media? Thanks!

**Comment by avih** [comment]
Out of curiosity, did you try without any plugin (enable the internal ISO reader by checking `iso` at the CDVD menu, then close pcsx2), then invoke `pcsx2 path/to/dvd_mount_point` ?

**Comment by Furaihai** [comment]
@avih I just tried that and i got errors. I can post screenshots if you want.

**Comment by avih** [comment]
Screenshot can't hurt, and emulog would help even more.

**Comment by Furaihai** [comment]
http://pastebin.com/kVhq9vq0

Attached is the emulog

**Comment by avih** [comment]
Just summarizing in case that paste disappears at some point, `CDVDiso Error: No filename specified.` is the only relevant message.

**Comment by gregory38** [comment]
Cdvd plugins on linux are in bad state. You can still build them with the --extra option of the build script.

**Comment by Furaihai** [comment]
@gregory38 Is the --extra option possible if I install from the PPA? I don't like building the code myself because I usually have dependency issues and don't like having to move the built software myself afterwards. Something like sudo apt-get install pcsx2 --extra?

**Comment by gregory38** [comment]
No. Do an image dump or find someone to improve the quality of a cdvd plugin.

**Comment by JMC47** [comment]
Not entirely sure why this was closed; the last time I used PCSX2 I attempted to load some games from my DVD drive in order to test them without hooking up my PS2 or wasting time attempting to make an ISO (my main box didn't have a DVD drive) and the games didn't work.  A long while later, I realized this was because PCSX2 on Linux can't read discs.

While I do understand if no one is using it, that you wouldn't put this as a high priority issue, but considering that it works on Windows, I do think it is an issue nonetheless.  Just my two cents, as I was looking for an issue on the matter.

**Comment by avih** [comment]
The CDVD plugin is distributed together with PCSX2, and should be considered part of it as far as users are concerned.

I think this bug should remain open even if currently no one has any plans to work on it.

**Comment by willkuer** [comment]
Actually it is not on my side. Neither the ppa nor the build.sh create a dvd plugin except for the null one. Or maybe I did something wrong.

Still it is probably better to collect feature requests as direct dvd access.

>  I attempted to load some games from my DVD drive in order to test them without hooking up my PS2 or wasting time attempting to make an ISO (my main box didn't have a DVD drive)

This doesn't make sense, or? Either you have a drive and can either play the disk directly or dump an image or you don't have one and are completely lost. In the second case you can even dump the bios on a different pc. So the internal iso loader is actually a safe fallback for most scenarios and it normally provides higher performance than direct disk access. There is probably a reason why nobody made a proper plugin so far. Possibly because it is highly recommended to use iso's,

**Comment by karasuhebi** [comment]
It makes sense to me. He has more than one computer and his main computer doesn't have an optical drive so he didn't want to waste time making ISO images in one of his other computers which do have optical drives. One would assume the other computers are not as fast as his main one.

**Comment by codestar12** [comment]
has there been any work on this?

**Comment by Mikaela** [comment]
I would also request reopening in case this causes https://github.com/flathub/net.pcsx2.PCSX2/issues/12, where I always see "No disc" in CDVD menu, while if I `ddrescue /dev/sr0 game.iso game.ddrescue` and select it as iso, everything works.

I am on Debian testing (10/Buster) and the Flatpak is on commit 3a7f2a5c0b12362feb958dfbb207f4a5a15d2dfe.
