### ISSUE TITLE
[BUG]: The Urbz: The Sims in the city: White artifacts problems with software render

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#5214]
### Describe the Bug

In the game "The Urbz, the Sims in the city", there is a problem where the ingame graphics does not display properly in the software render.

The whole screen is covered of a lot of weird white dots. Hardware is less bad, but there are still those kind of glitch in the edges of the screen.

### Reproduction Steps

Load the GSdump.

### Expected Behavior

The game should not have artifacts like on real hardware.

### PCSX2 Revision

v1.7.2164

### Operating System

Windows 11

### CPU

I9 9900K

### GPU

RTX 3070

### GS Window Screenshots

The bug in action:

Software render:
![Capture d’écran 2021-12-26 211155](https://user-images.githubusercontent.com/90222976/147419099-141528a0-e7bd-43e3-9138-bb7774c93dd6.png)

### Logs & Dumps

GSdump:
[The URBZ White flares issue.zip](https://github.com/PCSX2/pcsx2/files/7777519/The.URBZ.White.flares.issue.zip)

**Comment by coornio** [comment]
Extra testing done on this, for better reproduction steps.

This bug only appears when you boot the game with software rendering. It will not appear if you boot as hardware. The first instance where the bug appears is during the intro Maxis logo. Once triggered there, these "blur" spots will appear on the edge of the screen (while still in software rendering) during gameplay instances, such as the urbz creator and actual game. If you *then* switch to hardware rendering, the screen becomes polluted just like in the picture above.

The bug can't seemingly be reproduced in hardware rendering, even on native resolution. The game suffers from a bunch of upscaling issues as well, which require both the "Vertex" and "Texture" options of half-pixel offset hack simultaneously to look correct. No other issues observed otherwise. Prafull has received a blockdump of the SW maxis logo so I reckon we might have further updates soon.

**Comment by refractionpcsx2** [comment]
This was fixed in 1.7.2392 but nobody noticed.
