### ISSUE TITLE
[Feature Request]: Move afix check to medium blend level (currently in high)

### ISSUE THREAD

**Issue by nobleflame** [PCSX2/pcsx2#5242]
### Description

Recently, tellowkrinkle moved the afix check from full to high blending accuracy to fix #5193. This was merged into the current master.

This worked but in the case of MGS2 still produces slow down during some scenes. 

Would it be possible to move the afix check to medium blending accuracy as this produces little in the way of a performance hit but fixes the texture issues mentioned in #5193?

NOTE: please delete this if this is not possible. 

### Reason

Medium blending accuracy does not affect performance too much, but high does. The afix check fixes the textures issues in MGS2 but will still produce slow down in specific scenes if high blending accuracy is selected.

### Examples

In MGS2 (any version) 

Set blending accuracy to high.

Simply play the game up until any of the following moments

BIG SHELL - play up until you meet Peter Stillman - the following cutscenes will produce slow speeds where the game is unable to run beyond 70% speed.

**Comment by tellowkrinkle** [comment]
> Would it be possible to move the afix check to medium blending accuracy as this produces little in the way of a performance hit but fixes the texture issues mentioned in #5193?

Have you moved the check to medium and tested it for yourself?  The check isn't magic.  Moving it from full to high improved things because it stopped enabling sw blend for unrelated draws.  But unless the game *also* uses C == 1 draws, I'm going to guess the slowdown you're seeing is from enabling it for the draws that are fixing your problem, and moving it from high to medium will just make medium slow down in the exact same way.

If you haven't already, I'd recommend testing out the Vulkan PR.  It improves the performance of sw blend, especially on Nvidia cards, which might solve your issue.

**Comment by nobleflame** [comment]
Thanks for response. I’m not knowledgable enough to move the check myself, but I get what you’re saying about the draw causing the slow down. Although I will also add that the scenes that are improved by the check do not slow down, so I'm not so sure. 

I’ll give the Vulkan api a go and see if performance improves.

**Comment by nobleflame** [comment]
@Kobi-Blade what are you system specs and did you originally state that the solution on longer works?

**Comment by stenzek** [comment]
Software blending is slow on AMD due to it flushing/invalidating more than necessary with each barrier (firmware limitations apparently). Best you can do is use Vulkan and drop the resolution.

**Comment by stenzek** [comment]
> Seems you confused, I'm playing with Vulkan with Blending set to High as recommended on Original topic for this problem, if I use Software rendering there no issues whasoever besides the game running at native resolution.

No, I'm not. I'm talking about software **blending**, not software renderer. The higher the blending accuracy, the more draws will go through the sw blend path.

**Comment by stenzek** [comment]
If you know so much about the topic, why are you even talking here?

The barriers required for software blending prevent draws from overlapping on the GPU. Since overlapping primitives end up split to a single triangle per draw, this is very slow. This usually manifests as high GPU usage, but may not show up in all measuring tools. Using a lower resolution can help, but it's not a complete fix, the only real solution here is to use lower blending accuracy, lower resolution (to some extent, but the barriers still hurt), or buy an NVIDIA/Intel GPU.

**Comment by stenzek** [comment]
I provided an explanation for the low performance on your hardware, since as the person who wrote the implementation I have knowledge on the subject. As well as a solution, if you can't accept it, that's your problem.

**Comment by stenzek** [comment]
A few points that you're missing:
1. Software blending isn't used in all scenes. It's scene dependent, even camera angle/object dependent as to whether it's needed or not. That's why you can use higher blending levels in other parts of the game, and not see an issue.
2. I specifically said that lower resolution isn't a complete fix. The barriers/stalls still significantly reduce parallelism on the GPU, just slightly less so.
3. The only way to avoid the barriers is to turn blending to minimum (basic still engages in plenty of scenarios), disable texture barriers in advanced settings, or use Direct3D.

If you look at the GS statistics, you'll likely see a correlation between the number of barriers (B) and the performance drop. The only other thing which might be causing this sort of slowdown would be readbacks (RB).

> Which is why this topic was made in first place as well, to make the fix work on lower accuracy levels.

Emulators aren't magic. You can disagree all you like, but it doesn't change the facts. We wouldn't be using software blending/draw splitting/feedback loops if there was a faster way. Like I said, buy an Intel or NVIDIA GPU if you want better performance.

**Comment by stenzek** [comment]
Like I said, if you know so much about the topic, then please feel free to write an alternative/faster blending implementation, we'd sure appreciate it.

But otherwise, I'd suggest not trying to talk down to developers who work for free, it's not a good look.

**Comment by stenzek** [comment]
> You already made it clear you not supporting half of the computer base

The machine I use for PCSX2 development actually has an AMD GPU. I'm well aware of the limitations, we've reported it to AMD (and did not receive a response [1]), and I personally discussed it with one of the radv developers, who suggested that based on what I had said, it was indeed a hardware+firmware limitation.

We do the best with what we have. The Vulkan renderer I wrote is **leagues** ahead of OpenGL in performance on AMD, how is that "not supporting half of the computer base"? But the barriers still hurt, *because of hardware limitations*. You wanted a solution, I gave you one, use different hardware if blending performance is critical. Again, emulators are not magic, you can't just wave a wand and make things both fast and accurate.

Perhaps look in the mirror at your own behaviour before accusing others of being rude.

[1]:: https://community.amd.com/t5/opengl-vulkan/vulkan-poor-performance-due-to-barrier-region-bit-being-ignored/td-p/501962

**Comment by stenzek** [comment]
Good for you. Now please kindly stop spamming our repository with nonsense.

**Comment by nobleflame** [comment]
> Good for you. Now please kindly stop spamming our repository with nonsense.

This guy is being so goddamn rude, mate. I'd just like to say that you didn't need to provide the details you did in response to his ignorance.  

I'd also like to say, as a complete layman when it comes to software development, that you guys are doing brilliant job. MGS2 runs incredibly well on my PC so thank you for all of your work.

**Comment by RaduNastase** [comment]
Is there still any interest in moving the blending code for Ocelot/Fatman/Vamp correct skin, from high to medium (or even basic if possible) blending accuracy?

It would still be a great adition to the overall experience, as some scenes that do not necesarily need high blending (like Olga fight in Tanker) are noticeably slower in high blending, which one would have to set, in order to not be forced to switch between settings mid-game.

Thank you so very much for all you efforts!
