### ISSUE TITLE
It would be nice to have savestate and load savestate shortcuts

### ISSUE THREAD

**Issue by i30817** [PCSX2/pcsx2#538]
On the linux port, if it isn't the same on the windows port.

**Comment by karasuhebi** [comment]
F1 and F3 don't work on Linux?

**Comment by gregory38** [comment]
It must. Except if the shortcut is intercepted by the windows manager so it never hit PCSX2.
You can lock all event to PCSX2 with CTRL-SHIFT-F12 (again to leave PCSX2 window)

**Comment by i30817** [comment]
Hmmm, it seems like alt+tabbing between the pcsx2 application windows (main emulation, game view, log) makes the window manager very confused and the events start to go to the wrong window.

**Comment by gregory38** [comment]
```
(Also there is no in-game window feedback for save state, or the current selected savestate slot)
```
There is one with zzogl plugin. GSdx doesn't have any OSD. I have a branch for it but bug fixes have a higher priority.

Pad are directly polled from the linux driver state, it would work even on a different virtual desktop. The keyboard is much more complex.

Normally events are intercepted by PCSX2 main windows. Then they're sent to the plugin. In old-days, plugin uses to directy poll the event loop. I think the loop is still active even if I expect it to remain empty.

As a temporary solution don't alt-tab (just double click to reduce full screen)

**Comment by i30817** [comment]
It would be kinda nice to be able to savestate on a gamepad.

**Comment by karasuhebi** [comment]
This has been discussed before and I believe @Sarania is working on Lilypad to achieve just that. In the mean time, you should see if there's any Linux alternatives to JoyToKey.

**Comment by i30817** [comment]
Mmm, yes i'm actually currently using the keyboard exclusively, it was a hypothetical for the future ;)

**Comment by gregory38** [comment]
Honestly it is not difficult to implement. But I have a awfully loaded schedule.

**Comment by Sarania** [comment]
Yeah, I was working on that. I got stalled though because I can't figure out how to make a new tab in lilypad. Once I figure that out, shouldn't be too hard.

**Comment by Hirato** [comment]
Hmmm, it seems like alt+tabbing between the pcsx2 application windows (main emulation, game view, log) makes the window manager very confused and the events start to go to the wrong window (probably).

Not quite.
The window seems to have an event loop of sorts that handles all keys, and when it receives a down/pressed event for 'ALT' it sets a variable to handle all other events as though they have alt-pressed (I'm assuming).
Then you tab out, and let go of the key, the window due to having lost focus never gets the up/release for the 'ALT' key, so it still thinks that the alt-key is pressed, even though it isn't.

So after you focus the window again and press F1/F3 or any other key, it handles it as ALT+F1, or ALT+F3, etc.
To make it go back to normal, you only need to tap the alt key.
Same goes for any other key you were holding whilst the window lost focus - also note that the left/right keys are handled independently.

**Comment by JPTIZ** [comment]
Sorry for the necrobump, just wanted to check out: isn't this issue solved?

**Comment by refractionpcsx2** [comment]
As far as I'm aware you should be able to user F1 to save and F3 to load, F2 to change slot.

If you're using a laptop and this doesn't work, you might have to press the "Fn" button which is probably close to your space bar

**Comment by JPTIZ** [comment]
Oh, sorry if I was unclear. I was asking in case if this could already be marked as closed, since the shortcuts have been on for a while and it was already discovered the OP was having the Alt-unpressed issue.

**Comment by refractionpcsx2** [comment]
oh right, yeah it is resolved and can be closed. thanks!
