### ISSUE TITLE
Broken GSdx Recorder

### ISSUE THREAD

**Issue by Nobbs66** [PCSX2/pcsx2#539]
Core issue:

Issue title: Broken GSdx Recorder

-PCSX2 version: 1.3.0 GIT 2015-04-17 

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: GSdx, SPU2-X, Lilypad, Linuz ISO/Gigaherz CDVD,rest null plugins

-Plugin settings: Defaults, no settings modifications affect the issue

-Description: The internal video recorder is no longer working and is giving the error: " (Pcsx2AppMethodEvent) STL Runtime Error:device or resource busy:device or resource busy"

-How to replicate: Start any game normally using either Fast or Full boot and press F12

-Last known version to work: 1.3.0 2015-04-16

-PC specifications: CPU: Intel Core i5 4440 @ 3.1Ghz GPU: MSI GTX650 1GB OC OS: Windows 8 64bit

-Other comments: The issue was originally reported here:http://forums.pcsx2.net/Thread-PCSX2-Built-in-Recorder-Broke and confirmed my both myself and Ssakash.

**Comment by bositman** [comment]
Thank you for the bug report. It seems the gsdx-boost-queue branch merge is to blame. @gregory38 it's all yours ;)

**Comment by Sarania** [comment]
@Nobbs66 et al - Good report.

While we are at it, I am wondering how useful the internal recorder even is any more? Is there some specific case where it's better than something like e.g. FRAPS or Bandicam? I mean, of course it's free and those are limited, but aside from that.

Also does Shadowplay/Ratpr work? I know SP did in Desktop mode before, but that was kind of crappy.

What I am saying is there some really good reason to even keep it, or should we just drop it?

And if there is some good reason, don't shoot me! I'm just discussing possibilities.

**Comment by Nobbs66** [comment]
I think it's best use is for those that want to record really demanding games like SotC, but can't afford a solution that can use the GPU for video capturing.

**Comment by Sarania** [comment]
@Nobbs66 Well SP and Raptr are free - if they work.

Bandicam and FRAPS both have free version with a 10 minute limit. And there are other solutions too.

Also, how likely is it that someone has a CPU powerful enough for SotC but not for video recording? Intel's stuff has QuickSync which many solutions can use, and it doesn't eat CPU power. AMD's stuff have VCE on their die too, so same situation.

It would only be really old CPU that didn't, and even without a GPU those CPU are unlikely to be too useful for PCSX2. Maybe the Intel Core2Duo series... other than that, I can't think of any.

**Comment by Sarania** [comment]
Well, I did think of one situation. Since the game doesn't have to be full speed for the internal recorder in order for the video to be full speed, it could be useful for people with slow machine to record. But I wonder how often that happens?

**Comment by ssakash** [comment]
It happens most of the times. even I use the Internal recorder function if I wanted to record on my Core2duo. since, it doesn't have enough single thread performance to cope with the other recording software like Fraps (or) Bandicam @60fps on specific games.

I don't suggest the removal of this Internal recorder function. The fact that it was notified very fast on the forums means that most of the users are still using the internal recorder function.

@Nobbs66 
Yeah, good report, :smile:

**Comment by Sarania** [comment]
@ssakash It wasn't really noticed that fast, it's been over a month.

But are you saying that the recorder is LESS demanding than other methods? If so, that is a good reason to keep it yeah. I'll have to make a test.

**Comment by ssakash** [comment]
> But are you saying that the recorder is LESS demanding than other methods? 

I don't mean it as less demanding while recording. It's actually more demanding while recording since, the internal recorder reads/writes uncompressed frames as default and that will prove to bottleneck for most HDD's since, it's not well optimized for the task. 

 Let's compare a game where the conroe architecture is limiting the game from attaining 30+fps. I don't want the same speed on my recorded file. the Internal recorder always produces the Video at 50/60fps so, it would be a nice feature for people with low end processors.

**Comment by Sarania** [comment]
@ssakash 
"Let's compare a game where the conroe architecture is limiting the game from attaining 30+fps. I don't want the same speed on my recorded file. the Internal recorder always produces the Video at 50/60fps so, it would be a nice feature for people with low end processors. "

Yes I said that above. That is the only real reason I can think of.

Well, I guess since it has some use, and it's already there, might as well leave it. I didn't mean to clutter this issue up with pointlessness, but I had been wondering about this for a while and it seemed like a good time to bring it up.

**Comment by gregory38** [comment]
Well I'm not surprised... If you can post the git hash version in bug report it would be nice too.

**Comment by gregory38** [comment]
Could you edit stdafx.h, comment the line 65?
```
#define _CX11_
```
And tell me if it works ok.

**Comment by bositman** [comment]
Please don't pollute the issue with chatter, you can do so in the forum if you need to.
I'll check it out when i get home if no one else has done so before

**Comment by gregory38** [comment]
Ok. I think I know more or less the bad code. I will revert it. It isn't a big deal. I just need to be careful to avoid breaking the windows build.

**Comment by Sarania** [comment]
@bositman If you say so. However, I at least felt that deciding whether the topic feature is even relevant anymore was very much on topic. To the point that Nobbs sent me a PM saying I should take it elsewhere and I said "No, this is the most appropriate place"

You may delete this post since this one truly is not relevant to the issue.

**Comment by bositman** [comment]
@gregory38  Won't compile. Error log: http://pastebin.com/3H31XsdX

**Comment by gregory38** [comment]
Sorry. Remove the full block
```
// Require at least Visual Studio 2012
#if defined(__linux__) || (defined(_MSC_VER) && (_MSC_VER >= 1700))
#define _CX11_
#define ENABLE_BOOST // queue is from boost but it doesn't require a full boost install
#endif
```

**Comment by bositman** [comment]
Yeah deleting that fixes it

**Comment by gregory38** [comment]
Does it fixes the GSdx recorder issue or only the compilation?

**Comment by bositman** [comment]
Sorry I meant it compiles ok and the recorder issue is fixed too

**Comment by gregory38** [comment]
Great I wil check the code tomorrow. Thanks

**Comment by gregory38** [comment]
Could you try this patch: https://gist.github.com/gregory38/206fd8534e24ab9241a0
Just copy paste in a file and do git apply the_file
Tell me if you have issue to apply it, first time I use gist.

**Comment by bositman** [comment]
Not sure if it's git for windows failing or what :P
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.


D:\pcsx2 [master]> git apply recorder.patch
error: patch failed: plugins/GSdx/GSCapture.cpp:387
error: plugins/GSdx/GSCapture.cpp: patch does not apply
error: patch failed: plugins/GSdx/GSCapture.h:33
error: plugins/GSdx/GSCapture.h: patch does not apply
D:\pcsx2 [master +1 ~0 -0 !]>

**Comment by gregory38** [comment]
sigh.. I created a branch ```gsdx-issue-539```

**Comment by bositman** [comment]
Branch works fine, good job

**Comment by gregory38** [comment]
Great. Thanks very much for the test

**Comment by Nobbs66** [comment]
NIce job gregory!
