### ISSUE TITLE
Removing DirectX SDK dependency

### ISSUE THREAD

**Issue by mirhl** [PCSX2/pcsx2#564]
I.. am not sure if removing is the only option, or if we could just provide a fallback case where libraries and headers from built-in Windows SDK are used instead (or on the contrary DX SDK become the fallback choice)

Anyway, the two biggest issues I encountered without DX SDK were the lack of *d3dx11.h* and *dxguid.lib*, [both](http://blogs.msdn.com/b/chuckw/archive/2013/08/21/living-without-d3dx.aspx) (easily?) [solvable](http://www.ogre3d.org/forums/viewtopic.php?f=2&t=70302)

Anyone with enough time to work on it?

**Comment by refractionpcsx2** [comment]
So let me get this right, you want to remove the DirectX SDK dependency and replace it with the Windows SDK dependency in the hope gabest never used any other features which wont be available? Can I ask what the point in that would be?

Not to mention, the Windows SDK according to that link does not have proper DirectX 9 support and GSDX still uses DirectX9, so then we would need the DirectX SDK AND the windows SDK.

**Comment by mirhl** [comment]
Wait, isn't Windows SDK already between requirements?

And it's not D3D 9 that disappeared, but D3D*X*9. After reading [this](https://msdn.microsoft.com/en-us/library/windows/desktop/ee663275.aspx) I supposed replacing the (few?) functions used could be straightforward.

**Comment by refractionpcsx2** [comment]
We don't use the windows sdk at the moment as far as i know, i never install it, only what comes with VS (even the express versions) is used, and DX SDK of course.

**Comment by mirhl** [comment]
Oh, my bad then.

I guess.. I could close it

**Comment by refractionpcsx2** [comment]
I can see now why you'd suggest it, if that was the case or ever becomes the case, it will be certainly worth pursuing :)

**Comment by mirhl** [comment]
Well, in the long run it would definitively be a necessity. And after 5 years I start to think there might be outdated components too. 

But on the even longer run, *OpenGL* is probably the winner (if not for its open nature, at least because it's the only renderer our gregory master wants to improve).

**Comment by refractionpcsx2** [comment]
The current opengl implementation is as good as directx but also more flexible (probably due to opengl being used/similar on the ps2 itself) so now speed is no longer an issue, it could probably take over from directx as the go-to renderer

**Comment by mirhl** [comment]
Unfortunately it's still an issue on AMD cards d:

**Comment by refractionpcsx2** [comment]
Probably AMD's fault after the hairworks dabocle :P

**Comment by mirhl** [comment]
Oddly, somebody else already managed to get this
https://github.com/turtleli/pcsx2/tree/win8_vs2013

**Comment by Bigpet** [comment]
@mirhl does what it compiles run on WinXP too?

**Comment by mirhl** [comment]
Unfortunately I have only vs2015 at home (which doesn't end compilation in both versions)

If nobody can get a working build with vs2013 before monday, I guess I might.

**Comment by turtleli** [comment]
It compiles and runs for me on Windows 8.1, using VS2013 with the Windows SDK (not just what comes with VS2013) installed. I set the minimum version to Windows 8, so that should work as well.

Windows 7 requires the DirectX SDK for XAudio2 2.7 and possibly XInput as well. So lowering the version requirements to Windows 7 won't work.
Windows XP is almost certainly a no, I've changed the toolkit from v120_xp to v120.

So yeah, it seems like the DirectX SDK is going to be needed for quite some time.

I could always attempt a Windows 7+ transition branch. I think what I've changed will work on Windows 7 if I reinclude the DirectX SDK (so it depends on both SDKs) and lower the version requirements, but I need to clean up the current branch first and I don't have Windows 7 installed.

**Comment by refractionpcsx2** [comment]
Thank you for testing @turtleli :)

If XP is a no no, although I'd love to say "no more XP" it's still popular amongst some and we do have directx9 support, so i'm against putting artificial requirements in place for the sake of not having to make 1 extra step when setting up VS.

**Comment by mirhl** [comment]
Jesus. I can't believe they are so narrow minded to not even consider 7. 

~~And besides for [XAudio2](http://blogs.msdn.com/b/chuckw/archive/2012/04/02/xaudio2-and-windows-8-consumer-preview.aspx), you still need DX SDK for [Xinput 9.1.0](http://blogs.msdn.com/b/chuckw/archive/2012/04/26/xinput-and-windows-8-consumer-preview.aspx) (which is the only version supported in XP)~~ Ok I checked: XP supports any XInput version 7 has. 

Speaking of which, I'm also against dropping XP support, if it's not strictly necessary. If it's still supported in VS2015 I guess it's not all that burden after all. 

What's the actual difference between built-in SDK and "dedicated" one then? Shouldn't the first even be more updated?
And what issues v120_**xp** entails?

Last.. does all of this help cleaning the code or improving performance in your opinion?

**Comment by turtleli** [comment]
Am I being called narrow minded? ;)

It's not that I wanted to rip out Windows 7 support, but that working with the Windows SDK and without the DirectX SDK requires it. The xaudio2.h header errors out and tells you that you need to target Windows 8 and above.

The actual Windows SDK contains a lot more stuff, I don't specifically know what is in it though.
v120_xp is the last toolset that supports XP. I needed to change it to v120 for vs2013 to choose the right includes and libraries.

The stuff that I've changed doesn't affect performance in my opinion. It probably doesn't help with cleaning the code much, except for perhaps that I've looked through the code and seen that some parts are a mess (though that might have been due to my attempt at switching pcsx2 to use wxWidgets 3 on Windows - which REALLY didn't work out well).

**Comment by mirhl** [comment]
I was actually calling MS narrowminded. 

Anyway couldn't those problems with v120_xp toolset be [related](https://msdn.microsoft.com/en-us/library/windows/desktop/ee663275.aspx#sdk_vs11) to the fact you are using VS express?

**Comment by turtleli** [comment]
Nope, I'm using VS2013 Community.

**Comment by mirhl** [comment]
[This](https://tedwvc.wordpress.com/2014/01/01/how-to-target-xp-with-vc2012-or-vc2013-and-continue-to-use-the-windows-8-x-sdk/) seems interesting.

**Comment by turtleli** [comment]
If someone is really determined to support XP then I suppose it could be done. I'm not that someone though.

What toolkits does VS2015 have?

Is anything before XP supported? I found this in common/src/Utilities/Windows/WinMisc.cpp
```
	pGNSI = (PGNSI) GetProcAddress( GetModuleHandle(L"kernel32.dll"), "GetNativeSystemInfo" );
	if(NULL != pGNSI)
		pGNSI( &si );
	else
		GetSystemInfo( &si );
```
but GetNativeSystemInfo is supported by XP so it could be replaced by `GetNativeSystemInfo(&si);`.

**Comment by Bigpet** [comment]
@turtleli surprisingly VS2015 still has a v140_xp toolkit, I think that it will be the last version to have XP support.

**Comment by mirhl** [comment]
I think this can be closed. DirectX SDK will be required forever, at least for XAudio2 and XInput (idk if DirectInput support is also included in pcsx2, still the point it's the same)
