### ISSUE TITLE
[Feature Request]: Adaptive Internal Resolution Scaling

### ISSUE THREAD

**Issue by DrEVILish** [PCSX2/pcsx2#5733]
### Description

During easy to render games, increase the "Internal Resolution" until a certain GPU percentage has been reached.
This means that your GPU can now be utilised to its fullest extent while keeping frame times consistent.

If this option is enabled, there should be two other options added into the UI
1. min Internal Resolution (the lowest the pixel count will drop to during gameplay)
2. max Internal Resolution (caps the resolution so if playing on a 720p display it doesn't ramp up to 8k as you'll never notice much beyond 1080p)

### Reason

With games like Gran Turismo 4, there are a couple of tracks/environments that include very detailed lighting scenarios that hammer the frame rate. Frame Time on PS2 games is more important than image resolution. So when complex scenes load in and frametime/FPS starts to tumble reduce the resolution until they lock back at the locked Vsync.

This prevents the user from having to open and close settings just to play 1 particular level.

Settings: Mipmapping: Full, CRC Hack Level: Aggressive, Blending Accuracy: Ultra
Native Res 1x @ min 41fps
720p Res 2x @ min 24fps
1080p Res 3x @ min 15fps

Just a small reduction in perceptible image quality renders a massive boost in playability.

### Examples

https://docs.unrealengine.com/4.27/en-US/RenderingAndGraphics/DynamicResolution/
https://github.com/AlexRazor1337/godot-resolution-scale
https://www.intel.com/content/www/us/en/developer/articles/technical/dynamic-resolution-rendering-article.html

Different topic but would also be effective behind the scenes.
https://github.com/GPUOpen-Effects/FidelityFX-FSR

**Comment by refractionpcsx2** [comment]
FSR is useless because it requires motion information or an antialiasing pass during rendering (which we can't do), but I like the idea of modifying the upscale if your framerate is struggling (providing the GPU is the limiting factor)

**Comment by coornio** [comment]
An interesting idea, but this would only potentially work by limiting your desired upscale to a lesser multiplier, and hoping that whatever the bottleneck is, it's something that the upscaling affeccts directly in order for the entire process to have any effect on your framerate.

The point is, it's entirely possible for some games to have bottlenecks before either the CPU or GPU utilization hit half their expected capacity, solely because there exist operations that take place which stress parts of the system (like bandwidth bottlenecks, or accumulation of operation overhead) that do not fall under the percentage these counters represent.

Suffice to say, it's also possible to hit bottlenecks on modern, top of the line hardware that stress the CPU/GPU to their core limit due to incorrect emulation or just shitty dev practices on a particular title; in these cases, upscaling adjustments may be entirely pointless.

For this whole thing to work, you'd need a curated list with different parameters/notes for each game, and even then it would be unreliable during the development cycle of the emulator. Hell, the WIP database for upscaling fixes currently underway will be a massive project by itself, I don't think something like this would be desirable on top of it all.

**Comment by SirFancyBacon** [comment]
Sounds like a unique idea; almost like an "Internal Resolution Auto" setting.

I myself always turn off dynamic resolution; but i can see it's appeal.
Is it even possible for PCSX2 adjust internal resolution dynamically?

**Comment by coornio** [comment]
> Is it even possible for PCSX2 adjust internal resolution dynamically?

Technically yes. Realistically no. If you read my earlier message you'll understand the shortcomings of the idea.

**Comment by RedPanda4552** [comment]
It's actually somewhat easy to detect a GPU bottleneck even without any GPU utilization metrics. Quite simply, if the CPU thread utilizations reported in the title bar are all under ~95%, then the limiting factor is the GPU and you're almost certainly going to see improvements from ducking IR down.

Caveat being, there is likely to be a stall while ducking down, so that's going to make this a miss, imo.

+1 to FSR being a miss, the sharpening worked kinda nice if you were already at a higher IR. But it seems like any sort of pseudo upscale with FSR is doomed to fail, all the prior attempts at it yielded basically a slightly sharper but equally low resolution image that really didn't look that great. Plus with FSR 2 requiring motion vectors that puts it completely off the table.

**Comment by DrEVILish** [comment]
I completely understand that in the current PCSX2 build changing resolution does induce a stutter into the game.
I'm sure someone much cleverer than me can work out a way to smoothly transition.

In my opinion, looking at the System level FSRv1 (which has now been renamed to RSR Radeon SuperRes) it seems to require a high level of detail regardless of resolution in the source.
 PS2 games only have low-quality resolution textures, getting better texture packs for each game would in my opinion would enable RSR to show its strength.

**Comment by lightningterror** [comment]
Currently out of scope for such small gain.
