### ISSUE TITLE
[Feature Request]: Support large pnach files and fixes

### ISSUE THREAD

**Issue by SWHSmash** [PCSX2/pcsx2#5776]
### Description

I would like to know if the current pnach support cam be updated to support large cheat files, also that the codes actually working correctly.

### Reason

I want to play the Kingdom Hearts: Critical Mix made by Xendra, but the current dev version doesn't support large pnach files or the codes won't apply like there would apply when I use the PCSX2-EX 1.5.0 Mod by TopazTK (and these doesn't got the Vulkan support ofc.)

### Examples

Using this pnach file (https://drive.google.com/file/d/1_t8l4DJRwg7pw14IEwbO9Cy-lc87pv8B/view), with the given Extended Pnach support mod (https://drive.google.com/file/d/1SrzxEtpXAR9UscmLH5TyHLTw9YNgcE9T/view).

The rom was send by discord members.
It works flawless with this mod, but there is no Vulkan support and that's important to get ride of the slow downs for me.

Running on:
Windows 10 1809 64 bit
Intel I7-2600k (OC to 4.1GHz)
AMD RX580 8GB

**Comment by RedPanda4552** [comment]
The pnach format no longer has a size limit, as per [this commit](https://github.com/PCSX2/pcsx2/commit/628f5abaac0328aea92933dbc8837725c6bd407c).

If your pnach was built using a PCSX2 fork, the issue is almost certainly a behavioral change between the fork and mainline PCSX2 which is causing the pnach to be incompatible with mainline PCSX2. If there's an issue with a pnach developed on current PCSX2, let us know but otherwise this seems like an issue with the downstream fork, and you'll need to work with the pnach creator and downstream fork to make your pnach compatible.
