### ISSUE TITLE
[Feature Request]: Add a 3:2 aspect ratio option

### ISSUE THREAD

**Issue by GN876** [PCSX2/pcsx2#5842]
### Description

When using PCRTC offsets with PR#5810 , Progressive scan games look squished. It can be fixed by using a 3:2 aspect ratio.

This happens due to the displaying a 720x480 framebuffer at 4:3 aspect ratio, which means the 640x448 display resolution of some 480p games will be squished, and thus look slimmer than intended. This happens due to game developers not accounting for the PS2's usage of none square pixels.

### Reason

By setting progressive scan signal to 3:2 aspect ratio using square pixels, the correct aspect ratio of 480p (640x448) games will be preserved, and the image will look as intended and without distortion.

### Examples

Valkyrie Profile 2 running at 480p using the 4:3 aspect ratio option:

First image is a 640x480 window, which looks squished and incorrect:

![4x3](https://user-images.githubusercontent.com/61622979/162639020-99966375-f65f-47f2-8b47-b676578ba217.png)

Second image is running inside a 720x480 window, which displays the game at the correct aspect ratio.

![3x2](https://user-images.githubusercontent.com/61622979/162639083-112591a6-33b2-4ad9-879d-c02b079db32e.png)

**Comment by kenshen112** [comment]
Related to https://github.com/PCSX2/pcsx2/issues/5330

**Comment by refractionpcsx2** [comment]
> Related to #5330

Not really, my PR #5810 basically already does that

**Comment by Zinfidel** [comment]
I'm chiming in since #5330 was mentioned and have some concerns over terminology here. When we're talking about "correct" aspect ratio, people might mean two different things: the way it would actually appear on a CRT television, or the way it was intended to appear by the developer. In #5330 I am specifically suggesting ways to make the emulation look as a CRT would (the vaunted "accuracy" argument).

Despite the first screenshot of yours appearing squished, I believe that it (possibly) is the accurate version of the image. As mentioned, not all developers accounted for the 10:11 PAR of the PS2's 480i/p mode which means the perfect circle in square pixels would appear squished in the narrow 10:11 dots/samples. The irony of my example showing the opposite of this situation is not lost on me. Another thing that complicates this is that magic 720x480 (3:2) resolution does not actually line up exactly with clean aperture 704x480 resolution and thus squishing to 4:3 is problematic.

I am not entirely sure how the PS2's progressive mode changes things here and a lot of this is over my head, but I wanted to leave my 2 cents here in any case.

**Comment by refractionpcsx2** [comment]
Well, if you don't like it, you don't have to use it, by I've been told this is a result of direct captures from the PS2 by gamespot which were used as a comparison and the image is adjusted when in 480p mode to compensate for a different aspect ratio.

You're free to continue to use the 4:3 aspect with the offsets (which will still be different) but in the second screenshot the circle is perfectly round, which to me seems like what it should be.

**Comment by Zinfidel** [comment]
Oh I'm all about having options and I think it's perfectly good to be able to select square-pixels or squished pixels - I have no issues there. I was pointing out that describing either square or non-square pixel output as "correct" is murky territory due to games not necessarily appearing on a TV as a developer intended if they didn't account for the shape of the pixels. In good cases, TV representation and developer intentions line up, but unfortunately often they don't. :/

As for the round circle, I think it is clear that the developers did not account for TV sampling complexities and I agree that the square-pixel image looks better and is certainly what the devs wanted. There are games that will have the opposite effect here though, wherein square pixels will actually distort the image.

**Comment by crashGG** [comment]
From my observation, the correct ratio of this game is not 4:3 nor 3:2, but the native pixel ratio （10:7）

4:3 ratio
![Valkyrie Profile 2 - Silmeria_SLPM-66419_20240925215338_4b3](https://github.com/user-attachments/assets/576fed69-818c-49c7-9406-744e9cc3854e)
3:2 ratio
![Valkyrie Profile 2 - Silmeria_SLPM-66419_20240925215322_3b2](https://github.com/user-attachments/assets/9d8495e5-548f-4252-b87b-a02784c281ce)
native pixel ratio(10:7)
![Valkyrie Profile 2 - Silmeria_SLPM-66419_20240925215301_native](https://github.com/user-attachments/assets/2732d7d2-b509-4530-8d8c-2fc707a6fbd0)
