### ISSUE TITLE
[BUG]: (pcsx2:87714): Gdk-CRITICAL **: 01:22:45.156: gdk_window_process_updates: assertion 'GDK_IS_WINDOW (window)' failed

### ISSUE THREAD

**Issue by pupilo-py** [PCSX2/pcsx2#5946]
### Describe the Bug

 After updating to version 1.7.2620 or 22, I can't modify the emulator settings or even load a game. Whenever I try to do something I get errors like this: (pcsx2:87714): Gdk-CRITICAL **: 01:22:45.156: gdk_window_process_updates: assertion 'GDK_IS_WINDOW (window)' failed
![bug](https://user-images.githubusercontent.com/58078395/164956831-9d2980dd-a48b-4bbf-aace-f55f05397dcf.png)

### Reproduction Steps

1 - General Settings
2 - Edited some settings or i choose a game
3 - Apply or load a game
4 - Crash

### Expected Behavior

1 - General Settings
2 - Edited some settings or i choose a game
3 - Apply or load a game
4 - work

*Sorry for any mistakes in writing, because I'm Brazilian and I'm translating through Google Translate

### PCSX2 Revision

v1.7.2650

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Kubuntu 20.04

**Comment by refractionpcsx2** [comment]
Sorry we don't help when piracy is involved.

**Comment by pupilo-py** [comment]
> 

But friend, it's not a piracy issue, it's a bug issue with GTK. It's not just to help me, it's to help everyone who is having a problem with this on Linux.

**Comment by refractionpcsx2** [comment]
well, you pirated your BIOS files, so I'm not willing to help you. We have a string no piracy or no support rule.

**Comment by pupilo-py** [comment]
Alright, but this problem will be fixed, if someone who hasn't pirated complains?

**Comment by refractionpcsx2** [comment]
sure, if somebody who hasn't pirated has the problem, we'll look in to it.

**Comment by arcum42** [comment]
One thing I will say is that I'd consider the problems with it crashing and the gtk errors to be separate issues. One thing Gtk has always done is it spams warnings and errors to the console any time anything happens it doesn't like, and often these will still occur even if the code itself is actually working. There are actually many gtk programs that spam errors like this, and it'll very depending on the version of gtk you have installed, too. 

Our code pipes the console messages into the log window, so they appear there. I *have* seen those errors before even when everything is working fine.

It's fairly hard to track down, though, as the errors are most likely coming not from actual gtk code in pcsx2 (there is still some in USB and dev9, IIRC), but the gtk code in wxwidgets.

Wasn't having much luck tracking it down the previous times I looked at it, though, and since we're eventually getting rid of wx, it didn't seem worth the time.

**Comment by pupilo-py** [comment]
It's because I'm not the only one having this problem, I've seen other people too.

But so guys, understanding your position, really, but the PS2 is a console launched 22 years ago, it's not manufactured anymore and its games are not sold. I'm not wrong to pirate.

I'm saying this because I felt a little disrespected because of the response to the closing of my issue, I know I didn't pay for the program, but I expected a little more consideration with my problem, it's not like a lot of people who send issues here do not hack to play.

**Comment by pupilo-py** [comment]
Good news guys, with the update in Flatpak format (which was not working before and the issue is with the Appimage format) to v1.7.2648 now works! Thanks!

**Comment by refractionpcsx2** [comment]
I honestly don't care what you think is justified or not, it's still copyrighted materials and still illegal to download them.  All of the forementioned are readily available in second hand markets, you have *zero* excuse to pirate.
