### ISSUE TITLE
Corrupted menu in Final Fantasy X Internaional with mesa drivers. Bisected.

### ISSUE THREAD

**Issue by steemandlinux** [PCSX2/pcsx2#605]
The error appeared after e774fecb779696871d15d61045828e332d233bde commit

glxinfo: https://clbin.com/hAuTR llvm-3.7

screen: http://i.imgur.com/G6v1CQy.png

**Comment by Gusar321** [comment]
That commit was made because I tested geometry shaders on Intel and it works great. But you have AMD graphics and it seems it doesn't work there. The commit should've just removed the "|| intel_buggy_driver" part instead of the whole thing.

Until the code is changed to automatically disable geometry shaders on AMD, go to GSdx Config - Advance Setting, change Geometry Shaders from Auto to Force-Disabled.

PS. Considering it works on Intel, I'd consider this a bug in the Mesa AMD driver, so you might want to report it to the mesa developers.
