### ISSUE TITLE
[BUG]: Regression: Tales of the Abyss

### ISSUE THREAD

**Issue by Ryudo300** [PCSX2/pcsx2#6075]
### Describe the Bug

Upscaling causes an unplayable blurry effect in certain towns where bloom is very active (Engeve being a prime example).

Each time you increase the upscale multiplier (2x to 3x, etc), it causes the blurred effect to fill the screen further to the point where it fully covers the screen.

After testing out various builds, it was discovered to be a regression caused by https://github.com/PCSX2/pcsx2/pull/5419.

Example Screenshots:

Native: (Bug not present)
![pcsx2x64-avx2_2022-05-14_03-55-29](https://user-images.githubusercontent.com/10039778/168406599-fb771eb3-9edf-4a96-b766-ad957da3d821.png)

2x Native:
![pcsx2x64-avx2_2022-05-14_03-56-30](https://user-images.githubusercontent.com/10039778/168406622-2ce6db6a-f8f7-4bd7-a600-86fba6049740.png)

3x Native:
![pcsx2x64-avx2_2022-05-14_03-56-52](https://user-images.githubusercontent.com/10039778/168406631-acad3d09-ed56-4021-b446-b9ec9bf82fe9.png)

### Reproduction Steps

One of the earlier locations you can spot this in, is in the town called Engeve. Simply enter the town and you'll notice these effects. Inside the buildings it's fine again (presumably because there's no bloom effect in there). 

### Expected Behavior

Expected behavior should be as seen below here in a screenshot taken on PCSX2 1.6.0

![pcsx2_2022-05-14_04-04-00](https://user-images.githubusercontent.com/10039778/168406834-1ad8b089-35cb-4169-a718-d4b6dd13f112.png)

### PCSX2 Revision

v1.7.2.2744

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 3600

### GPU

MSI GeForce GTX 1660 SUPER

### GS Settings

**Internal Resolution:** 3x Native
**Anisotropic Filtering:** Off
**Dithering:** Off
**Mipmapping:** Automatic (Default)
**CRC Hack Level:** Automatic (Default)
**Blending Accuracy:** Basic (Recommended)
**Texture Preloading:** None (Default)

### Logs & Dumps

GSdump (Using 3x native)

[gs_20220514040621_Tales of the Abyss _NTSC-U__SLUS-21386.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/8691981/gs_20220514040621_Tales.of.the.Abyss._NTSC-U__SLUS-21386.gs.xz.zip)

**Comment by lightningterror** [comment]
@iMineLink for you.

**Comment by iMineLink** [comment]
So, removing the "can upscale" hack `GSRendererHW::CU_TalesOfAbyss` dedicated to this game actually fixes the issue.
Removing the hack prevents a depth buffer to be downscaled to 1x when upscaling.
The real issue though is that we're getting a black output when downscaling the cited depth buffer, and this breaks the rendering.
I want to analyze why this is happening because I smell a subtle bug somewhere in the `GSDevice::StretchRect` area when using the `ShaderConvert::DEPTH_COPY` shader, even though the fix is trivial: just get rid of the hack.

**Comment by iMineLink** [comment]
There is a bug in the ogl stretch rect implementation which prevents the depth copy shader to properly work.
But fixing it just brings the ogl renderer on par with the other renderers, so having the top left square sharp and the rest of the image blurry.
Again, removing the can upscale hack fixes this.
Still, there is an issue when drawing with a rescaled depth buffer (removing the "can upscale" hack prevents the depth rescaling) which I'm investigating.
Also, I noticed that this related to three other issues:

* We do not always set the scale of the source texture when built from target (in lookup source)
* When reusing a depth buffer as texture (lookup depth buffer) we just reference it without copying (but the reference might become invalid if the depth target is changed)
* we keep a "from target" reference for shuffling purposes in the sources as a pointer to the framebuffer   texture; but also in this case it might become invalid (rescale/resize case)

To fix the latter two cases, using a double pointer in the source to the texture used in the frame/depth buffer can fix the misalignment.
I need still to investigate instead why it is now working the source sampling without proper scale set in the color case (but it might be unrelated to this issues) and how it is done the sampling in the depth case (where the actual bug lies, I hypothesize there's a wrong assumption on the actual scale of the depth source texture).

**Comment by refractionpcsx2** [comment]
@iMineLink You mentioned depth upscaling problem, I wonder if this issue might be related as this was introduced when depth conversion was fixed https://github.com/PCSX2/pcsx2/issues/5592

Could be worth keeping note of, should you put a fix together.

**Comment by lightningterror** [comment]
Regarding the gl issue, maybe related to #6054 ?
