### ISSUE TITLE
Pluggable VPU support

### ISSUE THREAD

**Issue by ADormant** [PCSX2/pcsx2#610]
Perhaps it could be implemented in the PCSX2 too? It'd allow for more advanced enhancements and also help avoid upscaling bugs and related hacks.

https://github.com/jpd002/Play-/pull/61

**Comment by refractionpcsx2** [comment]
It's an interesting idea, however I'm slightly nervous of the prospect of Interlocking and COP2 support as they rely heavily on the VPU's being in sync with the EE, making it a plugin would make this effort much more difficult.

Not to mention it would be messy with the whole MTVU thing, as only VU1 is threaded, VU0 is not and cannot be, due to the forementioned interlocking.

**Comment by ADormant** [comment]
Maybe it's possible to finally merge GSDX into the PCSX2's core?

**Comment by refractionpcsx2** [comment]
I think it would be best waiting a little longer for that, at least until it is a bit more compatible. However it doesn't really address the idea you are proposing :p

**Comment by ADormant** [comment]
So what is the biggest problem, recompilers? I don't think it has to be a separate plugin but a modification to PCSX2 and GSDX's current VPUs/GS. The author may be able to explain better.
@bigianb

**Comment by refractionpcsx2** [comment]
The recompilers are not my issue, the emitter is a shared project, so that shouldn't be a problem.  The issue i'm worried about is the synchronization between the VPU plugin and the core, in interlocking mode (used in games like MGS2) needs to be almost instruction accurate, when you pull something out as a plugin, it has no way of timing and relies on sync from the core which is only sent on a plugin "poll", much like SPU2-X does and we all know what happens when your framerate fluctuates!

**Comment by ADormant** [comment]
@bigianb  @refractionpcsx2 

> when you pull something out as a plugin, it has no way of timing and relies on sync from the core which is only sent on a plugin "poll", much like SPU2-X does and we all know what happens when your framerate fluctuates!
Is that the limitation of PS Emu Pro plugin specification?

**Comment by ADormant** [comment]
I hope something can be done about it in PCSX2 eventually anyway. @bigianb

**Comment by refractionpcsx2** [comment]
It is sort of a limitation of the PS Emu Pro plugin spec yeh.  Passing data across DLL's can be expensive, which is why making plugins internal can be of benefit.   If you're constantly polling the cycle count in order to keep in time, there will be a huge overhead, also to do so it will have to be threaded else it relies on the main thread (the emulator) to tell it what to do, which it isn't going to do constantly because again, very expensive, especially on recompilers.  However if you have it threaded, you have to pass information between the threads, which again, you guessed it! Expensive.

**Comment by ADormant** [comment]
The best option would be to merge GSDX but perhaps it might be possible to expand this plugin spec and add what is needed? For example N64 plugin specs are still in development. @refractionpcsx2

**Comment by ADormant** [comment]
https://github.com/cxd4/rcp64

**Comment by MrCK1** [comment]
Closing since this is an old issue and plugins are in the process of being merged
