### ISSUE TITLE
single predefined macro for consistency. 

### ISSUE THREAD

**Issue by ssakash** [PCSX2/pcsx2#622]
There are lot of instances where _WINDOWS , WIN32 and other such preprocessor macro definitions are used instead of the default _WIN32 which is pre-built. https://msdn.microsoft.com/en-us/library/b0084kay.aspx

I was currently working on a PR to remove all of those different instances and have a single one for consistency. any opinions on this ? @gregory38  @refractionpcsx2  @ramapcsx2 @bositman @gigaherz  @gabest11 

The following method saves a lot of preprocessor definition lines and has a single one for consistency and make it even more easier for new developers.

**Comment by turtleli** [comment]
Just to save you some effort if there's agreement for it - I did this for the experimental no dx sdk branch I attempted a few weeks ago. https://github.com/turtleli/pcsx2/commits/win8_vs2013

Look at "Standardise on _WIN32 preprocessor macro" and "GSdx: Use proper Windows includes and targets" (Made a mistake with the _WIN32_WINNT macro though). The other commits might have some version targeting stuff as well. So mainly the code that I ripped out early on in the branch will need standardised.

Side note: Your PR #621 - Look at  "Gsdx - remove old config dialog code", it might serve as a useful reference.

**Comment by ssakash** [comment]
I also did some initial work on standardizing the macro, I managed to replace every _WINDOWS occurrence to  _WIN32 on the GSdx side. there are still some place where I have to remove the macro definitions on the props. Just took a look at the reference you had mentioned for the removal of old config code, Honestly thanks very much now I don't have to track each and every one of those old variables.

**Comment by gabest11** [comment]
I don’t really care anymore, by the time my last pull request got accepted, the fork diverged so much that I have given up on synchronizing it again. I’d never think of doing any coding again there, it is a pain in the ass. Could be a nice system if you are able to directly upload changes, like with subversion of google code, but not like this.

From: Akash 
Sent: Sunday, June 28, 2015 3:34 PM
To: PCSX2/pcsx2 
Cc: gabest11 
Subject: [pcsx2] single predefined macro for consistency. (#622)

There are lot of instances where _WINDOWS , WIN32 and other such preprocessor macro definitions are used instead of the default _WIN32 which is pre-built. https://msdn.microsoft.com/en-us/library/b0084kay.aspx

I was currently working on a PR to remove all of those different instances and have a single one for consistency. any opinions on this ? @gregory38 @refractionpcsx2 @ramapcsx2 @bositman @gigaherz @gabest11 

The following method saves a lot of preprocessor definition lines and has a single one for consistency and make it even more easier for new developers.

**Comment by refractionpcsx2** [comment]
Nice of you to rear your head gabest, you really should hang around more ;)

I'm not against this at all, Ssakash actually approached me with this this morning, but I didn't really want to get too involved with it in case it was like it is for some sort of backwards compatibility (or future compatibility) reason.

You are more than welcome to work on GSDX since it's your baby.  Might be worth heading to IRC now and again and talking to Gregory (or converting his OGL changes to DX would be awesome as i haven't a flipping clue what I'm doing lol)

**Comment by Bigpet** [comment]
>Could be a nice system if you are able to directly upload changes, like with subversion of google code

@gabest11 that part didn't actually change. It's just the same as it always was. It was just called "commit access" with subversion and now is called "push access" in Git. It's just that "pull requests" are what was called "submitting patches to get them merged" is now slightly easier because merging works slightly better in Git in many cases and there's tools to do things like "rebasing" a little more automated. 

Sure, the git model is a little bit more complicated but the subversion model just seems weird for open source projects.

**Comment by refractionpcsx2** [comment]
oh yeh @gabest11 there is a TortoiseGit like there was for SVN if you want something a bit more familiar.  Obviously it works slightly differently, but it does the job of making control easier.  I do prefer SVN still tho :P

**Comment by gabest11** [comment]
My problem with pull requests is that it takes time to get accepted. Last time months for the opencl patch. While it was in the “queue”, I went on and tried different ideas, making it completely new and different. But at the same time, others were also working on the code and when I tried to reverse update my fork, there were so many conflicts that I said screw it.

**Comment by refractionpcsx2** [comment]
@gabest11 Well so you don't have to make PR's, I am more than happy to set you with commit access so you can update the code directly.  I have no reason to believe your changes need to be reviewed first.

**Comment by gigaherz** [comment]
Note that git has a svn frontend, for those tho dislike Git. You can use it to commit directly into the repo, skipping the local copy that git creates, and all the advantages of distributed development.

**Comment by gregory38** [comment]
```
I don’t really care anymore, by the time my last pull request got accepted, the fork diverged so much that I have given up on synchronizing it again. I’d never think of doing any coding again there, it is a pain in the ass. Could be a nice system if you are able to directly upload changes, like with subversion of google code, but not like this.
```
I hope the conflict wasn't generated by my rebase/changes otherwise I'm sorry. @gigaherz could you add commit access to gabest, thanks.

I made some experimentation with the HW renderer that will be nice to port on Dx. The top 3 features are
1/ Support of pseudo 16 bits target (with fbmask 0x3FFF). Game uses it to copy a channel to another channel. For example they can copy the green channel to the alpha channel. It fixes wall of fog (Green on GoW) and various vertical bands. GoW is running without any CRC hacks. The implementation is a hack to emulate the channel shuffling rather than to convert texture.

2/ Support of pseudo 8 bits index target. A more complex trick than above, the purpose is also to extract a channel. Previously method is limited to Green, I think the purpose here is to extract the blue channel. It fixes the blur effect in Valkyrie Profile 2, and partially fixes Metal Gear Solid3 effect (the later hit some textures cache limitations). Current implementation is to convert the texture on the GPU. However I scale it down so quality is not so nice and the shader is a bit slow. The 8 bits format is just awful. Maybe a hack solution (as 1) to only fetch the blue channel could work.

3/ Support of Depth Upload and Conversion from to Target. It helps to emulate those depth of field effect. And maybe help games that have depth issue (like SMTNocturne)

**Comment by refractionpcsx2** [comment]
A note on 1), i've already made a start on the implementation of this, but it's currently a hack and doesn't work correctly.

**Comment by ssakash** [comment]
@gabest11

Refraction mentioned that he's ready to provide commit access to you, so that you could directly edit the source without worrying about any merge conflicts. Any thoughts on this ?

**Comment by gabest11** [comment]
That would be great. But I still have to catch up with the changes. And currently I have no time, but maybe in the future.

**Comment by refractionpcsx2** [comment]
@gabest11 i've sent you a request to be an owner of pcsx2 along with the rest of us, that should give you full permissions to do as you need to :)

**Comment by ssakash** [comment]
I know that it's not relevant to the issue but, @gregory38 is still a collaborator, considered making him an owner ?

**Comment by refractionpcsx2** [comment]
Yeh done. I didn't realise either

**Comment by gregory38** [comment]
Is the macro renaming done ? (and therefore the issue closed)

**Comment by turtleli** [comment]
One of the winpcap headers requires the WIN32 macro so it still exists in some property sheets. It should probably be restricted to dev9ghzdrk but property sheets aren't fun at all.

It's done for pcsx2 + maintained plugins.

**Comment by gregory38** [comment]
Ok. Can be closed? Or is it useful to do the remaining one?

**Comment by turtleli** [comment]
Yeah. I'll close it. The property sheet stuff can be done separately (there is some other unneeded stuff in the property sheets so it's really a different issue).
