### ISSUE TITLE
[BUG]: Analog sticks cannot reach 100% range in diagonal directions (Slow walking)

### ISSUE THREAD

**Issue by butterbutts** [PCSX2/pcsx2#6230]
### Describe the Bug

In certain games which need you to press the analog stick 100% to the limit to be able to walk/run at full speed, diagonal inputs are being read as slightly too short. This is most easily seen in the Katamari games where walking diagonally is significantly slower than it should be. As far as I can tell this started happening after the UI update.
Setting the axis scale to around 1.10x fixes it, but I'm not sure if that negatively effects the analog range in cardinal directions in any games.
This happens on Xbox, Playstation, and 8bitdo controllers, but not on Switch controllers. The issue is probably that Switch controllers have square analog ranges, where the other controllers have round ranges.

### Reproduction Steps

- Set up a controller using the automatic binding
- Load a game with a sensitive analog range
- Point the analog stick 45 degrees diagonally
- Your character will run slower than they should

### PCSX2 Revision

1.7.2816

### Operating System

Windows 11

**Comment by coornio** [comment]
Different controllers indeed have different value outputs for their analog ranges. Some have a fake analog that behaves literally like a dpad, others have a square range analog, some have octagonal range analog, some have fully round analog.

I won't pretend to know what sort of values the DualShock 2 passed along to the console for it to have no problems, but you definitely shouldn't assume that all controllers are equal in that regard. 

Some will work out of the box, some might need a slight axis scale decrease, and some might need a slight axis scale increase. Basically, set it to what works best for your particular controller according to thy observations.

One day the controller setup might take this into account and adjust it accordingly. Until then, you'll need to do it manually. This isn't an issue.

**Comment by CookiePLMonster** [comment]
FWIW I hit the same issue in Crash Twinsanity recently where left diagonals on an Xbox One controller wouldn't hit 100% but right diagonals did, and I was sure it's a PCSX2 issue - however, I tried with a different XBone controller and it was fine, so it's likely a combination of a slightly off-center gamepad and a game very picky about inputs.

**Comment by NineKain** [comment]
Happens on my DS4 too, and i have seen at least 2 other users having the same issue

**Comment by coornio** [comment]
Similarly, in Suikoden 3, you can't move diagonally forward/left when on keyboard (axis values would be -1 and -1), probably due to some developer oversight with maximum values, but the character just stops. Changing the axis power to 0.95 and boom, worked again.

I'm starting to think that the DS2 analogs behave closer to a smoothened square rather than a circle, which would explain why some games have walk animations when going diagonally with the likes of xbox controllers

**Comment by CookiePLMonster** [comment]
> That said, let's not forget that Qt is now using SDL as its base for interpreting controller input rather than the xinput api like before. Maybe you guys should all do a quick test between the two?

I considered the game, no change in Crash Twinsanity.

**Comment by NineKain** [comment]
> That said, let's not forget that Qt is now using SDL as its base for interpreting controller input rather than the xinput api like before. Maybe you guys should all do a quick test between the two? 

I tried using DS4Windows, which changes the input into xinput and it has the same issue

**Comment by secondsabre** [comment]
Also having the same problem in Castlevania: Curse of Darkness (haven't tested any other games) and the issue only seems to be affecting the down-right and down-left directions on the left stick.  I'm using a wired DualShock 4 with DS4Windows; could be something specific to my controller, but did some testing to be sure.
-Tried using both the SDL and Xinput controller configs in Qt, same issue with both
-Tried with DS4Windows off and on, same issue
-Did a recalibrate in Windows (USB Game Controllers) to see if that would have an effect, no change.

Flipping back to the same game in the legacy build of PCSX2 ('XInput' and 'Monitor when in background' settings checked) had no issues with the controller, so it seems to be something in the Qt build specifically.

**Comment by CookiePLMonster** [comment]
> Flipping back to the same game in the legacy build of PCSX2 ('XInput' and 'Monitor when in background' settings checked) had no issues with the controller, so it seems to be something in the Qt build specifically.

OK, now we are getting somewhere - are you able to bisect between this "legacy" build and the current one to find when did it start breaking? Or if it's a Qt build, is the current wx one fine?

**Comment by MrPillze** [comment]
also experiencing this in several titles feels very strange to walk about in some titles. also being to setup deadzone's again would be wonderful. i guess it's all planned and just not top priority right now.  thanks for all your amazing effort on this great emulator.

**Comment by secondsabre** [comment]
> 
> OK, now we are getting somewhere - are you able to bisect between this "legacy" build and the current one to find when did it start breaking? Or if it's a Qt build, is the current wx one fine?


Sure thing!  Sorry, 'legacy' = the WX build; I suppose it's not legacy since it's still being actively developed, I just wasn't sure of the lingo to differentiate between the two (even though it's right there in the download link ^_^;;)

Test bed:
Wired DualShock 4, running DS4 windows as an Xinput wrapper, calibrated in Windows USB Game Controller options
All PCSX2 installs are portable, no configs buried in User files (Documents, etc)
Game: Castlevania: Curse of Darkness
Actions: Boot game, load save file, multiple 360 motions on left stick

--------------------------------

PCSX2 Nightly (WX) - 1.7.2677
(Checked control options: XInput, Monitor when in background
Running my existing config that has been carried through 3+ years of PCSX2 updates)
**Result:** character runs in all directions

PCSX2 Nightly (Qt) - 1.7.2843
(Checked control options: Enable XInput Input Source
Fairly new config, just started it yesterday; attempted to match my existing config in the WX build)
**Result:** character runs in most directions, switching to walking randomly with down-left, always walks on down-right

PCSX2 Nightly (Qt) - 1.7.2843
(Checked control options: Enable SDL Input Source
Same as previous, just with SDL instead of XInput)
**Result:** character runs in most directions, switching to walking randomly with down-left, always walks on down-right

PCSX Nightly (WX) - 1.7.2843
(Pulled existing configs from previous WX install for consistency; expected behaviour should be the same as 1.7.2677)
**Result:** character runs in all directions, same as previous WX version

And just to be exhaustive and rule out configs being the problem

PCSX2 Nightly (WX) - 1.7.2843
(fresh install, brand new configs, nothing changed from default except adding my memory card and BIOS file)
**Result:** character runs in all directions, same as other WX tests

PCSX2 Nightly (Qt) - 1.7.2843
(fresh install, brand new configs, added my memory card and BIOS file. Enabled both SDL and XInput, used controller auto-config to map SDL and test, then map XInput and test)
**Result:** Same as other Qt tests on both SDL and XInput. Character runs in most directions, down-left will randomly flip to walking, down-right with always walk

-------------------

Testing seems to indicate the the problem is specific to the Qt build.  SDL and XInput also produce the same results, so it's probably due to how the Qt pad plugin polls the controller?  I also tried another controller (newer DualSense) and while the problem wasn't as noticeable, it still occurred occasionally on the down-right direction, so there might be a modicum of controller jank in play as well.

Like [butterbutts](https://github.com/butterbutts) said, changing the axis scale seems to be an okay workaround (1.05x eliminated the problem for me on the DS4), but no adjustments are needed on the WX build.  Maybe it's just that Qt has a smaller scale baked into it, so anything a little less than perfect will cause this?  I compared WX and Qt (at 1.0x axis scale), and noticed in Qt I had to push the stick a fair amount further before 'walking' became 'running'.

Hopefully that provides some helpful info, happy to provide any other testing info you need.

**Comment by CookiePLMonster** [comment]
So I checked and there actually isn't anything wrong - it's **just** that in wx the default axis scale is equivalent to Qt's x1.33!
![image](https://user-images.githubusercontent.com/7947461/171999922-f06606bc-0011-4a3f-b721-c0482ddc65e5.png)

**Comment by iTsukishimaKei** [comment]
i'm playing basara heroes in pcsx 1.6.0 and having this issue as well and figured it worked well when i used this setting on the Analog 
![Screenshot 2024-03-18 002950](https://github.com/PCSX2/pcsx2/assets/163761741/d3d16117-a950-424d-b644-959137332b20)

**Comment by NABN00B** [comment]
Bumping this because it's still an issue in v2.0.2 using my DualShock 4. Also tried with a low-budget DInput controller and that works perfectly. The difference is that DS4 has circular analog input while the cheap one has square analog input. Adjusting the sensitivity doesn't help (in fact it doesn't seem to do anything at all).

We need a way of translating circular analog input square analog output.

**Comment by celimaskaya** [comment]
bumping this because it is still an issue on 2.1.210. moving both analog sticks (in suikoden 3 the right stick is also for movement)  sets the character move speed to 0. Controller is a DualShock 4, tried it with SDL and with DS4Windows

**Comment by Mrlinkwii** [comment]
@celimaskaya  please use the discord / forums for support :)
