### ISSUE TITLE
[BUG]: Bug with the updater

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#6250]
### Describe the Bug

It's not really a bug but...
If you rename the main executable and run it,when you check for updates pcsx2 will download the latest version and run the same executable it was started before the update(the old renamed exe)

pcsx2-qtx64-avx2 looks too long so I rename it to just pcsx2 and pcsx2 is only downloading the pcsx2 version you are running(SSE4 or AVX)

### Reproduction Steps

1.Download the Qt version manually
2.After extracting the archive,rename the main executable
3.Run pcsx2 and check for updates
If there are updates pcsx2 will download and replace the old version but after the restart it will run the same executable it was running before

### Expected Behavior

Maybe delete the old executable and rename the new one to the name the old one was set to 

### PCSX2 Revision

Any

### Operating System

Windows 10 (64bit)

**Comment by dio-gh** [comment]
Lol, I remember asking for this as a feature back in RPCS3 :joy:

I guess one man's bug really is another man's feature.

**Comment by stenzek** [comment]
Why are you renaming the exe? If you mess with a program like that, expect things to break.

Therefore, invalid and working as intended, it specifically runs the current exe name because if we ended up having both avx2/sse4 builds in the same archive, it would need to run the correct one. The updater needs to be forward compatible in this manner.
