### ISSUE TITLE
[Feature Request]: (Qt) Remember last position in the game grid/list

### ISSUE THREAD

**Issue by Rex000** [PCSX2/pcsx2#6405]
### Description

A feature to save your current position in the game list/grid and recall it the next time you open the emulator.

### Reason

When I'm playing some game on a regular basis, I always find myself scrolling through the game list/grid to get to that game whenever I open PCSX2 which is a bit inconvenient.

### Examples

None required.

**Comment by dio-gh** [comment]
I don't find this to be a sound design.

Depending on the time difference between application launches, or if the user experienced a significant-enough context switch. it may very well be not obvious why the app restored the list scroll state. Would feel like a bug/oddity for many as a result, and you can't keep adding options unless you want to make the settings even more of a plane cockpit than it already is shaping up to be.

If you want to get to your game of choice quick, click on the first game in the game list, then start typing your game's name. It will jump to it as you type.

Example:

- first game in my game list is Crash Bandicoot WoC, so I click on that
- i press `t`, I get Tekken 4 selected
- i quickly move on to pressing `r`, as if i was typing the name of the game
- True Crime: NYC becomes selected. all i need is to press enter now

This works in many places outside of the emulator as well by the way, though it may be limited to first character only (such as on your desktop, in the file browser, etc.).

Hopefully in the future a search feature will be included so that this behavior will be more obvious.

**Comment by Rex000** [comment]
I'm doing the same as in your example. But it doesn't work very well for games that have the same beginning name but have several sequels like for instance Resident Evil or WWE games. 

Now if I want to search for Resident Evil Code Veronica, the ideal keyword for it would be "Veronica", which obviously won't work here because it will bring up the "V" category of games.

Mame already has this feature and I believe I have seen it elsewhere too. It just stores your position in the list and the next time you open it, you are at the same spot.

**Comment by Rex000** [comment]
I'm doing the same as in your example. But it doesn't work very well for games that have the same beginning name but have several sequels like for instance Resident Evil or WWE games.

Now if I want to search for Resident Evil Code Veronica, the ideal keyword for it would be "Veronica", which obviously won't work here because it will bring up the "V" category of games.

MameUI already has this feature and I believe I have seen it elsewhere too. It just stores your position in the list and the next time you open it, you are at the same spot.

**Comment by dio-gh** [comment]
The way this is normally resolved is through a "Last Played" section. This, combined with a search field would/will resolve this completely.

That being said, jumping to Resident Evil games should already put you close enough that you can pretty much immediately select whichever sequel with your mouse, no?

**Comment by stenzek** [comment]
-1, this is completely silly. If you add a new game, it'll scroll to the wrong position anyway.

Having a search box is on the todo list.

**Comment by Rex000** [comment]
Ok, but it's not too often that you add a new game.

That said, I'm fine with a search box. Just want to quickly get to the game that I want to play with the least amount of hassle.

**Comment by Rex000** [comment]
Ok, but it's not too often that you add a new game.

That said, I'm fine with a search box. Just want to quickly get to the game that I want to play with the least amount of hassle.

Though for the search box, if possible I'd request it be made in a way that when you open the emulator and start typing, you automatically type in the search box. An example is Discord -- when you start typing, you're automatically put into the text typing box.

**Comment by stenzek** [comment]
It's on the todo list, but it's extremely low priority, much more important things to address first.

You're welcome to implement it yourself and open a pull request.

**Comment by dio-gh** [comment]
> if possible I'd request it be made in a way that when you open the emulator and start typing, you automatically type in the search box.

That's... also a bit odd, and will depend on how the search box will be implemented (i.e. will it be hidden by default). Discord is a chat application, it only makes sense to have the typing textbox focused by default.

This is not the case here necessarily, and hitting e.g. a CTRL+F will come plenty natural to everyone who ever used a web browser. If anything, a button press after startup should do the jumping behavior by default (as opposed to the user having to select a game first), as that's the usual expected behavior (see anywhere inside Windows).

**Comment by jonasos3** [comment]
> The way this is normally resolved is through a "Last Played" section. This, combined with a search field would/will resolve this completely.
> 
> That being said, jumping to, say, Resident Evil games should already put you close enough that you can pretty much immediately select whichever sequel with your mouse, no?

A "last/recently played" sort would be great. In Wx it was easy to navigate using the mouse; start the app, go to DVD-ISO Selector, select from the recently played games, then boot. Qt is a bit more finicky, either you have to scroll through a list with the mouse or type it with the keyboard. Of course, not a big deal or priority, but a welcome QOL feature.

**Comment by stenzek** [comment]
Search and sort by recently played (based on serials) has been implemented for some time now.
