### ISSUE TITLE
[Feature Request] [Regression]: Missing individual button sensitivity with removal of plugins

### ISSUE THREAD

**Issue by ElderCub** [PCSX2/pcsx2#6629]
### Description

In the past using the Lilypad plugin allowed you to set the pressure sensitivity of each button allowing you to overcome limitations of emulated controllers compared to their modern counterparts.

Allow the user to wheel click on a bound button to open a modal or window with button specific options such as sensitivity.

![image](https://user-images.githubusercontent.com/13523975/179087279-96a5ce41-9530-4bf1-81c0-a4b5e103509f.png)

### Reason

With the new pluginless version of pcsx2 this can only be rescaled for the whole controller so to correct throttle inputs also upsets the steering sensitivity.

For now I'll be rolling back to an older version of the emulator as this impacts my enjoyment of the games that are affected by it.

### Examples

Gran Turismo 3 (GT4, Tourist Trophy, likely more) have analog button support. Placing the accelerator on R2 on real hardware allows around 20% of the button's throw to act as the throttle range with the latter 80% being 100% pressure, this is very sensitive with a modern analog trigger.

**Comment by Blackbird88** [comment]
> Gran Turismo 3 (GT4, Tourist Trophy, likely more) have analog button support. Placing the accelerator on R2 on real hardware allows around 20% of the button's throw to act as the throttle range with the latter 80% being 100% pressure, this is very sensitive with a modern analog trigger.

While not a solution to your feature request, these games in particular can be improved with the **Adjusted triggers sensitivity** cheats made by @CookiePLMonster 
https://cookieplmonster.github.io/mods/gran-turismo-3/
https://cookieplmonster.github.io/mods/gran-turismo-concept/
https://cookieplmonster.github.io/mods/gran-turismo-4-prologue/
https://cookieplmonster.github.io/mods/gran-turismo-4/
https://cookieplmonster.github.io/mods/tourist-trophy/

**Comment by Aphegis** [comment]
There is also the need of fixing the "analog deadzone" parameter, it's noticeable how in games like Gran Turismo 4, even with the analog deadzone set at "0", there is still a substantial zone that is not detected by the gamepad.

![GT 4 1](https://user-images.github
![GT 4 3](https://user-images.githubusercontent.com/34956440/195600275-3b98cc82-d5ba-4132-950d-e26559812041.JPG)
usercontent.com/34956440/195600261-75e52c62-efd2-428f-a060-cb80759d6847.JPG)
![GT 4 2](https://user-images.githubusercontent.com/34956440/195600270-779f84e5-b6be-4fa9-9edd-b6205a4a5434.JPG)

Image 1: No input at all.
Image 2: I'm moving my Dualshock 4 left analogic to the right but the game still doesn't registers it (analog deadzone at 0)(notice how the windows tool already registers a substantial amount of movement).
Image 3: Finally the game starts registering the smallest turn possible.

**Comment by Mrlinkwii** [comment]
in terms of pressure sensitivity  QT  has a pressure modifier settings you can try
![image](https://user-images.githubusercontent.com/17685135/195682051-588f683a-98ed-44b7-b663-74a9344d35c6.png)

**Comment by stenzek** [comment]
> There is also the need of fixing the "analog deadzone" parameter, it's noticeable how in games like Gran Turismo 4, even with the analog deadzone set at "0", there is still a substantial zone that is not detected by the gamepad.

Then you probably need to adjust the sensitivity. You can use padtest to find the values the emulated pad is reporting to the game: https://cdn.discordapp.com/attachments/309643527816609793/960157429146976296/padtest_ps2.elf

**Comment by Aphegis** [comment]
Thanks for possible solutions but i wasn't able to fix it.

> in terms of pressure sensitivity QT has a pressure modifier settings you can try ![image](https://user-images.githubusercontent.com/17685135/195682051-588f683a-98ed-44b7-b663-74a9344d35c6.png)

I tried this but it only changes the sensitivity, it doesn't change the deadzone at all, am i missing some option that i need to activate so it affects the deadzone, or something like this?
 
> Then you probably need to adjust the sensitivity. You can use padtest to find the values the emulated pad is reporting to the game: https://cdn.discordapp.com/attachments/309643527816609793/960157429146976296/padtest_ps2.elf

You're talking about the "Analog sensitivity" parameter? I tried it from 0.2 to 2 and unfortunately it doesn't change the deadzone behavior at all, only the sensitivity of the analogic (so it still requires the same amount of movement before the emulator starts registering any steering like i explained in my previous post).

At this point i would like to know if the problem is just in my system and if you guys on yours are capable of steering cars in GT 4 (or other games) using the QT version in the same way that games like Formula 1 22, Forza 7, etc adjusting only the sensitivity? I mean like with no deadzone at all, moving the left analogic just a tiny little bit and already being able to feel steering? Anyone with GT 4 can please try to quickly replicate the steering behavior? I'm really curious and i spent hours and hours trying to fix this with no success. Thank you.

**Comment by Formedras** [comment]
@Aphegis You didn't really specify if the deadzone was actually because of the emulator or because of the game. Try the PadTest homebrew and see if THAT also has a deadzone.
If not, then it's the emulator; either there is a deadzone in effect or what we need is an anti-deadzone (like seen in Steam Input's settings).
If yes, then it's part of the game and you need additional patch codes to remove it.

**Comment by ElderCub** [comment]
Since this issue was opened I've been relying on the cheat code, however I'm playing with a wheel now and the cheat doesn't appear to work for the simulated wheel devices provided the emulator. "Skip deadzone" or "Anti-deadzone" as steaminput would call it has become relevant again. Requiring me to press the brake pedal down a little less than half way to start. Can the old lilipad code be integrated into the new Shift+LClick menu? 

Edit: Related #9154

EditEdit: Nevermind I had inversion ignoring enabled causing a weird binding
