### ISSUE TITLE
[BUG]: Crash when interpreter with cache enabled is toggled off

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#6637]
### Describe the Bug

Pcsx2 completely crashes when I re-enable the recompiler, if interpreter cache was previously enabled. 

### Reproduction Steps

Disable recompiler
Start a game (or at least SCES-52424, bios seemed fine). 
Even just in the loading screens re-enable the recompiler. 

### Expected Behavior

It shouldn't crash. 
Emulation hangs also seem to happen if I play with the toggles too much, but I guess that's way lower priority (if begging so much for problems can be considered a bug at all, that is). 

### PCSX2 Revision

v1.7.3073

### Operating System

Windows 10 (64bit)

### CPU

i5-10300H

### GPU

RTX 3060 laptop

### Emulation Settings

![immagine](https://user-images.githubusercontent.com/9366725/179251411-422c589a-fa17-444a-a3e0-13a23473facb.png)

### Logs & Dumps

[pcsx.zip](https://github.com/PCSX2/pcsx2/files/9121931/pcsx.zip)
I have two crash dumps here.

**Comment by Mrlinkwii** [comment]
can this be checked on master :)

**Comment by refractionpcsx2** [comment]
Probably still crashes, since the cache doesn't flush.

**Comment by TheTechnician27** [comment]
Okay, so I disabled the recompiler in 'Advanced' settings, then while still in PCSX2, I booted into SCUS-97353 (UYA). Just for fun, I got in-game into Veldin, and reenabling the recompiler briefly stuttered, but it seems to have worked successfully (no crash at least). This worked both for global settings and for per-game settings on PCSX2 v2.1.226. @Mrlinkwii @JordanTheToaster @kamfretoz If two or three of you can also independently verify this issue is fixed, I think we can close this.
