### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by ronoverdrive** [PCSX2/pcsx2#6663]
### Describe the Bug

On a fresh install when attempting to open a dialog window to select a game or bios directory the emulator locks up. This only happens with the Qt UI not the Wx UI.

### Reproduction Steps

Download and extract the latest nightly for the Qt AVX2. Run the exe. Either click the "Add Game Directory" button or open up the BIOS settings and click "Browse." Emulator locks up.

### Expected Behavior

Should open up a dialog box to select a directory.

### PCSX2 Revision

v1.7.3088 Qt

### Operating System

Windows 10 (64bit)

**Comment by F0bes** [comment]
Use Open Shell, not something like NewOldExplorer as it's having problems with upstream QT, not related to us.

**Comment by F0bes** [comment]
For now I am going to assume that this has resolved your issue. If not, feel free to comment and I can re-open.

**Comment by Metamoran** [comment]
Sorry for necroing this, but I feel it's worth posting about it for those having the same problem. I was running into the same issue, and it was indeed being caused by OldNewExplorer (to be referred to as 'ONE' going forward). Unfortunately, ONE is apparently abandonware by now and thus bound to never get fixed. Fortunately, we only need to disable ONE long enough to select the Game Library/BIOS/etc directories within PCSX2, after which it can be re-enabled with no issue. There's no need to disable it on subsequent runs after the setup has been completed unless we want to select different directories.

**Comment by RedDevilus** [comment]
> Sorry for necroing this, but I feel it's worth posting about it for those having the same problem. I was running into the same issue, and it was indeed being caused by OldNewExplorer (to be referred to as 'ONE' going forward). Unfortunately, ONE is apparently abandonware by now and thus bound to never get fixed. Fortunately, we only need to disable ONE long enough to select the Game Library/BIOS/etc directories within PCSX2, after which it can be re-enabled with no issue. There's no need to disable it on subsequent runs after the setup has been completed unless we want to select different directories.

I heard talks about NewOldExplorer or One or whatever it is called now that it already bypasses any detection and breaks Qt before it has any chance to be detected to be stopped. Unless this statement is deemed uncorrect, I don't think it can be fixed  on PCSX2 side besides not using it.

**Comment by Metamoran** [comment]
> I heard talks about NewOldExplorer or One or whatever it is called now that it already bypasses any detection and breaks Qt before it has any chance to be detected to be stopped. Unless this statement is deemed uncorrect, I don't think it can be fixed on PCSX2 side besides not using it.

Well, it's not a problem caused by PCSX2 itself and development of OldNewExplorer is dead, so yeah. The workaround is extremely simple (the only real issue being my failure to realize what exactly was causing the emulator to hang, though Google managed to lead me here). Anyways, like I said I only necroed this thread to give confirmation and some more info for anyone else with the same issue, not to demand a fix. My thanks to you and F0bes.

PS: Open-Shell was mentioned above, but it is not a valid alternative in my case since it lacks the one and only feature I use ONE for (showing the details pane at the bottom of Explorer windows).

**Comment by F0bes** [comment]
In order to stop it we would have to hook any library injection / load into our process. It's  manageable, there's a library for it iirc and would open up other things like troublesome anti virus detection (looking at you, ESET). But alas, no one wants to dedicate their time to that as there are more important things on our to-do lists.
