### ISSUE TITLE
[BUG]: Kao the Kangaroo - Round 2 is incredibly difficult to play due to PCSX2's input lag. 

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6840]
### Describe the Bug

During the snowboarding level in Kao the Kangaroo - Round 2, you have a very small window of time to press jump to avoid falling in the lava. In PCSX2 this section is borderline unplayable due to input lag. Half the time my input is dropped entirely, and the other half the input is simply not registered in time to prevent dying. Fullscreen helps slightly, but not enough. I have played this game extensively on real hardware and it should not be this hard. I am playing with a wired Xbox one controller. 

![Kao the Kangaroo - Round 2_SLUS-20296_20220814165113](https://user-images.githubusercontent.com/96800307/184526163-8a3b2e29-5bfd-483e-87b9-92b2e97de6c5.png)

### Reproduction Steps

Play the lava section of the level and count how often your input is ignored or doesn't register in time. 

### Expected Behavior

The game should register my inputs correctly. 

### PCSX2 Revision

pcsx2-v1.7.3205-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
PCSX2's input lag being bad is a meme which hasn't been true in some time.

Set vsync queue size = 0 (or tick optimal frame pacing), **disable** vsync to prevent your driver queuing frames, don't use skip duplicate frames, and optionally use exclusive fullscreen.

The most you'll get is +1 frame, because of where the vblank interrupt happens, and that's assuming your input was right at the end of the 16ms window.

**Comment by drachenschanze** [comment]
@stenzek I am not memeing, I am getting dropped inputs. I'll try the things you suggested.

**Comment by refractionpcsx2** [comment]
I must be honest, I've never heard of PCSX2 dropping inputs.  Lagging? sure, but dropping them completely? that's a new one on me.

**Comment by drachenschanze** [comment]
@refractionpcsx2 Could be the game is just poorly programmed. I tried Stenzek's suggestions and while I still got a few dropped inputs, it helped enough to get me past the section. Though I found that Vsync off + fullscreen causes screen tearing.

**Comment by refractionpcsx2** [comment]
it will do yeah, ideally you need to use VRR like gsync or freesync on it. but it's either that, or tearing, or windows gives you 3 frames of lag, so it's a lesser evil if input lag is something you're having a problem with.

**Comment by TransparentBlue** [comment]
There's a possibility that the input lag / dropped inputs are caused by the game not doing something hard to emulate, one of the Metal Slug game (probably Anthology) used to have that (might still have it, i haven't checked in years), it was pretty ludicrous amounts of delay (something close to half a second)  so it clearly wasn't A/V related.

**Comment by dezraj** [comment]
Hello @refractionpcsx2 and @stenzek! I'm sorry to bump this issue again but I was also trying to implement stenzek's suggestions in order to possibly fix the lag in Konami's time precision sensitive games such as the Dance Dance Revolution series, but I wasn't able to turn on exclusive full-screen mode as recommended. When I click on Full-screen mode in the Graphics -> Display tab the only option apparently available is "Borderless Fullscreen".

I'm using the Qt version, build 1.7.3260.

Thank you so much in advance if you eventually read this.
