### ISSUE TITLE
[BUG] (Qt): Globally installed linux build cannot find resources

### ISSUE THREAD

**Issue by Hirato** [PCSX2/pcsx2#6939]
### Describe the Bug

The QT_BUILD fails to run games when installed globally installed inside /usr/
When launching the following lines can be seen

```
AppRoot Directory: /usr/bin
Resources Directory: /usr/bin/resources
```

The actual resources however, are actually at `/usr/share/PCSX2/resources/`
These resources include fonts, the GameIndex, various icons, and the shaders.
The WxWidgets build does not have this issue; this is unique to the Qt build.

### Reproduction Steps

Launch a game
App closes immediately
see this in the terminal
```
/usr/src/debug/pcsx2/pcsx2/Frontend/ImGuiManager.cpp:89: assertion failed in function bool ImGuiManager::Initialize(): Failed to load font data
```

### PCSX2 Revision

v1.7.3256

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch

**Comment by kenshen112** [comment]
You have a few options. Use the AppImage builds, or a package like pcsx2 -git to fix this issue

**Comment by stenzek** [comment]
The old "package mode" isn't supported with Qt. We probably should make cmake throw an error if it's enabled though.

**Comment by Hirato** [comment]
That's rather unfortunate, since it means every distro will end up
maintaining their own patch for this,
or do something cheeky like have a script execute the binary inside
`/usr/share/PCSX2` instead.

At least this ticket is here I suppose, to make the "not planned" stance
clear.

**Comment by tellowkrinkle** [comment]
No need for a script, you can symlink it

AFAIK the plan is to eventually bundle resources into the executable, but that hasn't happened yet

**Comment by stenzek** [comment]
We don't support packages in the first place, so it's a non-issue.

I've been through this many times, but putting stuff in /usr/share:

1. Doesn't make sense, since it's not shared between applications.
2. Makes the application not self-contained for easily being moved/removed.
3. Means you can't have multiple versions installed.
4. Every other platform is self-contained (Windows, Mac).

With basically no upsides.

**Comment by Hirato** [comment]
@tellowkrinkle wow that actually works, what a neat trick.
Since that works, why not have pcsx2-qt install to /usr/share/PCSX2 with a symlink from /usr/bin instead of deliberately breaking package mode?


@stenzek You're wrong, I'd rather not argue this, but since I'm not adverse to flame wars...
1. /usr/share is for shared static resources, so that ALL USERS can access it; if multiple apps have used for a single resource, that's just a bonus.
Linux is primarily a multi-user system, and that is the paradigm for which this packaging system is intended. Granted we mostly only ever deal with a single user, that is beside the point.
Depending on how things go (i.e. embedding the resources) I can envision a distro splitting PCSX2 into pcsx2-wx, pcsx2-qt, and pcsx2-common; would this now satisfy your arbitrary condition of "shared between applications"?
2. You'll have to explain to me how removing PCSX2 completely is magically made more difficult by changing the process from `rm PCSX2-$version.AppImage && rm -rf ~/.config/PCSX2` to `pacman -R pcsx2 && rm -rf ~/.config/PCSX2`.
Same with moving data from one system to another; I can copy the config folder, AND an AppImage, or I can copy my config folder AND do the equivalent of `apt install pcsx2`.
It's not a more difficult method, it's just a different method; one is user managed, and the other is distro managed
3. You absolutely can have multiple versions installed simultaneously via a package manager, but this is **immensely undesirable**, and only done (and supported) in *extremely* specific and deliberate cases, for example how Ubuntu and Debian handle Kernel Upgrades.
This also requires you to clean up the old versions over time (there's usually something for dealing with orphaned packages), but it's not that different to just cleaning up old and irrelevant AppImages.
The only caveat to such an approach is that you can't can't go back and deliberately install old versions to bisect/test where an issue was introduced.



Anyways, I've said my piece, so I will not be responding further to this ticket.

**Comment by stenzek** [comment]
I contemplated whether I should even respond here, as it's obviously an inflammatory post, contradicting itself trying to illicit a response. So instead I'll put an invitation out:

I don't even use Linux on the desktop. I begrudgingly took over maintenance because Linux Qt was broken for months, with nobody else putting the time in to make it work. Wayland especially has caused much frustration. So, I would be very happy for someone else to take over maintenance for the platform, and then you can have the debate with them instead, and change things if needed.

However, said maintainer has to actually maintain the platform. That includes fixing any bugs and actioning feature requests where there's platform disparity, there's several currently open. Not just changing a couple of lines to support their package and nothing else. Some people expressed interest, but again, never actually did anything for months, just talk, hence why I  ended up doing it (because otherwise it's just delaying getting rid of wx). So, if you can "put your money where your mouth is", then I'll gladly step back, it would be less work for me, I already have too much on my plate.

But until then, users have to accept things as they are. This is free software, worked on by volunteers, in our spare time. You have the right to suggest ideas/changes, just as we have the right to reject them. Ideally we could make everyone happy and action every request, but that's not feasible with commercial software, let alone a team of hobbyists. Alternatively, submit a patch/pull request. But again, we don't have to accept it, in which case, you have the freedom to fork the software. If yours is superior, I'm sure users will gravitate to it instead.
