### ISSUE TITLE
Lupin The Third : GSdx regression both in software and hardware mode

### ISSUE THREAD

**Issue by prafullpcsx2** [PCSX2/pcsx2#695]
The game used to work correctly in very old GSdx versions but slowly more and more bugs cropped up in the game. Software mode was broken first, then DX10 HW and lastly DX9 HW.

Issues with the game:-

Texture corruption & Totally missing textures (See the boxes)
Problem with Radar especially in HW mode
Holes in the wall (partially fixed by Using 8 bit textures)

Here is a GS Dump.

I think @gregory38  already had a look at this, posting here so @gabest11 can have a look and hopefully fix it.

![lupin](https://cloud.githubusercontent.com/assets/12788199/9027584/d327a54e-3978-11e5-9974-a45ff829ae60.jpg)

http://www.filedropper.com/lupin

**Comment by gabest11** [comment]
Don't know why it looks broken, trying to find the last good version on googlecode.

**Comment by prafullpcsx2** [comment]
Last perfectly working build which I found is this-

http://guliverkli.sourceforge.net/GSdxv1-8.zip

It's probably r782 from here http://sourceforge.net/p/guliverkli/code/commit_browser

You can run that build to see how the game should actually look (check screen)-

Next working build which I found was two months after this and it was broken in software mode. 

After a few builds even DX10 HW mode was broken. Although DX9 HW mode showed other bugs but textures were ok in this till r1340 on google code.

https://code.google.com/p/pcsx2/source/detail?r=1340

![lupincorrect](https://cloud.githubusercontent.com/assets/12788199/9040683/4f49c3ac-3a21-11e5-8bb9-08cba11244f2.jpg)

Here is a block dump if you can test with pcsx2, you will notice that every single screen is broken in one way or other. Infact even the first screen which now shows only a small yellow line with software mode is supposed to be " Now Loading " screen. There are two cutscenes which you should skip to avoid getting out of blocks.

http://www.filedropper.com/showdownload.php/lupin_1

**Comment by refractionpcsx2** [comment]
half the options on the title screen are missing too

**Comment by gabest11** [comment]
This is a nasty one. They seem to set random texture sizes, then address them outside the bounds very liberally.

**Comment by gabest11** [comment]
For example, the first image that shows up (I think this is the now loading screen) is at y=96-128, also reagion clamped to this range, but TH=5 (height=32 pixels).

**Comment by gabest11** [comment]
At least now we know how ps2 handles out of bounds texture addressing, it just lets it. Texture sizes are informal.

**Comment by gabest11** [comment]
Looking through the code, we could add a dirty fix by extending the cached texture size to the upper limits of the region clamp values. Not sure what to do in repeat mode yet. And as I see, I forcefully do 

std::min<uint16>(context->CLAMP.MAXV, th - 1); // ffx anima summon scene, when the anchor appears (th = 256, maxv > 256)

... to prevent over-addressing the texture buffer. 

In non-region clamping mode, the limit is set automatically, therefore MAXV should be set to TH automatically, even on real hardware. So, the only problem is the region mode.

**Comment by gabest11** [comment]
Btw, the green highlighting of the menu items also look a bit bogus. I wonder why, it must be an unrelated problem.

**Comment by gabest11** [comment]
Every region mode, including horizontal and repeat modes are affected, if I remove the range limits by texture size (to allow addressing outside), then opencl renderer gets fixed because it uses no texture cache.

**Comment by gregory38** [comment]
```
At least now we know how ps2 handles out of bounds texture addressing, it just lets it. Texture sizes are informal.
```
Personally I think GS doesn't have any notion of texture. Just some parameter to interpret a blob of data. Sometimes I feel game uses the GS as a pseudo-compute shader.

```
the opencl renderer gets fixed because it uses no texture cache.
```
Is it useless on openCL or no time to implement it?

```
I think the fix will be to detect this problem and increase TW/TH as much as needed. It does not work for directx, and maybe opengl, because the vertex shader uses the original values. We should push through the pipelene the premultiplied texture coordinates instead of normalized, as the sw renderer, and do texture lookups by integers and loads to be able to apply this workaround.
```
Actually I was planning something similar. I mean using absolute value instead of normalized value. It would avoid bad resizing when reading back the RT as a 1024x1024 textures. And improve rounding (truncate as int)

I'm still trying to decipher your explanation. Could you show me an example of the bad case?
What are the TW/TH value of the texture? The clamping mode? UV or ST coordinate? How do you guarantee that the final lookup remain in the GL texture. Or the plan is to increase the size of texture. For example GS requests a 32x32 texture but we create directly a 128x128 texture.


If you want to code something on GSdx, I could propose you to port the texture shuffling code/depth support / HDR float color clipping.

**Comment by prafullpcsx2** [comment]
https://code.google.com/p/pcsx2/issues/detail?id=262

I think this relevant to the topic?

**Comment by gabest11** [comment]
I don't think xenosaga is related to this.

To sum it up:
- there are certain given TW/TH values of TEX0 badly set by the game programmers,
- texture coordinates refer to a larger texture,
- there are two clamping modes that do not automatically clamp to TW/TH, region clamp and region wrap, where it seems to be perfectly valid to sample outside the texture if the clamping values produce such coordinates.

This game, lupin the third, is full of these problems. I can give you links to the iso if you need it.

My fix for sw and cl rendering is to extend TW/TH as much as needed before GetTextureMinMax and use the modified TEX0 from that point. Ideally, I'd put this before the virtual Draw() call, but the vertex transformation functions and the vertex shader needs the original values.

**Comment by prafullpcsx2** [comment]
I didn't meant xenosaga, I meant the issue mentioned there [quote] ALWAYS update the 
whole texture (1024x1024 or 1024x512) instead of the intended size (64x64 
or such size). 
The function returning the bad dirty region is the following :

void MinMaxUV(int w, int h, GSVector4i& r)

(it generate always the whole texture in DX9, while it works fine in DX10) [/quote]

So Lupin textures were also working ok with DX9 till that revision and were broken after that fix for xenosaga. Anyway, mine is only the guess work. :)

**Comment by gabest11** [comment]
It was just a problem with the min/max calculation. I mentioned this function, because the texture size is also used here combined with the min/max values of the texture coordinates and the clamping values, and if these do not overlap the texture size wins and reduces the fetched texture area to a smaller texture than needed. For example, "now loading" texture is 256x32, but sampled from x=0-170 y=96-128.

**Comment by gabest11** [comment]
> Is it useless on openCL or no time to implement it?

Faster to just read the system memory, and I think it is cached somewhere already between the gpu-cpu, so there are no overwrites happening.

**Comment by gabest11** [comment]
Dumped some of the corrections I make to TEX0 in this game.

TBP0 TBW PSM TW TH UVmax (from VertexTrace) WMS WMT MINU MAXU MINV MAXV

02060 8 20 tw 6=>7 th 5=>6 uvmax 64,32 wm 3,3 (63,64,31,32)
01f40 4 20 tw 6=>8 th 5=>7 uvmax 64,32 wm 3,3 (63,128,31,96)
01ee0 2 20 tw 5=>7 th 5=>7 uvmax 88,120 wm 2,2 (64,95,96,127)
02100 16 19 tw 6=>7 th 6=>6 uvmax 47,47 wm 3,3 (63,64,63,0)
02060 8 20 tw 6=>8 th 6=>7 uvmax 64,41 wm 3,3 (63,128,63,64)
01fa0 4 19 tw 3=>8 th 4=>4 uvmax 9,17 wm 3,3 (7,248,15,0)
02100 16 19 tw 6=>10 th 6=>8 uvmax 64,64 wm 3,3 (63,896,63,128)
02100 16 19 tw 6=>10 th 6=>8 uvmax 64,64 wm 3,3 (63,960,63,128)
02100 16 19 tw 6=>10 th 6=>8 uvmax 65,65 wm 3,3 (63,704,63,128)
01fe0 8 19 tw 8=>8 th 5=>6 uvmax 56,33 wm 3,3 (255,0,31,32)
01fa0 4 19 tw 3=>8 th 4=>4 uvmax 9,17 wm 3,3 (7,248,15,0)
01fe0 8 19 tw 8=>8 th 5=>6 uvmax 257,29 wm 3,3 (255,0,31,32)
02100 16 19 tw 6=>10 th 6=>8 uvmax 65,65 wm 3,3 (63,896,63,128)
02100 16 19 tw 6=>10 th 6=>8 uvmax 64,64 wm 3,3 (63,960,63,128)
01fa0 4 19 tw 3=>8 th 4=>4 uvmax 9,16 wm 3,3 (7,248,15,0)
01fa0 4 19 tw 6=>6 th 2=>4 uvmax 64,4 wm 3,3 (63,0,3,8)
01fa0 4 19 tw 6=>6 th 2=>4 uvmax 64,4 wm 3,3 (63,0,3,8)
02100 16 19 tw 6=>7 th 6=>6 uvmax 64,64 wm 3,3 (63,64,63,0)

**Comment by gabest11** [comment]
Went through my 147 gs dumps, found one more with this problem, skygunner, water in the menu background, no visible problems though. Looks like the vertical mask (=127) creates a possibility of addressing above 64x64, but not triggered.

01ea0 0 19 tw 6=>6 th 6=>7 uvmax 320,769 wm 3,3 (63,0,127,0)
01ea0 0 19 tw 6=>6 th 6=>7 uvmax 192,512 wm 3,3 (63,0,127,0)
01ea0 0 19 tw 6=>6 th 6=>7 uvmax 518,640 wm 3,3 (63,0,127,0)
01ea0 0 19 tw 6=>6 th 6=>7 uvmax 133,257 wm 3,3 (63,0,127,0)
01ea0 0 19 tw 6=>6 th 6=>7 uvmax 193,512 wm 3,3 (63,0,127,0)
01ea0 0 19 tw 6=>6 th 6=>7 uvmax 512,1152 wm 3,3 (63,0,127,0)
01ea0 0 19 tw 6=>6 th 6=>7 uvmax 321,769 wm 3,3 (63,0,127,0)
01ea0 0 19 tw 6=>6 th 6=>7 uvmax 193,384 wm 3,3 (63,0,127,0)
01ea0 0 19 tw 6=>6 th 6=>7 uvmax 128,384 wm 3,3 (63,0,127,0)
01ea0 0 19 tw 6=>6 th 6=>7 uvmax 129,384 wm 3,3 (63,0,127,0)
01ea0 0 19 tw 6=>6 th 6=>7 uvmax 129,385 wm 3,3 (63,0,127,0)

And another two where it was just +1 more than the texture size, probably some rounding error.

**Comment by gregory38** [comment]
```
Faster to just read the system memory, and I think it is cached somewhere already between the gpu-cpu, so there are no overwrites happening.
```
My current understand was that texture cache was used
1/ to avoid CPU-GPU transfer
2/ to reduce the swizzle->linear conversion

Is it correct? I guess SW texture cache was done for case 2. Do you cache only input texture or also the RT in SW? What do you do in openCL, just convert on the fly (with a lookup?) ?

**Comment by gabest11** [comment]
In opencl I do a direct deswizzling lookup, through all the PixelAddress functions, like in the old days. What I mean by hidden caching is probably done after accessing one bit in the system memory from the kernels, then the driver fetches a larger portion into the gpu memory.

There is another important function of the GS's single page texture cache. Same source and target writes work because the target is read into the cache and can be used as a texture in the previous state, and swizzled output writes don't randomly overwrite the pixels between the 16 units (or 8 with texturing) that work on a column (or half column). There are many examples, one I can remember is the wheel rims in gran turismo. 

The funny thing with opencl is that the kernels don't seem to overwrite each others pixels. So it just happens to work for some reason.

**Comment by gabest11** [comment]
I wonder if pixel shaders got fast enough over the time to use buffers and similar lookups as well nowadays.

**Comment by gregory38** [comment]
And how do you handle the RT. You need to swizzle it, or you do it on the fly in the store.

```
The funny thing with opencl is that the kernels don't seem to overwrite each others pixels. So it just happens to work for some reason.
```
I don't know openCL but it likely depends on the caching/coherency behavior. Standard textures (on GL) are Read or Write only. For RW texture you need to set special flags, otherwise it just read the cached data I guess.

```
I wonder if pixel shaders got fast enough over the time to use buffers and similar lookups as well nowadays.
```
The issue is that nowadays people want x3/x4 upscaling. You can easily compare the raw speed with the frequency. Output is likely close of 1 instruction by cycle (on scalar arch). So barely better than 5 years old GPU. However they have bigger cache ^^ And much more shaders. However due to all the sync issue (blending/program/texture state change), I'm not sure that we can really load the GPU.

**Comment by gabest11** [comment]
> And how do you handle the RT. You need to swizzle it, or you do it on the fly in the store.

No render target texture types. When writing the output, it is swizzled to its place in vram. And I invalide the tc as I said.

**Comment by refractionpcsx2** [comment]
What is the status on this?

**Comment by gabest11** [comment]
To also fix HW rendering, we would have to premultiply the texture coords with the original texture size and normalize them again in the shader with the new size. That's a reciprocal multiplication for every pixel, some performance loss, with ifdefs for this case. I might try it some time later.

**Comment by refractionpcsx2** [comment]
Can we not identify these cases so it only does the multiplication on the textures which need it instead of all of them? that should alleviate some of the performance loss.

**Comment by gregory38** [comment]
Code already do a renormalization for WMS/WMT 3. The extra operation for WMS/WMT 2 won't be killer as I'm sure it is not enough used.
