### ISSUE TITLE
Shadow Hearts Covenant broken fusion effect

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#6959]
### Describe the Bug

When using fusion in battle the spherical effect around the character is not rendered properly. The issue has been present for as long as I can remember. Since I started using PCSX2 back in 2014 so it isn't a new issue. 

### Reproduction Steps

Run game in hw mode and use a fusion pay close attention to how the effect looks in hw mode vs sw mode.

### Expected Behavior

Effect should render like sw mode. 

### PCSX2 Revision

v1.7.3264

### Operating System

Windows 11

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

Default

### Emulation Settings

default

### GS Window Screenshots

![Screenshot (4)](https://user-images.githubusercontent.com/12180630/187540195-35ac8bd3-74ca-48f4-8715-333e66614880.png)

### Logs & Dumps

[snaps.zip](https://github.com/PCSX2/pcsx2/files/9456558/snaps.zip)

**Comment by Fothsid** [comment]
After doing some testing, it seems like this chunk of code in the texture cache breaks the effect:

https://github.com/PCSX2/pcsx2/blob/9bcf4d25713abcc8b2746968dc22a5ca291567cb/pcsx2/GS/Renderers/HW/GSTextureCache.cpp#L946-L976

**Comment by BParks21** [comment]
This seems to be fixed.

**Comment by refractionpcsx2** [comment]
awesome, thanks for testing!

**Comment by BParks21** [comment]
> awesome, thanks for testing!
NP

**Comment by Fothsid** [comment]
I think you got a false positive. The glitch doesn't always happen.

This is on v1.7.4157
![image](https://user-images.githubusercontent.com/18036123/221702721-a39fc1e6-26aa-46e1-8156-bec82b79bccf.png)

**Comment by RedDevilus** [comment]
Not sure if a GS Dump will help with that, just wondering to test it on other PRs / master.

**Comment by refractionpcsx2** [comment]
Can you try it on #8289 ?

**Comment by refractionpcsx2** [comment]
Reproduced on my PR.

**Comment by Fothsid** [comment]
Here's a GS dump from #8289 for testing purposes:
[Shadow Hearts - Covenant [Disc 2 of 2]_SLUS-21044_20230228001137.zip](https://github.com/PCSX2/pcsx2/files/10845100/Shadow.Hearts.-.Covenant.Disc.2.of.2._SLUS-21044_20230228001137.zip)

**Comment by refractionpcsx2** [comment]
It doesn't look busted :/

![image](https://user-images.githubusercontent.com/6278726/221711169-09d3dda6-6533-471f-9ed3-d75671519cba.png)

**Comment by BParks21** [comment]
Hmm I tested it several times I couldn't produce the original graphical error

**Comment by refractionpcsx2** [comment]
I tried the dump again and now I can't make it not do it lol

**Comment by BParks21** [comment]
I wasn't even using a dump I was just running the game in the same area performing fusions.

**Comment by refractionpcsx2** [comment]
I can make it work, but I don't know how safe this is, I'm doing a GS dump run to see if it flags anything up, but not expecting much.

The issue is it uses the alpha channel as an 8bit texture, and at one point it does a 32bit draw to the RGBA channels, but then it stets the 8bit texture in the alpha up again, but instead of just killing the alpha channel it kills the whole texture, which it then later tries to use as a 24bit texture, and it has to load from GS memory (which is just garbage), causing the bad effect.

So I'm trying a heuristic where the erase would happen to say if it's a 32bit texture and only the alpha channel is going, make it a 24bit texture and carry on.

![image](https://user-images.githubusercontent.com/6278726/221723916-8547695b-fcd4-49f6-adad-06a3b18939ee.png)
