### ISSUE TITLE
[Feature Request]: Bringing back support for Flightsticks, Wheels, Lightguns etc.

### ISSUE THREAD

**Issue by brad86m** [PCSX2/pcsx2#6979]
### Description

I have collected a good amount of peripherals over the years that I used to use with PCSX2, but since the removal of external plugins, this is no longer possible. The masses don't care about these features, but it was nice for those of us that do. 
Losing analogue (button pressure sensitivity) was bad enough, as the replacement for it now does not have the same effect, at all.
Those that have the real controllers to make use of such feature/s no longer can.

### Reason

.

### Examples

.

**Comment by stenzek** [comment]
Implementing USB in the Qt interface is on the TODO list: https://github.com/PCSX2/pcsx2/discussions/5947

But none of us are interested in working on it, since it requires rewriting a fair bit of code to bring it up to standard. Pull requests are welcome, but please remember we're a volunteer team with limited time, we prefer to work on the things we are interested in ourselves. It's not a job, none of us get paid, therefore interest is the only motivation.

> Losing analogue (button pressure sensitivity) was bad enough

Except it's not lost. There's the pressure modifier, which frankly is a lot more usable than the previous system, as you didn't have a ton of extra buttons to bind. And if you have a DS3, you can use DsHidMini for passthrough pressure.

**Comment by refractionpcsx2** [comment]
Nobody said there was no intention of bringing it back, Sten just said nobody wants to work on it, because moving USB over needs a redecisgn in how the device detection works and you have to make a lot of cross platform considerations and OS specific code, it's ugly, gross, and nobody really wants to do it, at least at the moment.  It's not that we *won't* bring it back, it's just when somebody wants to do it.,

**Comment by stenzek** [comment]
> Look at the modified SPU plugin, which is essential for Fatal Frame audio to work correctly. Speaking with a current developer, besides yourself on the team, basically said to me that he and no one else cares about fixing this, and that it would indeed be rather simple to implement that sound fix within a patch.

If it's such a simple change, then why don't you open a pull request and submit it?

But, if it's a hackfix, then it's a completely different scenario. You might only care about that game working, but every hackfix added means more code that has to be maintained long term, more things which can break when other changes are made, more things which have to be tested, etc. Hacks are not sustainable.

Again, we're not a commercial team with paying customers who we need to make happy to keep our jobs. Frankly, expecting us to work on something we're not comfortable or interested in doing, is a bit rude. This is the same for every volunteer-based open source project. Some light reading: https://boyter.org/posts/the-three-f-s-of-open-source/

**Comment by refractionpcsx2** [comment]
> > Look at the modified SPU plugin, which is essential for Fatal Frame audio to work correctly. Speaking with a current developer, besides yourself on the team, basically said to me that he and no one else cares about fixing this, and that it would indeed be rather simple to implement that sound fix within a patch.
> 
> If it's such a simple change, then why don't you open a pull request and submit it?
> 
> But, if it's a hackfix, then it's a completely different scenario. You might only care about that game working, but every hackfix added means more code that has to be maintained long term, more things which can break when other changes are made, more things which have to be tested, etc. Hacks are not sustainable.

**Comment by brad86m** [comment]
Not wanting to work on something is perfectly normal. Not arguing against that, but maybe don't remove something without the intention of replacing it.

Currently having to use pre-plugin removal builds to play Ace Combats, Time Crisis, Fatal Frame, Armoured Core, and many other games because features that were present have been removed. The main reason for wanting these within newer builds is because of the absolutely horrendous input latency within PCSX2 that has plagued it for decades, which is somewhat better on newer builds. Still far from ideal, but better.

**Comment by refractionpcsx2** [comment]
Okay, you're obviously not listening, you're still banging the "no intention of replacing it" drum.

Have a good day.

**Comment by brad86m** [comment]
There is no intention, it's play as day to see, and that's fine. Just a same as an end user, that's all.

**Comment by stenzek** [comment]
Software evolves, things get changed. If the old way of doing things is so much better, nobody's stopping you from using the old builds.

That's the thing with open source software. If you don't like something, you have the power to fork it, change it, and ideally upstream your changes so everyone benefits. But implying things which aren't true, then flaming the people who give their time up for free is just being an unappreciative ass. If you want to make requests with a greater chance of being actioned, I'd suggest using a commercial emulator. But even that is not a guarantee.

I'm done here too.
