### ISSUE TITLE
Automatically adjust refresh rate 

### ISSUE THREAD

**Issue by LasagnaPie** [PCSX2/pcsx2#70]
All my games are PAL and majority of which run at 50FPS although some games 
are PAL-60 that run at 60FPS, My TV/Monitor supports PAL 1080p50 / 1080i50.

PCSX2 needs an option to automatically adjust the refresh rate to match the games output.

**Comment by avih** [comment]
This is out of scope for PCSX2.

On windows, one could either switch refresh rate via the driver configuration or driver access profiles, or using third party tools which may allow to do that in a batch file, such as [nircmd](http://www.nirsoft.net/utils/nircmd2.html#setdisplay) which has e.g.
`setdisplay {monitor:index/name} [width] [height] [color bits] {refresh rate} {-updatereg} {-allusers}`


> In JAK II and noticed Progressive Scan option changes the frame rate from 59.94 to 60.
> I would assume it would be 59.94 Progressive.

This is a bug where it would always use 60 for NTSC-progressive instead of 59.94 by default (also regardless of custom NTSC rates). Fixed today.

**Comment by filevans** [comment]
> It already does. If it's getting it wrong with some specific game, please specify which so we can look into it.

Hello, Tokyo Road Race PAL has a 50hz / 60hz switcher at bootup but doesn't switch the screen resolution to 60hz, do I need to change any settings?

**Comment by filevans** [comment]
> Wait, I get it. You want it to adjust the SCREEN rate on the computer, not the framelimiter rate.

yes that's what we want, retroarch does it

**Comment by JordanTheToaster** [comment]
> > Wait, I get it. You want it to adjust the SCREEN rate on the computer, not the framelimiter rate.
> 
> yes that's what we want, retroarch does it

Please don't post on 9 yearold issues if you need help use the forum or Discord.

**Comment by filevans** [comment]
> > > Wait, I get it. You want it to adjust the SCREEN rate on the computer, not the framelimiter rate.
> > 
> > 
> > yes that's what we want, retroarch does it
> 
> Please don't post on 9 yearold issues if you need help use the forum or Discord.

the exact same issue still exists on the latest version, and the issue was never closed or fixed

**Comment by JordanTheToaster** [comment]
> the exact same issue still exists on the latest version, and the issue was never closed or fixed

Then use the forums or Discord don't necro a 9 yearold issue please.
