### ISSUE TITLE
[Feature Request]: Qt: Add Toggle Analog Sensitivity button

### ISSUE THREAD

**Issue by Brunokenway07** [PCSX2/pcsx2#7000]
### Description

Right now the Controller Settings in Qt are pretty much perfect with the addition of the Pressure Modifier button, but I see that it doesn't affect the analogs. So I wonder if is possible to add a button to toggle the analog sensitivity or maybe an option to let the pressure modifier to include the analogs.

Thank you

### Reason

Keyboards and some generic controllers don't have any variable sensibility features; for many games is vital to be able to change the pressure applied to the analogs while playing.

There is no need for complicated pressure configurations for each button thanks to the Pressure Modifier button, including the analogs to its effect would make the controller emulation experience complete.

### Examples

Including the analogs to the Pressure Modifier button would be similar to what the PC version MGS2 Substance did when porting the game.

**Comment by stenzek** [comment]
The controller settings panels already have too many options. Once again, I see no need to further complicate it. The pressure modifier exists because everything outside of DS2/DS3 do not have pressure-sensitive buttons, but this is not the case for the sticks.

It's pretty much universally accepted across all emus and games in general that if you want fine-grained analog control, you use a gamepad.
