### ISSUE TITLE
[BUG]: Valkyrie Profile 2 multiple issues: Upscaling and rendering bugs

### ISSUE THREAD

**Issue by DuckSalmon** [PCSX2/pcsx2#7044]
### Describe the Bug

Upscaling Issues:

-  white/rainbow lines at borders in differents locations.
'The Royal Underground Path' for example is afflicted with large rainbow bands on borders.
![Valkyrie Profile 2 - Silmeria_SLUS-21452_20220913114513](https://user-images.githubusercontent.com/20885496/189869923-d2c27e21-f272-4e7a-8fa8-fe623bdfc502.png)

- the infamous Grid texture bug visible in the forests levels. 
![Valkyrie Profile 2 - Silmeria_SLUS-21452_20220913114300](https://user-images.githubusercontent.com/20885496/189870187-d712a37c-2358-40ed-ae0f-cb32e21a2da4.png)
here you can see the grid (it is more visible in the first forest level called "lost forest") and the white bar at the bottom on the screen.

Some levels and area are more afflicted by these two problems. 

- Coriander's tree texture bug 
![photo_2022-09-13_11-15-49](https://user-images.githubusercontent.com/20885496/189866783-2a280eb2-229b-431e-bf63-e3937631d408.jpg)
These trees's fronds appear flashy and with some glitched line.
(white lines also present here)

all of these bugs are caused by upscaling on all rendering modes

Misc bug/rendering bug:

- Battle/map transitions rendering errors
![photo_2022-09-13_11-15-50](https://user-images.githubusercontent.com/20885496/189867098-d10933cb-57b5-49ab-a2ac-719fb47754a6.jpg)
Everytime during battle transitions, teleports and map transitions a strange tile appears in the top left corner.

### Reproduction Steps

No patched, no cheat codes used
tested the game in different rendering modes (opengl and dx 11/12)

### PCSX2 Revision

1.7.3303

### Operating System

Windows 10 (64bit)

### CPU

both AMD and intel tested

### GPU

different machines tested

**Comment by refractionpcsx2** [comment]
As the template says

We do not accept issues relating to upscaling at this time
We are aware of the various problems with upscaling. The issue spans many games and having hundreds of issues for the same fundamental issues isn't particularly helpful. There are several workarounds for graphical problems that come as a result of upscaling
Please try your game at native resolution before creating an issue
If your bug is the result of upscaling please use the forums or discord for assistance with various upscaling workarounds. Additionally, the unofficial PCSX2 [Wiki](https://wiki.pcsx2.net/Main_Page) often lists various fixes for upscaling issues
