### ISSUE TITLE
[BUG]: The Punisher (SLUS-20864) save corrupting on memory card set as a folder. 

### ISSUE THREAD

**Issue by bizarf** [PCSX2/pcsx2#7166]
### Describe the Bug

The game reports that the save maybe corrupt. It then asks to overwrite the save which is successful, and will let you select from the list of saves. Selecting a save will then bring up a message saying "loading failed" with a message saying that it couldn't load the save with the option to retry loading. Selecting yes will loop back to the first message about the save possibly being corrupt. Selecting no would offer the option to make a new save, which doesn't seem to save after making it. 

### Reproduction Steps

1. Set memory card 1 to a folder. 
2. Create a new save.
3. Shut down the game
4. Load the game again
5. Attempt to load the save. 

### Expected Behavior

Save should load. I checked with a regular 8mb memory card file and the game saved and loaded just fine. 

### PCSX2 Revision

1.7.3398

### Operating System

Windows 10 (64bit)

### CPU

FX-8320

### GPU

GTX1060

**Comment by RedPanda4552** [comment]
@bizarf Can you upload a copy of a working save file?

**Comment by bizarf** [comment]
[punisher_memcards.zip](https://github.com/PCSX2/pcsx2/files/9874385/punisher_memcards.zip)

I've included two memcards. The corrupted memcard folder, and the 8MB memcard file (this one has the working save file)

**Comment by refractionpcsx2** [comment]
any chance somebody could try this again with #10791 ?

**Comment by TheTechnician27** [comment]
> any chance somebody could try this again with #10791 ?

On it, ref. :)

**Comment by TheTechnician27** [comment]
I was unable to reproduce the issue with a folder memcard in the first place on v1.7.5550 without pandz's PR.

* I used the SpongeBob.ps2 folder I was using to test BfBB and Movie (I did a sanity check to make sure I wasn't on the PR AppImage, which I wasn't, and SpongeBob.ps2 doesn't show up on the PR anyway since it's damaged goods).
* I created a new game.
* I closed out of the emulator.
* I booted the game back up.
* The save file shows up, and selecting it loads the save file correctly.
* In the menu after loading the game, I saved it again, shut down PCSX2, and opened back up, and it still loads correctly.

**Comment by Mrlinkwii** [comment]
@bizarf  can you double check if this still happens for you , since it works on latest nightly for @TheTechnician27

**Comment by bizarf** [comment]
I just checked on the latest nightly build and can confirm that the issue has been resolved.

**Comment by refractionpcsx2** [comment]
Thanks folks :)
