### ISSUE TITLE
[BUG]: Dialogue text missing or rendered incorrectly in Katamari Damashii when using non-software renderer

### ISSUE THREAD

**Issue by vilhelmgray** [PCSX2/pcsx2#7181]
### Describe the Bug

I'm running the `pcsx2-v1.7.3411-linux-AppImage-64bit-AVX2-Qt.AppImage` build on Fedora 36 with an 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz CPU with an Intel(R) Xe Graphics (TGL GT2) GPU.

Character speech bubble text is missing or rendered incorrectly in Katamari Damashii when a non-software graphics renderer is used; the issue is present with both OpenGL and Vulkan renderers.

The issue is not  present when using the Software renderer; everything appears to display correctly.

### Reproduction Steps

Configure PCSX2 to run with the Vulkan or OpenGL graphics renderer. Load Katamari Damashii and start a new game. When the first character speech bubble appears, the issue will be visibly present.

Complete the same steps with the Software graphics renderer, and the issue will not be present.

### Expected Behavior

I expect PCSX2 with non-software graphics renderers to render the character speech bubbles text correctly and without missing characters, as it appears to do so correctly with the Software renderer.

### PCSX2 Revision

v1.7.3411

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Fedora 36

### CPU

11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz

### GPU

Intel(R) Xe Graphics (TGL GT2)

### GS Window Screenshots

**Running with Vulkan renderer:**
![Katamari Damacy_SLPS-25360_20221012180444](https://user-images.githubusercontent.com/5282157/195458412-7c33cd1b-4a56-4ab8-83bc-f3bfa1c208a1.png)

**Running with Software renderer:**
![Katamari Damacy_SLPS-25360_20221012180548](https://user-images.githubusercontent.com/5282157/195458407-306fc72f-d2bc-4280-af17-2cf8285df35c.png)

**Comment by F0bes** [comment]
Would you be able to create a GS dump for us?
This allows us to replay the issue without owning the game.
It doesn't matter what renderer or GS settings are toggled when you do this.

**Comment by vilhelmgray** [comment]
Here's the GS dump (compressed with gzip so GitHub accepts it):
[KatamariDamashii_SLPS-25360_SpeechBubbleTextRenderBug.gs.xz.gz](https://github.com/PCSX2/pcsx2/files/9776070/KatamariDamashii_SLPS-25360_SpeechBubbleTextRenderBug.gs.xz.gz)

**Comment by F0bes** [comment]
Game is doing some weird stuff where it uploads the font map to the PSMCT32 framebuffer, in a 4HL format. I assume the intent is to load the index into the alpha part of the framebuffer. The texture cache is probably getting confused and trashing that area when it gets looked up because that area is being drawn to, and that's a case the texture cache isn't equipped to handle.

If you enable preload frame data, on GS reloads you can briefly see the correct text, until it gets trashed next vsync (further adding to my hypothesis).

Here is the result with preload frame data on.
![image](https://user-images.githubusercontent.com/29295048/195767454-957450b9-32d0-43af-89f3-45860e78acb0.png)

**Comment by SeruranBlue** [comment]
it is fixed in v1.7.4791.
![Katamari Damacy_SLPS-25360_20230724235359](https://github.com/PCSX2/pcsx2/assets/121824800/a5badada-6d74-4eec-ad09-64f332b47866)

**Comment by Mrlinkwii** [comment]
Nice
