### ISSUE TITLE
[BUG]: Incorrect PNACH extended behaviour

### ISSUE THREAD

**Issue by EdnessP** [PCSX2/pcsx2#7222]
### Describe the Bug

The D-codetype in the <tt>extended</tt> pnach mode, which from my understanding is supposed to emulate the behaviour of [PS2RD on a real PS2](https://github.com/mlafeldt/ps2rd/blob/master/Documentation/code_types.txt), isn't being parsed correctly.

While really any scenario would be affected, this is the following patch I've written for the Japanese version of Burnout 3: Takedown (SLPM-65719) that patches the main font with an unused font that is loaded in RAM temporarily
<pre>
D0488874 05001640 // Check if it's loaded (original ptr)
50DD1890 000200C0 // Copy texture data bytes
00495A90 00000000
20488874 00495840 // Overwrite 3rev pointer DD1640->495840
4068A3D0 00020002 // Overwrite fontmap pointers (main, kbd)
00488870 00000000
</pre>

The 1st line is supposed to only allow the next 5 lines to execute if the 16-bit value at 00488874 is 1640 which becomes true after said texture dictionary is loaded, and then those lines copy the data, overwrite pointers, including the one being originally checked just so the PS2 wouldn't be constantly and needlessly copying 128KiB every frame.
**This works without issue on a real PS2**, but on PCSX2 (tried 1.4, 1.6, 1.7.2225, and 1.7.3442) it seems to constantly be copying those 128KiB even long after the game has overwritten the data with other stuff, which then causes corruption like this and in the end - a complete hang.
![pcsx2_2022-10-17-231720](https://user-images.githubusercontent.com/55930127/196288997-0b67094e-6395-4fa0-a76c-1a94a0555460.png)

### Reproduction Steps

In my case, entering in-game on the Japanese version of Burnout 3: Takedown (SLPM-65719) with this PNACH cheat active, but in theory any case where the D-codetype is supposed to block multiple lines from executing if the condition is not met.
<pre>
patch=1,EE,D0488874,extended,05001640
patch=1,EE,50DD1890,extended,000200C0
patch=1,EE,00495A90,extended,00000000
patch=1,EE,20488874,extended,00495840
patch=1,EE,4068A3D0,extended,00020002
patch=1,EE,00488870,extended,00000000
</pre>

### Expected Behavior

The line <tt>patch=1,EE,D0488874,extended,05001640</tt> is supposed to block the next 5 cheats in the list from executing if the condition is not met, as per [PS2RD codetype specifications](https://github.com/mlafeldt/ps2rd/blob/master/Documentation/code_types.txt).

### PCSX2 Revision

v1.6, v1.7.3442

### Operating System

Windows 10 (64bit)

**Comment by Tokman5** [comment]
D-type code is currently implemented as a **single line** conditional code.
If you want to skip multiple lines, use E-type code instead.
replace your D-type code with a E-type code.

**Comment by EdnessP** [comment]
Understood.

If I may ask, is there any particular reason why the D-codetype isn't supported for multiple lines?  Because it seems to have been this way for years, if not over a decade.

**Comment by Tokman5** [comment]
simply because D-type code is not tested well.
Many of code type guides on the Internet ignore the code arguments such as number of lines to execute and 16bit/8bit flag, so everyone believes D-codetype is a single line conditional code.
If PCSX2 team confirm that the major cheat tools such as Action Replay and CodeBreaker support such arguments, those behaviour may be implemented.

**Comment by refractionpcsx2** [comment]
afaik we only implement this version

`Daaaaaaa 0030dddd | Only when the value at the address specified by aaaaaaa is greater than the value specified by dddd will the next line of code be executed.`

with the 0030dddd being either 0000dddd, 0010dddd, 0020dddd, 0030dddd, depending on which comparison.

Possibly because we need the address, on the version you're mentioning the beginning needs to be D2 or D3 etc depending on how many lines it relates to, but that takes away from the address, which could be a problem on PS2 considering technically the maximum address before the hardware registers is 0xFFFFFFF

if anybody needs a reference to the commands these are based off, the reference is here https://sites.google.com/site/ps2hackingconverting/PS2-Commands

**Comment by Tokman5** [comment]
I tested D-type codes which are supposed to skip multiple lines with Pro Action Replay MAX (one of Japanese version of Action Replay). Unfortunately, the codes don't work well. D-type codes seem to skip only one line.

**Comment by refractionpcsx2** [comment]
As I explained above, there is 2 types of D-type codes, one which specifies how many lines following it involves and one which doesn't, so it can have a longer address.  We only implement the single line version with the longer address, so it will only ever skip/execute 1 line.

if you need to do multiple lines, you will likely need to do the D code multiple times.

**Comment by Tokman5** [comment]
Here's the quote from the guide EdnessP linked above.
```
"Do multi-lines if conditional"

16-bit test
D-aaaaaaa nnt0vvvv

8-bit test
D-aaaaaaa nnt100vv

a = address (25 bits)
n = number of lines to execute (8 bits)
t = test condition (3 bits)
    0 equal      1 not equal
    2 less than  3 greater than
    4 NAND       5 AND
    6 NOR        7 OR
v = value (8/16 bits)
```
According to this explanation, the number of lines to skip/execute is specified at the beginning of the data section and does not affect targeting address. I followed this format for the test.

**Comment by refractionpcsx2** [comment]
This must be a completely different command list, because it's not the one we use, what we do have is the E command which does multiple lines

`Ennndddd 0aaaaaaa  - Only when the value at the address specified by aaaaaaa is equal to the value specified by dddd will the next nnn lines of code be executed. Otherwise, they will be skipped.
`
again the zero gets changed out for the command and only less than, greater than, equal and not equal are supported. I don't know what this command list you have is.

**Comment by EdnessP** [comment]
PS2RD is what's baked into Open PS2 Loader's cheat system, and presumably what most people nowadays use, if they don't have access to the cheat device discs.  I guess it makes sense that other OG cheat device makers would have their own implementation, but besides D-codetypes, everything else at a seems to work/behave identically with PCSX2's extended mode.

PS2RD also has E-codetype support, so it's no problem for me to use that if needed (such as in this situation), in its documentation it says that E-codetypes are deprecated and internally converted to D-codetypes, so it never occurred to me to try using E-codetypes even on PCSX2, since it's always "just worked" for me on a PS2.

**Comment by refractionpcsx2** [comment]
I mean we adhere to the original codebreaker spec so online cheats work fine and such, it's how it has been for 15 odd years, I don't know if ps2rd has been updating it for OPL, I don't know, but we haven't added any new stuff. it CAN be added, that's fine, but it wasn't a bug, it was just we weren't aware of any other variations of the command.
