### ISSUE TITLE
[Feature Request]: Decrease Lower Limit On Audio Latency (Qt)

### ISSUE THREAD

**Issue by cuckydev** [PCSX2/pcsx2#7268]
### Description

In older versions of PCSX2, you could set the audio latency down to 4ms.
While this still works if you modify the settings directly, the Qt user interface does not allow you to do this.

### Reason

Being able to reduce the audio latency should be possible via the UI rather than through the .ini.
Having a lower audio latency improves responsiveness between the game and the sound effects, and would be useful when emulating rhythm games.

### Examples

Latency set to 15 (Current UI lower bound)
https://user-images.githubusercontent.com/44537737/197370281-01315eac-6c10-4b5d-a93f-a8e8095ebe80.mp4

Latency set to 1 (Done by modifying PCSX2.ini)
https://user-images.githubusercontent.com/44537737/197370360-5d480cb8-38ac-420c-83eb-4fc9c2bc592d.mp4

**Comment by stenzek** [comment]
You're not getting 4ms of latency in the first place. There's two levels of buffering - the timestretcher, as well as the system/API buffer. The current "Latency" refers to the former's target size.

What we could do, is something similar to what I have in DuckStation - make the two explicit:

![image](https://user-images.githubusercontent.com/11288319/197372293-80d291be-62c7-4936-ba37-eda8f0f361ac.png)

**Comment by cuckydev** [comment]
> You're not getting 4ms of latency in the first place. There's two levels of buffering - the timestretcher, as well as the system/API buffer. The current "Latency" refers to the former's target size.

I do have time stretching off, as it tends to have undesirable effects for me. If making the two bars separate would help then that may be a solution worth looking into.

**Comment by cuckydev** [comment]
I hate to bump issues, but I'd really like for something to be done about this. The lower latency values are absolutely accepted by the audio system if you're in the right sync mode (none). This is purely an issue with the user interface so I'm sure it'd be a simple issue to amend. The current minimum latency introduces so much latency (far more than it says it should at 15ms) that it makes certain games impossible to play.

**Comment by oddMLan** [comment]
This issue and #7608 are making PaRappa the Rapper 2 very unenjoyable to play on the current versions of PCSX2.
@stenzek I understand what you mean, and I like the idea to make it more like Duckstation, but before more explicit buffer options are made available in the UI I think the 'target buffer' should be allowed to be set lower than 15ms through the UI like in pre-Qt versions. As long as you set Timestretching to 'None' there is absolutely a palpable difference in the reduction of latency.

**Comment by refractionpcsx2** [comment]
I don't understand how people are having issues with timing on parappa, I can pretty much nail every note, so I don't know what you guys are doing on your end.

**Comment by oddMLan** [comment]
@refractionpcsx2 Parappa 2 is forgiving with timing and you might clear the game OK even with the latency. Your senses will adjust to the latency. But if you want to make cool sounding lines (especially if your play style relies on swing timing, which requires sub-beat precision) it's a lot less responsive/more frustrating than on real hardware. Us who have played on real hardware immediately notice. While the previous lowerbound of 4ms wasn't quite the same as real hardware it certainly faired better than the poor 15ms that is  currently made available on the UI.

**Comment by refractionpcsx2** [comment]
I mean, I come from a musical background, so I was hitting it pretty much right on the beats, and it was pretty much spot on, so I dunno what to tell you...

and 15m is literally less than a frame, you're not gonna get much better than that, no matter what you do, this IS emulation after all, it's possible that Cubeb isn't even giving you the 15ms the UI is.

**Comment by oddMLan** [comment]
Well, it's not so much the fact that I'm unable to hit the notes "on beat" as they appear on screen. Even if the timing is a little off, you can adapt to this timing deviation and keep acing the notes on screen.

There is a gameplay function called Cool mode, where you don't have a beat bar and instead improvise entirely by ear. The algorithm of the game, in order to get a high score, encourages to play in offbeat and swing timing. Even the smallest increase in responsiveness helps immensely here.

And cubeb is lower latency than XAudio since it routes through WASAPI (which I've been able to use with RetroArch in Exclusive mode down to 7ms - to play the prequel to this game, UmJammer Lammy of course!).

If 4ms helped XAudio (although as I understand, it's not an absolute value but a "target" value) even if you effectively gain 1 or 2ms extra from the 15ms, it's noticeable and worth allowing through the UI (and the emu supports it internally! - telling people to edit ini files, especially when it was something that was previously allowed through the UI is cumbersome).

I got nothing else to offer than my own experience and the word of avid Parappa 2 players who have used the same 4ms configuration with the pre-Qt versions of PCSX2.
