### ISSUE TITLE
wxWidgets 3.0 issues

### ISSUE THREAD

**Issue by bositman** [PCSX2/pcsx2#736]
This will help as a master issue for any regressions we may have with the wxWidgets 3 upgrade ( https://github.com/PCSX2/pcsx2/pull/657 )
@turtleli Your help will be appreciated :)

- [x] Error message when you run any game:
wxWidgets Debug Alert
....\src\common\string.cpp(1186): assert "c < 0x80" failed in wxString::FromAscii(): Non-ASCII value passed to FromAscii().
Do you want to stop the program?
You can also choose [Cancel] to suppress further warnings.
Caused by running SPU2-X with portaudio as module (which is the default). No error with Xaudio2

- [x] Using the screenshot function in settings (lower left photo icon) produces unusable images
[Old screenshot](http://bositman.pcsx2.net/pcsx2_CoreSettings_EE-IOP2.png)
[New screenshot](http://bositman.pcsx2.net/pcsx2_CoreSettings_EE-IOP.png)

- [x] Clicking on the 1 (middle) mark of the EE slider does not set it to 1 but to 2. Same behavior for the VU cycle stealing slider, can't click directly to the 2 value. Sliding it with the mouse works though

- [x] Unconfirmed GSdx not showing the 'You need to update your directx' message when applicable, but simply shows an error message: http://forums.pcsx2.net/Thread-Plugin-Detection-Error-on-W10?pid=473245#pid473245

- [x] GSdx window content is white instead of black (as it used to be) before we get any display from the game

- [x] Various GUI issues with DPI 150% http://screenshotcomparison.com/comparison/139234

**Comment by turtleli** [comment]
GSdx DirectX - probably unrelated, but it does show an interesting UI bug - It shouldn't be asking "Press Ok to go to the Plugin Configuration Panel" when you're at the First Time Config.

Notes:
 * SPU2-X portaudio - not reproducible on my end. The debug message narrows the problem area down a lot so I can still work on it. Seems Windows only.
 * Screenshot - Background transparency and not saving black text? Weird. Seems Windows only.
 * EE and VU slider - seem to be adding/subtracting 2 when it's clicked. Seems Windows only.
 * GS Window - Probably just needs a background colour specified. Think it affects Linux too. Low priority for me.

There's also a minor wxCore30 build bug (the rcdefs.h move means it can't find the file and believes the project is always out of date), but that's an easy fix.

**Comment by turtleli** [comment]
Partial regression:
 * Emulation Settings, Speedhacks - text descriptions are truncated more (see MicroVU hacks part). Checkbox related it seems. Affects both Windows and Linux.

Not a regression:
 * Button location changes - Trigger by minimising and restoring dialog boxes (Emulation Settings, Plugin/BIOS selector, doesn't affect Memory Card?). Also makes screenshot function weird ([Before](http://turtleli.unospace.net/pcsx2_before.png) and [After](http://turtleli.unospace.net/pcsx2_after.png) from a Windows wx2.8 build). Windows only, but possibly related to #219 on Linux, I wonder if the dialog box construction is incorrect.

**Comment by micove** [comment]
You need to change the language to reproduce the SPUX-2 issue. I changed my system from English to Greek (since bositman reported this) and the error popped up instantly. I tried Japanese and it does not happen.This 86d62433cf07158cbcecf3ad09ab7e66d2f2846b sort of fixes the issue in SPU2-X but the cause of the problem is in portaudio. Portaudio does not handle the CP932 and whatever the codepage for greek is and mangles the device name into trash. I looked at the byte representation of info->name and in Japanese the device name turned into "3F3F3F3F3F3F3F3F3F" which is basically "???????" this is ASCII so no error but in Greek it gets manged to bytes >=0x80 and the error pops up. The device name getting mangled causes other problems but this is for the most part an old issue.

I believe the wxString constructor handles the CP conversion in windows so I used that and wxfprintf is useless until portaudio generates a info->name that is not trash.

**Comment by bositman** [comment]
I can confirm GSdx background issue fixed, Screenshot issue fixed (albeit as said above the icons look crappy but it serves its purpose), EE/VU sliders issue fixed. All tested in Windows

@micove is correct this only happens on my work PC which has the greek locale of windows 7

**Comment by turtleli** [comment]
I can't reproduce the Debug Alert on Windows 8.1 Pro, I tried Greek, Chinese and Japanese. But I did see the DirectSound "Primary Sound Driver" localisation being messed up in all three.

@micove - I think your commit will work fine for solving the immediate SPU2-X issue. Are you planning on doing the PortAudio update? I'll look into it only if you have no plans for it.

**Comment by micove** [comment]
@turtleli 
I had to install the Language Packs (they are rather big) and change language stuff in various places for it to become reproducible. It was a bit of a pain to reproduce but I managed to do it in W10.

I don't like my commit after reading the portaudio bug report. It would be better to update to at least svn1948 (fixes a buffer overflow in Windows in the unicode part, but this is almost the HEAD revision so might as well get HEAD) and just change the FromASCII to FromUTF8 since they said portaudio should output everything in utf8. Since it's using utf8 then the fprintf must be changed and SendMessageA to SendMessage should be done.

I was not planning too but I guess I could do it later today. I need to fix some Linux stuff first since the Debian package is about to explode in a few days with the change to gcc 5.2.

**Comment by turtleli** [comment]
Ok, I can reproduce it now. Apparently I wasn't trying hard enough when I used the Greek language pack. If I don't select PortAudio DirectSound as the Host API in the SPU2-X config panel, the popup doesn't appear for me at all.

**Comment by micove** [comment]
@bositman 

You can strike-through the Unconfirmed one. The reporter in http://forums.pcsx2.net/Thread-Plugin-Detection-Error-on-W10?pid=473245#pid473245 said it was a driver issue.

I also use W10 Pro and the "Please install DX runtime" window appeared so much that I just installed the runtimes to shut the window up.

**Comment by turtleli** [comment]
Screenshot stuff - seems like what I did was work around an actual wx3.0 Windows bug. See http://trac.wxwidgets.org/ticket/14403, there's a few more similar bug reports out there but this one matches best. So the crap screenshot icons will have to do for now unless someone wants to change the icons.

GSdx - What the OP of that thread actually seems to be describing is how they can't access the GSdx config panel anymore if GSdx fails to load. It was just rather badly described. That happened before the change to wx3.0, so it's unrelated.

**Comment by bositman** [comment]
Cool, I still have a few stuff to add here, like Higher DPI messing up the dialogs (they become huge) but I'll add em when I get time again. Thanks for the quick fixes and investigation ;)

**Comment by gregory38** [comment]
http://forums.pcsx2.net/Thread-Problem-with-the-Debugger

**Comment by turtleli** [comment]
Found the debugger error, will PR the fix later.

**Comment by bositman** [comment]
GUI issues, while using DPI 150% Took 4 screenshots, you can see them in the link provided. Especially the plugin selection is very problematic since I can't even see the filename of the plugins so I can select the ones I want.
http://screenshotcomparison.com/comparison/139234

**Comment by turtleli** [comment]
I think it's to do with DPI awareness on Windows, the text is much clearer but the images haven't scaled up as well. It seems as if the images are being used for the dialog sizing.

**Comment by bositman** [comment]
I tried bypassing windows DPI by setting the 'Disable display scaling on high DPI settings' on the pcsx2.exe, but nothing changed

**Comment by mirhl** [comment]
http://www.anandtech.com/show/7939/scaling-windows-the-dpi-arms-race/3
https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266.aspx

Also, I [read](http://windows10_dpi_blurry_fix.xpexplorer.com/) W10 is using yet another way to handle things.

**Comment by turtleli** [comment]
I think I'll try and size the dialog widths based on the dpi and see how that works out. That should sort out the immediate problem.
I'll probably need to scale the images on GSdx and SPU2-X (alternatively I could just delete the images).

**Comment by turtleli** [comment]
Another issue:
* GS Panel "Use synchronised MTGS" and Gamefixes Panel "Enable manual game fixes" checkbox descriptions don't grey/ungrey themselves when the Presets checkbox changes state. Windows only. Something to do with the pxCheckbox stuff, but haven't figured it out yet.

**Comment by gregory38** [comment]
Don't hesitate to post a more recent status

**Comment by turtleli** [comment]
DPI issues - I think only the debugger is still affected. It uses custom paint stuff and specific font sizes which shouldn't really be done, but changing it might be problematic for small screens. Unlikely to be fixed by 1.4.

Grey/ungrey bug - still there on Windows (and also on Linux wx2.8). I think custom paint stuff (in pxStaticText) and enable/disable behaviour isn't defined behaviour, so it probably used to work on Windows by chance. (Might be fixable/hack-fixable by 1.4)

There's also an issue with the listbook width on Windows 7 which depends on the users theme preferences (see vsub's comments in #801). An attempted update to the latest wx3.0.x git branch to see if that changes anything gave me a 20-30 second Windows GUI lockup on boot - a SetThreadUILanguage() call increased debugger lock time to 1-2ms, and the debugger uses 12000+ * 2 locks when calling DisassemblyDialog::reset() (which I will probably fix, it currently causes a 2-3 second Windows GUI lockup). So yeah, I got sidetracked looking at the debugger. :S

**Comment by turtleli** [comment]
Well, the debugger does somewhat support DPI, though it has to be done manually by changing the FontWidth and FontHeight settings in PCSX2_vm.ini. I'll consider it working, mainly because the debugger resizing stuff is a PITA.

**Comment by turtleli** [comment]
Kingcom fixed the debugger DPI scaling issues.

The 20-30 second lockup if I update wxWidgets to the latest on the 3.0.x branch - it can be solved by changing the debugger mutex/locks to use the C++ recursive_mutex and lock_guard.

I'll migrate the listbook width issue on Windows 7 (I assume Windows Vista might also be affected) to another issue at some point (or someone else can do it) since that's not a regression caused by the upgrade and then I'll close this issue.
