### ISSUE TITLE
Ghost in the Shell SAC performance regression

### ISSUE THREAD

**Issue by Interocitor** [PCSX2/pcsx2#743]
This commit https://github.com/PCSX2/pcsx2/commit/42f51591df66c3b82d353dc6bb6aad7e14d1127d by @gabest11 decreases my performance in DX11 software mode sharply for Ghost in the Shell: Stand Alone Complex PAL.

i5 2500K stock / HD7870

Before the commit I get I get 50fps (EE 90% GS 60%). All CPU cores have an equal load.
After the commit I get ~22fps (EE 40% GS 95%). One CPU core is at 100% while the others are at 50% utilization.

Tested with default settings, except 'extra rendering threads' at 2 extra threads.
I tested ZoE 2 but there seems to be no difference in performance.

**Comment by gabest11** [comment]
I tested all my dumps and have not found any other like this. The extend function that fixes Lupin 3 is the problem here. It corrects some textures to be 1024x1024 (128x64 originally). Maybe I'm not interpreting it right, region repeat mode is difficult to predict, but it looks like it wants to address texels above 1000. It loops through the image in tiles, similar to letter printing that eats all the memory in other games, but it picks data from the bottom right corner, pretty unfortunate, because all textures have to be 1024x1024.

**Comment by karasuhebi** [comment]
Would a GS dump help?

**Comment by gabest11** [comment]
Not needed, I have the game.

**Comment by gabest11** [comment]
There are a few bugs in this code. Forgot that negative values can wrap around in repeat mode, bilinear sampling needs +/-0.5, and for this game the region repeat mask could be used better.

**Comment by gabest11** [comment]
I think this can be considered fixed.
