### ISSUE TITLE
"Do not show this dialog again" checkbox for CDVD source swap dialog does nothing

### ISSUE THREAD

**Issue by yorkiesandskittles** [PCSX2/pcsx2#766]
When you change the CDVD source, a dialog box will appear, asking if you want to swap discs or reset the system, with a checkbox to never show the dialog again. If you check the box, choose an option and change CDVD sources again, the dialog will appear, even though the box was checked.

The "never show this again" checkbox works for the Reboot CDVD options, but does not work here.

**Comment by charliebruce** [comment]
In inis/PCSX2_ui.ini, what do you have in the "[PopupDisablers]" section, if anything?

**Comment by charliebruce** [comment]
Just checked this issue out - it doesn't work correctly when disablers are used alongside custom buttons because "ParseThatResult" returns wxID_ANY when the button is a custom one, which can't be used with a disabler (line 182 of ConfirmationDialogs.cpp). I've played around with a fix for this, which seems to work OK, but there might be some unintentional side effects of the change to ConfirmationDialogs.cpp - I'm not sure if there was a reason that it was checking `if( resultNum != wxID_ANY )`.

Can anyone with more experience weigh in on the changes I made here? https://github.com/charliebruce/pcsx2/commit/1f16651e32e9f2c0887ae969afd580b56e178165

**Comment by ramapcsx2** [comment]
Hey @avih! It's a gui thing and you love those, right!? :)

**Comment by avih** [comment]
TBH, I don't think this checkbox should exist at all, since if the user checks it, then from that point onward it's impossible to choose if to reboot or to swap discs.

The proper fix is therefore IMO to remove the checkbox.

**Comment by willkuer** [comment]
Is resetting the ps2 ever wanted? Is there any scenario where i dont want to hot swap? I think if both games are not compatible with hotswap the ps2/emulator resets in any case or?

At least i think hot swapping is as well the only feature the ps2 supports.

**Comment by avih** [comment]
I use reset frequently. i test with few games, and just select a new ISO to reboot to a new game.

**Comment by charliebruce** [comment]
@avih Maybe the best solution is to add a multiple-choice menu, similar to the Iso/Plugin/No disc toggle options in the CDVD menu, that allows the user to select what is done when swapping images?

**Comment by charliebruce** [comment]
Something like this:

![hotswap](https://cloud.githubusercontent.com/assets/2148474/9313009/576db00a-4518-11e5-8e76-7aa9645338eb.png)

**Comment by yorkiesandskittles** [comment]
Having a multiple choice menu called "Disc Swap Method" that leads to
Hot-Swap and Reset would be better IMO. It just makes the context of these
options more clear.

**Comment by avih** [comment]
While personally it doesn't bother me at all (and I probably have to click "reset" more than other have to click "swap disk" if only because swapping disks is probably not as frequent as I'm testing stuff with different games), I think the idea of the menu item to choose between reset/hotswap is not too bad.

We could also use a single checkbox instead of two radio items, like on the system menu (load cheats, etc).

If anyone wants to work on it.. go ahead.

**Comment by ramapcsx2** [comment]
@willkuer I also use this feature regularly. I also switch from the 2 options so yea, it has a good use.

**Comment by willkuer** [comment]
But what is the difference between hotswap and reset in the current implementation?

If I switch from Game1 to Game2 and both do not depend on each other. HotSwap leads to the same as reset, or?
If I switch from Game3 to Game4 and they depend on each other HotSwap leads to additional functionality. But actually HotSwap doesn't even work at the moment, or? Dynasty Warriors and MonsterRancher need HotSwap but don't work.

Maybe there is no difference for end-users but I never noticed a difference between both options.

I never worked with wxWidget but I guess I could implement a function like what charliebruce suggests (as it is probably just copy pasting from the source selector and putting a readConfig at the right position.). I can look into this when I find time. Removing the checkbox probably is even easier. Just decide what it should be.

**Comment by avih** [comment]
Hot swap changes the disc at the tray without resetting the PS2. Reset well.. resets, which boots into the other disc.

**Comment by turtleli** [comment]
The checkbox has been removed from the Swap disc or reset dialogs.
If a dialog has the "Do not show this dialog again" checkbox and you press cancel, it now won't save your decision if the checkbox is ticked.

But do feel free to improve things further :)

**Comment by gregory38** [comment]
Shall we close the issue

**Comment by turtleli** [comment]
Guess so. If someone wants to make changes and wants to discuss, they can ask for it to be reopened.
