### ISSUE TITLE
Error message for unsupported locale when the user has selected another language

### ISSUE THREAD

**Issue by mkwong98** [PCSX2/pcsx2#787]
-PCSX2 version: 1.3.1-20150821112949 (v1.3.1-1021-g6e826d5)

-PCSX2 options: English (U.S.) in Language selecter

-Description: I'm using Windows 7 with locale "zh_HK" / "Chinese (Hong Kong). I changed the language of the emulator to "English (U.S.)", but the emulator still shows an error message "locale 'zh_HK' cannot be set" every time I open it.

-How to replicate: run Windows in an unsupported locale and change the language of the emulator to one of the supported.

-Last known version to work: 1.3.1-20150729114532 (v1.3.1-807-g5c58bd2)

-PC specifications: CPU: Intel Core i3-3220 @ 3.3Ghz OS: Windows 7 Pro SP1 32-bit

**Comment by gregory38** [comment]
It is just an informative message.

**Comment by mkwong98** [comment]
Here is a screen shot of it, definitely not a simple informative message.
![pcsx2error](https://cloud.githubusercontent.com/assets/4365079/9424634/92c671c6-4925-11e5-8a59-be86863d0458.png)

**Comment by turtleli** [comment]
Just to check - does the error message show up if you leave it at the default language?

**Comment by mkwong98** [comment]
Yes, it does. The default language is Chinese (Traditional).

**Comment by turtleli** [comment]
I can't reproduce the error here but I think I know what is happening. Can you replace pcsx2.exe with the one at http://turtleli.unospace.net/pcsx2.7z and tell me whether it works?

**Comment by mkwong98** [comment]
Yes, the error message is gone now, thanks. I'll close this issue when the fix is available in the automated builds.

**Comment by charliebruce** [comment]
I have a similar/the same problem with en-GB on Windows 8.1, here's what happens for me:
Stepping through 3rdparty\wxwidgets3.0\src\common\intl.cpp(91), wxLocale::Init

lang = 58
info->WinLang = 9
lcid = 3435973836
m_impl = L"English_United Kingdom.1252"

wxSetLocale goes on to call setlocale(category=0, locale = 0x00c2a5f0 "English_United Kingdom.1252") which returns 0, in turn making retloc in wxLocale::Init equal to 0 (line 494).

It finally goes on to call wxGetANSICodePageForLocale, which returns 1252, so the condition .empty() isn't met on line 509, and the warning ends up getting logged on 542. 


I don't understand what it means when it says in a comment on line 503 "... wxSetlocale() call fails for such languages but we don't want to report it as an error -- so that at least message catalogs can be used.". Perhaps someone with more knowledge re internationalisation can explain what happens around here?


Not sure if any other UK users have similar issues. I run an odd setup (custom keyboard layout based on a US keyboard, on a system which uses UK layout/localisation).

**Comment by turtleli** [comment]
I've never had it happen to me when I was using Windows 8.1 with the en-GB locale.

I've commited a fix for it, though the fix is slightly different from the one I used in the exe I previously linked to.

**Comment by mkwong98** [comment]
My problem is fixed in the latest build so I'm closing this issue. Thanks.
