### ISSUE TITLE
[Feature Request]: Support for slang shader pipeline via librashader

### ISSUE THREAD

**Issue by NatParable** [PCSX2/pcsx2#7918]
### Description

> [librashader](https://github.com/SnowflakePowered/librashader) is a complete reimplementation of the RetroArch slang shader pipeline that allows standalone emulators to easily and optionally implement support for RetroArch-style shaders and shader presets.

https://github.com/SnowflakePowered/librashader
https://snowflakepowe.red/blog/introducing-librashader-2023-01-14

If I understand correctly, incorporating librashader into pcsx2 would allow users to use the plethora of slang shader effects that already exist for RetroArch.

### Reason

While I am aware that it's possible to use third party tools like ReShade to apply shader effects to games emulated with pcsx2, ReShade only officially supports Windows. This makes ReShade much more difficult to use on something like the Steam Deck (which I currently use as my main emulation machine). Being able to apply and adjust shader presets using the regular pcsx2 in-game menu, much like how you currently can with RetroArch, would be amazing.

### Examples

Such a feature would hopefully allow pcsx2 to use the amazing Mega Bezel Reflection Shader by HyperSpaceMadness.

https://www.libretro.com/index.php/retroarch-introducing-the-mega-bezel/

**Comment by stenzek** [comment]
No, because:

1. The risk of creating drama, it's well documented if you google.
2. Making rust a dependency complicates the build system.
3. Reshade already exists.
4. It's probably not compatible with Metal.

Integrating reshade's compiler is a better idea - then you have the potential of using depth buffers, depending on when post processing is applied.
