### ISSUE TITLE
Release SSE/AVX builds don't build all plugins

### ISSUE THREAD

**Issue by tony971** [PCSX2/pcsx2#831]
They only build GSdx.

**Comment by micove** [comment]
Only GSdx uses Release SSE4/SSSE3/AVX/AVX2 therefore if you compiled Release beforehand there is no reason to rebuild everything. What you are suggesting is recompiling everything when there is no need too.

The current behavior is correct therefore closing.

**Comment by willkuer** [comment]
This behaviour was always unclear to me. Why do you separate gsdx in the build process? Why don't you build pcsx2 and plugins on avx build?

1. Scenario: release builds pcsx2, releaseAvx builds gsdx:
- if I built release already and build releaseAvx I get a working emulator plus desired gsdx plugin
- if I did not built release and build releaseAvx I get a non-functioning emulator

2. Scenario: release builds pcsx2, releaseAvx first builds pcsx2 and then gsdx
- if I built release already and build releaseAvx building of emulation is skipped since up2date and gsdx plugin is built. I get a working emulator.
- if I did not build release and build releaseAvx first the emulator is built and then gsdx. I get a working emulator.

For a user it makes absolutely sense to include pcsx2 into the build process of gsdx releases. Is it different for devs?

**Comment by willkuer** [comment]
Ah this stupid github destroyed my structure and I am on phone and can not change posts....

2&3 belong to 1 and 5&6 belong to 4

**Comment by micove** [comment]
Currently if you pick any of the solution configuration like "Release AVX" and compile only that everything gets compiled and you get a functioning emulator. Only GSdx has the targets for AVX/AVX2/SSS4/SSSE3 because it's the only project that actually implemented code that uses those instructions. The other projects could get the AVX/AVX2/SSS4/SSSE3 targets too but that would make the bot timeout since it would take about 2+ hours to compile and it would include 5 pcsx2.exe and all plugins x5. It would enable auto-vectorization and other things but not sure if that alone is worth it. Also SSE2/SSSE3/SSE4 would end up as the same binaries so technically there would only be 3 flavors unless you use the Intel compiler.
