### ISSUE TITLE
[BUG]: PCSX2 latest nightly build crashing due to unhandled error with input monitoring

### ISSUE THREAD

**Issue by jedis00** [PCSX2/pcsx2#8344]
### Describe the Bug

I am using Multiplicity to control several desktop computers from a single keyboard/mouse. This works fine.

PCSX2 latest nightly crashes when I change input control to another computer and try to send a key press or mouse activity. It is easily reproducible.

### Reproduction Steps

1) Install Multiplicity
2) Configure it to connect to another computer
3) Change input to other computer and send a mouse click
4) PCSX2 instantly crashes.

### Expected Behavior

PCSX2 to gracefully handle input capturing and for the program to not crash.

### PCSX2 Revision

v1.7.4191

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Post the crash dump. This might not be our bug.

**Comment by stenzek** [comment]
Closing as invalid - jumping to a null pointer, very likely a bug in some driver, or the this program. Manually reconstructing the stack shows addresses from within SDL's joystick message handling, so probably a hook it's installed.

I'm definitely not going to buy it to investigate. You could try with SDL disabled, but we're not responsible for bugs in other software.

**Comment by jedis00** [comment]
Just because _you_ don't feel like working on it doesn't mean it should be closed. If there was proper exception/error handling in the application, it wouldn't be crashing. This community is toxic.

**Comment by stenzek** [comment]
Man, the "toxic" insult gets thrown around so inappropriately these days.

I took the time to investigate your bug. It's not crashing in our code, so it's already out of our control. That's really all I can do - if you're expecting me to go out and spend $40 on software I have no use for, that's a bit silly, don't you think? (considering I'm not paid by PCSX2, this isn't my job).

Perhaps you should report it to the software vendor, since it's likely on their end, and they're the ones who can fix it, not us.

Despite that, I suggested a possible workaround, based on what I _could_ see in the crash. But apparently that's "toxic"?.

For what it's worth, you can't just wrap everything in "exception/error checking". In this case, it's jumping to null, so there isn't even a valid call stack to unwind to get back to a catch point with something like SEH. And doing so for buggy third-party software is generally a bad idea, especially if it's corrupting memory, the program's just going to be in a screwed up state and crash later regardless.
