### ISSUE TITLE
[BUG]: PAD - SIO - True Crimes L.A. requires second pad

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#8482]
### Describe the Bug

the game won't start without second controller emulated. 

### Reproduction Steps

try to start a game. 

### Expected Behavior

games starts like normal

### PCSX2 Revision

1.7.4274

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

**Comment by kamfretoz** [comment]
This is already a known issue

**Comment by seta-san** [comment]
yes. it's a known issue. but not one that is posted on github. it's better documented for users than not.

**Comment by Goatman13** [comment]
I think that bug is in: https://github.com/PCSX2/pcsx2/blob/6e40081dd90e6bb3718fff0313b73de601267dab/pcsx2/Sif.h#L56
That code preserve new "junk" from IOP memory if i understand correctly. While what seems to be more likely to happen is that SIF create QW packet for EE from new words for lower part and old fifo data for upper part.

What i mean is that currently function is backing up wrong "junk". What should be preserved is probably current fifo content from previous write. Changing code to `memcpy(&junk[size], &data[((writePos - size) & (FIFO_SIF_W - 1))], amt << 2);` resolved pad issue and assets loading issue, and seems to work ok. But i don't know if this is really correct thing to do.

**Comment by refractionpcsx2** [comment]
I'm pretty sure I tried that, and it didn't work, but it made the most sense.  our fifo sizes aren't correct, iirc, so that doesn't help.

I was going to revisit it and try again, just hadn't gotten around to it yet :P

**Comment by refractionpcsx2** [comment]
It's possible that also won't always be the case, for example if the transfer is more than 128 words, the old "junk" will be the state of the fifo at the time, not what was there beforehand, so the code needs rethinking a little bit.

**Comment by Goatman13** [comment]
Yeah. I think i will leave that one for you (or someone else). Seems to be little bit complicated for me to do it. :D Btw. Old patch still work for it, so it seems to confirm that's issue with sif junk content.

**Comment by refractionpcsx2** [comment]
Yeah I figured it might be. I'll have another crack at it this week, I need a break from GS stuff, my genitals can only take so much of a beating from that :(
