### ISSUE TITLE
Switching between multiple ISO's crashes the emulator at random times

### ISSUE THREAD

**Issue by deadair3210** [PCSX2/pcsx2#856]
Version - PCSX2 1.3.1-20150928094130
Specs - i5-2500k @ 4.0 GHz, 11 GB DDR3, GTX 660 3GB
Description - Sometimes, after switching to a new iso or cso the emulator will hard crash and windows will force it to close.
Procedure - Load a iso or cso, Boot (Full) and let it play at least until the title screen, then switch to another iso/cso and it reset on the dialog. do this repeatedly until the emulator eventually crashes.

**Comment by avih** [comment]
If this happens also with normal ISOs, then it has nothing to do with CSO, at which case the title is misleading.

CSO is just a thin layer of code which exposes CSO compressed ISO as normal ISO to PCSX2, and from there onward PCSX2 doesn't care that it was originally CSO.

So unless you must user CSO in order to reproduce the bug, please don't include it in bug descriptions since it's just irrelevant and creates noise and FUD.

So does the bug also happen without using CSO?

**Comment by avih** [comment]
Also, this seems to me highly related to #851 .

**Comment by deadair3210** [comment]
Seems to happen regardless of format type, I will change the title. the bug happens about 1 in 10 times, or not at all. Haven't figured out exactly what trips it, all i know is its related to switching games,

**Comment by gregory38** [comment]
Now that #851 was fixed. Is this issue still valid?

**Comment by deadair3210** [comment]
Sorry for not responding, have not had access to my desktop, but issue does not appear ob my laptop with the latest build on the buildbot
