### ISSUE TITLE
Half-pixel offset

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#860]
From @willkuer's https://github.com/PCSX2/pcsx2/pull/829#issuecomment-141786351

>Does it actually make sense that the default for halfpixel offset is 0 and not 1.1 or something related? Somehow the transition from upscaling to native is not smooth in this function...

>Also are these values really that precise? Maybe one could replace the switch by
Modx = mody = factor +0.2;

>Put probably a bit off topic here. I still have the feeling switch is overused for the upscaling hack.

These half-pixel offset questions seem valid and I'd like to see them addressed if at all possible. Thank you for reading!

**Comment by ssakash** [comment]
we don't need to change the offset of OFX and OFY in case of native resolution, these are values for converting from the primitive co-ordinate system to window co-ordinate system. 

In Half pixel offset hack, we alter the vertex offset to suit the scaling resolution. so using 1.1 for native seems equivocal ? @willkuer

**Comment by willkuer** [comment]
Yes it is reasonable that we don't change the offset for native. I guess halfpixeloffset is either disabled in native or would do nothing if applied correctly (if half pixels get truncated to integer pixels)

I was more questioning the idea behind those other values. As there is no magic happening in this function I would expect to see a smooth function (all derivatives are smooth as well). So offset would be some polynomial function of resolution. The switch indicates something similar to linear which on the first glance seems reasonable.

The question is why do we not se a linear function there but instead a discrete function with some odd values. Continuous function would as well work with custom res.

**Comment by willkuer** [comment]
But obviously there is something else as well as the likelyoffset parameter indicates some handling later.

**Comment by ssakash** [comment]
> But obviously there is something else as well as the likelyoffset parameter indicates some handling later.
```likelyoffset``` is a bool for checking whether to alter 0x2 and oy2 for vertex offset. if it's false, it just does it the default way like native resolution. 

> The question is why do we not se a linear function there but instead a discrete function with some odd values. Continuous function would as well work with custom res.

you can try checking whether different modx, mody values for half pixel offset works in the respective internal resolution , It's probably discrete due to some kind of weird upscaling trick which is why it's limited to scaled resolutions. (maybe ? )

**Comment by willkuer** [comment]
Yeah that's what I thought as well. I think it needs to be slightly larger than integer value to ensure that rounding/flooring happens correctly. If you write .2 or .1 probably doesn't matter at all.

Actually I couldn't care less. I also haven't open the issue. Dev idealsm probably doesn't allow to work on hacks but rather improve emulation to avoid game specific hacks at all. Gregory said already that he would like to combine all rounding error and upscaling hacks into one that is permanently applied to fix all games.

So I guess nobody will take care of it. I neither have time nor the game database to improve here anything. I just made the comment because the switch looked fishy at that point.

**Comment by ssakash** [comment]
> . I neither have time nor the game database to improve here anything. I just made the comment because the switch looked fishy at that point.

Lots of games work better in different modx and mody values for Half-Pixel offset it seems, like the case with tales of abyss. http://forums.pcsx2.net/Thread-Solved-Dev-Question-about-GUI-edit-Text-descriptions-for-hacks?page=3

you're right though, if someone wants to improve the Half pixel offset part they should probably make sure that it works okay with most of the games which would be quite time consuming. :(

**Comment by gregory38** [comment]
I'm busy with others activities. Anyway I really think that a better solution could be done (albeit much more complex).

**Comment by gregory38** [comment]
Let's concentrate on real bugs rather than useless details.
