### ISSUE TITLE
[BUG]: Bug with linearity of steering Wheel

### ISSUE THREAD

**Issue by Aaronsitoo** [PCSX2/pcsx2#8725]
### Describe the Bug

When configuring my steering wheel in the emulator and putting the respective buttons and axis when turning, it has many degrees that it does not recognize, approximately 360º that the emulator does not detect.

### Reproduction Steps

1.-Settings and the Controllers

2.-Enable SDL input source (i have also tried "enable SDL Raw input" and "enable DInput Input Source" and nothing)

3.-USB port 1 Select "Wheel device" and Driving force pro (i have also tried all types of wheels and nothing)

4.- Steering left and right axis and my wheel have a lot of degrees that not recognize the emulator

### Expected Behavior

idk, my wheel drivers and PC works 100% y tried many games like assetto corsa Forza horizon 5 etc and works perfectly

### PCSX2 Revision

1.7.4410

### Operating System

Windows 11

**Comment by stenzek** [comment]
You didn't even specify which wheel you're using.

But regardless, there's nothing we can do about it - we just get the axis values from SDL. If you would like to debug and fix it yourself, we'd appreciate it, but otherwise since none of the team own identical hardware, let alone any wheels, there's nothing we can do.
