### ISSUE TITLE
[Feature Request]: Save Cover Download Template URL in Cover Downloader

### ISSUE THREAD

**Issue by NotLazy** [PCSX2/pcsx2#8792]
### Description

I feel like the cover downloader should keep template urls that are put in should be saved between sessions, so that when new games are added, users don't need to lookup a new template url, or manually type out their own template url for those (if any) that are using their own covers.

### Reason

This feature would make downloading covers of newly downloaded games, much easier, as you can easily use the same URL(s) you used last time.

### Examples

Simply autofilling into the box, the same value that was there the last time the downloader was used.

**Comment by Mrlinkwii** [comment]
Making the user enter the URL each time  is the intended experience

**Comment by Mrlinkwii** [comment]
see  https://github.com/PCSX2/pcsx2/issues/8013#issuecomment-1409637302

**Comment by NotLazy** [comment]
ah, my bad.

**Comment by Offlinemaker** [comment]
I know this is a old request but I am really interested as to why that is the intended experience? I have read through all issues I could find regarding that feature and could only find vague statements about preventing piracy. I fail to understand how saving a user provided link locally on the users installation could have other implications than having to input the URL every time again.

As the other threads have been quickly locked I just want to state that I do not intend to discuss whether you should change your stance on this or not, I would only like to understand the reasoning behind the decision.

**Comment by RedDevilus** [comment]
I understand as a regular user this might seem a bit too on the protective side but things are always a balance between comfort (ease-of- use, features, QoL)  and security (not getting attacked by corporations on a myriad of issues ranging from copyright/trademark or other infringements). 

As an entity the PCSX2 team decided that technically downloading cover art or images are under copyright and while using a scraper isn't something corporations tend to go after as a priority that's true. Either way basically my personal opinion on how far to go or not go is not essential how cold it may be. 

Though it's not at out of bound request to have something similar to how DNS is handled:

![Image](https://github.com/user-attachments/assets/8a59dd7f-a2a7-4240-bebd-a7d98db78c52)


So people can have a permanent spot to point their server for example. Or as the original request just remember old link. as a string Not saying we should do permanent links to other public databases which can be dangerous how small the risk for PCSX2 would be in the long run.

It is maybe worth considering re-opening the issue in one way or another because just making users do another step seems a bit silly even if you don't have to do it daily. Just when you add 1 or more games to your PCSX2.

**Comment by Offlinemaker** [comment]
Re-opening and an open discussion would be amazing. And even if it may ultimately be decided that nothing will be changed having the reasoning easily available might stop further endless discussions on the matter!

Just to add my personal 2c: I mainly use PCSX2 on the Steam Deck. Due to storage constraints I only add a few games at a time. Entering any kind of URL or switching to desktop mode for easier copy pasting from a messenger app is considerable hassle compared to how great and hands-off everything else with PCSX2 works as soon as it is set up. (Especially since the addition of the wonderful big picture mode)

**Comment by RedDevilus** [comment]
> Re-opening and an open discussion would be amazing. And even if it may ultimately be decided that nothing will be changed having the reasoning easily available might stop further endless discussions on the matter!
> 
> Just to add my personal 2c: I mainly use PCSX2 on the Steam Deck. Due to storage constraints I only add a few games at a time. Entering any kind of URL or switching to desktop mode for easier copy pasting from a messenger app is considerable hassle compared to how great and hands-off everything else with PCSX2 works as soon as it is set up. (Especially since the addition of the wonderful big picture mode)

Did you get a bigger MicroSD for the steamdeck and are you also compressing your games with CSO/CHD? (I know it's off-topic if you need more help on that end better to be on Discord)

**Comment by Offlinemaker** [comment]
> > Re-opening and an open discussion would be amazing. And even if it may ultimately be decided that nothing will be changed having the reasoning easily available might stop further endless discussions on the matter!
> > Just to add my personal 2c: I mainly use PCSX2 on the Steam Deck. Due to storage constraints I only add a few games at a time. Entering any kind of URL or switching to desktop mode for easier copy pasting from a messenger app is considerable hassle compared to how great and hands-off everything else with PCSX2 works as soon as it is set up. (Especially since the addition of the wonderful big picture mode)
> 
> Did you get a bigger MicroSD for the steamdeck and are you also compressing your games with CSO/CHD? (I know it's off-topic if you need more help on that end better to be on Discord)

Haha not to get too off topic, but using syncthing it is quite easy to maintain a collection over a few devices, including saves. So there is no need for a big collection and this way I can easily have all the games I currently am likely to play on all of my devices - which are not all dedicated gaming systems so I try and save space for other purposes.

So entering the URL is the only manual step I have to take on each device. Which objectively is not a huge burden, but also 100% of the remaining manual work. 😄
