### ISSUE TITLE
[BUG]: Emulator freezes and becomes unresponsive when starting certain games using vulkan with an nvidia gpu

### ISSUE THREAD

**Issue by rayanHappy** [PCSX2/pcsx2#8794]
### Describe the Bug

When starting certain games(e.g. Def Jam - Fight for NY) the emulator freezes and it seems to cause the NVIDIA driver to crash.

i was able to bisect this issue in Arch Linux and it led me to this [8613](https://github.com/PCSX2/pcsx2/pull/8613) pull request.

I was also able to replicate this issue in a different laptop that has Windows 10 with an NVIDIA 940mx gpu.
The issue only occurs when using vulkan, it doesn't happen when using directx 11, 12 or opengl.

with linux i tried different versions of NVIDIA drivers, i went from NVIDIA 530 to NVIDIA 520 and the issue still persists.
with Windows 10 i only used the latest driver which is NVIDIA 531.68.

i would be very appreciative if some people with NVIDIA gpus test this, see how to reproduce below.

I used vkconfig to debug the issue and i got some results, look at the logs and dumps bellow.

note.1 Both 940mx and 840m use NVIDIA GM108 chip.
note.2 The issue does not occur when using vulkan with the igpu.

### Reproduction Steps

run Def Jam - Fight for NY or Scarface  with vulkan and an nvidia gpu.
Also make sure the start in fullscreen option is not checked as this issue doesn't seem to occur in linux when that option is checked.

### PCSX2 Revision

v1.7.4462

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

Arch linux

### CPU

intel not ultra 7 5500U(linux), intel not ultra 5 8250U(Windows)

### GPU

nvidia 840m(linux), nvidia 940mx(Windows)

### GS Settings

default with the exception to the renderer and the adapter.

### Emulation Settings

default

### Logs & Dumps

[vkconfig.log](https://github.com/PCSX2/pcsx2/files/11400089/vkconfig.log)

**Comment by Mrlinkwii** [comment]
how are you getting pcsx2  on linux?

**Comment by rayanHappy** [comment]
I am using my own builds, but i was able to replicate the issue using AppImage builds.

**Comment by stenzek** [comment]
We provide no support for self or packaged builds.

If you're using the appimage, it'll give you a backtrace when it crashes, post that.

Same with windows, it'll produce a crash dump, which you can upload here.

**Comment by MrBlank111** [comment]
I have the same problem on my modern AMD GPU in Windows 11 when loading Ratchet and Clank. Builds prior to v1.7.4377 without 'GS/HW: VS expand instead of GS for DX/GL/Vulkan #8613' work without freezing. I am using the official PCSX2 nightly builds. I looked for crash dumps in C:/Windows but didn't find any. PCSX2 only freezes the running game window (not the whole program) and crashes the driver so I don't know if there would be any. Please advise.

**Comment by stenzek** [comment]
"modern AMD GPU" doesn't really tell us anything, you need to be specific with the driver version and model.

We have testers with AMD GPUs (including myself, although I don't have it in my system right now), and it works fine.

**Comment by MrBlank111** [comment]
I am using an AMD 7900 XT on the latest 23.4.3 driver. I was initially using 23.4.1 but after updating the problem remained. 

I could not find any dump file in the root directory. I found the option to enable File and Verbose logging so I recreated the freeze conditions and here is the log.
[emulog.txt](https://github.com/PCSX2/pcsx2/files/11425032/emulog.txt)

Let me know if this helps or you need me to do something else.

**Comment by stenzek** [comment]
I tested Def Jam with a GTX 950 on both Windows (GH build) and Linux (AppImage), everything works fine.

Also with an RX 580 on 23.4.3. No issues.

I'm considering adding an option to disable vs expand, because apparently it's broken on NVIDIA Fermi, which is plausible at least. But the reported issue here seems invalid as far as I can tell.
