### ISSUE TITLE
[BUG]: USB wheel force feedback does not work  in the latest Nightly version.

### ISSUE THREAD

**Issue by atomic76** [PCSX2/pcsx2#8831]
### Describe the Bug

I think it worked around December last year.
but in the latest Nightly version, force feedback on USB wheels does not work.

### Reproduction Steps

Connect the usb wheel, specify the usb device type as wheel in the controller option,
map the axis and button, and run Gran Turismo 4

### Expected Behavior

When you run the game, the usb wheel should be calibrating left and right, but it doesn't, and there should be force feedback within the game.

### PCSX2 Revision

v1.7.4485

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Unless you can bisect it to an exact build, nothing any of us can do, we don't have wheels.

**Comment by stenzek** [comment]
Did a quick check and everything seems fine - it tries to create the effects (which doesn't work in my case, because I don't have a wheel), and the functions which forward the values to SDL get called as expected.

Probably user error, you need to bind FFB too, and use SDL, not DInput. Or the wheel isn't compatible with SDL.
