### ISSUE TITLE
[Request][SPU2-X & GSdx] Free up F12 Key for use with Steam

### ISSUE THREAD

**Issue by Pyrii** [PCSX2/pcsx2#886]
I would love it so this key could be remapped to stop me having to lose game focus while playing for quick snapshots and also stop that annoying "recording.wav" constantly cluttering up the program directory". I can't tell how

**Comment by avih** [comment]
You should have a `PCSX2_keys.ini.default` where your PCSX2 is installed or extracted (portable). Read it and follow the instructions. If you can't find it, see here: https://github.com/PCSX2/pcsx2/blob/master/bin/PCSX2_keys.ini.default

If that doesn't solve your problem, post another comment here and I'll reopen this issue.

**Comment by Pyrii** [comment]
This doesn't work in the 1.2.1 version which I'm currently using due to the current build causing Buggy shadows in cutscenes within the .hack games.

Given this is implemented in later versions I guess this can be considered already fixed though. Do you know which build this was implemented?

**Comment by avih** [comment]
It works with 1.2.1, but the default ini file wasn't included with it, so copying it from where I pointed (like you did already) would be fine. It's unrelated to the plugins since it's purely for pcsx2.exe itself.

Also, 1.2.1 prints a message to the console for every "remapping" at `PCSX2_keys.ini`, but newer development builds print a message only if the remapping actually changes the key.

And another thing, I just noticed that I'm unable to remap "plain" keys, like "m" or "z" or "q". This didn't work for me neither with the official 1.2.1 nor with the latest development build, but I'm pretty sure it used to work well (it does print the remapping message to the console, but pressing the key doesn't seem to perform the action). Weird, I should look into it.

If anyone else is able to confirm that plain keys work/don't-work, I'd appreciate it.

**Comment by karasuhebi** [comment]
Confirmed not working.

**Comment by avih** [comment]
> And another thing, I just noticed that I'm unable to remap "plain" keys, like "m" or "z" or "q"

There were actually three different issues here: incorrect parsing of shift with letter (e.g. `shift-q) at the ini, event key codes for letters were incorrect, and key codes for symbols were incorrect.

Should be fixed now with the latest build.

Also, if the Dev/Verbose console source is enabled, then it will print all key presses to the console (Including with ALT etc), which could then be copied to `PCSX2_keys.ini`, so that should help too.
