### ISSUE TITLE
[BUG]: Singstar: OPENING WRONG TEXTURE.

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#8872]
### Describe the Bug

![SingStar '90s_SCUS-97626_20230518104524](https://github.com/PCSX2/pcsx2/assets/8851653/506ad342-7ade-45b2-93f2-81aeca717697)

### Reproduction Steps

just start any singstar game. 

### Expected Behavior

![SingStar '90s_SCUS-97626_20230518104603](https://github.com/PCSX2/pcsx2/assets/8851653/c9236954-9eb3-42d6-8c30-dbaac0ef0954)

### PCSX2 Revision

1.7.4517

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

### Logs & Dumps

[SingStar '90s_SCUS-97626_20230518104524.gs.zip](https://github.com/PCSX2/pcsx2/files/11509283/SingStar.90s_SCUS-97626_20230518104524.gs.zip)

**Comment by refractionpcsx2** [comment]
Preload frame fixes it

**Comment by seta-san** [comment]
well. that's going to be one hell of a entry into the gamesdb

**Comment by memory-hunter** [comment]
> Preload frame fixes it

I am testing on SCES-55538, being game A and SCUS-97626, being game B.
This test applies to 4517 and 4526 builds.

Before applying the fix:
The issue was there, reproducible. The problem disappears after Resetting the game (from the System tab at the top left).
![Screenshot_1](https://github.com/PCSX2/pcsx2/assets/59766692/53d74a42-35a2-4c17-b755-d5ab07981310)
![Screenshot_2](https://github.com/PCSX2/pcsx2/assets/59766692/8fea0a35-7792-44b6-80ac-fe81557606d6)
The "reset fix" carries over to game B, when I started with game A.
![Screenshot_3](https://github.com/PCSX2/pcsx2/assets/59766692/6f7db198-7c83-4093-aa77-a2209de1eb80)

I applied the preloadFrameFix on every SingStar game in the `GameIndex.yaml`, 
No changes, same behaviour.
![Screenshot_4](https://github.com/PCSX2/pcsx2/assets/59766692/8fa3e118-586d-4361-bf98-01a6921e7b4d)
![Screenshot_5](https://github.com/PCSX2/pcsx2/assets/59766692/bb1b478d-2236-4059-80fd-112d5c8204a0)
Same here, carries over to game B.
![Screenshot_6](https://github.com/PCSX2/pcsx2/assets/59766692/2a19265e-4048-4f3d-98d0-f65160e1e781)

Was that a definite answer or just a possible fix that could've worked?
I am trying to contribute to PCSX2. I am working on my skills to contribute to open-source software. 
I was going to make a PR with the fix but looks like this wasn't the solution.

**Comment by stenzek** [comment]
Doesn't need preload frame. It's just a single page "FBW" clear.

#8961 seems to fix it, but I didn't go ingame.
