### ISSUE TITLE
[BUG]: Pnach codes that start with "0x" hard crash the emulator on startup

### ISSUE THREAD

**Issue by Phoenix-neat** [PCSX2/pcsx2#8893]
### Describe the Bug

Codes such as:
patch=0,EE,0xa03004,word,3c010035

Will crash the emulator, and do not work unless the 0x is removed like so
patch=0,EE,a03004,word,3c010035

This affects a large number of pnach files already floating around the internet, including several used in Persona 3 FES modding. These codes have worked for years but are nonfunctional in nightly builds.

### Reproduction Steps

Here's a pnach you can use with Persona 3 FES (NTSC) https://github.com/Tupelov/Game-Patches/blob/main/PS2/Persona%203%20FES/Get%20Field%20ID/94A82AAA_GetFieldID.pnach

### PCSX2 Revision

1.7.4526

### Operating System

Windows 11

**Comment by Berylskid** [comment]
Pnach doesn't support "0x" prefix afaik

**Comment by seta-san** [comment]
But it always takes hex doesn’t it? Using 0x notation seems redundant.

**Comment by Phoenix-neat** [comment]
This is something that works in the stable build and has worked prior to 2022. The emulator at some point was updated to remove support for this and it broke a lot of compatibility with a bunch of cheats that were written with the 0x prefix.

The problem goes from mild to major when you have people that aren't technically savvy (or even those that are who have NO CLUE this is a new issue cause it's POORLY DOCUMENTED) reporting working cheat codes as broken, having inconsistent errors based on nightly vs stable builds, incorrectly reporting mods as the cause due to accepted cheat codes suddenly breaking rather than other stuff, etc.

The mod menu for Persona 3 FES utilizes a cheat code that has this notation and a lot of time was spent trying to fix something that worked for years until PCSX2 broke it. That one instance may be fixed but I've got a lot less interest fixing every single pnach file that happens to have this notation cause the dev team decided a functional feature wasn't worth supporting anymore at the drop of a hat.

**Comment by F0bes** [comment]
Looks like the incompatibility arose when we migrated away from the WX string handling
commit: https://github.com/PCSX2/pcsx2/commit/29cea584713f51f8cd3beb74c58bd637d1d80fcd
Looks like the underlying issue comes from [std::from_chars](https://en.cppreference.com/w/cpp/utility/from_chars), see the first note:
`"0x" or "0X" prefixes are not recognized if base is 16 `

On a non-technical note, I'd like to add that you're coming off like a dick and it's pretty unreasonable.
Cheers.

**Comment by Phoenix-neat** [comment]
> On a non-technical note, I'd like to add that you're coming off like a dick and it's pretty unreasonable

This is something I'm clearly passionate in and I disagreed with the two prior messages giving pushback. When I give pushback to support a removed feature, it isn't an attack. Take constructive criticism without outright insulting your userbase, especially the ones that actually bother to report issues. There's plenty of people that don't like working with PCSX2 EXACTLY because of interactions like this. 

My initial message was straight to the point. The follow-up was an honest defense (the change IS poorly documented, and it does break a lot of compatibility. If it was an intended feature removal, as implied by one of the responses, it should have been noted). You're the one name calling.

Moving past _that_, I look forward to the issue being resolved

**Comment by seta-san** [comment]
I vote to leave the 0x notation off as a matter of style and saving space

**Comment by F0bes** [comment]
> I vote to leave the 0x notation off as a matter of style and saving space

It's a regression that breaks existing users tooling and work flows, that's not really up for debate.

**Comment by stenzek** [comment]
+1 you to you coming across as an arrogant dick.

**We don't work for you**. You did not pay a cent. **You are not a customer.**. You are not entitled to anything.

That said, obviously it shouldn't crash, I'll sort that out since it's probably my regression.

**Comment by stenzek** [comment]
However, I guess we should really discuss what to do about the prefix - personally I'm in the camp of "it must be a hex value" regardless, i.e. anything containing a non-hex digit is invalid.

Otherwise, it's just silly, `123` represents different numbers in hex and decimal, saying "it's hex if there's no prefix, or if there's a 0x prefix" is counter-intuitive to basically everything else on the planet, which is decimal unless prefixed.

If a user wants to use a broken/ill-formatted patch, then that's their problem, not ours.

**Comment by TheLastRar** [comment]
While they have come off on the aggressive side, I personally don't think they come across as a dick.

Is the pnach format used by anything else? If we are the only, or main consumer of pnach files then our (stable) implementation ends up being the de-facto standard, rather than what is documented.

If we do want to officially drop support for pnaches with the hex prefix, that that should be properly communicated, given that it is a breaking change.

**Comment by stenzek** [comment]
The report was kinda garbage to be honest.

OP claimed it "crashes", but didn't provide a crash dump. Turns out PCSX2 wasn't crashing, their broken patch was writing to null, causing the game to jump to null, which made PCSX2 abort. Not an "emulator crash", but a game crash (which causes PCSX2 to behave differently in release vs devel builds).

> Is the pnach format used by anything else? If we are the only, or main consumer of pnach files then our (stable) implementation ends up being the de-facto standard, rather than what is documented.

No, it's not, and I've checked all the patches in our repo - none of them use the 0x prefix.

The linked patch is just stupid. Look at the first patch line - it doesn't prefix the address, but the others do, except 4th, which prefixes the value, but not the address, again, inconsistent from the rest.

> If we do want to officially drop support for pnaches with the hex prefix, then that should be properly communicated, given that it is a breaking change.

My PR adds log messages when it parses, as well as instructs the user that it should be a hex literal. That's good enough, if they can't read, not our problem.

Personally, like I said, I think we should treat values as decimal unless prefixed (**especially** for the value), but that would break basically all well-formed patches out there.

**Comment by TheLastRar** [comment]
> The report was kinda garbage to be honest.
> 
> OP claimed it "crashes", but didn't provide a crash dump. Turns out PCSX2 wasn't crashing, their broken patch was writing to null, causing the game to jump to null, which made PCSX2 abort. Not an "emulator crash", but a game crash (which causes PCSX2 to behave differently in release vs devel builds).

We only distribute release builds, so an abort/force close due to a game bug, and an emulator crash would be difficult to differentiate without building a debug build yourself, I would consider this inaccuracy forgivable as a result.

While we didn't get crash dump we did get sufficient information to easily reproduce the crash, which is still pretty good considering.

I don't know what you're expecting to consider a report not garbage.

> 
> > Is the pnach format used by anything else? If we are the only, or main consumer of pnach files then our (stable) implementation ends up being the de-facto standard, rather than what is documented.
> 
> No, it's not, and I've checked all the patches in our repo - none of them use the 0x prefix.
> 
> The linked patch is just stupid. Look at the first patch line - it doesn't prefix the address, but the others do, except 4th, which prefixes the value, but not the address, again, inconsistent from the rest.
> 

How stupid it may look is mostly irrelevant when it worked.

My argument was more so that because we accepted it in the past, we should continue to do so as that may be the expectation.
Ultimately the strength of that argument depends on how common malformed pnaches are.
Given that it's taken over a year for this issue to crop up it's probably pretty rare.

**Comment by Phoenix-neat** [comment]
This isn't a user friendly solution as the emulator doesn't actively inform the user the pnach isn't being taken into account and why it isn't being taken into account unless the console is open.

Furthermore we had a solution, why not just integrate this? https://github.com/PCSX2/pcsx2/pull/6221

**Comment by TheLastRar** [comment]
> That's exactly why we have the crash dumping system.
> 
> I started by doing what the OP says - adding the specified patch line. Nothing crashed. So that part of the report **was** garbage.
> 

Okay I guess that's fair I guess, I tried with the reproduction steps, which where accurate and gave me a crash dump.
I would assume then that the OP only tried with one game (or game engine) and assumed it was universal.

> If they'd have posted the crash dump file, assuming PCSX2 did actually crash, then I would've known it was a game crash, and wouldn't have had to download the linked patch and try with that specific game. Additionally, if they'd attached a log file, **as the report template requests**, then we'd have also known it was a game crash.

It seems they used the "Application Bug Report" instead of the "Emulation Bug Report" template, which doesn't ask for logs or dumps.

Based on their report, and assuming my assumption above is correct, they may have assumed it was an application bug rather then an emulation bug. 

> > My argument was more so that because we accepted it in the past, we should continue to do so as that may be the expectation.
> 
> Please read what I originally posted again. I specifically addressed why this would be a bad idea - it's ambiguous: [#8893 (comment)](https://github.com/PCSX2/pcsx2/issues/8893#issuecomment-1560496272)

While removing ambiguity is good, I don't know if it's strong enough point to warrant a breaking change.

Sure you could argue that the presence of a prefix on a hex number 0x1234 implies that 1234 (no prefix) would be a decimal number, but we've had the offending wx code for a _long_ time, only being remove a little over a year ago. and pnach makers seem to have figured things out.
Additionally all guides explicitly state the value is hex (regardless of prefix), which does help clear the ambiguity.

**Comment by Phoenix-neat** [comment]
You're being pretty rude to me. I still got the email with your deleted issue comment you sent me (the one your edit acknowledges as "a little overactive"). Calling this a "garbage report", calling me a dick, it's low effort I'm arrogant etc none of this is warranted to a GitHub bug report. The Nightly's changing the HostFS system required me to re-setup the mods for the emulator and I wasted about two hours with this pnach problem, but I'm not here to incite you I'm here cause I want the feature back.

I assumed the issue was to be filed under Application as it appeared to be unanimous across all titles regardless of whichever game was used provided it has the "0x" notation problem. The template doesn't request it under application, it's at worst an honest mistake at best I did nothing wrong.

When I say things like
>There's plenty of people that don't like working with PCSX2 EXACTLY because of interactions like this.

And then you go and say offensive things to me, delete your comments, and continue to be rude, this is exactly what I'm talking about.

Cool. I'm happy something's been done, but you've made me incredibly uncomfortable and I don't feel comfortable enough to report issues in the future as a result of your conduct.

**Comment by stenzek** [comment]
Closing this out:

> The Nightly's changing the HostFS system required me to re-setup the mods for the emulator and I wasted about two hours with this pnach problem, but I'm not here to incite you I'm here cause I want the feature to work as intended.

Using the nightly build was your choice. Things change in major software releases, it's inevitable. You can always use the stable release.

How could you honestly say your post was not intended to incite? You complain about the lack of documentation for a volunteer project, yet do nothing to improve said documentation.

Let me quote you: "That one instance may be fixed but I've got a lot less interest fixing every single pnach file that happens to have this notation cause the dev team decided a functional feature wasn't worth supporting anymore at the drop of a hat.".

This was not a "feature". The old behaviour was a quirk of how the wx routines operated. A new wx version could have changed this behaviour too. Again, quirks and unintended behaviour get resolved all the time, this is nothing unusual for software development.

What happens when we next modify the parser to support togglable cheats? Are you going to complain that because you happened to use the tokens which now have meaning for something else, that we should remove the new functionality so that your malformed patches continue to work? At some point things are going to break, even if it's not intentional. If you don't want that, use the stable build.

> And then you go and say offensive things to me, delete your comments, and continue to be rude, this is exactly what I'm talking about.

I never said anything negative about you personally. I +1'ed the earlier remark about coming across as a dick, and subsequently removed it because in hindsight, throwing more fuel on the fire is never helpful, so next time this inevitably happens, I'll choose my words more wisely. But it still won't change the outcome.

Like I stated in my original reply, we have no contract, we're not here to serve your needs. When you basically say "I want you to restore incorrect behaviour because I can't be bothered to fix my patches", that is not setting the stage for a positive interaction, so it shouldn't be that surprising if that's interpreted negatively. If you don't like the way something behaves, you can submit a patch, and we'll merge it if it is reasonable, otherwise you can always fork the software.

> Cool. I'm happy something's been done, but you've made me incredibly uncomfortable and I don't feel comfortable enough to report issues in the future as a result of your conduct.

The feeling is mutual mate. Even now, I'm still interpreting this as a sense of entitlement (perhaps I'm incorrect), but being able to report "issues" is not a right, developers have the freedom to reject or resolve issues as they feel fit. If you want someone to action your feedback exactly how you request, I'd suggest employing a team of people to write your own PS2 emulator.
