### ISSUE TITLE
[BUG]: "SDL-0: USB Gamepad" is no longer recognized in the current version 1.7.4737 (1.7.4573 works)

### ISSUE THREAD

**Issue by rtek1000** [PCSX2/pcsx2#9261]
### Describe the Bug

"SDL-0: USB Gamepad" is no longer recognized in the current version 1.7.4737 (1.7.4573 works)

### Reproduction Steps

"SDL-0: USB Gamepad" is no longer recognized in the current version 1.7.4737 (1.7.4573 works)

### PCSX2 Revision

"SDL-0: USB Gamepad" is no longer recognized in the current version 1.7.4737 (1.7.4573 works)

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu 22.04.2 LTS

### Logs & Dumps

"SDL-0: USB Gamepad" is no longer recognized in the current version 1.7.4737 (1.7.4573 works)
![pcsx2-v1 7 4573-linux-AppImage-64bit-Qt](https://github.com/PCSX2/pcsx2/assets/8660811/1c5f0fcb-e9fd-4805-8a31-b49f02aae23b)
![pcsx2-v1 7 4737-linux-AppImage-64bit-Qt](https://github.com/PCSX2/pcsx2/assets/8660811/8d572c4c-9144-4a19-bb1e-9522cd60f3e6)

**Comment by rtek1000** [comment]
- Note

Joypad install:

```
sudo apt-get install xboxdrv joystick

sudo apt-get install jstest-gtk
```

restart USB

**Comment by stenzek** [comment]
A ~200 build bisect isn't helpful, and you haven't posted a logfile.

**Comment by refractionpcsx2** [comment]
It's probably the cheap Chinese identified one which sdl removed, not us. If you want to use it you'll need to enable the "SDL Raw Input" option.

**Comment by kamfretoz** [comment]
> It's probably the cheap Chinese identified one which sdl removed, not us. If you want to use it you'll need to enable the "SDL Raw Input" option.

SDL Raw Input not a thing on Linux 😛

**Comment by refractionpcsx2** [comment]
Then I guess they're screwed :P

**Comment by stenzek** [comment]
If SDL removed the mapping, then that would make sense (although I'd think it'd still show up as a joystick..). You could recreate the mapping and update the file yourself, I suppose.

I'll pre-emptively close for now, if the logfile suggests there's an issue, we can reopen.

**Comment by rtek1000** [comment]
So if version 1.6 recognizes the Gamepad, and even version 1.7.4573 was recognizing it, now the emulator may not recognize it? Is the user going to update the emulator and have to rework the gamepad? Is this right? OK thanks.

**Comment by stenzek** [comment]
We can't help you if you don't provide basic information like a log file, as the template requests.

**Comment by rtek1000** [comment]
I'm sorry the case is closed

**Comment by stenzek** [comment]
And I said I'd be happy to reopen it if you provided the required information, and we determined that it was actually a bug.

Arguing is silly, so let's not waste each others time - if you'd rather be passive aggressive, rather than work with us to identify the issue, then yes, there's indeed no point in responding further.

**Comment by rtek1000** [comment]
It's bad when someone plays with the same cards we use, isn't it?

v1.7.4637 works, v1.7.4700 not works

![pcsx2-v1 7 4637-linux-AppImage-64bit-Qt](https://github.com/PCSX2/pcsx2/assets/8660811/6a277ccb-cb89-4657-901f-98a23285ed5d)

**Comment by stenzek** [comment]
> It's bad when someone plays with the same cards we use, isn't it?

Mate, we're trying to do you a favour by trying to debug it here. This really is a support issue, since nobody else has reported this problem, so it's out of scope for GitHub, and should be held on the Forums or Discord instead, until it is ascertained that there is actually a bug. GitHub is not for support.

If you think this is some "game" and you can "one up" us and make us look bad by refusing to provide information, you're mistaken, as far as I'm concerned there's actually no bug, therefore I won't lose a moment of sleep if this is forgotten about.

I'll make it clear: Provide a full log file from startup, and information about your controller (specifically VID/PID), or I am going to lock this issue.

**Comment by rtek1000** [comment]
I also don't know what causes this, I'm using the successive approximation technique, my internet is very slow, 2Mbps. the v1.7.4680 version works.

I tried to find in the [documentation](https://pcsx2.net/docs/) how to generate the log, but I couldn't find it. I also didn't find a button to generate the log in the emulator, it could be interesting to have a button in the Help menu.

I found a checkbox to activate the log, but that alone leaves the user lost.

![Enable log](https://github.com/PCSX2/pcsx2/assets/8660811/8b07926c-e900-4747-9e01-ae1485c88960)

**Comment by stenzek** [comment]
The log file is located in the data directory, under logs.

Under normal support situations, there's a bot on DIscord which provides this information, so no, the user is not "lost".

**Comment by rtek1000** [comment]
v1.7.4693 works, v1.7.4694 not works

**Comment by stenzek** [comment]
Great. I suspected it's a SDL2 issue, so that is not surprising at all, but also out of our control.

Regardless, since you **still** haven't provided the requested information, and I've tried several times to get this across, so I'm locking this issue now.
