### ISSUE TITLE
[BUG]: Pcsx2 closes when loading Onimusha 4 USA

### ISSUE THREAD

**Issue by Felipefpl** [PCSX2/pcsx2#9660]
### Describe the Bug

1st of all my awful specs:

Core i7 1.8 Ghz, 4 GB RAM and Intel HD 2000.

Yes, i know it's bad and the game will be slow but i dont mind. I'm just thankful for all the work the devs made with pcsx2. I even write reviews in the wiki for those with bad computers like me to help them to play the games the faster they can:

https://wiki.pcsx2.net/Rygar:_The_Legendary_Adventure

The reason i'm playing onimusha 4 in the 1.7.0 is because it's hard to see what is written in-game because of the graphics' corruption in the old versions. That's why i decided to install win10 to play it. There are 2 interesting facts about this situation:

1 - I still have rygar here and the game works fine with 1.7.0.

2 - Onimusha 4 works with software renderer but not DX 11 or OpenGL (which i cant use here, apparently i dont have support for it even although it says in the main page the minimum GPU requirement is Direct3D10 support and OpenGL 3.x support and i have full support for OpenGL 3.1 and 75% support for OpenGL 3.3)

### Reproduction Steps

Load onimusha 4 with DX 11 and the game or pcsx2 will crash before reaching the new game's screen.

### Expected Behavior

Pcsx2 should work.

### PCSX2 Revision

1.7.4830

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
What actual CPU do you have ?

**Comment by stenzek** [comment]
You need GL3.3 minimum.

Post the crash dump. But most likely it's a broken driver.

**Comment by stenzek** [comment]
As https://github.com/PCSX2/pcsx2/commit/ff9ca059c7849695c17beda33b0cc30e95c2be9e dropped support below feature level 11, you could try to reproduce the crash with WARP (Microsoft Basic Render Adapter) I suppose. If it still happens, post the crash dump. Otherwise, it's likely a broken driver.

**Comment by Felipefpl** [comment]
@stenzek - I searched for a crash dump in pcsx2's folder but i couldnt find any. :/

> Feature level 11.0 GPUs were first released in 2009, almost 14 years ago now. Older GPUs have not had drivers released in a long time, and are known to be buggy.

None of us have hardware this old, so it's impossible for us to support it.

I saw this update and my graphics' driver is from 05/19/2016, it's old but not from 2009, Intel HD 2000 was released in 2011.

**Comment by stenzek** [comment]
> I searched for a crash dump in pcsx2's folder but i couldnt find any. :/

Then there's nothing we can do. I suggested using WARP to at least isolate the issue to the driver, but that appears to be ignored.

> and my graphics' driver is from 05/19/2016

So? Doesn't mean it's not broken, which is possibly the case here, since nobody else has reported any issues with the game.
The latest driver for my 2017 XPS's HD 630 is only from last month, and OpenGL is still broken - PCSX2 hangs the GPU, it resets, then nothing else renders. It's only fixed on Xe and newer, they tend not to backport fixes.

> it's old but not from 2009, Intel HD 2000 was released in 2011.

Feature Level 11.0 GPUs were first released in Sep. 2009, that's almost 14 years ago. When we don't have hardware which we can use to debug these issues, what do you expect us to do? Not dropping support means users such as yourself get confused, when the requirements state it's supported, but driver issues prevent it from actually working.

I can empathize with you if you don't have access to newer hardware, but it's unrealistic to expect 2023 software to run on hardware which is close to a decade and a half old. Using software more period correct for your hardware is always an option.

Also FYI, your HD 2000 has less fill rate than the PS2's GS. That's how slow it is :/

**Comment by Felipefpl** [comment]
Ok then, thanks for the replies.
