### ISSUE TITLE
MGO1 Widescreen hack

### ISSUE THREAD

**Issue by Blackbird88** [PCSX2/pcsx2#968]
I found it on SaveMGO forums in RAW format and converted it with PCSX2CE and it works, but how to add it when the WS fixes are in .zip file?

CRC = **01B2FA7F**
>comment=Widescreen
>patch=1,EE,2026D1DC,extended,3F40000

![image](https://cloud.githubusercontent.com/assets/4414625/11121729/c2ef8906-8957-11e5-9521-1401a144b85c.png)

**Comment by willkuer** [comment]
You can just put it into your cheats ws folder. Also we have a dedicated forum at pcsx2.net where you can post such codes. They are then validated managed by devina and his/her team.

**Comment by Blackbird88** [comment]
As you can see I made it work, but I had no idea where to post it since you can't PR .ZIP very well :dancer: Thanks for the heads up.

**Comment by willkuer** [comment]
I dont think a pr wouldve been accepted. The widescreen patches are collected in one thread and only added unfrequently. All widescreen hacks that are added are tested in this thread and normally mustn't create issues somewhere in the game.

Widescreen hacks actually have a quite strict review process.

**Comment by nhydock** [comment]
Instead of having a forum thread for archiving widescreen hacks, do you think the PCSX2 organization could open up repository for them?  I just think it could be cleaner and more centralized that way, as it kind of goes hand-in-hand with PCSX2.

**Comment by willkuer** [comment]
Good idea. I would suggest again to visit the forum to discuss this in the dedicated thread. So far widescreen hacks are.managed by users not by the main pcsx2 devs. This issue is not the optimal place to discuss this. I would rather first discuss it in the forum and make a decision using a poll or something like that and then open a pr/issue with the suggested changes.
