### ISSUE TITLE
[Feature Request]: Wait for external HDD to wake up from sleep when Loading Games

### ISSUE THREAD

**Issue by mrtawsiti3** [PCSX2/pcsx2#9693]
### Description

PCSX2 will crash when you load a game if external HDD is in sleep mode.

### Reason

Saves 5-10 seconds of time and few keyboard and mouse clicks.

### Examples

Yuzu emulator have this feature

**Comment by Mrlinkwii** [comment]
its not advised to use an external HDD

**Comment by F0bes** [comment]
Can you provide a crash dump (.dmp) or a backtrack if on Linux when this happens?
Hard drive sleep should have no visible side effects for PCSX2 besides startup latency.

**Comment by stenzek** [comment]
This makes no sense.

1. We don't know how long to wait for a HDD to spin up again.
2. PCSX2 reads the ELF from the disc on startup, before the VM runs. So startup will be blocked, not emulation, therefore this is already happening.
3. It's not going to stop the drive going to sleep during periods of gameplay where the CDVD is not being actively read.

If there's a crash, as fobes said above, please post the crash dump, because that *may* be a bug. But otherwise, I see no reason to implement this.
