### ISSUE TITLE
[BUG]: Dragon Quest VIII: graphical issue on cave walls.

### ISSUE THREAD

**Issue by bigol83** [PCSX2/pcsx2#9791]
### Describe the Bug

I just noticed it into the first cave walls so can't say it's a more widespread issue or not, but here it is

![Dragon Quest VIII - L'Odissea del Re maledetto_SLES-53974_20230813235632](https://github.com/PCSX2/pcsx2/assets/38129260/9c798a84-eb74-4091-87ee-9bef005668e6)

See those rectangles under the water. Those appear at native resolution too and in every renderer, only software renderer doesn't have this issue. 

I tested some options and it seems that setting CPU sprite render size to 1 and blended sprite triangles fixes it. 

### Reproduction Steps

Go to the first cave ingame and notice those weird crystal like rectangles near the cave walls.

### Expected Behavior

Clean cave walls textures. 

### PCSX2 Revision

pcsx2 1.7.4915

### Operating System

Windows 10 (64bit)

### CPU

intel g4560

### GPU

nvidia gtx 1050 ti

### Logs & Dumps

Gsdump

[Dragon Quest VIII - L'Odissea del Re maledetto_SLES-53974_20230813235632.zip](https://github.com/PCSX2/pcsx2/files/12330530/Dragon.Quest.VIII.-.L.Odissea.del.Re.maledetto_SLES-53974_20230813235632.zip)

**Comment by RedDevilus** [comment]
Damned I jinxed it ![IMG_20230814_001556.jpg](https://github.com/PCSX2/pcsx2/assets/24227051/2ac3c0a6-266b-4ec3-8ebe-f07cb4bddd88)

**Comment by bigol83** [comment]
I read it's a regression but since Refraction told me to test the game a bit more i reached the first cave. I never really played it on Pcsx2 after the first town so can't say when it regressed.

**Comment by refractionpcsx2** [comment]
So I don't talk forever on my PR (linked below), what was happening here, is there was a larget target being used for rendering part of the character, which it then decided to use for doing the water, but the problem is, it uploaded a background colour to blend with the water texture, and due to the target being a different width, the wrong pixels got invalidated and the target was reused as a new target with the uploaded texture in the wrong place.

So I've been more aggressive with deleting old targets which don't match.
