### ISSUE TITLE
[Feature Request]: Add an option to exit PCSX2 from the "Pause Menu" (Big Picture)

### ISSUE THREAD

**Issue by awsms** [PCSX2/pcsx2#9793]
### Description

I would like to have a button "Exit PCSX2" under the existing "Exit Without Saving" button, so I can exit the emulator without having to use my mouse after launching a game from the game list.

On a side note, what do you think about renaming "Exit And Save State" & "Exit Without Saving" to "Shut Down And Save State" & "Shut Down Without Saving" respectfully, so it matches the options from the "System" menu?
So an actual "Exit" option would make more sense.

### Reason

It's currently impossible to exit PCSX2 from the "Pause Menu" if you didn't launch a game with the "Big Picture" mode.
You can only quit the current game, and be brought back to the game list.

### Examples

![Screenshot from 2023-08-14 02-49-14_](https://github.com/PCSX2/pcsx2/assets/48278661/e1e6d094-e2c3-48bf-b2e5-ebb9328fcdcf)

**Comment by stenzek** [comment]
-1, IMO it would just result in misclicks, for very little if any benefit.

**Comment by awsms** [comment]
> it would just result in misclicks

What about adding a Y/N pop-up "are you sure you want to exit PCSX2" after it was pressed?

**Comment by stenzek** [comment]
Then it's the same amount of clicks as doing so from the main menu?

**Comment by stenzek** [comment]
Closing for reasons noted above.

**Comment by ZazaMastro** [comment]
Serioulsy this has been flagged as "not planned"?! Guys be serious, this is a needed quality of life improvement and must be done. So many people using PCSX2 with a mini PC in a sofa configuration without mouse or keyboard. Is this reason enough to proceed? Come on...

**Comment by refractionpcsx2** [comment]
Then start the emulator in big picture mode, and it won't be a problem.

**Comment by stenzek** [comment]
And it's the same number of button presses regardless of whether you exit from a hypothetical option in the exit submenu, or exit the game, then exit the emu from the main menu. That's why it's redundant.

More redundant menu options = clutter and confusion.

You can always modify the source and add it yourself, too. ;)

**Comment by ZazaMastro** [comment]
At least it's not possible to simply reintroduce the option to "close PCSX2 when emulation stops" like in the old PCSX2 versions?

**Comment by refractionpcsx2** [comment]
use -nogui

**Comment by GSTDiandre** [comment]
@stenzek I'm genuinely confused how it's the same number of clicks.

Exiting the game from the Big Picture menu returns the user to this screen

<img width="1887" height="872" alt="Image" src="https://github.com/user-attachments/assets/9d878574-6b50-47d0-929b-20297f90182d" />

They'll need to scroll all the way (three right presses, then confirm), pick Exit, then make sure they don't fumble picking between two more options behind the Exit button with two more clicks:

<img width="1578" height="758" alt="Image" src="https://github.com/user-attachments/assets/a710a98c-a450-4708-b7e4-48e07a6f0c12" />

The alternative is a simple "Exit PCSX2" with a Y/N confirm on the Big Picture menu that lends itself to muscle memory quite easily. We could even make it fit the classic up => confirm => up => confirm we use in countless other games and software to exit things. That is, if we could make the big picture menu wrap around like it probably (definitely) should. It already does on Duckstation.

The overhead is there, I don't think people would complain otherwise.

**Comment by refractionpcsx2** [comment]
You're the only guy who seems to be complaining, nobody else has mentioned it in 2 years.

**Comment by GSTDiandre** [comment]
And that means it's not worth fixing? My bad then.
