### ISSUE TITLE
FFX/X-2 - SLPS-25088/SLPS-25250 - Fine horizontal grey lines

### ISSUE THREAD

**Issue by kotarou3** [PCSX2/pcsx2#981]
Screenshots of the bug:
https://0x0.st/-XB.png
https://0x0.st/-XM.png

I have tested for this issue under:
 - Ubuntu 14.04.3
 - Both hardware and software renderers
 - Both native and 4x internal resolutions
 - Both native and fullscreen display resolutions

Taking an internal screenshot (with F8) did not show the bug.

I compiled PCSX2 directly from the repository, with a minor modification to change the config directory.
I bisected the issue to 1659d5974eceb45a8ed4c3cbf06630322cb258e7.

**Comment by kotarou3** [comment]
Reading #928, pressing F7 a few times fixed it.

Suggest having a GUI config for it somewhere? I couldn't find any existing one.

**Comment by gregory38** [comment]
```
Suggest having a GUI config for it somewhere? I couldn't find any existing one.
```
It is a Easter egg :p

**Comment by kotarou3** [comment]
For someone who might have accidentally pressed F7 and not realising it (like me), there's no indication of how to switch it off, or if it is on at all (apart from the changed display) in the GUI. It made me spend a good few hours working out why it occured.

If it's supposed to be an easter egg, maybe only show a config option when it's enabled? That way people could easily turn it off without knowing the F7 hotkey.

**Comment by willkuer** [comment]
The eater egg suggestion was more or a joke i guess. We thought several times now that it would be good to add this option to the normal config. Another 'easter egg' was recently fixed/shown in the config. So it is possible it is possibly not even hard but there is not much time. Maybe - if it doesnt exist - you can open an issue requesting the gui element.

**Comment by turtleli** [comment]
Well, I'm actually just waiting to see if anyone wants to open an issue and also wants to tackle it. ;)

Mainly because adding another combobox might make the GSdx dialog height too big for small screens (both Windows and Linux), which might mean a redesign, and that'd be a pain.

**Comment by willkuer** [comment]
Maybe remove OpenCl Combobox? I am not sure Gabest will finish this implementation soon. Maybe he doesn't even want to finish it. In any case it is not used and can be added again later.

Or AF to HW hacks section?

**Comment by karasuhebi** [comment]
I agree that this needs to be reflected somewhere other than printing it in the console (maybe in the GSdx OSD once someone decides to do that? :D) but another suggestion could be would be to disable that shortcut by default. Or maybe @avih could create a GUI for the shortcut system so that people know what the default hotkeys are? Something like Dolphin's shortcut GUI would be nice:
![usiwbc7](https://cloud.githubusercontent.com/assets/6857825/11287920/4a71af22-8eed-11e5-86d4-ed162241369f.png)

**Comment by ssakash** [comment]
There are actually lots of improvements to make on the dialog -

* Integrate all NULL renderers on video renderer combo-box to a single one. 
* Tabs ? for consistency with Linux.
* and probably make the F9 toggle on the plugin side instead of on the core to have a future tab on the GSDX plugin settings for customization.

> Well, I'm actually just waiting to see if anyone wants to open an issue and also wants to tackle it. ;)

I was actually thinking you would do it !  I'll PR it in 3-5 days if no one gets to it.

**Comment by ssakash** [comment]
also would be better if someone could open up an issue, I'm too lazy to do it :p

**Comment by gregory38** [comment]
I updated the linux gui.
