### ISSUE TITLE
[BUG]: Black borders in OBS

### ISSUE THREAD

**Issue by YukiXXL** [PCSX2/pcsx2#9862]
### Describe the Bug

Black borders are appearing in OBS.

![Nightly](https://github.com/PCSX2/pcsx2/assets/53857551/d3dbc8b5-194f-4570-8aac-89aedeaa8037)

### Reproduction Steps

1. Run the emulation
2. in OBS: add the "Game Capture" source with "Capture specific window" and select PCSX2.

### Expected Behavior

Display the whole screen without black borders like in 1.6

![Stable](https://github.com/PCSX2/pcsx2/assets/53857551/662359c6-4927-4166-9c78-db2d77b735c4)

### PCSX2 Revision

Latest Nightly

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
this seems an OBS thing and not a pcsx2 issue

**Comment by YukiXXL** [comment]
if that's the case, then why did it work in 1.6 and doesn't work in 1.7?

**Comment by stenzek** [comment]
Not a clue. Maybe try render to separate window.

But we're not adding borders to the window, so I don't see how this is on our end.

**Comment by YukiXXL** [comment]
> Not a clue. Maybe try render to separate window.
> 
> But we're not adding borders to the window, so I don't see how this is on our end.

I tried it and it still shows.
The borders are being shown when window size is being changed from aspect ratio or when in full screen.

**Comment by stenzek** [comment]
Yes? Of course it's going to happen in full screen - the window is full screen.

I thought about it some more, 1.6 used a **really** janky way of presenting, it mixed GDI with the 3D surface, which is terrible for performance and doesn't work on all platforms. So that's probably what it was relying on, and we're *definitely* not going back to that.
