### ISSUE TITLE
[BUG]: pcsx2 no longer builds on linux

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#9871]
### Describe the Bug

PCSX2 is no longer building on linux (Mint, which is a Ubuntu derivative) apparently due to a new requirement for a more recent SDL2 version than what is in the repo.  According to #9290, building now requires 2.28.2 vs. 2.28.1.  However, the test platform has been using the repo's latest version (2.0.20) even when it was compiling fine on master prior to when this PR was merged.

Relevant test system specifications:

* CPU: Intel i7-10870H
* Compiler: gcc-12.3.0
* CMake: 3.24.0
* Last known good commit: b8cfd83d33b60bdc21e144df97ab0e53a0baf471

### Reproduction Steps

Attempt to build using a linux/ubuntu derivative OS.

### Expected Behavior

PCSX2 builds properly.

### PCSX2 Revision

Commit 43335cd729a2ffcfedf5ea869b55afc148096bbc

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Linux Mint 21.2

### Logs & Dumps

Build log: [build.log](https://github.com/PCSX2/pcsx2/files/12449942/build.log)

**Comment by stenzek** [comment]
"no longer builds on linux" is complete rubbish. Our CI produces both AppImage and Flatpaks, and it works finef or me locally.

21.2 is likely too old anyway. Update your OS and/or dependencies - you can use our CI's build script.

**Comment by TellowKrinkle** [comment]
We used to include SDL as a submodule to use when system SDL was too old, but we no longer do
You can always manually compile a modern SDL and point cmake at it with `-DCMAKE_PREFIX_PATH=/path/to/my/sdl`

**Comment by stenzek** [comment]
Considering 2.0.20 was released in Jan '22, I'd expect this wouldn't be the only dependency with issues, hence why I suggested following our dependencies build script. I know it works on Ubuntu 22.04, at least (20.04 is too old - the compiler is missing C++20 bits).

**Comment by helkaluin** [comment]
To be fair, 2.28.2 is quite new. Neither the latest releases of Ubuntu (23.04 is on 2.26.3) nor Fedora (38 is also on 2.26.3) has it.

See: https://repology.org/project/sdl2/versions

Since you're going dynamic with the SDL2 dep it might be quite difficult to package the latest PCSX2 the old-fashioned way with distro-native packages. Technically I could shove the whole SDL 2.28.2 into the PCSX2 daily PPA, but overriding such a system-criticial lib is going to be a Bad Idea™.

I suppose the project's maintainers want to go full Flatpak/Appimage? With this change I'm afraid the Ubuntu daily PPA won't be able to catch up, at least for the Ubuntu releases still in support.

**Comment by stenzek** [comment]
We absolutely need the latest SDL version. Controller support, which is what we use it for, is constantly being broken and fixed. "my controller isn't working" is common enough, let alone "my controller isn't working because I'm using a third-party package with outdated libraries", and nobody specifies that they're using outdated libraries which are at fault, and they're blaming us instead.

We require Qt 6.5 too. The only reason that check isn't enforced, is because MacOS is still on 6.4, because 6.5 requires 11.0, which Tellow hasn't bumped yet. Older Qt versions cause issues, and at least we're not wasting time debugging bug reports which are already fixed.

> Technically I could shove the whole SDL 2.28.2 into the PCSX2 daily PPA, but overriding such a system-criticial lib is going to be a Bad Idea™.

That's exactly what we do. Not trying to be a twat, but if your priorities are "I want to follow stupid antiquated distro practices" instead of "not creating a support headache for developers", well, that's exactly why we provide zero support for users of packages.

> With this change I'm afraid the Ubuntu daily PPA won't be able to catch up, at least for the Ubuntu releases still in support.

And this is our problem, how? We provide two builds which work perfectly fine on Ubuntu (AppImage, Flatpak), both which automatically update. If you want to package our software, maintaining it and providing support is your responsibility, not upstream. The code is out there, you're within your rights to fork it if you don't like how we do things.

**Comment by helkaluin** [comment]
>And this is our problem, how?

Never said it is, so please calm down.

I'm just trying to guage what's the upstream's current stance is on these distro-specific daily builds. I've set up the Ubuntu daily PPA years ago with the help of  Gregory (I don't think he's still involved with pcsx2 these days?) and I'm just checking in to see what's the current mood like.

Every time there's one of these compilation/packaging changes I check in and see what's upstream's stance (last time was when pcsx2 started using git submodules, because automatic builds on Launchpad are done fully offline and cannot pull submodules as part of the build process). This is yet another such instance.

Since it seems the current slew of maintainers pretty much want everyone to just use the Flatpak/Appimage, should I just go ahead and delete the daily PPA? Just let me know. And you may want to delete the references to the PPA as well from your wiki just so future users will know to use the Flatpak/Appimage.

**Comment by RedDevilus** [comment]
https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily you mean this one? It always was kinda distributed alongside the regular builds. If they work fine or can be adjusted, I don't see why there has to be such extreme measures even if I can understand the grievances, git submodules on paper sound easier but it sneaks in alongside normal commits and then you accidentaly desync it.

Though even the Orphis builds were pulled out: https://buildbot.orphis.net/pcsx2/ (Orphis also having more server space again) as it's more controlled on the team side. So I can understand that with the uniformity with it all, that there might still be a place for the PPA. Just like the flatpak used to be controlled by a seperate maintainer and did their own stuff and other locations which give headache to support even if it was the same PCSX2 nightly.

**Comment by TellowKrinkle** [comment]
For packaging, it might be easiest to include [a patch](https://github.com/PCSX2/pcsx2/files/12451389/0001-Allow-static-SDL.patch) that switches the sdl include to `SDL::SDL-static` so you can build and static link a copy of 2.28.2 (which is what used to happen with the submodule if your SDL was too old)

Either that or patch the minimum version, but if you do that, users complaining that their joy cons don't connect aren't our problem.

**Comment by stenzek** [comment]
> Never said it is, so please calm down.

Everything's fine here ;) I was just making it clear that packaging woes are not our problem, because some people seem to misunderstand and think that it is.

> because automatic builds on Launchpad are done fully offline and cannot pull submodules as part of the build process). 

Your builds won't have WS patches either, then. Because we download these as part of the build process, that's the main reason that the Flatpak is built on our infrastructure, rather than Flathub's.

> Since it seems the current slew of maintainers pretty much want everyone to just use the Flatpak/Appimage, should I just go ahead and delete the daily PPA? 

Do what you like. But anything other than the builds on pcsx2.net will receive no support. Ideally, you should make it clear that they are unofficial, and that users should seek support from the packagers, rather than upstream, sadly this very rarely happens.

> And you may want to delete the references to the PPA as well from your wiki just so future users will know to use the Flatpak/Appimage.

I doubt many users read the wiki, they're going to go the website instead. But yes, all that stuff needs to be tossed out once we tag 2.0, since basically none of it is relevant past 1.6.

>  switches the sdl include to SDL::SDL-static

FWIW, I believe SDL will internally search for a dynamically linked module anyway, so that users can swap it out with a newer library. That's the main reason I dumped static linking on Windows, it was kinda redundant.

**Comment by RedDevilus** [comment]
There is a seperate one for the patches: https://code.launchpad.net/~pcsx2-team/+recipe/pcsx2-patches-daily

**Comment by helkaluin** [comment]
The WS patches are a solved problem. I just have Launchpad build them as another package (it just zips them up whenever the git repo changes): https://code.launchpad.net/~pcsx2-team/+recipe/pcsx2-patches-daily and https://git.launchpad.net/~helkaluin/+git/pcsx2_patches/tree/

It's the SDL that's going to be more of a problem package-wise, but that's not what I was trying to gauge. The daily PPA was set up years ago because it was the only sensible way that Ubuntu users could get hold of an up-to-date PCSX2 (stable releases were few and far between). Now that you guys have these AppImages and Flatpak builds all automated, I'm just questioning if I need to keep maintaining the daily PPA, since the use case can be served with more upstream means.

So it's really just that. It's less of a technical issue and more of a "does upstream still want a daily PPA" king of thing, because the daily PPA was originally set up to help upstream in solving a certain problem.

**Comment by helkaluin** [comment]
>we have no need for it

Yay, one less thing to look after :)

**Comment by YukiXXL** [comment]
I have the same problem on Debian 12. Has that new SDL2 package even been tested? The Debian team tests packages before releasing them on "Stable" branches.
Also, the AppImage and Flatpak versions have the Network bug with PCAP. It has been mentioned many times hence the reason to build PCSX2 instead if the package isn't available on the repo.

**Comment by Shoegzer** [comment]
> 21.2 is likely too old anyway. Update your OS and/or dependencies - you can use our CI's build script.

Mint 21.2 is current as of the July 16 long-term support release and is based on the Ubuntu 22.04 package base.  While that doesnt use the latest repo, even the latest doesn't include `sdl2_2.28.2`.

> We used to include SDL as a submodule to use when system SDL was too old, but we no longer do

Thanks @TellowKrinkle.  This was a point of confusion leading to the issue report as earlier builds were succeeding with `sdl2_2.0.20` even when the pcsx2 requirement was higher.  I had assumed it was still included as a submodule, but after you mentioned it wasn't, I compiled and installed new 2.28.2 libraries and it builds fine now.  I wanted to do this manually vs. the dep script for other local reasons, but I'm sure that would have also worked.  In any event I'm fine with this issue being closed, though I'm not sure others won't encounter this too.

> To be fair, 2.28.2 is quite new. Neither the latest releases of Ubuntu (23.04 is on 2.26.3) nor Fedora (38 is also on 2.26.3) has it.

Yup, though the reasons @stenzek stated for keeping sdl2 up to date on a project so heavily reliant on disparate arrays of input devices with a large margin of error is completely understandable.  If users complaining about "broken controllers" can be at least partially mitigated by the requirement for more recent libraries, then it's a win.
