### ISSUE TITLE
[Feature request] hotkeys for Game Volume control in both PCSX2 OS versions

### ISSUE THREAD

**Issue by belldandu** [PCSX2/pcsx2#992]
Can you guys add 3 hotkeys for Game Volume control in pcsx2 that are specific to the spu2 So that we don't have to open the menu every time we want to either mute, turn up, or turn down the games volume. 
I like to listen to music outside of the games i play sometimes and its a pain to have to open a menu every time i want to make a change to something like the games volume. (Sure i could turn down my computers volume but that defeats the purpose of trying to play music over the game e.e)
Can someone please grant my selfish request :3

**Comment by kamijoutouma** [comment]
>.> @ssakash @refractionpcsx2 @TheLastRar

**Comment by willkuer** [comment]
Pinging random devs is not nice. If not disabled they will receive a mail - if they subsribed they get another mail.

Normally devs select the subject they want to tackle by themselves. Also if devs that are not mentioned see this issue they probably wont consider it as there seem to be other devs involved.

Your issue could be solved by windows beginning with vista I guess. You have the ability to select volume settings specific for different apps in the mixer. Unfortunately i think there is no hotkey for that. But probably there is third party software available to solve the issue.

Nevertheless your idea is valid and the proposed function would be a nice feature. That's also probably the reason this issue is still open. There is just nobody around who had time to solve it.

**Comment by lightningterror** [comment]
Volume mixer already provides the necessary functionality so I don't see this being added anytime soon. Closing as it's very low priority.
