### ISSUE TITLE
Would it be possible to replace FXAA with SMAA?

### ISSUE THREAD

**Issue by AmbientMalice** [PCSX2/pcsx2#997]
I'm just curious whether it would be possible to replace the outdated and blurry FXAA with the superior SMAA post-processing AA method. It's not a huge concern, but FXAA gives terrible results, while SMAA gives generally excellent results.

**Comment by cyclonmaster** [comment]
Sound interesting, plus SMAA said to give better performance and same as FXAA quality.

**Comment by karasuhebi** [comment]
> to replace the outdated and blurry FXAA with the superior SMAA post-processing AA method.

@AmbientMalice Not to be an asshole but have you actually used PCSX2's FXAA? Is not a total blurfest like most implementations of FXAA. @Asmodean- knows what he's doing. XD

**Comment by AmbientMalice** [comment]
>Not to be an asshole but have you actually used PCSX2's FXAA? Is not a total blurfest like most implementations of FXAA.
FXAA has never really provided satisfactory results in any game or software that I have seen it used in. PCSX2 seems to excessively smear object edges. Despite this, I tend to use it because MSAA is too hacky. I was reminded of FXAA limitations when playing Resident Evil: Revelations 2 and Resident Evil 6 on PC, which only offer very high quality FXAA, which I found to be simply not good enough. PPSSPP's FXAA is pretty terrible, too. I'm not sure whether there's a particular licensing or tech reason so many emudevs go for FXAA over SMAA, but FXAA is overall pretty bad.

**Comment by AmbientMalice** [comment]
>Sound interesting, plus SMAA said to use less graphics resources and give better performance and same as FXAA quality.
SMAA is slightly more intensive than FXAA, but it gives results similar to MSAA 4x, depending on who you talk to. SMAA and shaders like it became the preferred AA method for games on PC since MSAA is a huge performance drain with deferred rendering, and FXAA was attracting too much criticism for being blurry.

**Comment by Sarania** [comment]
PCSX2's FXAA is really really good. Asmodean tweaked the hell out of it and it shows. I am one of the most anti FXAA people around but I honestly thing PCSX2's is the best I've seen. To my eyes it looks somewhere between 2xMSAA and 4xMSAA in quality and without blurryness.

However more options is always good, and SMAA could be useful on some titles. I will ping @Asmodean again so maybe he will notice this. He is the shader master and hopefully he will take a look.

**Comment by karasuhebi** [comment]
It's @Asmodean- that you need to ping. :)

**Comment by Sarania** [comment]
Frickin dash. Well I pinged a random dude too, maybe he knows secret black magic :tongue: Anyway thanks!

**Comment by Ryudo300** [comment]
Agreeing with Blyss about FXAA on PCSX2. It's pretty damn good lol.

Having it as an 'additional option' is ok to me though. But replacing it? No way.

**Comment by AmbientMalice** [comment]
>Having it as an 'additional option' is ok to me though. But replacing it? No way.

What would be the downside to replacing it, in your view? More precisely, what advantages do you think FXAA offers over SMAA?

**Comment by Sarania** [comment]
A big disadvantage of SMAA is that when applied to the whole scene indiscriminately, SMAA tends to really smear text about a lot. Since we have no way to really separate our framebuffer in to 2d and 3d that's a major consideration for PCSX2.

**Comment by AldousP** [comment]
Out of curiosity, what is the incentive to replace it?

**Comment by AmbientMalice** [comment]
>Out of curiosity, what is the incentive to replace it?

In my experience, it provides a cleaner image than FXAA. It's *generally* less destructive. FXAA in PCSX2 seems to give edges a noticable fuzzing in some games. It'd be nice to see some screenshots comparing the two shaders. But actually screenshotting PCSX2's FXAA would be kind of tricky.

>A big disadvantage of SMAA is that when applied to the whole scene indiscriminately, SMAA tends to really smear text about a lot.

FXAA does the same thing.

**Comment by Sarania** [comment]
FXAA does not smear text in the same way I meant. It can blur it yeah, but SMAA actually smears it. Kind of like the effect pixel art scalers like HQ2X have on text.

But the question that @AldousP asked I think meant "Why do we need to replace FXAA with SMAA as opposed to just adding SMAA along side it?"

**Comment by mirhl** [comment]
I guess because ideally, every time I (and him?) read people using it, they just preferred to scrap FXAA altogether.
Since this ticket I never even heard of somebody preferring the later for reasons other than "hey, it's in sweefFX it must be gr8". 

Performance of FXAA, with just less blur. That's what I (we?) thought.  Where did you see the smearing?

**Comment by Sarania** [comment]
The text smearing issue I saw when using SMAA in GTA IV. Admittedly that's my own limited experience with it. It did anti alias pretty well without much blur, but it also smeared the text badly. That said, it wasn't any better than PCSX2s FXAA is. I consider PCSX2s FXAA in a completely different class if I haven't made that obvious already. There is literally no other program or game I can even tolerate it in, I hate it. But PCSX2s is different. Better by leaps and bounds. That's why I'm not in favor of removing it. Adding SMAA alongside - sure. But removing our FXAA? Definitely not.

**Comment by ADormant** [comment]
SMAA is a very complex shader I don't think any emulator currently supports it and 4xSMAA is  a hybrid hardware/postprocessing AA and requires MSAA suport.

**Comment by mirhl** [comment]
@Sarania That's a point indeed. I also intriguingly tried SMAA in gta 4.. and I swear it was at least bearable, compared to FXAA that was making me sick. I guess we need some actual hard data for this.. Which I guess is what we are going to hear from:
@ADormant 
Interesting. So 4xSMAA would require hardware renderer hacks? This is quite bad. 
What about the lighter version? Do you think it has at least some kind of advantage over your FXAA implementation? Performance, quality.. whatever..?

**Comment by ADormant** [comment]
SMAA 4X is enhanced MLAA + 2x temporal SSAA + 2x MSAA. 1xSMAA is probably still better than FXAA 3.11 but it requires multi-pass shader support I think it takes 2 or 3 passes in addition to some other things. There are also experimental AA methods.
https://github.com/vispy/vispy/wiki/Tech.-Antialiasing
https://github.com/vispy/experimental/tree/master/fsaa
However what we need for now is MSAA for OpenGL and which is much easier to add than SMAA and is required for higher than 1x SMAA anyway.
@gregory38

**Comment by Sarania** [comment]
@mirhl It was usable in GTA IV. I did keep it on despite the text thing. And it was way better than FXAA there yeah. But it didn't look as good as PCSX2 FXAA IMO

**Comment by AmbientMalice** [comment]
>However what we need for now is MSAA for OpenGL

The problem there is that MSAA causes various side effects in most 3D emulators. It's one of the reasons high-quality post-processing AA is so important.

**Comment by ADormant** [comment]
MSAA and SSAA are okay in Dolphin though they  too had to fix many bugs related to them. PCSX2 D3D implementation is probably  less than perfect . SMAA would cause much more bugs anyway since it's more complex and requires things like 3+ passes, two bytecode precomputed textures, or  implementation of annotations for external texture path handling so no way it'll work in PCSX2 without seriously upgraded post-processing system.

**Comment by ADormant** [comment]
MSAA and SSAA are okay in Dolphin though they  too had to fix many bugs related to them. PCSX2 D3D implementation is probably  less than perfect . SMAA would cause much more bugs anyway since it's more complex and requires things like 3+ passes, two bytecode precomputed textures, or  implementation of annotations for external texture path handling so no way it'll work in PCSX2 without seriously upgraded post-processing system and maybe even texture replacement.

**Comment by lightningterror** [comment]
Closing, trivial.
